### PR TITLE
Pr/oshmem man v1.10

### PR DESCRIPTION
**Pull request by igor-ivanov**
Added man/man3 pages for OpenSHMEM

@jsquyres, @rhc54, @miked-mellanox  see related PR in master as open-mpi/ompi#769

### CODE REVIEW

**Comment by mike-dubman** [comment]
:+1:

**Comment by jsquyres** [comment]
:-1: This suffers from the same problem that was identified in open-mpi/ompi#850

**Comment by mike-dubman** [comment]
@jsquyres - we will address open-mpi/ompi#850 as separate PR for master and v1.10 branches.
This PR is synchronized with same one from master.

**Comment by mike-dubman** [comment]
bot:milestone:v1.10.1
bot:label:enhancement
bot:assign: @jsquyres

**Comment by jsquyres** [comment]
:-1: I do not want to knowingly commit something that is broken with the intention that it will be fixed later.  Please fix it on master, and then add that commit to this PR.  Thanks.

**Comment by igor-ivanov** [comment]
Added requested changes (see master PR https://github.com/open-mpi/ompi/pull/879)

**Comment by jsquyres** [comment]
@igor-ivanov Thank you.  :+1:

**Pull request merged**
