### PR TITLE
Topic/v2.x/sentinel fixes

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1330/ for details.

**Comment by ggouaillardet** [comment]
:bot:assign: @hjelmn 
:bot:label:bug
:bot:milestone:v2.0.0

**Comment by hjelmn** [comment]
:+1:

**Comment by jsquyres** [comment]
@hjelmn indicates that he is going to add one minor cleanup after this PR is merged (on both master and here).

**Pull request merged**
