### PR TITLE
v1.10 cm priority

### PR DESCRIPTION
**Pull request by hjelmn**
:bot:label:bug
:bot:assign: @miked-mellanox 
:bot:milestone:v1.10.1

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/881/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/882/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mike-dubman** [comment]
could you please describe what problem this PR solves? and if it change previous component selection logic - what is a new one?

**Comment by hjelmn** [comment]
This PR solves a problem that only occurs during dynamic loading. If ob1 gets loaded before cm then cm never gets selected.

Looks like I need to fix a few bugs in the PR before you can review this.

**Comment by hjelmn** [comment]
@rhc54 Is it ok to change the arguments of an internal API in a release series? I added an argument to mca_base_select. If not I will rename the new version with _new and have the old version call with NULL as the priority argument. I can drop a bunch of changes from this patch if I do that.

**Comment by rhc54** [comment]
I believe so - @jsquyres: you have any qualms?

**Comment by jsquyres** [comment]
We do try to avoid changing major internal APIs so that any developers outside of the OMPI tree (e.g., http://processors.wiki.ti.com/index.php?title=MCSDK_HPC_3.x_OpenMPI) doesn't get unexpectedly screwed with a new Open MPI minor release.  I think mca_base_select() qualifies as a major API.

So I'd be in favor of @hjelmn's proposed approach: add a `_new` version (with a suitable comment explaining why this is happening, yadda yadda yadda) and have the old version just call the new version with a NULL param.

**Comment by rhc54** [comment]
I can live with that, but then let's do that as a custom patch only for 1.10.1 - I'd hate to have that workaround in the future code base.

**Comment by hjelmn** [comment]
@rhc54 Agreed. Just want to get this functionality into 1.10.1.

**Comment by jsquyres** [comment]
@rhc54 Agreed: this is specific for v1.10.x.  Master / v2.x will continue to not have the `_new` workaround.

**Comment by hjelmn** [comment]
@rhc54 @jsquyres @miked-mellanox Good to go now.

**Comment by hjelmn** [comment]
Shoot, lost a commit. Let me rebase this one more time.

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
Also need @regrant and @tkordenbrock to chime in to see what this whole thing does to portals BTL / MTL.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/883/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/884/ for details.

**Comment by rhc54** [comment]
I'm just going to mark this as pushed-back so I don't accidentally commit it before @regrant and @tkordenbrock can confirm no issue with portals, and @miked-mellanox confirms same for mxm

**Comment by hjelmn** [comment]
Looks good to go with comments from @regrant in open-mpi/ompi#1058

:bot:nolabel:pushed-back

**Comment by hjelmn** [comment]
@yburette Included the ofi priority change.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/897/ for details.

**Pull request merged**
