### PR TITLE
v2.x: pkgconfig fixes

### PR DESCRIPTION
**Pull request by ggouaillardet**
Thanks Alastair McKinstry for the report.

Fixes open-mpi/ompi#2069

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2173/ for details.

**Comment by ggouaillardet** [comment]
:bot:assign: @jsquyres 
:bot:milestone:v2.0.2
:bot:label:bug
:bot:label:enhancement

**Comment by jsquyres** [comment]
👍

**Comment by jsquyres** [comment]
I would actually classify all of these as bug fixes, not enhancements.

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Pull request merged**
