### PR TITLE
Fix some type declarations so make check works for SPARC.

### PR DESCRIPTION
**Pull request by rhc54**
Thanks to Paul Hargrove for the report and correction. Take from master commit

open-mpi/ompi@91bec7e9dd54cdfd684ba0b2c5c2a0339f01bec4

### CODE REVIEW

**Comment by rhc54** [comment]
@bosilca can you please review/approve?

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/69/
Test PASSed.

**Comment by jsquyres** [comment]
FWIW, looks ok to me.

**Comment by bosilca** [comment]
Good catch, they should be bool and not int.

**Pull request merged**
