### PR TITLE
Add new mca variables opal_abort_delay and opal_abort_print_stack

### PR DESCRIPTION
**Pull request by igor-ivanov**
Port https://github.com/open-mpi/ompi/pull/1151

@miked-mellanox @rhc54 could you look at this

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1069/ for details.

**Comment by igor-ivanov** [comment]
:bot:label:bug
:bot:label:enhancement
:bot:milestone:v2.0.0
:bot:assign: @rhc54

**Comment by jsquyres** [comment]
Per the original description, this PR should be contingent upon open-mpi/ompi#1151 (i.e., we need to wait for 1151 to be merged before accepting this one).

**Comment by hppritcha** [comment]
open-mpi/ompi#1151 has been merged.

**Comment by jsquyres** [comment]
@hppritcha Just waiting for one additional confirmation: whether we need to also update some man pages and/or FAQ pages (see https://github.com/open-mpi/ompi/pull/1151#issuecomment-161082509).

**Comment by igor-ivanov** [comment]
@jsquyres @hppritcha I have not found other places to change

**Pull request merged**
