### PR TITLE
v1.10: fortran: Fix many Fortran binding bugs

### PR DESCRIPTION
**Pull request by kawashima-fj**
PR for v1.10.3

@jsquyres please review

bot:label:bug
bot:milestone:v1.10.3

Not critical; can be delayed to v1.10.4

(cherry picked from part of commit open-mpi/ompi@4566286)

### CODE REVIEW

**Comment by jsquyres** [comment]
@kawashima-fj Compared to #1083, this PR seems incomplete...?

**Comment by kawashima-fj** [comment]
@jsquyres Sorry, I added 2 commits which had conflicts. Please review again.
This should be a complete PR. Though #1083 consists of 10 commits, this PR consist of 9 commits because open-mpi/ompi@17d32ac and open-mpi/ompi@e854404 are merged into one commit.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1522/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1523/ for details.

**Comment by jsquyres** [comment]
@kawashima-fj Ah, I just noticed that you added the new commits.  Sorry -- I missed the mail (I get too much per day... 😦 ), and the "pushed-back" label was still on this PR).  Pro tip: once you address review comments brought up in a PR, you can remove the "pushed-back" label to let the reviewer know that it's ready to review again, like this:

bot:nolabel:pushed-back

**Comment by jsquyres** [comment]
👍

**Pull request merged**
