### PR TITLE
HCOLL:  Fix OMPI to HCOLL predefined datatypes, Ops mapping

### PR DESCRIPTION
**Pull request by bureddy**
open-mpi/ompi@e398ad66196575196cd086a076d2c42ad3cc70ba

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/97/
Test PASSed.

**Comment by bureddy** [comment]
@rhc54 ,   Can you please merge this in?  I need to push a fix on top of this fix.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/101/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/100/
Test PASSed.

**Comment by rhc54** [comment]
@jladd-mlnx someone want to review this?

**Comment by jladd-mlnx** [comment]
@rhc54 Looks good to go.

**Pull request merged**
