### PR TITLE
Integrate PMIx 1.0 with OMPI.

### PR DESCRIPTION
**Pull request by rhc54**
This is still being worked, but is a placeholder for the eventual merge

Rolled up from:
open-mpi/ompi@cf6137b530e7478720fbf87da83d6a46c1774dbe
open-mpi/ompi@79827ceaa8e383cae74a9fda35734418a612e629
open-mpi/ompi@1d71037139efc3ca4e985ef2c57affc9209eee7d
open-mpi/ompi@3cab860a0118bfc852961ae88a16f9b8d1fb9d83
open-mpi/ompi@0d5814b5ca1170cfe2dbbc1bdab3d3c3af4961db
open-mpi/ompi@38ba54366ca5f21cba17e036da8cf3f511c8e334
open-mpi/ompi@b0d756440079b8b77a913aad4bc4b8fe1dd1b794
open-mpi/ompi@bcabd1e28295c0808efd67d1b4ecc478a9816a0d
open-mpi/ompi@a3842af709e133221e45a99ff3a76d08abc655d3
open-mpi/ompi@ef69958e0144f1f49e7a92b60ff33d7359111d04
open-mpi/ompi@c1bbd7bc7842397b5f136a1f14916bd0b4b0e5c0
open-mpi/ompi@95dbd70f44e618e2edf6efc434a9cc7a1110f191
open-mpi/ompi@a772b46c15c87b0227f71ab8228c40f0e646d5c9
open-mpi/ompi@f6948c2bb475fcc90f581b2bd3edacb4a9b71d4b
open-mpi/ompi@37c3ed68e7340fc6798f2a5c8db210270cae344a
open-mpi/ompi@e6add86e4f94f0777a3749500618569d10f9f4a4
open-mpi/ompi@1cdb86b8c7bfaed846a7a839c9073e9543916ed1
open-mpi/ompi@291afe502ff075829bfa2278bc87be1e1da96ab8
open-mpi/ompi@7f0ed74d24a3e539d0a08a2f57a6a4874fd33325
open-mpi/ompi@b79cffc73b88c2e5e2f2161e096c49aed5b9d2ed
open-mpi/ompi@4c47c498ace8fe0c0965e807e83c9b04cb5a7857
open-mpi/ompi@f94f3cda214ab937c46802896fb53b84bec6cc3a
open-mpi/ompi@899bf548a25c5bd183cb9fa680928bb0288b2cd6
open-mpi/ompi@2bbf22e2d05cb78ff76c2ebcf76e592dd82e72cc
open-mpi/ompi@a2a15cea8a0654e2fcc3c32eac9e31506a637818
open-mpi/ompi@e0a52354d48a7b6495d6ecbad04d831ee567559c
open-mpi/ompi@6a8fad49e57007cf8edce4ad8406f724d4e11f8f
open-mpi/ompi@dc5796b8a19129cae2c3def9014fa921e45f51c2
open-mpi/ompi@b60b03d613b4763ecac53af8aae6e895d2c8f429
open-mpi/ompi@22d7c0081a58c39408adad3c72fa73549c530083
open-mpi/ompi@0e7e14449fc5b8bf374ccda56e3d4767f2b59131
open-mpi/ompi@69b9bc2269044f4ab80d9b3a39ea32a52f80973b
open-mpi/ompi@c1bbbb5e2f54476f80a42a6390c9532de3e5a66e
open-mpi/ompi@8b88ea9b13dcc5527753d59e1702d8d74098a20f

Bring over the relevant part of commits:  
open-mpi/ompi@1f8de276
open-mpi/ompi@1b7930ad52fa9fe5ce30f774f6782f150d15bbcd

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by rhc54** [comment]
Passes MTT with only 3 timeouts that appear unrelated.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/711/ for details.

**Comment by jsquyres** [comment]
Per email from Ralph on 2015-09-16, PMIx looks good to go for v2.x.

**Pull request merged**
