### PR TITLE
memory: fix typo

### PR DESCRIPTION
**Pull request by hjelmn**
This is a 2.x specific change. No master equivalent.

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

PEBKAC. Wasn't caught by MTT or CI.

:bot:label:bug
:bot:milestone:v2.0.0
:bot:assign: @jsquyres

### CODE REVIEW

**Comment by hjelmn** [comment]
One more commit coming. Apparently MEMORY_LINUX_PTMALLOC2 is being defined to 1 even though memory/linux disabled itself. Tracking down now.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1564/ for details.

**Comment by hjelmn** [comment]
Found the other issue. The MCA build priorities for the memory framework. Should probably be removed on master but I have a tweak that should help here.

**Comment by hjelmn** [comment]
@hppritcha Also updating the LANL platform files to not force ptmalloc2.

**Comment by hjelmn** [comment]
@jsquyres Ready for review.

**Comment by jsquyres** [comment]
The gap between 40 and 41 is a little small.  :smile: But good enough for now.  :+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1565/ for details.

**Comment by hjelmn** [comment]
On master I will remove the memory component priorities. They were only there because we could have only one memory component before. Now we can have multiple.

**Comment by jsquyres** [comment]
I'm going to merge these so that they can get into tonight's snapshot.

**Pull request merged**
