### PR TITLE
PML UCX: fix typo.

### PR DESCRIPTION
**Pull request by yosefe**
Fix typo in PML UCX, which was not completely fixed by #834

### CODE REVIEW

**Comment by yosefe** [comment]
bot:label:bug

**Comment by yosefe** [comment]
bot:milestone:v1.10.3

**Comment by yosefe** [comment]
bot:assign:hppritcha

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1495/ for details.

**Comment by hppritcha** [comment]
:+1:

**Pull request merged**
