### PR TITLE
Turn off message coalescing to avoid segfaults until a better fix can be...

### PR DESCRIPTION
**Pull request by rhc54**
... provided. This is a 1.8 series change only, so no master commit is cited.

@hjelmn please review

### CODE REVIEW

**Comment by mellanox-github** [comment]
Merged build triggered.

**Comment by mellanox-github** [comment]
Merged build started.

**Comment by mellanox-github** [comment]
Merged build finished. Test PASSed.

**Comment by mellanox-github** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/10/
Test PASSed.

**Comment by mellanox-github** [comment]
Merged build triggered.

**Comment by mellanox-github** [comment]
Merged build started.

**Comment by mellanox-github** [comment]
Merged build finished. Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/1/

**Build Log**
_last 50 lines_

```
[...truncated 6 lines...]
 > /usr/bin/git init /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace # timeout=60
Fetching upstream changes from https://github.com/open-mpi/ompi
 > /usr/bin/git --version # timeout=60
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git1418481543298245604.credentials # timeout=60
 > /usr/bin/git fetch --tags --progress https://github.com/open-mpi/ompi +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
 > /usr/bin/git config remote.origin.url https://github.com/open-mpi/ompi # timeout=60
 > /usr/bin/git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config remote.origin.url https://github.com/open-mpi/ompi # timeout=60
Pruning obsolete local branches
Fetching upstream changes from https://github.com/open-mpi/ompi
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git830811408821228796.credentials # timeout=60
 > /usr/bin/git fetch --tags --progress https://github.com/open-mpi/ompi +refs/pull/*:refs/remotes/origin/pr/* --prune # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
 > /usr/bin/git rev-parse origin/pr/79/merge^{commit} # timeout=60
FATAL: Command "/usr/bin/git rev-parse origin/pr/79/merge^{commit}" returned status code 128:
stdout: origin/pr/79/merge^{commit}

stderr: fatal: ambiguous argument 'origin/pr/79/merge^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

hudson.plugins.git.GitException: Command "/usr/bin/git rev-parse origin/pr/79/merge^{commit}" returned status code 128:
stdout: origin/pr/79/merge^{commit}

stderr: fatal: ambiguous argument 'origin/pr/79/merge^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1435)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1411)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1407)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1110)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1120)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:516)
    at hudson.plugins.git.GitAPI.revParse(GitAPI.java:257)
    at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:83)
    at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:815)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:915)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1258)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:622)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:528)
    at hudson.model.Run.execute(Run.java:1759)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
```

Test FAILed.

**Comment by jsquyres** [comment]
@miked-mellanox That's a false jenkins failure, right?

**Comment by mike-dubman** [comment]
yep, i just added jenkins job for "master" but forgot to change url.
sorry.

**Comment by jladd-mlnx** [comment]
@rhc54 @hppritchard I think this should be signed off on by Howard before it's merged. It should also be added to the 1.8.4 release notes.

**Comment by hjelmn** [comment]
Looks good to me.

**Comment by hjelmn** [comment]
@jladd-mlnx this was discussed already at lanl and howard and I agreed this was the way to go for now

**Comment by rhc54** [comment]
I will be sure it gets into the NEWS as well.

**Comment by jladd-mlnx** [comment]
@rhc54 thanks!

**Comment by hjelmn** [comment]
@jladd-mlnx I should mention the fix for message coalescing can be found here: https://github.com/hjelmn/ompi/commit/db84aa9cb77050fdc200a597acc3c1b3a8bcf4bf

**Pull request merged**
