### PR TITLE
hint processing should not open files

### PR DESCRIPTION
**Pull request by hppritcha**
move opening of files from hint processing and into open routines.

This is MPICH commit 92f1c69f0de8 and 22a77dceda11

see https://trac.mpich.org/projects/mpich/ticket/2261
Ref: https://github.com/open-mpi/ompi/issues/158

Signed-off-by: Pavan Balaji balaji@anl.gov

Conflicts:
    ompi/mca/io/romio314/romio/adio/ad_lustre/ad_lustre_open.c

@edgargabriel 
cherry-pick of open-mpi/ompi@6e9cbe39

### CODE REVIEW

**Comment by hppritcha** [comment]
@edgargabriel looks like somethings wrong with ad_lustre_open.c, it doesn't compile with lustre enabled for romio

**Comment by hppritcha** [comment]
pushed the same fix Edgar did for master - I think.  an errant bracket from Rob's patch.

**Comment by edgargabriel** [comment]
yes, sorry for the delay, you will need 8561f5f1805a03d9e40521bb47b7fd443e28aff2 to compile correctly.

**Comment by edgargabriel** [comment]
looks good as far as I can see. Some of the files in the ad_lustre subdirectory still show differences in whitespaces compared to master, but content wise it looks now identical.

**Pull request merged**
