### PR TITLE
Shmem fixes (Don't merge until #1041 is merged)

### PR DESCRIPTION
**Pull request by karasevb**
Cherry-picked from https://github.com/open-mpi/ompi/pull/1867 and https://github.com/open-mpi/ompi-release/pull/1041
Don't merge until https://github.com/open-mpi/ompi-release/pull/1041 is merged.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2104/ for details.

**Comment by jladd-mlnx** [comment]
@artpol84 Please have a look.

**Comment by artpol84** [comment]
bot:milestone:v2.1.0

**Comment by artpol84** [comment]
bot:label:WIP-DNM

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2129/ for details.

**Comment by artpol84** [comment]
@jsquyres this PR is ok, but the base PR is failing.

**Comment by jsquyres** [comment]
@artpol84 Ah, you mean this one won't pass CI until #1041 is merged?

**Comment by artpol84** [comment]
@jsquyres right!

**Comment by artpol84** [comment]
At least I hope so - we'll see once #1041 will be merged and this commit will get a chance to be verified.

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2169/ for details.

**Comment by jsquyres** [comment]
@karasevb @artpol84 Getting a compile failure in in SPML UCX.

**Comment by artpol84** [comment]
@jsquyres this is expected:

we depend on #1041 which in turn depends on #913. Won't get compiled untill those 2 are in.

**Comment by jsquyres** [comment]
@artpol84 Ok

**Comment by jsquyres** [comment]
The `ompi-release` repo is now closed; all release branches have been moved to the `ompi` repo (https://github.com/open-mpi/ompi).  Please re-open this PR on the corresponding branch on the `ompi` repo.

**Comment by artpol84** [comment]
ported to ompi (open-mpi/ompi#2127).
Please close this one to avoid confusion.

**Pull request closed without merging**
