### PR TITLE
pml/yalla: fix performance degradation caused by mxm misconfig.

### PR DESCRIPTION
**Pull request by artpol84**

### CODE REVIEW

**Comment by artpol84** [comment]
bot:milestone:2.0.1

**Comment by artpol84** [comment]
bot:milestone:v2.0.1

**Comment by artpol84** [comment]
bot:label:blocker

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/f276c70c807a2a5e1530904573b6c79f

**Comment by artpol84** [comment]
:bot:assign: @alex-mikheev

**Comment by artpol84** [comment]
bot:ibm:retest

**Comment by artpol84** [comment]
addresses https://github.com/open-mpi/ompi/issues/1831

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/abfb2cb7b9e29eccf21865653e4b4aba

**Comment by jjhursey** [comment]
IBM CI is still hitting some intermittent errors - I'm trying to isolate them, but hopefully this should work now.
bot:ibm:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2140/ for details.

**Comment by jsquyres** [comment]
@artpol84 @jladd-mlnx @alex-mikheev @miked-mellanox @igor-ivanov Can someone at Mellanox please review this ASAP?

**Comment by jladd-mlnx** [comment]
👍

**Pull request merged**
