### PR TITLE
btl/sm: re-enable the use of CMA and knem

### PR DESCRIPTION
**Pull request by hjelmn**
At some point we added a sanity check to the btl base to ensure that
the btl flags match the available functions (this prevents user's from
specifying get or put when no function exists). This check was
disabling get for the sm btl since at the time of the check there is
no btl_get function. The simplest fix is to set a dummy value to btl_get
that will be overwritten with the proper value on btl initialization.

Includes master references:
open-mpi/ompi@d7c7bb399388e7f85aa856c38865c8062bf7c0e6
open-mpi/ompi@998e69a6facdecdaa95996ac996b5a249c42f8e0

### CODE REVIEW

**Comment by hjelmn** [comment]
Reference open-mpi/ompi#239

**Comment by hjelmn** [comment]
@jsquyres Can you please review?

**Comment by jsquyres** [comment]
I just put a comment about the code here: https://github.com/open-mpi/ompi/commit/d7c7bb399388e7f85aa856c38865c8062bf7c0e6#commitcomment-8265592

**Comment by hjelmn** [comment]
@abouteiller I brought over your fixes with the enhancements suggested by Jeff.

**Pull request merged**
