### PR TITLE
Update v2.x osc components to master

### PR DESCRIPTION
**Pull request by hjelmn**
:bot:label:enhancement
:bot:assign: @ggouaillardet 
:bot:milestone:v2.0.0

This PR includes the new osc/rdma component for true MPI-3.0 RMA support as well as updates to osc/pt2pt for dynamic add_procs.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/899/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/916/ for details.

**Comment by jsquyres** [comment]
@hjelmn Can you include open-mpi/ompi@140cf90e3e0bc8c194f85a4e7c7ac913f4766373 in this PR?  It's a minor compiler warning stomp.

**Comment by hjelmn** [comment]
Added.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/922/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/943/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/969/ for details.

**Comment by hppritcha** [comment]
@ggouaillardet  when you have a chance in the next few days could you review this? thanks.

**Comment by ggouaillardet** [comment]
@hjelmn 

there is at least an issue
with ibm/onesided/c_fence_lock here is a crash

```
[thread 1 on process 11304] Signaled SIGBUS(10): opal_list_get_first() at line 324 in /volume1/home/usersup/gilles/src/ompi-release/opal/class/opal_list.h.
324     assert(1 == item->opal_list_item_refcount);
fdb* tb
#0 0xffffffff070b3998 (opal_list_get_first + 0x2c) (list=(struct opal_list_t *) 0x000000002090cd28) at line 324 in /volume1/home/usersup/gilles/src/ompi-release/opal/class/opal_list.h
#1 0xffffffff070b3c60 (opal_list_remove_item + 0x30) (list=(struct opal_list_t *) 0x000000002090cd28,
    item=(struct opal_list_item_t *) 0x0000000020913eb0) at line 478 in /volume1/home/usersup/gilles/src/ompi-release/opal/class/opal_list.h
#2 0xffffffff070bf3d4 (ompi_osc_pt2pt_unlock_internal + 0x1dc) (target=0,
    win=(struct ompi_win_t *) 0x000000002090c760) at line 363 in /volume1/home/usersup/gilles/src/ompi-release/ompi/mca/osc/pt2pt/osc_pt2pt_passive_target.c
#3 0xffffffff070bfa9c (ompi_osc_pt2pt_unlock + 0x28) (target=0,
    win=(struct ompi_win_t *) 0x000000002090c760) at line 439 in /volume1/home/usersup/gilles/src/ompi-release/ompi/mca/osc/pt2pt/osc_pt2pt_passive_target.c
#4 0xffffffff00f16284 (PMPI_Win_unlock + 0x2a4) (rank=0,win=(struct ompi_win_t *) 0x000000002090c760) at line 59 in /volume1/home/usersup/gilles/build/ompi-v2.x-sparcv9/ompi/mpi/c/profile/pwin_unlock.c
#5 0x0000000000101520 (main + 0x220) (argc=1,argv=(char **) 0x000007feffffea68) at line 47 in /volume1/home/usersup/gilles/src/ompi-tests/ibm/onesided/c_fence_lock.c
#6 0xffffffff0250b81c (__libc_start_main + 0x194) (0x101300,0x1,0x7feffffea68,0x1030a8,0x103098,0x0)
#7 0x00000000001011ac (_start + 0x2c) ()
```

from `ompi_osc_pt2pt_unlock_internal` 

```
opal_list_remove_item (&module->outstanding_locks, &lock->super);
```

but `module->outstanding_locks` is an `opal_hash_table_t`, not an `opal_list_t`

/\* compiler reports a warning about that issue

```
  CC       osc_pt2pt_passive_target.lo
../../../../../../src/ompi-v2.x/ompi/mca/osc/pt2pt/osc_pt2pt_passive_target.c: In function 'ompi_osc_pt2pt_unlock_internal':
../../../../../../src/ompi-v2.x/ompi/mca/osc/pt2pt/osc_pt2pt_passive_target.c:363:5: warning: passing argument 1 of 'opal_list_remove_item' from incompatible pointer type [enabled by default]
     opal_list_remove_item (&module->outstanding_locks, &lock->super);
     ^
In file included from ../../../../../../src/ompi-v2.x/ompi/mca/osc/pt2pt/osc_pt2pt.h:28:0,
                 from ../../../../../../src/ompi-v2.x/ompi/mca/osc/pt2pt/osc_pt2pt_passive_target.c:27:
../../../../../../src/ompi-v2.x/opal/class/opal_list.h:470:33: note: expected 'struct opal_list_t *' but argument is of type 'struct opal_hash_table_t *'
 static inline opal_list_item_t *opal_list_remove_item
                                 ^
../../../../../../src/ompi-v2.x/ompi/mca/osc/pt2pt/osc_pt2pt_passive_target.c:363:5: warning: passing argument 2 of 'opal_list_remove_item' from incompatible pointer type [enabled by default]
     opal_list_remove_item (&module->outstanding_locks, &lock->super);
     ^
In file included from ../../../../../../src/ompi-v2.x/ompi/mca/osc/pt2pt/osc_pt2pt.h:28:0,
                 from ../../../../../../src/ompi-v2.x/ompi/mca/osc/pt2pt/osc_pt2pt_passive_target.c:27:
../../../../../../src/ompi-v2.x/opal/class/opal_list.h:470:33: note: expected 'struct opal_list_item_t *' but argument is of type 'struct opal_free_list_item_t *'
 static inline opal_list_item_t *opal_list_remove_item
```

master is quite different, is there any chance you missed some commits ?

**Comment by hjelmn** [comment]
Looks like an error in a merge conflict. Will fix and rebase.

**Comment by hjelmn** [comment]
Should be fixed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1002/ for details.

**Comment by ggouaillardet** [comment]
:+1:

**Comment by hppritcha** [comment]
@hjelmn we want #754 to go in prior to this correct?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1020/ for details.

**Comment by hjelmn** [comment]
No, #754 is not needed for this one. Anyway, can we disable Mellanox Jenkins. The false failures are getting old.

**Comment by hjelmn** [comment]
I have a fix for mlx5 coming. This will be ready to go then.

**Comment by jsquyres** [comment]
@hjelmn Arrgh -- I just noticed your "I will have a fix for mlx5 soon" comment (in the future, please remove the "reviewed" tag when stuff like this happens).  :frowning: Should I revert this PR?

**Comment by hjelmn** [comment]
no need. the mlx5 fix will probably go in today

**Comment by jsquyres** [comment]
Roger; thanks.

**Pull request merged**
