### PR TITLE
Make the PMI barrier/modex be non-blocking so that opal_progress can …

### PR DESCRIPTION
**Pull request by rhc54**
…run. This fixes a hang when direct launching jobs that use PSM

@matcabral Can you please test?

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1630/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1631/ for details.

**Comment by rhc54** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1632/ for details.

**Comment by rhc54** [comment]
@Di0gen Looks like something is borked on the Jenkins server - having trouble downloading from Github?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1634/ for details.

**Comment by matcabral** [comment]
@rhc54  This passed my tests and seems to solve open-mpi/ompi#1559 hang.

**Comment by rhc54** [comment]
@hppritcha Could you please give this a try on your machine? @matcabral confirms that it fixes the hang on his systems. I suspect other transports may also be impacted as without this patch we are blocking all MPI progress during RTE barriers and modex when direct launched.

**Comment by rhc54** [comment]
Fixes https://github.com/open-mpi/ompi/issues/1559

**Comment by hppritcha** [comment]
I'll test when I'm back next week.  I can't access our omnipath remotely.

**Comment by rhc54** [comment]
@matcabral I believe this now includes the fix for the missing CPPFLAGS you told me about - can you please verify?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1663/ for details.

**Comment by matcabral** [comment]
@rhc54, unfortunately not :( 

> cat Makefile |grep _pmi_CPP
> common_pmi_CPPFLAGS =
> db_pmi_CPPFLAGS =
> ess_pmi_CPPFLAGS =
> grpcomm_pmi_CPPFLAGS =
> pubsub_pmi_CPPFLAGS =

**Comment by rhc54** [comment]
Wow, I'm totally puzzled there. It certainly works for me:

``` shell
$ cat Makefile | grep -e "pmi_.*LAGS"
common_pmi_CPPFLAGS = -I/home/common/slurm/build/rhc54/include/slurm
common_pmi_LDFLAGS = -L/home/common/slurm/build/trunk/lib
db_pmi_CPPFLAGS = -I/home/common/slurm/build/rhc54/include/slurm
db_pmi_LDFLAGS = -L/home/common/slurm/build/trunk/lib
ess_pmi_CPPFLAGS = -I/home/common/slurm/build/rhc54/include/slurm
ess_pmi_LDFLAGS = -L/home/common/slurm/build/trunk/lib
grpcomm_pmi_CPPFLAGS = -I/home/common/slurm/build/rhc54/include/slurm
grpcomm_pmi_LDFLAGS = -L/home/common/slurm/build/trunk/lib
pubsub_pmi_CPPFLAGS = -I/home/common/slurm/build/rhc54/include/slurm
pubsub_pmi_LDFLAGS = -L/home/common/slurm/build/trunk/lib
```

Can you confirm your configure line for me? Mine looked like this:

``` shell
./configure --prefix=foo
     --with-pmi=/home/common/slurm/build/rhc54
     --with-pmi-libdir=/home/common/slurm/build/trunk
```

**Comment by matcabral** [comment]
./configure CFLAGS=-O3 --prefix=/tmp/matcabral --with-libfabric=no --with-psm2=/usr  --enable-debug --with-pmi=/usr/local/include/slurm/ --with-pmi-libdir=/usr/local/lib/

**Comment by rhc54** [comment]
Hmmm...

``` shell
$ ./configure CFLAGS=-O3 --prefix=/home/common/openmpi/build/foobar
     --with-libfabric=no --enable-debug --with-pmi=/home/common/slurm/build/rhc54
     --with-pmi-libdir=/home/common/slurm/build/trunk

$ cat Makefile | grep -e "pmi_.*LAGS"
common_pmi_CPPFLAGS = -I/home/common/slurm/build/rhc54/include/slurm
common_pmi_LDFLAGS = -L/home/common/slurm/build/trunk/lib
db_pmi_CPPFLAGS = -I/home/common/slurm/build/rhc54/include/slurm
db_pmi_LDFLAGS = -L/home/common/slurm/build/trunk/lib
ess_pmi_CPPFLAGS = -I/home/common/slurm/build/rhc54/include/slurm
ess_pmi_LDFLAGS = -L/home/common/slurm/build/trunk/lib
grpcomm_pmi_CPPFLAGS = -I/home/common/slurm/build/rhc54/include/slurm
grpcomm_pmi_LDFLAGS = -L/home/common/slurm/build/trunk/lib
pubsub_pmi_CPPFLAGS = -I/home/common/slurm/build/rhc54/include/slurm
pubsub_pmi_LDFLAGS = -L/home/common/slurm/build/trunk/lib
```

Are you working from a tarball or git? If the latter, can you try doing:

``` shell
$ git clean -dfx
$ ./autogen.pl
```

and then redo your configure? Also, please ensure you pulled the latest version of this PR.

**Comment by rhc54** [comment]
@matcabral Okay, I finally tracked down the difference in what you were doing. You were specifying the entire path to pmi.h, which resulted in configure actually failing to find the header. Sadly, we were failing to abort in that situation, which is why your CPPFLAGS were empty.

I have handled this case now, and so your configure line should work. I have also fixed it so we do abort if we don't find the header.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1664/ for details.

**Comment by matcabral** [comment]
@rhc54 confirmed the latest patch does create a valid Makefile,

**Comment by hppritcha** [comment]
@rhc54 may have to wait till tomorrow to test.  our omnipath system seems to be down today.

**Comment by hppritcha** [comment]
I'm having some weird problems with this.  Unless I use ob1, for a 1 process job there is a hang in the very first modex exchange.  Oddly, if within a salloc sesssion, if I get a successful ob1 run in, then all subsequent ones using cm work.  Investigating.

**Comment by hppritcha** [comment]
okay I think I see a problem.  What's happening is that we're getting stuck in opal_progress:

```
0x00002b084b88ac98 in psm2_mq_ipeek2 () from /lib64/libpsm2.so.2
Missing separate debuginfos, use: debuginfo-install hfi1-psm-0.7-238.ch6.x86_64 libcxgb3-1.3.1-8.el7.x86_64 libcxgb4-1.3.5-3.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libhfi1-0.2-2.el7.x86_64 libibumad-1.3.10.2-1.el7.x86_64 libibverbs-1.1.8-8.el7.x86_64 libipathverbs-1.3-2.el7.x86_64 libmlx4-1.0.6-5.el7.x86_64 libmlx5-1.0.2-1.el7.x86_64 libmthca-1.0.6-13.el7.x86_64 libnes-1.1.4-2.el7.x86_64 libnl3-3.2.21-10.el7.x86_64 libpciaccess-0.13.4-2.el7.x86_64 librdmacm-1.0.21-1.el7.x86_64 libuuid-2.23.2-26.el7_2.2.x86_64 munge-libs-0.5.12-1.ch6.x86_64 numactl-libs-2.0.9-6.el7_2.x86_64 opensm-libs-3.3.19-2chaos.ch6.x86_64 tcp_wrappers-libs-7.6-77.el7.x86_64
(gdb) bt
#0  0x00002b084b88ac98 in psm2_mq_ipeek2 () from /lib64/libpsm2.so.2
#1  0x00002b084cd7e8ca in ompi_mtl_psm2_progress () at mtl_psm2.c:402
#2  0x00002b0841834045 in opal_progress () at runtime/opal_progress.c:187
#3  0x00002b0840c187e0 in ompi_mpi_init (argc=1, argv=0x7ffd7646f8b8, requested=0, provided=0x7ffd7646f76c) at runtime/ompi_mpi_init.c:649
#4  0x00002b0840c58c1e in PMPI_Init (argc=0x7ffd7646f7ac, argv=0x7ffd7646f7a0) at pinit.c:84
#5  0x0000000000400949 in main ()
```

It appears the process gets stuck in psm2_mq_ipeek2, or the loop that is invoking this function.

**Comment by hppritcha** [comment]
I notice with the ofi MTL that this works.  I'll recheck using PSM2 MTL on 1.10.x branch once this PR is merged, but since these issues seem to be specific to the PSM2 MTL, I think this PR is good to go.
@matcabral what's odd is it appears the process is stuck in `psm2_mq_ipeek2`.  It never returns so opal progress gets blocked and hence we never get through the modex exchange.

@rhc54 good to go

**Comment by matcabral** [comment]
@hppritcha I will try to reproduce the behavior you are seeing. I did not see it when testing this PR. I don't think the execution is stuck in psm2_mq_ipeek2(), this is a non-blocking function. Instead, it is probably being intensively called inside int ompi_mtl_psm2_progress(), registered for opal_progress. My first thought is that this sounds like the normal behavior for the thread making PSM progress.

**Comment by matcabral** [comment]
@hppritcha I cannot reproduce the behavior you are seeing. Would you please share what your 1 rank job does? this is what I'm doing (assuming v1.10 HEAD + 1150 patch):
- single system with SLRUM and PSM2, fresh boot, always running psm2 mtl. 
- srun -n 1 hello_c 
- salloc -n 1;  mpriun hello_c
- several combination for salloc /  srun, num of ranks and osu_\* benchmarks.

**Comment by hppritcha** [comment]
I'm just using ring_c.c

I do salloc -N 1 --ntasks=16
srun -n 1 ./ring_c
(hangs in psm2_mq_ipeek2) - it really hangs, it never comes back.
This only happens with PSM2 MTL.  It doesn't happen with OFI MTL using PSM2 provider.
If I run with
export OMPI_MCA_pml=ob1
then the code runs successfully.  
If I then subsequently run the app with OMPI_MCA_pml=cm it runs with PSM2 provider.  As long as I'm using the same slurm allocation it will then work fine.  If I exit and ask for a new allocation, I'm back to the same hang behavior.  

I'm suspicious given this behavior that there is some state in the hfi1 device driver that is playing a role here.

I'm using ompi in this PR, i.e.  git pull https://github.com/rhc54/ompi-release.git cmr10/pmi

**Comment by hppritcha** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1674/ for details.

**Comment by rhc54** [comment]
@matcabral Seems to be that the difference here is that your hello_c program doesn't do any communication, whereas the ring_c being used by @hppritcha does. Please see if you can reproduce the problem with something that communicates (e.g., ring_c).

**Comment by matcabral** [comment]
@hppritcha and @rhc54,  (please apologize the delay, had issues with access to test host ) I'm replicating the exact same steps that @hppritcha shared in his ring_c test and everything runs just fine.   I can only think of a difference in other components (hfi1.ko, psm2, HFI HW)

**Comment by rhc54** [comment]
@hppritcha I'm not sure how to go forward here with 1.10.3. @matcabral is configuring as follows:

``` shell
--with-libfabric=no --with-psm=no --with-openib=no --with-psm2=<path> --with-pmi=<path> --with-slurm=<path>
```

Does that match your config? If so, then I think we are down to looking at differences in drivers and hardware. Could you share your version info for hfi1.ko and psm2 libraries, and the HFI hardware on your cluster?

If that is where the difference lies, then I'll merge this PR and move ahead with 1.10.3 release.

**Comment by hppritcha** [comment]
sysadmins just upgraded some of the software on the cluster yesterday.  I'll get that info when I can get access again to the system.  I think the changes in this PR are fine and should be merged in.  The behavior does indicate the problem is not in ompi, but may be in the hf1 device driver or something about the way slurm is setup on the cluster.  I'd suggest merging this PR and move ahead with the release.

**Pull request merged**
