### PR TITLE
mca: fix for broken -am option

### PR DESCRIPTION
**Pull request by mike-dubman**
based on https://github.com/open-mpi/ompi/pull/532

### CODE REVIEW

**Comment by mellanox-github** [comment]
- Coverity found 1472 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_219/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_219/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_219/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/219/

**Build Log**
_last 50 lines_

```
[...truncated 141774 lines...]
+ echo 'test the dist mapping policy in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
test the dist mapping policy in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ dirname ./jenkins_scripts/jenkins/ompi/ompi_jenkins.sh
+ rel_path=./jenkins_scripts/jenkins/ompi
++ readlink -f ./jenkins_scripts/jenkins/ompi
+ abs_path=/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi
+ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test.c
++ ibstat -l
+ for hca_dev in '$(ibstat -l)'
+ set +e
+ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpirun -np 8 --map-by dist -mca rmaps_dist_device mlx4_0 /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test
--------------------------------------------------------------------------
The specified mapping policy is not recognized:

  Policy: dist

Please check for a typo or ensure that the option is a supported
one.
--------------------------------------------------------------------------
+ val=213
+ set -e
+ '[' 213 -ne 0 ']'
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpirun -np 8 --map-by dist -mca rmaps_dist_device mlx4_0 /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test
++ grep Skip
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
+ exit 1
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/219/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/219/tap-master-files/cov_stat.tap].
not ok - coverity detected 1472 failures in all_219 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_219/output/errors/index.html
not ok - coverity detected 23 failures in oshmem_219 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_219/output/errors/index.html
ok - coverity found no issues for mxm_219
not ok - coverity detected 7 failures in fca_219 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_219/output/errors/index.html
ok - coverity found no issues for hcoll_219

TAP Reports Processing: FINISH
coverity_for_all    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_219/output/errors/index.html
coverity_for_oshmem http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_219/output/errors/index.html
coverity_for_fca    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_219/output/errors/index.html
Setting commit status on GitHub for https://api.github.com/repos/open-mpi/ompi-release/commit/9269b0810d32f398874948329c5aa3451f30744c
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of a9993f27bee8397868c42b1f58a5780f786438b4 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/219/ and message: Merged build finished.
```

Test FAILed.

**Comment by mike-dubman** [comment]
@elenash - could you please fix jenkins script to test if dist flag available before using it?
thanks

**Comment by elenash** [comment]
@miked-mellanox I will fix jenkins script but we don't need to add this fix to ompi_release since it's needed only when both amca and tune options present. Ompi-release doesn't have -tune option.

**Comment by mike-dubman** [comment]
ok. so we will drop this PR soon, just keep it for testing jenkins script

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1472 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_220/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_220/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_220/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/220/
Test PASSed.

**Pull request closed without merging**
