### PR TITLE
Ensure the command args are correct when user provide -Djava.library.path=foo argument

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1699/ for details.

**Comment by rhc54** [comment]
Patch is identical to https://github.com/open-mpi/ompi-release/pull/1185, which has been tested by reporting user

👍

**Comment by hppritcha** [comment]
looks good!

**Comment by hppritcha** [comment]
@jsquyres ready to go

**Pull request merged**
