### PR TITLE
Fix a segfault during comm_spawn when we possibly send a message with a NULL callback function

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by rhc54** [comment]
Fixes https://github.com/open-mpi/ompi/issues/2030

**Comment by sjeaugey** [comment]
Should indeed fix my spawn crash in v2.x. Thanks. :+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2149/ for details.

**Comment by jsquyres** [comment]
Happiness -- this clears the way for v2.0.1.

**Pull request merged**
