### PR TITLE
README and VERSION updates for v2.0.1

### PR DESCRIPTION
**Pull request by jsquyres**
@hppritcha Any comments?

### CODE REVIEW

**Comment by hppritcha** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha Gives a 👍  in IM.  This is README / NEWS only; not waiting for CI.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2135/ for details.

**Pull request merged**
