### PR TITLE
mtl/ofi: Merge changes from master

### PR DESCRIPTION
**Pull request by yburette**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1088/ for details.

**Comment by hppritcha** [comment]
@yburette please assign a reviewer

**Comment by yburette** [comment]
bot:label:bug
bot:assignee:hppritcha

**Comment by hppritcha** [comment]
:+1:

**Comment by hppritcha** [comment]
@jsquyres this is good to go

**Pull request merged**
