### PR TITLE
It is valid to modify the remote segment that will be used with the

### PR DESCRIPTION
**Pull request by hjelmn**
btl put/get operations as long as the resulting address range falls in
the originally prepared segment. Vader should have been calculating the
offset of the remote address in the registered region. This commit
fixes this issue.

Backported from open-mpi/ompi@cfbb9cba1610e8452b28950f0f3eb4de63671293

### CODE REVIEW

**Comment by hjelmn** [comment]
@ggouaillardet This should fix the offset issue with oshmem. Please review after jenkins confirms.

**Comment by mike-dubman** [comment]
test_vader

**Comment by hjelmn** [comment]
@miked-mellanox Thanks for triggering the vader tests. With this commit vader should now work fully with oshmem when using knem.

**Comment by mellanox-github** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/26/
Test PASSed.

**Comment by hjelmn** [comment]
Added one more fix. This one adds remote write access to prepare_src regions. This is the only way we can work around the issue @ggouaillardet found.

**Comment by hjelmn** [comment]
test_vader

**Comment by mellanox-github** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/28/
Test PASSed.

**Comment by hjelmn** [comment]
@miked-mellanox did jenkins actually test the case that was previously failing?

**Comment by hjelmn** [comment]
Looks like it didn't test vader.

Please retest this with vader

**Comment by mike-dubman** [comment]
@hjelmn checking... moment

**Comment by mike-dubman** [comment]
retest this please

**Comment by mellanox-github** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/29/

**Build Log**
_last 50 lines_

```
[...truncated 26440 lines...]
                MCA spml: parameter "spml_yoda_free_list_num" (current value: "1024", data source: default, level: 9 dev/all, type: int)
                MCA spml: parameter "spml_yoda_free_list_max" (current value: "1024", data source: default, level: 9 dev/all, type: int)
                MCA spml: parameter "spml_yoda_free_list_inc" (current value: "16", data source: default, level: 9 dev/all, type: int)
                MCA spml: parameter "spml_yoda_bml_alloc_threshold" (current value: "3", data source: default, level: 9 dev/all, type: int)
                          number of puts to wait                                       in case of put/get temporary buffer                                       allocation failture
                MCA spml: parameter "spml_yoda_priority" (current value: "10", data source: default, level: 9 dev/all, type: int)
                          [integer] yoda priority
              MCA sshmem: parameter "sshmem" (current value: "", data source: default, level: 2 user/detail, type: string)
                          Default selection set of components for the sshmem framework (<none> means use all components that can be found)
              MCA sshmem: parameter "sshmem_base_verbose" (current value: "0", data source: default, level: 8 dev/detail, type: int)
                          Verbosity level for the sshmem framework (0 = no verbosity)
              MCA sshmem: parameter "sshmem_base_start_address" (current value: "4278190080", data source: default, level: 9 dev/all, type: unsigned long long, synonyms: memheap_base_start_address)
                          Specify base address for shared memory region
              MCA sshmem: parameter "sshmem_base_backing_file_dir" (current value: "/dev/shm", data source: default, level: 9 dev/all, type: string)
                          Specifies where backing files will be created when mmap is used and shmem_mmap_anonymous set to 0.
              MCA sshmem: parameter "sshmem_mmap_priority" (current value: "20", data source: default, level: 3 user/all, type: int)
                          Priority for sshmem mmap component (default: 20)
              MCA sshmem: parameter "sshmem_mmap_anonymous" (current value: "1", data source: default, level: 4 tuner/basic, type: int)
                          Select whether anonymous sshmem is used for mmap component (default: 1)
              MCA sshmem: parameter "sshmem_mmap_fixed" (current value: "1", data source: default, level: 4 tuner/basic, type: int)
                          Select whether fixed start address is used for shmem (default: 1)
              MCA sshmem: parameter "sshmem_sysv_priority" (current value: "30", data source: default, level: 3 user/all, type: int)
                          Priority for the sshmem sysv component (default: 30)
              MCA sshmem: parameter "sshmem_sysv_use_hp" (current value: "-1", data source: default, level: 4 tuner/basic, type: int)
                          Huge pages usage [0 - off, 1 - on, -1 - auto] (default: -1)
              MCA sshmem: parameter "sshmem_verbs_priority" (current value: "40", data source: default, level: 3 user/all, type: int)
                          Priority for sshmem verbs component (default: 40)
              MCA sshmem: parameter "sshmem_verbs_hca_name" (current value: "", data source: default, level: 3 user/all, type: string, synonyms: memheap_base_hca_name)
                          Preferred hca (default: the first)
              MCA sshmem: parameter "sshmem_verbs_mr_interleave_factor" (current value: "2", data source: default, level: 3 user/all, type: int, synonyms: memheap_base_mr_interleave_factor)
                          try to give at least N Gbytes spaces between mapped memheaps of other PEs that are local to me (default: 2)
              MCA sshmem: parameter "sshmem_verbs_shared_mr" (current value: "-1", data source: default, level: 4 tuner/basic, type: int)
                          Shared memory region usage [0 - off, 1 - on, -1 - auto] (default: -1)
+ local 'common_mca=--bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M'
+ local 'mca=--bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M'
+ timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,tcp /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_strided_puts
target on PE 1 is 1 3 5 7 9
+ '[' no == no ']'
+ timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,sm /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_strided_puts
target on PE 1 is 1 3 5 7 9
+ '[' yes == yes ']'
+ timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,vader /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_strided_puts
--------------------------------------------------------------------------
SHMEM_ABORT was invoked on rank 0 (pid 10590, host=jenkins01) with errorcode -1.
--------------------------------------------------------------------------
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by hjelmn** [comment]
@miked-mellanox Is there any way to get more detail on the failure?

**Comment by mike-dubman** [comment]
``` shell
21:20:55 + timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,vader /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_strided_puts
21:20:55 --------------------------------------------------------------------------
21:20:55 SHMEM_ABORT was invoked on rank 0 (pid 10590, host=jenkins01) with errorcode -1.
21:20:55 --------------------------------------------------------------------------

```

**Comment by mike-dubman** [comment]
@hjelmn - click on http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/29/ ("Details") link and got to Console from the left. can provide you with ssh access if needed (send me your ssh public key)

**Comment by hjelmn** [comment]
retest this please

**Comment by hjelmn** [comment]
@ggouaillardet Should be fixed now.

**Comment by mellanox-github** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/30/
Test PASSed.

**Comment by ggouaillardet** [comment]
retest this with vader

**Comment by hjelmn** [comment]
I see vader in the test :)

**Comment by hjelmn** [comment]
04:56:45 + timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,vader /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_symmetric_data
04:56:46 Target on PE 4 is  0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  
04:56:46 Target on PE 2 is  0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  
04:56:46 Target on PE 5 is  0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  
04:56:46 Target on PE 7 is  0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  
04:56:46 Target on PE 3 is  0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  
04:56:46 Target on PE 6 is  0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  
04:56:46 Target on PE 1 is  0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15

**Comment by hjelmn** [comment]
@ggouaillardet Thanks again for bringing this to my attention. I want vader working with more than just ob1 in v1.8

**Comment by jsquyres** [comment]
Is that good / the correct answer?

On Nov 12, 2014, at 10:00 PM, Nathan Hjelm notifications@github.com wrote:

> 04:56:45 + timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,vader /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_symmetric_data
> 04:56:46 Target on PE 4 is 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
> 
> 04:56:46 Target on PE 2 is 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
> 
> 04:56:46 Target on PE 5 is 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
> 
> 04:56:46 Target on PE 7 is 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
> 
> 04:56:46 Target on PE 3 is 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
> 
> 04:56:46 Target on PE 6 is 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
> 
> 04:56:46 Target on PE 1 is 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by hjelmn** [comment]
@jsquyres I believe so. Before this commit it was aborting.

**Comment by rhc54** [comment]
@hjelmn So where does this sit? Are we ready to accept this solution and commit it?

**Comment by hjelmn** [comment]
Given that it passes the mellanox test I think this is ready to go

**Pull request merged**
