### PR TITLE
Add MPI_THREAD_MULTIPLE support for btl/usnic.

### PR DESCRIPTION
**Pull request by thananon**
This PR add multithreaded support to btl/usnic.

### CODE REVIEW

**Comment by thananon** [comment]
bot:milestone:v2.1

**Comment by thananon** [comment]
bot:milestone:v2.1.0

**Comment by jsquyres** [comment]
👍 

@hppritcha While Cisco would love this to go into v2.0.1 😄 , it's clearly a new feature/enhancement, so it is destined for v2.1.0.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1784/ for details.

**Comment by thananon** [comment]
Added 1 commit to fix common symbol.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1801/ for details.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2049/ for details.

**Comment by jsquyres** [comment]
This PR made moot by #1326 (so that @thananon does not need to maintain the PR branch).

**Pull request closed without merging**
