### PR TITLE
Revive the coll/sync component, adding a test to show it. Clean some permissions

### PR DESCRIPTION
**Pull request by rhc54**
@matcabral This is the v1.10 version of the coll/sync restoration, if we need it

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2111/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2112/ for details.

**Comment by rhc54** [comment]
Per same change for v2.x

👍

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2116/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2113/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2120/ for details.

**Comment by matcabral** [comment]
Works as expected. Note that to get the sync coll to be used, both config options must be set: coll_sync_priority and  coll_sync_barrier_before

**Comment by jsquyres** [comment]
bot:ibm:retest

**Pull request merged**
