### PR TITLE
MTL portals4 : remove useless PtlMDBind PtlMDRelease calls for rendez…

### PR DESCRIPTION
**Pull request by francois-wellenreiter**
…-vous messages

### CODE REVIEW

**Comment by francois-wellenreiter** [comment]
equivalent to PR open-mpi/ompi#1120 in ompi repository

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1066/ for details.

**Comment by hppritcha** [comment]
@regrant please double check

**Comment by regrant** [comment]
:+1:

**Pull request merged**
