### PR TITLE
MPI_Win_{get,set}_info : add man pages

### PR DESCRIPTION
**Pull request by hjelmn**
Add missing man pages.

### CODE REVIEW

**Comment by hjelmn** [comment]
:bot:assign: @ggouaillardet

**Comment by hjelmn** [comment]
:bot:milestone: v2.x

**Comment by hjelmn** [comment]
:bot:milestone:v2.x

**Comment by hjelmn** [comment]
:bot:milestone:v2.0

**Comment by hjelmn** [comment]
:bot:milestone:v2.0.0

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
