### PR TITLE
v2.x: fortran: Fix many Fortran binding bugs

### PR DESCRIPTION
**Pull request by kawashima-fj**
PR for v2.0.0

@jsquyres please review

bot:label:bug
bot:milestone:v2.0.0

Not critical; can be delayed to v2.0.1

(cherry picked from commit open-mpi/ompi@4566286 and open-mpi/ompi@e854404)

### CODE REVIEW

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1521/ for details.

**Comment by jsquyres** [comment]
@di0gen This looks like some kind of local Mellanox jenkins failure.  

bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1524/ for details.

**Pull request merged**
