### PR TITLE
Fixes for MPI_THREAD_MULTIPLE on v1.8 branch

### PR DESCRIPTION
**Pull request by jsquyres**
This PR contains three main things:
1. Revert 01b41a4653e5215dbff1c53d1acbacad16adcd53 and bc16fa81a99c8f4d3268b0790b86fd778ed2e707.  Those 2 commits actually _removed_ a valuable MPI_THREAD_MULTIPLE fix and only fixed the performance problem of always enabling locks indirectly.  Hence, we need to revert these commits and put back the valuable MPI_THREAD_MULTIPLE fix, and fix the performance issue a different way.
2. Improve the performance of free lists by only using atomics in MPI_THREAD_MULTIPLE scenarios
3. Move the OPAL thread level setup earlier in ompi_mpi_init() so that _everything_ is setup with the same thread level infrastructure

The first 2 commits are just reverts; they clearly needed to happen.  Nathan wrote the last 2 commits; Jeff reviewed them (and made very minor style changes).  There are no corresponding master commits because this is a v1.8-specific issue.

@hjelmn please sanity check this PR/commits to ensure I got it all correct.

### CODE REVIEW

**Comment by jsquyres** [comment]
@miked-mellanox @alinask @jladd-mlnx All of you were watching this issue, so I thought I'd notify you on the PR that hopefully fixes it.  Can you verify that your MPI_THREAD_MULTIPLE tests run again with this PR?

**Comment by jsquyres** [comment]
@afriedle-intel Andrew -- can you verify that your PSM message rate is still ok with this PR?

**Comment by mellanox-github** [comment]
Merged build triggered.

**Comment by mellanox-github** [comment]
Merged build started.

**Comment by mellanox-github** [comment]
Merged build finished. Test PASSed.

**Comment by mellanox-github** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/12/
Test PASSed.

**Comment by bosilca** [comment]
I have 2 questions:
1. Why did you enabled the atomic operation in the base object class?
2. Why the debug versions of our mutex accessors have been removed (e.g. opal_thread_debug_trylock)?

**Comment by jsquyres** [comment]
@hjelmn and I chatted briefly -- @bosilca raises good points. New patch(es) coming shortly from Nathan...

**Comment by mike-dubman** [comment]
retest this please

**Comment by mellanox-github** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/17/

**Build Log**
_last 50 lines_

```
[...truncated 30126 lines...]
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o overlap overlap.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o no_overlap.o no_overlap.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o no_overlap no_overlap.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o conc_allred.o conc_allred.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o conc_allred conc_allred.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o conc_allred_th.o conc_allred_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o conc_allred_th conc_allred_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o collcomp.o collcomp.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o collcomp collcomp.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o message_rate.o message_rate.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o message_rate message_rate.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o message_rate_th.o message_rate_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o message_rate_th message_rate_th.o
+ popd
/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace
+ for exe in overlap latency latency_th bw_th message_rate_th
+ exe_path=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ PATH=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin:/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ LD_LIBRARY_PATH=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/lib:
+ mpi_runner 2 /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
+ local np=2
+ local exe_path=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ local exe_args=8
++ ompi_info --param pml all --level 9
++ grep yalla
++ wc -l
+ local val=0
++ ibstat -l
+ for hca_dev in '$(ibstat -l)'
+ local hca=mlx4_0:1
+ local 'mca=-bind-to core -mca btl_openib_if_include mlx4_0:1 -x MXM_RDMA_PORTS=mlx4_0:1'
+ '[' -f /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap ']'
+ echo 'Running /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8'
Running /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
+ timeout -s SIGKILL 3m mpirun -np 2 -bind-to core -mca btl_openib_if_include mlx4_0:1 -x MXM_RDMA_PORTS=mlx4_0:1 -mca pml cm -mca mtl mxm /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
Time per iteration on each process (ms)
Time     Compute time    Comm time
222.11   218.62      3.50 
222.11   219.20      2.91 
+ timeout -s SIGKILL 3m mpirun -np 2 -bind-to core -mca btl_openib_if_include mlx4_0:1 -x MXM_RDMA_PORTS=mlx4_0:1 -mca pml ob1 -mca btl self,tcp /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
[warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
[warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
Time per iteration on each process (ms)
Time     Compute time    Comm time
./hpc_tests/jenkins/ompi/ompi_jenkins.sh: line 78: 11361 Killed                  $timeout_exe mpirun -np $np $mca -mca pml ob1 -mca btl self,tcp ${exe_path} ${exe_args}
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by mike-dubman** [comment]
this PR fixed problem for mxm, but not for tcp (see last 10 lines of the jenkins log.
Does tcp btl supports threading?

**Comment by rhc54** [comment]
@jsquyres @hjelmn Any progress on this? I'd like to get this resolved so we can test/validate it.

**Comment by rhc54** [comment]
I have replaced this PR with one on my repo. It is based on this code, but includes changes per George's comments.

**Pull request closed without merging**
