### PR TITLE
patcher/overwrite: use OPAL_ASSEMBLY_ARCH to determine architecture

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

(cherry picked from commit open-mpi/ompi@7349ddc93779bece4ec9909a8ede40c3eae61d4d)

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

This PR will be used for updating the overwrite patcher component to fix xlc support. Please only +1 this once the issue is fixed.

:bot:label:bug
:bot:milestone:v2.0.1
:bot:assign: @PHHargrove

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1782/ for details.

**Comment by PHHargrove** [comment]
@hjelmn  Sorry, but no change with this PR.
I can only assume the XLC problem is something entirely different.

My time to work with this is somewhat limited right now.
I recall that @jjhursey also has XLC access - maybe he can help out.

-Paul

**Comment by PHHargrove** [comment]
Some additional info:

On the big-endian system "xlc -m32" is doing fine testing PR1232.
So, the problem is ppc64-specific.

The little-endian system does not have -m32 support:

```
/opt/ibm/xlC/13.1.2/bin/.orig/xlc: error: 1501-280 The -m32 option is not supported on this platform. Compilation cannot proceed.
```

**Comment by hjelmn** [comment]
I think it has to do with _CALL_ELF == 2. It doesn't seem to be defined by gcc-5.3 but it might be defined by the xlc pre-processor. @jjhursey Probably can look into this and figure out why the toc stuff isn't working with xlc on ppc64.

**Comment by PHHargrove** [comment]
> I think it has to do with _CALL_ELF == 2.... it might be defined by the xlc pre-processor.

Nope:

```
$ xlc -qshowmacros -E hello.c | grep ELF
#define __ELF__ 1
```

**Comment by artpol84** [comment]
bot:retest

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1854/ for details.

**Comment by jsquyres** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
Jenkins was rebooted, need to retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1883/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1891/ for details.

**Comment by jsquyres** [comment]
@hjelmn @PHHargrove Has this been reviewed / did it fix the problem?

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2008/ for details.

**Comment by hjelmn** [comment]
@jsquyres It doesn't fix the XLC problem but it is good to go if you are ok with it. This commit makes the architecture checks consistent.

**Comment by hppritcha** [comment]
nominally reviewed

**Comment by jsquyres** [comment]
False Travis failure -- we fixed this in the .travis.yml a while ago, but Travis builds don't take the .travis.yml from the top of the merged tree.

**Pull request merged**
