### PR TITLE
Updated psm2 mtl with new externally exposed symbols of psm2.so

### PR DESCRIPTION
**Pull request by matcabral**
This change already merged in ompi master branch.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1050/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1051/ for details.

**Comment by jsquyres** [comment]
@matcabral Can you squash these two commits down into one?

**Comment by matcabral** [comment]
sure, I was a little reluctant to push -f. I will do it.

**Comment by jsquyres** [comment]
@matcabral Usually, being reluctant to `push -f` is a Good Thing.  :smile: Just about the only acceptable time to do a `push -f` is on a pull request (i.e., before it hits the public, immutable history).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1056/ for details.

**Comment by matcabral** [comment]
the was merged in ompi:master mpi/ompi@8ebcac1b2c8f79c866c058e81afe58a19abd94ff

**Comment by matcabral** [comment]
bot:milestone:v1.10.2

**Comment by matcabral** [comment]
bot:assign:@rhc54

**Pull request merged**
