### PR TITLE
v2.x accumulate ordering

### PR DESCRIPTION
**Pull request by hjelmn**
This PR brings over support for the accumulate_ordering info key. To support parsing the info key I am also proposing bringing over MCA base support for flag variable enumerators. This info key is the only MPI-3.1 standard key missing.

:bot:assign: @jsquyres 
:bot:label:enhancement
:bot:milestone:v2.0.1

### CODE REVIEW

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1701/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1704/ for details.

**Comment by jsquyres** [comment]
@hjelmn Do we have any tests for this new functionality?  Also, this looks like a big new feature -- is it really v2.0.1, or should it be v2.1.0?

**Comment by hjelmn** [comment]
It might be too big for 2.0.1. I forgot that we didn't bring flag enumerators over to 2.0.0. We do want the info key though but it is hard to separate out since the enumerator does all the parsing and validation.

**Comment by jsquyres** [comment]
Is it ok to defer that key to v2.1.0?

**Comment by hjelmn** [comment]
Probably. I want the key for completeness but we really need the info rework to make sure the correct value is returned to the user.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2050/ for details.

**Comment by jsquyres** [comment]
I added the "pushed back" label because it was slated for v2.0.1 -- now that it's slated for v2.1.0, I'll remove the pushed back label.  @hjelmn can you get this reviewed?

**Comment by jsquyres** [comment]
The `ompi-release` repo is now closed; all release branches have been moved to the `ompi` repo (https://github.com/open-mpi/ompi).  Please re-open this PR on the corresponding branch on the `ompi` repo.

**Comment by jsquyres** [comment]
This repo is now closed.

**Pull request closed without merging**
