### PR TITLE
v2.x: fix make distclean when using external pmix/hwloc/libevent

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1834/ for details.

**Comment by ggouaillardet** [comment]
:label:bug
:milestone:v2.0.1
:assign:@jsquyres

**Comment by ggouaillardet** [comment]
:bot:label:bug
:bot:milestone:v2.0.1
:bot:assign:@jsquyres

**Comment by jsquyres** [comment]
👍

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1872/ for details.

**Comment by jsquyres** [comment]
@jladd-mlnx @artpol84 @Di0gen The Mellanox Jenkins doesn't look happy:

```
10:00:44 /bin/sh: fork: retry: Resource temporarily unavailable
```

**Comment by artpol84** [comment]
@jsquyres 
Thank you. I'll check today/tomorrow.

**Comment by artpol84** [comment]
bot:retest

**Comment by hppritcha** [comment]
please hold off on the bot retest stuff.  there's a very big backlog of jobs now on the IU jenkins server.  Currently there is a backlog of 38 distchecks trying to grind through the UH server.

**Comment by artpol84** [comment]
Sorry, I launched one more on the other PR. Won't start any new now.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1881/ for details.

**Comment by artpol84** [comment]
@Di0gen @jladd-mlnx there is a problem with `mlx4_0:1`. According to `ibv_devinfo` it is in the  `PORT_INIT` state. Maybe related to the reboot. The error for `mlx4_0:1` is:

```
WARNING: There is at least non-excluded one OpenFabrics device found,
but there are no active ports detected (or Open MPI was unable to use
them).  This is most certainly not what you wanted.  Check your
cables, subnet manager configuration, etc.  The openib BTL will be
ignored for this job.

  Local host: jenkins01
```

`mlx4_0:2` is active but I'm getting the following error:

```
--------------------------------------------------------------------------
No OpenFabrics connection schemes reported that they were able to be
used on a specific port.  As such, the openib BTL (OpenFabrics
support) will be disabled for this port.

  Local host:           jenkins01
  Local device:         mlx4_0
  Local port:           2
  CPCs attempted:       rdmacm, udcm
```

@Di0gen can you please check from hardware side?

**Comment by artpol84** [comment]
@jsquyres all retests on PR's that I've activated yesterday failed with the same error. It seems like a configuration issue. We will check this after the weekend.

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1885/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1886/ for details.

**Comment by artpol84** [comment]
@Di0gen thank you!

**Pull request merged**
