### PR TITLE
Fix the INDEXED_BLOCK issue identified by Satis Balay

### PR DESCRIPTION
**Pull request by jsquyres**
(cherry picked from commit open-mpi/ompi@015d3f56cf749ee5ad9ea4428d2f5da72f9bbe08)

Submitted by Satish Balay @balay, reviewed by @bosilca

### CODE REVIEW

**Comment by jsquyres** [comment]
Add @balay (found Satish's Github ID)

**Comment by mellanox-github** [comment]
- Coverity found 1467 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_264/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_264/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_264/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by jsquyres** [comment]
I fixed the title of this issue and the commit message associated with this PR: the bug was found by Satish Balay, Argonne -- not IBM.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/264/

**Build Log**
_last 50 lines_

```
[...truncated 58219 lines...]
FAIL: dlopen_test
============================================================================
Testsuite summary for Open MPI 1.8.5rc4
============================================================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ompi/debuggers/test-suite.log
Please report to http://www.open-mpi.org/community/help/
============================================================================
make[5]: *** [test-suite.log] Error 1
make[5]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/openmpi-1.8.5rc4/_build/sub/ompi/debuggers'
make[4]: *** [check-TESTS] Error 2
make[4]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/openmpi-1.8.5rc4/_build/sub/ompi/debuggers'
make[3]: *** [check-am] Error 2
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/openmpi-1.8.5rc4/_build/sub/ompi/debuggers'
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/openmpi-1.8.5rc4/_build/sub/ompi'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/openmpi-1.8.5rc4/_build/sub'
make: *** [distcheck] Error 1
Make distcheck failed.  Aborting
+ exit 11
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/264/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/264/tap-master-files/cov_stat.tap].
not ok - coverity detected 1467 failures in all_264 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_264/output/errors/index.html
not ok - coverity detected 23 failures in oshmem_264 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_264/output/errors/index.html
ok - coverity found no issues for mxm_264
not ok - coverity detected 7 failures in fca_264 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_264/output/errors/index.html
ok - coverity found no issues for hcoll_264

TAP Reports Processing: FINISH
coverity_for_all    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_264/output/errors/index.html
coverity_for_oshmem http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_264/output/errors/index.html
coverity_for_fca    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_264/output/errors/index.html
Setting commit status on GitHub for https://github.com/open-mpi/ompi-release/commit/bfb0f444587c83c11002e2cfa9347aa16b51c679
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of a2b6b4e8591274abb4e5c5c79fe8b7d5e0c5024f to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/264/ and message: Merged build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
- Coverity found 1467 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_265/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_265/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_265/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/265/

**Build Log**
_last 50 lines_

```
[...truncated 58219 lines...]
PASS: predefined_gap_test
============================================================================
Testsuite summary for Open MPI 1.8.5rc4
============================================================================
# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ompi/debuggers/test-suite.log
Please report to http://www.open-mpi.org/community/help/
============================================================================
make[5]: *** [test-suite.log] Error 1
make[5]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace-2/openmpi-1.8.5rc4/_build/sub/ompi/debuggers'
make[4]: *** [check-TESTS] Error 2
make[4]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace-2/openmpi-1.8.5rc4/_build/sub/ompi/debuggers'
make[3]: *** [check-am] Error 2
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace-2/openmpi-1.8.5rc4/_build/sub/ompi/debuggers'
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace-2/openmpi-1.8.5rc4/_build/sub/ompi'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace-2/openmpi-1.8.5rc4/_build/sub'
make: *** [distcheck] Error 1
Make distcheck failed.  Aborting
+ exit 11
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/265/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/265/tap-master-files/cov_stat.tap].
not ok - coverity detected 1467 failures in all_265 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_265/output/errors/index.html
not ok - coverity detected 23 failures in oshmem_265 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_265/output/errors/index.html
ok - coverity found no issues for mxm_265
not ok - coverity detected 7 failures in fca_265 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_265/output/errors/index.html
ok - coverity found no issues for hcoll_265

TAP Reports Processing: FINISH
coverity_for_all    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_265/output/errors/index.html
coverity_for_oshmem http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_265/output/errors/index.html
coverity_for_fca    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_265/output/errors/index.html
Setting commit status on GitHub for https://github.com/open-mpi/ompi-release/commit/bfb0f444587c83c11002e2cfa9347aa16b51c679
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 9636140b606f155be96b27247a73c5f9a5247b4e to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/265/ and message: Merged build finished.
```

Test FAILed.

**Comment by jsquyres** [comment]
@bosilca Is still working on a complete fix.

**Comment by bosilca** [comment]
I have pushed a complete fix for #268  and #267 on the comments in #267. Once tested they should be good to go.

**Comment by jsquyres** [comment]
This PR is now fully contained in #267.

I'm closing this as a dup.

**Pull request closed without merging**
