### PR TITLE
Improve the transport key print statement to ensure that we don't get zero fields as this can be a problem for PSM

### PR DESCRIPTION
**Pull request by rhc54**
(cherry picked from commit open-mpi/ompi@29bc24bdd503ced62ad40465085a1cb0249e26b0)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1610/ for details.

**Comment by hppritcha** [comment]
@jsquyres this fixes omnipath problems we were seeing with our clusters.  I suggest merging after CI completes.

**Comment by hppritcha** [comment]
this fixes the 1 rank problem I was seeing on omnipath. :+1:
It doesn't fix the multi-rank on one node problem - which was expected.

**Comment by hppritcha** [comment]
@jsquyres good to go

**Comment by rhc54** [comment]
@hppritcha Are you then still blocked on going into production? Or do you have a temporary path forward until the complete fix is released?

**Comment by hppritcha** [comment]
@rhc54 the sysadmins applied that patch from open-mpi/ompi#1578 and rebuilt the ompi 1.10.  That suffices for them now.  We do need this fix once the psm2 is fixed and we can go back to unpatched ompi.  So no, not blocked.

**Comment by hppritcha** [comment]
To be clearer, this fix should go in to 1.10.3 and 2.0.0.

**Comment by matcabral** [comment]
fixes  open-mpi/ompi#1559 epid=0 issue

**Comment by matcabral** [comment]
bot:milestone:v1.10.3

**Comment by matcabral** [comment]
bot:milestone:v2.0.0

**Comment by matcabral** [comment]
bot:milestone:v1.10.3

**Comment by matcabral** [comment]
bot:milestone:v2.0.0

**Pull request merged**
