### PR TITLE
v2.x: fix pmix typos and timeout

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by rhc54** [comment]
If we are going to handle the timeout up in the server, then we probably need to remove it from the pmix base function else we'll have a race to see who times out first.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1985/ for details.

**Comment by ggouaillardet** [comment]
i updated the PR,
now if you `OPAL_PMIX_EXCHANGE(...,0)` then `MPI_Comm_accept()` and `MPI_Comm_connect()` might hang forever.

under the hood, the timeout is triggered in `pmix` by `libevent`, and then it invokes the `orted` eviction callback.
if the timeout is 60 seconds, a timeout event will be generated every 2 seconds, and `orted` will check-in again into the opal hotel until the 60 seconds timeout expires.
if there is no pmix timeout, then the orted eviction callback is never called.

i do not understand what you mean by race condition.
the pmix timeout calls the orted "timeout" (simple function call, not through `libevent`)

**Comment by ggouaillardet** [comment]
Refs open-mpi/ompi#1905

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1986/ for details.

**Comment by rhc54** [comment]
You are absolutely correct - my bad. I was mistakenly thinking that we also did a timeout event down in the opal layer as well.

Can you please bring the relevant parts back to master as well?

Thanks!

👍

**Comment by jsquyres** [comment]
Please comment back here on this PR after this stuff has been committed to master and gone through a night of MTT.

**Comment by rhc54** [comment]
went into master now

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Pull request merged**
