### PR TITLE
ompi_check_package update

### PR DESCRIPTION
**Pull request by jsquyres**
Per the @PHHargrove's thread starting here: http://www.open-mpi.org/community/lists/devel/2015/04/17299.php, both dl components fail to configure/build for him on his *BSD systems.

I believe that it is because we did not bring over open-mpi/ompi@ed3809a2 and open-mpi/ompi@d6530b0e.

This PR brings over those 2 commits, which changes to use AC_SEARCH_LIBS in our main configury package checker m4 macro.  This should fix @PHHargrove's problem.

bot:hargrove

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/241/

**Build Log**
_last 50 lines_

```
[...truncated 963 lines...]
otflib_py/Makefile.am:13: installing 'config/py-compile'
autoreconf: Leaving directory `.'
--- Patching autotools output... :-(
    Patching PGI compiler version numbers in ltmain.sh
    Patching configure for Libtool PGI 10 fortran compiler name
    Patching configure for Libtool PGI version number regexps
    Patching configure for Sun Studio Fortran version strings ()
    Patching configure for Sun Studio Fortran version strings (_F77)
    Patching configure for Sun Studio Fortran version strings (_FC)
    Patching configure for IBM xlf libtool bug
Running: cp configure.patched configure

7. Running autotools on top-level tree

==> Remove stale files
==> Writing m4 file with autogen.pl results
==> Generating opal_get_version.sh
Running: autom4te --language=m4sh opal_get_version.m4sh -o opal_get_version.sh
==> Running autoreconf
Running: autoreconf -ivf --warnings=all,no-obsolete,no-override -I config
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I config --force --warnings=all,no-obsolete,no-override -I config
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `config'.
libtoolize: copying file `config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `config'.
libtoolize: copying file `config/libtool.m4'
libtoolize: copying file `config/ltoptions.m4'
libtoolize: copying file `config/ltsugar.m4'
libtoolize: copying file `config/ltversion.m4'
libtoolize: copying file `config/lt~obsolete.m4'
autoreconf: running: /hpc/local/bin/autoconf --include=config --force --warnings=all,no-obsolete,no-override
configure:67089: error: possibly undefined macro: AC_SEARCH_LIB
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /hpc/local/bin/autoconf failed with exit status: 1
Command failed: autoreconf -ivf --warnings=all,no-obsolete,no-override -I config
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
Setting commit status on GitHub for https://github.com/open-mpi/ompi-release/commit/7cda06006a20f993a02238d6c9ea4e48a6248f81
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of d69e724e820bcbd6420254a7fbd3a4551fe5c360 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/241/ and message: Merged build finished.
```

Test FAILed.

**Comment by PHHargrove** [comment]
"bot:hargrove" acknowledged.
will report....

**Comment by PHHargrove** [comment]
My autogen fails just as Jenkins shows (except +1 on the line number):

```
configure:67088: error: possibly undefined macro: AC_SEARCH_LIB
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

**Comment by rhc54** [comment]
@jsquyres it should be AC_SEARCH_LIBS - note the 'S' at the end

**Comment by PHHargrove** [comment]
I am testing now with the application of `s/AC_SEARCH_LIB/AC_SEARCH_LIBS/` to `config/ompi_check_package.m4`.
I can at least confirm that autogen runs to completion now :grin: 
Pushed to PHHargrove/ompi-release@ea4795ff8960b16b4dfd7d2a49ed2e5747fabc27

**Comment by PHHargrove** [comment]
Using the commit I noted above, I get correct configure behavior on at least one NetBSD and one Linux system.  I will try _all_ of my BSD systems soon (modulo dinner and things like that).

**Comment by PHHargrove** [comment]
:+1: 
All {Free,Open,Net}BSD systems which failed with 1.8.5rc2 are OK with this PR applied plus the missing-S correction (PHHargrove/ompi-release@ea4795ff8960b16b4dfd7d2a49ed2e5747fabc27).

**Comment by PHHargrove** [comment]
:-1: 
Arrgh!!  We've openned a can of worms here.

@jsquyres you probably remember this one from when we were working to remove libltdl on master:

```
--- MCA component mtl:psm (m4 configuration macro)
checking for MCA component mtl:psm compile mode... dso
checking --with-psm value... sanity check ok (/usr/local/Infinipath)
checking --with-psm-libdir value... simple ok (unspecified)
checking psm.h usability... yes
checking psm.h presence... yes
checking for psm.h... yes
looking for library in lib
checking for library containing psm_finalize... no
looking for library in lib64
checking for library containing psm_finalize... (cached) no
configure: error: PSM support requested but not found.  Aborting
```

So, there is still at least one more commit to bring over.

**Comment by PHHargrove** [comment]
OK, not a missing commit but rather another typo in the manual application of open-mpi/ompi@d6530b0.

Specifically `ac_cv_search_lib_` should have been `ac_cv_search_` (without the `lib_`).
I am re-testing now (and have pushed to PHHargrove/ompi-release@a1b456d).

**Comment by PHHargrove** [comment]
:sob: OK, that previous try wasn't right either.
Still poking for at least an hour before I may give up and through it back to Jeff.

**Comment by PHHargrove** [comment]
It looks like my previous attempt was exactly what was needed to match master.
@jsquyres feel free to squash my two typo-fix commits and pretend you got it right on the first try.

_However_, `_OPAL_CHECK_PACKAGE_LIB` is broken on master, too.
So PHHargrove/ompi-release@a1b456d merged to v1.8 _still_ fails w.r.t. psm_finalize.
It looks like Jeff missed (due to voting on MPI-3.1, IIRC) following up on that issue in PR410 (a.k.a. jsquyres/topic/libltdl-must-die) on master.  However, I get the blame for not catching that in testing.

Specifically, master needs the following (pushed as PHHargrove/ompi@f2eef72):

``` diff
--- a/config/opal_check_package.m4
+++ b/config/opal_check_package.m4
@@ -66,9 +66,7 @@ AC_DEFUN([_OPAL_CHECK_PACKAGE_LIB], [
     # This is stolen from autoconf to peek under the covers to get the
     # cache variable for the library check.  one should not copy this
     # code into other places unless you want much pain and suffering
-    AS_LITERAL_IF([$2],
-                  [AS_VAR_PUSHDEF([opal_Lib], [ac_cv_search_$2_$3])],
-                  [AS_VAR_PUSHDEF([opal_Lib], [ac_cv_search_$2''_$3])])dnl
+    AS_VAR_PUSHDEF([opal_Lib], [ac_cv_search_$3])

     # see comment above
     unset opal_Lib
```

and v1.8 needs the `s/opal/ompi/` equivalent (pushed as  PHHargrove/ompi-release@e169ce0)

My testing shows PHHargrove/ompi-release@e169ce0, merged to master, works on {Free,Net,Open}BSD _and_ on my mtl:psm test platform.

@jsquyres I am turning this back over to you.

I don't know if you want to update this PR with all three of my commits and apply the patch above to master, or fix master first and pull that fix.   Personally, I think it would be easiest to deal with v1.8 and master separately since the `ompi` -> `opal` rename (file _and_ variable) means a custom patch is required anyway.

Summary:
- ompi-release/v1.8 works for me after merging PHHargrove/ompi-release@e169ce0
- ompi/master works for me with the patch above applied (PHHargrove/ompi@f2eef72)

**Comment by jsquyres** [comment]
@PHHargrove @rhc54 Arrgh... I had already caught the LIB->LIBS fix locally, but somehow neglected to push it up to github.  Sorry about that.  :-(

The `ac_cv_search_$3` fix -- oops, missed that altogether.  I applied that to master and I added that commit to this PR (adapted to opal/master -> ompi/v1.8), too.

**Comment by jsquyres** [comment]
bot:hargrove

**Comment by mellanox-github** [comment]
- Coverity found 1468 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_243/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_243/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_243/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/243/

**Build Log**
_last 50 lines_

```
[...truncated 141918 lines...]
Success rank - 5: only one NUMA is scheduled.

Success rank - 2: only one NUMA is scheduled.

Success rank - 1: only one NUMA is scheduled.
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[38640,1],7]
  Exit code:    1
--------------------------------------------------------------------------
[jenkins01:14354] 7 more processes have sent help message help-mpi-btl-openib.txt / default subnet prefix
[jenkins01:14354] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[jenkins01:14354] 7 more processes have sent help message help-mpi-runtime.txt / mpi_init:warn-fork
+ val=1
+ set -e
+ '[' 1 -ne 0 ']'
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpirun -np 8 --map-by dist:mlx5_0 /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test
++ grep Skip
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
+ exit 1
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/243/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/243/tap-master-files/cov_stat.tap].
not ok - coverity detected 1468 failures in all_243 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_243/output/errors/index.html
not ok - coverity detected 23 failures in oshmem_243 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_243/output/errors/index.html
ok - coverity found no issues for mxm_243
not ok - coverity detected 7 failures in fca_243 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_243/output/errors/index.html
ok - coverity found no issues for hcoll_243

TAP Reports Processing: FINISH
coverity_for_all    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_243/output/errors/index.html
coverity_for_oshmem http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_243/output/errors/index.html
coverity_for_fca    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_243/output/errors/index.html
Setting commit status on GitHub for https://github.com/open-mpi/ompi-release/commit/8d8ce7f90edc93986588f05bdb0935f71c68553c
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 969feade4731edc276b62d7787fd26f94f512d65 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/243/ and message: Merged build finished.
```

Test FAILed.

**Comment by jsquyres** [comment]
@miked-mellanox This looks like a false Jenkins failure, too.  Is it registering as "fail" because the a few of the tests are calling fork(), and therefore emitting a show_help() message warning about that?  And/or the warnings about default subnet IDs?

**Comment by mike-dubman** [comment]
yep, @elenash just fixed it.
https://github.com/mellanox-hpc/jenkins_scripts/pull/8

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1468 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_247/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_247/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_247/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by rhc54** [comment]
@jsquyres I think you referenced the wrong pull request above as the two don't relate, so I'm going to ignore that reference.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/247/
Test PASSed.

**Comment by jsquyres** [comment]
I think we're just waiting for @PHHargrove testing now.

**Comment by jsquyres** [comment]
...or not.  :-)

**Comment by PHHargrove** [comment]
My day is just starting here and I will test from the merge commit open-mpi/ompi-release@2f02bc3 ASAP.  Visual inspection looks good.

**Comment by PHHargrove** [comment]
My retests on *BSD and the mtl:psm platform are in-flight now.
However, I am quite confident that there will be no problems this time.

As for "waiting ...or not.": `git diff 969feade e169ce06`  shows that the tree at Jeff's last commit of the PR is identical to the that of my commit that I reported having tested successfully.  So, I think @rhc54 was justified in merging without further delay.

**Comment by jsquyres** [comment]
Cool.  The "waiting... or not" was just humorous because I entered my comment almost exactly at the same time as Ralph merged.  :-)

**Comment by PHHargrove** [comment]
So as not to leave anybody in suspense:
The {Free,Net,Open}BSD and mtl:psm platforms all pass at open-mpi/ompi-release@2f028c3
[and my reference to a different commit hash a few comments back was a typo: 'b' for '8']

**Comment by jsquyres** [comment]
Yay!

**Pull request merged**
