### PR TITLE
v2.x: Do not return MPI_ERR_PENDING from collectives

### PR DESCRIPTION
**Pull request by ggouaillardet**
Also add some extra optimizations

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1972/ for details.

**Comment by jsquyres** [comment]
@ggouaillardet PR #1014 got moved to v2.1.0 because no one has replied as to whether it's good or not.  This PR doesn't have a milestone or classification associated with it.

**Comment by ggouaillardet** [comment]
:bot:label:bug
:bot:assign:@bosilca
:bot:milestone:v2.1

this PR and #1014 are exclusive !

**Comment by ggouaillardet** [comment]
:bot:milestone:v2.1.0

**Comment by abouteiller** [comment]
https://github.com/open-mpi/ompi/commit/80b267af1c8b432fe7c649dcb7375c31d5964a62#commitcomment-17800982

**Comment by ggouaillardet** [comment]
i updated the PR (backport open-mpi/ompi@60e91e890a45bb540a4ce942209420a03123fefa as discussed in open-mpi/ompi@80b267a#commitcomment-17800982, and rebased it to the latest v2.x)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2017/ for details.

**Comment by abouteiller** [comment]
👍

**Comment by jsquyres** [comment]
@ggouaillardet @abouteiller Just to clarify: these are all bug fixes, right?  I.e., this PR is suitable for v2.0.2?

**Comment by ggouaillardet** [comment]
three are bug fixes and two are optimizations (irecv/send instead of irecv/isend)
some bug fixes do fix the optimization...
milestone should be v2.0.2 (assuming it is too late for v2.0.1)

**Comment by ggouaillardet** [comment]
note the optimizations avoid the initial issue, so it is a double win, both in term of performance and code maintanability

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Comment by jsquyres** [comment]
@hppritcha and I talked -- approved.

**Pull request merged**
