### PR TITLE
BTL portals4: remove useless PtlMDBind PtlMDRelease calls for RMDA

### PR DESCRIPTION
**Pull request by francois-wellenreiter**

### CODE REVIEW

**Comment by francois-wellenreiter** [comment]
equivalent to PR open-mpi/ompi#1139 in ompi repository

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1067/ for details.

**Comment by hppritcha** [comment]
@regrant please double check

**Comment by regrant** [comment]
:+1: Looks good

**Pull request merged**
