### PR TITLE
fix spawn on heterogeneous clusters 

### PR DESCRIPTION
**Pull request by ggouaillardet**
fix spawn in heterogeneous clusters by retrieving the remote arch

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1359/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1360/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1361/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1362/ for details.

**Comment by ggouaillardet** [comment]
:bot:assign: @rhc54 
:bot:milestone:v2.0.0
:bot:label:bug

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
@ggouaillardet Can you supply a proper title and description for this PR?

**Comment by ggouaillardet** [comment]
done

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1392/ for details.

**Comment by jsquyres** [comment]
@rhc54 Can you have a look at this one, too?

**Comment by rhc54** [comment]
@jsquyres Looks fine to me

**Pull request merged**
