### PR TITLE
btl/openib: queue pending fragments once only when running out of credit

### PR DESCRIPTION
**Pull request by ggouaillardet**
Fixes open-mpi/ompi#640

(cherry picked from commit open-mpi/ompi@9f171de4125643345c605637356234499182ee6d)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @hjelmn

**Comment by ggouaillardet** [comment]
:bot:label:bug
:bot:milestone:v2.0.0

**Comment by ggouaillardet** [comment]
:bot:label:bug
:bot:milestone:v2.0.0

**Comment by mike-dubman** [comment]
bot:retest

**Comment by hppritcha** [comment]
Jeff/Howard decided today (7/6/15) to let this cook in master for a week. If no problems seen, will merge at that time.

**Comment by hppritcha** [comment]
time to merge

**Pull request merged**
