### PR TITLE
ompi/opal/orte/oshmem/test: max hostname length cleanup

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
:bot:milestone:v2.0.1

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1585/ for details.

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1905/ for details.

**Comment by jsquyres** [comment]
Git clone / RPC fail at Mellanox.  Trying again...

bot:retest

**Comment by jsquyres** [comment]
Belated 👍

**Pull request merged**
