### PR TITLE
opal_check_portals.m4: remove this unused file

### PR DESCRIPTION
**Pull request by jsquyres**
It looks like OPAL_CHECK_PORTALS is not used anywhere; it looks like it has been completely replaced by opal_check_portals4.m4 (OPAL_CHECK_PORTALS4).

(cherry picked from commit open-mpi/ompi@225c684ccc27d5d415ff22a9aecda550b076cedd)

@regrant @tkordenbrock please confirm that this removal is ok.  I committed this on master in Nov 2014 -- looks like it never made it over to v1.8 (and therefore didn't make it to v1.10).

### CODE REVIEW

**Comment by tkordenbrock** [comment]
Looks good.  :thumbsup:

**Comment by jsquyres** [comment]
@tkordenbrock Hah! I didn't know about the "thumbsup" version of the emoticon.  If you do the "+1", version, the bot will add the "reviewed" label, and it uses the same emoticon as "thumbsup".  Like this: :+1: 

(I'll go add "thumbsup" to the bot's vocabulary...)

**Comment by tkordenbrock** [comment]
@jsquyres  Ahh.  I guess that explains why the auto-complete suggested "+1" as I was typing "thumbsup".

**Comment by jsquyres** [comment]
@tkordenbrock FWIW, check out https://github.com/open-mpi/ompi/wiki/OmpiReleaseBotCommands

**Pull request merged**
