### PR TITLE
configury: fix fortran binding checks for ompi extensions

### PR DESCRIPTION
**Pull request by ggouaillardet**
(cherry picked from commit open-mpi/ompi@66ef1c3c558023dc5ea8ff9f9bb3544bbadce7cf)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @jsquyres 
:bot:milestone:v2.0.0
:bot:label:bug

**Comment by hppritcha** [comment]
looks like the nersc system is having issues, let's retry.

bot:retest

**Comment by hppritcha** [comment]
not sure what's going on with nersc.  The jenkins 
lanl-cray-xc check can be ignored for now.

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
