### PR TITLE
Remove the orte/qos framework and associated changes that should not …

### PR DESCRIPTION
**Pull request by rhc54**
…have been included in the 2.x series

Includes following reverts:
    open-mpi/ompi@9cb2fcfa5c5c327d5afc58e6039c3f0693a42021.
    open-mpi/ompi@01a9bdf4cf74693014d73e5a93b7df31e274638b.
    open-mpi/ompi@1f8de27

### CODE REVIEW

**Comment by hppritcha** [comment]
:+1:

**Comment by jsquyres** [comment]
It's hard to tell what exactly changed here... :-(  Is there any chance of removing the whitespace changes from this commit?  I ask not just to be a nit pick, but re-introducing all this white space will make it a little more troublesome to bring over future PRs from master.

**Comment by rhc54** [comment]
@jsquyres I would cleanup the whitespace, but Nathan's script (contrib/whitespace-purge.sh) doesn't work. All I get is:

```
sed: can't read s/[[:space:]]*$//: No such file or directory
```

I'm no sed expert - can someone take a look at that command and fix it?

**Comment by jsquyres** [comment]
I just committed an updated whitespace-purge.sh script on master; can you use that?

**Comment by rhc54** [comment]
@jsquyres @hppritcha Should be good to go now...

**Comment by jsquyres** [comment]
Ugh.  That made it even more difficult to see what the real changes were.  :-(

Oh well.

**Pull request merged**
