### PR TITLE
v2.0.0: init finalize mutex plus mutex static initializer

### PR DESCRIPTION
**Pull request by jsquyres**
Bring over @hjelmn's static mutex initializer and the MPI_INITIALIZED / MPI_FINALIZED updates for MPI-3.1.

Master commit IDs are in the commit messages.  See open-mpi/ompi#1026 (static mutex initializer) and open-mpi/ompi#1007 (INITIALIZED / FINALIZED updates).

@hjelmn @bosilca Please review.

### CODE REVIEW

**Comment by bosilca** [comment]
There are few other static mutexes in the code initialized to {{0}}. Do we want to change them to OPAL_MUTEX_STATIC_INIT ?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/859/ for details.

**Comment by hjelmn** [comment]
@bosilca Yes, we probably should. Especially since {{0}} is equivalent to not specifying an initializer at all.

I will take a look and PR that change separately.

:+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Pull request merged**
