### PR TITLE
fortran: do not build the f08 bindings if PMPI is not built

### PR DESCRIPTION
**Pull request by ggouaillardet**
(cherry picked from commit open-mpi/ompi@2d1a8fa920325b785553abce0b3408010d1f5b6b)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/794/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/795/ for details.

**Comment by ggouaillardet** [comment]
:bot:assign: @jsquyres 
:bot:label:bug
:bot:milestone:v1.10.1

**Comment by ggouaillardet** [comment]
the `--enable-mpi-profile` option will soon be removed from `master` and `v2.x` so i am not planning to PR this for the `v2.x` branch

**Comment by jsquyres** [comment]
See comments on open-mpi/ompi@2d1a8fa920325b785553abce0b3408010d1f5b6b

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/814/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/815/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/817/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/816/ for details.

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/818/ for details.

**Comment by ggouaillardet** [comment]
:bot:nolabel:pushed-back

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/823/ for details.

**Comment by jsquyres** [comment]
Ah, you updated this per open-mpi/ompi#990.  Same minor nit that I noted there: don't use "" around $MPI_MPI_PROFILING.

**Comment by jsquyres** [comment]
@ggouaillardet and I chatted on open-mpi/ompi@2d1a8fa -- we agreed to fix this in v2.0.0 and not worry about it for v1.10.x.

**Comment by ggouaillardet** [comment]
@jsquyres there is a misunderstanding ...
currently, v1.10 configure does not abort if the user requests let's say usempif08 binding but this bindings cannot be built. this is solved in master and v2.x, and i am fine not to backport this to the v1.10 series.
this PR is about not building usempif08 if PMPI is not built, and though this is quite a minor issue, it is also a minor fix and i think it should make it for 1.10.1

**Pull request closed without merging**
