### PR TITLE
Adding entry points for Allgatherv, iAllgatherv, Reduce, and iReduce.

### PR DESCRIPTION
**Pull request by jladd-mlnx**
Signed-off-by: Joshua Ladd jladd.mlnx@gmail.com

Conflicts:
    ompi/mca/coll/hcoll/coll_hcoll.h
    ompi/mca/coll/hcoll/coll_hcoll_ops.c

:cherries: -picked from ompi-mpi/ompi@e398bf6

### CODE REVIEW

**Comment by jladd-mlnx** [comment]
bot:milestone:v2.0
bot:label:enhancement
bot:assign:@hppritcha

**Comment by mike-dubman** [comment]
@jladd-mlnx - please integrate it into v1.10 as well.
thanks

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1261/ for details.

**Comment by jladd-mlnx** [comment]
bot:milestone:v2.0.0

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1265/ for details.

**Comment by jladd-mlnx** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1267/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1268/ for details.

**Comment by mike-dubman** [comment]
:+1:

**Comment by hppritcha** [comment]
Is this an enhancement along the lines of the PR #913?  If it is, the milestone for this PR should be 2.1.0.
In any case, could you please squash down to 1 commit?  The main reason for this is one of the commits is getting rid of merge conflict lines.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1304/ for details.

**Comment by jladd-mlnx** [comment]
Closing this and opening a new one:
https://github.com/open-mpi/ompi-release/pull/942

**Pull request closed without merging**
