### PR TITLE
opal_config_asm.m4: enable inline assembly on little endian POWER

### PR DESCRIPTION
**Pull request by nysal**
Suggested by Paul Hargrove,
http://www.open-mpi.org/community/lists/devel/2015/04/17323.php,
amended by Nysal Jan for 32 bit, too.

### CODE REVIEW

**Comment by nysal** [comment]
This is based on the following commit: open-mpi/ompi@f7b8c11027b73c04f136506eecf38b071e284151

**Comment by nysal** [comment]
:bot:assign: @rhc54

**Comment by nysal** [comment]
bot:milestone:v1.8.5

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/253/

**Build Log**
_last 50 lines_

```
[...truncated 9 lines...]
 > /usr/bin/git --version # timeout=60
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git697364303038693730.credentials # timeout=60
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/open-mpi/ompi-release +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
 > /usr/bin/git config remote.origin.url https://github.com/open-mpi/ompi-release # timeout=60
 > /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config remote.origin.url https://github.com/open-mpi/ompi-release # timeout=60
Pruning obsolete local branches
Fetching upstream changes from https://github.com/open-mpi/ompi-release
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git6859546705344018038.credentials # timeout=60
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/open-mpi/ompi-release +refs/pull/*:refs/remotes/origin/pr/* --prune # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/open-mpi/ompi-release
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:735)
    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:983)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1016)
    at hudson.scm.SCM.checkout(SCM.java:484)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
    at hudson.model.Run.execute(Run.java:1741)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:374)
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/open-mpi/ompi-release +refs/pull/*:refs/remotes/origin/pr/* --prune" returned status code 128:
stdout: 
stderr: error: Failed connect to github.com:443; Operation now in progress while accessing https://github.com/open-mpi/ompi-release/info/refs?service=git-upload-pack
fatal: HTTP request failed

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1591)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1379)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:86)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:324)
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:733)
    ... 11 more
ERROR: Error fetching remote repo 'origin'
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
Setting commit status on GitHub for https://github.com/open-mpi/ompi-release/commit/ad524807d09b53f1ecb74b0502985f428ddf0bdf
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 62f0f09188c3536eb3386eae59497bc3bbc223a6 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/253/ and message: Merged build finished.
```

Test FAILed.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1468 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_254/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_254/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_254/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/254/
Test PASSed.

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
