### PR TITLE
coll/hcoll mpi datatypes support

### PR DESCRIPTION
**Pull request by vspetrov**
cherry picked from ompi/master

### CODE REVIEW

**Comment by vspetrov** [comment]
bot:milestone:2.0.1

**Comment by jladd-mlnx** [comment]
bot:milestone:v2.0.1

**Comment by jladd-mlnx** [comment]
bot:label:reviewed

**Comment by jladd-mlnx** [comment]
@hppritcha This is a bug in the HCOLL datatype handling that our MTT picked up.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2109/ for details.

**Pull request merged**
