### PR TITLE
Fix relative node syntax for dash-host option

### PR DESCRIPTION
**Pull request by rhc54**
(cherry picked from commit open-mpi/ompi@24419b6523260d0e35e49408b52c660875bb78a9)

Add a new MCA parameter for default_dash_host to offer a mirror of the default_hostfile

(cherry picked from commit open-mpi/ompi@8bfbe7f16cfd62f565c66e88c8c03f2d481795b8)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/950/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/962/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/975/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/976/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/982/ for details.

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
