### PR TITLE
v1.10 MPI_Aint functions

### PR DESCRIPTION
**Pull request by hjelmn**
These merged cleanly into v1.10 so there is no reason they shouldn't be included even though they are MPI-3.1.

:bot:assign: @jsquyres 
:bot:milestone:v1.10.1
:bot:label:enhancement

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/840/ for details.

**Comment by jsquyres** [comment]
@rhc54 What's your feeling about accepting these in 1.10.1?  They're technically _new_ (i.e., they're part of MPI-3.1).  The functionality is pretty simple -- I think the highest risk is ensuring that we have all the Fortran bindings correct.

@hjelmn Do we have any regression tests for these functions in the IBM test suite for the different C and Fortran bindings?

**Comment by hjelmn** [comment]
Not in MTT. To test these I ran the tests in the mpich test suite.

**Comment by jsquyres** [comment]
They have tests for these functions in all 3 Fortran bindings?  Can we import those into the IBM suite in MTT?

**Comment by hjelmn** [comment]
I believe we can import them. I thought we held off because we were discussing importing the whole test suite.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/845/ for details.

**Comment by jsquyres** [comment]
MTT IBM MPI_Aint_\* tests coming shortly.

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
