### PR TITLE
fortran/mpif-h: Insert missing weak symbols & Fix incorrect symbol names.

### PR DESCRIPTION
**Pull request by kawashima-fj**
PR for v2.0.0

@jsquyres please review

(cherry picked from commit open-mpi/ompi@66a8bc9e4549464535601e8d2918d417da36567b)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/866/ for details.

**Comment by jsquyres** [comment]
:+1: 

bot:label:bug
bot:milestone:v1.10.1

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Comment by jsquyres** [comment]
Oops -- I set the wrong milestone above.  I re-set it to v2.x.

**Pull request merged**
