### PR TITLE
VERSION: update sonames for upcoming v1.8.6

### PR DESCRIPTION
**Pull request by jsquyres**
- libmpi code changed, but API did not
  - Therefore: increase revision (middle digit)
- java library code changed, but API did not
  - Therefore: increase revision (middle digit)
- common cude code changes, but API did not
  - Therefore: increase revision (middle digit)

### CODE REVIEW

**Comment by mellanox-github** [comment]
- Coverity found 1465 errors for all
- Coverity found 23 errors for oshmem
- Coverity found 7 errors for fca
- Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//305/Coverity_Report <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/305/
Test PASSed.

**Comment by rolfv** [comment]
Looks OK to me, although your comments seem a little off.  You are updating the revision, not the age.  And you updated the liboshmem revision, but your comment says you are changing java.

**Comment by jsquyres** [comment]
Oops -- you're right; the middle number is "revision", not "age".  Oops!

**Comment by mellanox-github** [comment]
- Coverity found 1465 errors for all
- Coverity found 23 errors for oshmem
- Coverity found 7 errors for fca
- Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//306/Coverity_Report <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/306/
Test PASSed.

**Comment by mellanox-github** [comment]
- Coverity found 1465 errors for all
- Coverity found 23 errors for oshmem
- Coverity found 7 errors for fca
- Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//308/Coverity_Report <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/308/
Test PASSed.

**Pull request merged**
