### PR TITLE
Topic/ikrit err fix v1.10

### PR DESCRIPTION
**Pull request by alex-mikheev**
check return of mxm_req_send correctly, memcheck support
Ported from master
https://github.com/open-mpi/ompi/pull/1126
@miked-mellanox 

:bot:label:bug
:bot:milestone:v1.10.2

### CODE REVIEW

**Comment by mike-dubman** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1013/ for details.

**Comment by rhc54** [comment]
@miked-mellanox I just want to check my understanding of this PR's purpose. I gather this adds memchecker support to try and catch the problems you recently discovered? And it checks for error conditions on send - are those related to the problem?

**Comment by mike-dubman** [comment]
@rhc54 - exactly. it is a fix and valgrind macros that can find such issues during jenkins time. 
we plan to push such macros down to the freelist APIs that it can be useful for other freelist end-users as well.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1023/ for details.

**Comment by mike-dubman** [comment]
:+1:

**Pull request merged**
