### PR TITLE
Patchs on mtl portals4

### PR DESCRIPTION
**Pull request by PDeveze**
These patchs concern the mtl/portals4 module.

### CODE REVIEW

**Comment by rhc54** [comment]
Have these been committed to master yet? If so, please provide those commit hashes. If not, then please commit them to master first.

Thanks

**Comment by PDeveze** [comment]
This was done onthe v2.x branch. I will do the job on master and re-submit the pull request.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1827/ for details.

**Comment by PDeveze** [comment]
Is it really necessary that I re-submit the pull request on the master branch ?
I am a bit new on the process, and it seems that it is on the way to accept the pull-request on the v2.x branch.

**Comment by jsquyres** [comment]
Yes, sorry; we require commits on master before they are submitted to a release branch.  This might help: https://github.com/open-mpi/ompi/wiki/SubmittingPullRequests

FWIW: we have a separate "ompi-release" repo because Github previously hasn't supported per-branch ACLs.  Now that Github supports different permissions on each branch, we plan to merge the ompi-release repo back into the ompi repo (i.e., the release branches will just be regular branches in the ompi repo) sometime after the v2.0.0 release.

@regrant @tkordenbrock Please review this PR (and its corresponding master PR when it is filed).

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1833/ for details.

**Comment by PDeveze** [comment]
Thanks Jeff for your information !

**Comment by hppritcha** [comment]
@PDeveze please assign a milestone and a reviewer

**Comment by PDeveze** [comment]
As I make a PR on ompi, could you please close this PR ?
@jsquyres

**Pull request closed without merging**
