### PR TITLE
Pr/lustre and aggregatorlogic fix

### PR DESCRIPTION
**Pull request by edgargabriel**
This pr moves the fixes for the lustre fs component from master to the v2.x branch. Also, a minor fix required for some special cases of the two-phase collective I/O component has been included for the sake of compactness.

### CODE REVIEW

**Comment by hppritcha** [comment]
I'll double check on nersc systems.

**Comment by hppritcha** [comment]
experiment with enhancements to disable dlopen check on IU jenkins.
bot:retest

**Comment by hppritcha** [comment]
works for me on lustre. :+1:

**Comment by hppritcha** [comment]
@jsquyres  if no objects I'll merge this later today

**Comment by jsquyres** [comment]
works for me

**Pull request merged**
