### PR TITLE
Ensure singletons register their progress thread

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1777/ for details.

**Comment by hppritcha** [comment]
Is this patch required on master?

**Comment by hppritcha** [comment]
:+1:

**Comment by rhc54** [comment]
i'll check master - i don't think so, but will verify

**Comment by rhc54** [comment]
i don't understand that mellanox failure - it doesn't look related to anything with singleton

**Comment by hppritcha** [comment]
This is the cantankerous multi-threaded test that periodically hangs. 
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1779/ for details.

**Comment by hppritcha** [comment]
going ahead and merging so MTT can digest it.

**Pull request merged**
