### PR TITLE
ownership: update ownership files

### PR DESCRIPTION
**Pull request by hppritcha**
per discussions at OMPI devel workshop

Signed-off-by: Howard Pritchard howardp@lanl.gov

Conflicts:
    ompi/mca/bcol/base/owner.txt
    ompi/mca/bcol/iboffload/owner.txt
    ompi/mca/bcol/ptpcoll/owner.txt
    ompi/mca/sbgp/base/owner.txt
    ompi/mca/sbgp/basesmsocket/owner.txt
    ompi/mca/sbgp/basesmuma/owner.txt
    ompi/mca/sbgp/ibnet/owner.txt
    ompi/mca/sbgp/p2p/owner.txt
    opal/mca/reachable/base/owner.txt
    opal/mca/reachable/netlink/owner.txt
    opal/mca/reachable/weighted/owner.txt

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-release-v1.8-pr/359/

**Comment by hppritcha** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-release-v1.8-pr/361/

**Comment by hppritcha** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-release-v1.8-pr/362/

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-release-v1.8-pr/363/

**Pull request merged**
