### PR TITLE
Add keepalive support to the TCP OOB component

### PR DESCRIPTION
**Pull request by rhc54**
@goodell Hate to bother you - need an "okey-dokey" to bring this across to 1.8

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/165/

**Build Log**
_last 50 lines_

```
[...truncated 7624 lines...]
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/mca/odls/default'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/mca/odls/default'
Making install in mca/oob/tcp
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/mca/oob/tcp'
  CC       oob_tcp_component.lo
  CC       oob_tcp.lo
  CC       oob_tcp_listener.lo
  CC       oob_tcp_common.lo
  CC       oob_tcp_connection.lo
  CC       oob_tcp_sendrecv.lo
oob_tcp_common.c: In function 'orte_oob_tcp_set_socket_options':
oob_tcp_common.c:181: error: 'mca_oob_tcp_component_t' has no member named 'keepalive_time'
oob_tcp_component.c: In function 'tcp_component_register':
oob_tcp_component.c:407: error: 'mca_oob_tcp_component_t' has no member named 'keepalive_time'
oob_tcp_component.c:413: error: 'mca_oob_tcp_component_t' has no member named 'keepalive_time'
oob_tcp_component.c:415: error: 'mca_oob_tcp_component_t' has no member named 'keepalive_intvl'
oob_tcp_component.c:421: error: 'mca_oob_tcp_component_t' has no member named 'keepalive_intvl'
oob_tcp_component.c:422: error: 'mca_oob_tcp_component_t' has no member named 'keepalive_probes'
oob_tcp_component.c:428: error: 'mca_oob_tcp_component_t' has no member named 'keepalive_probes'
make[2]: *** [oob_tcp_common.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [oob_tcp_component.lo] Error 1
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/mca/oob/tcp'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte'
make: *** [install-recursive] Error 1
+ exit 10
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
Setting commit status on GitHub for https://github.com/open-mpi/ompi-release/commit/3159ec33ed86ed38cb25489d0f71b29dda06f6e3
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of decf1ded3a008945b41c50f2a55aba07469e6d4a to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/165/ and message: Merged build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
- Coverity found 1493 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_166/output/errors/index.html
- Coverity found 29 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_166/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_166/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by goodell** [comment]
It seems like it might be OK to me, but I'm concerned that this isn't exactly the same as open-mpi/ompi#477.  For example, these two things (which are really the same thing):
- the missed changes to oob_tcp_component.h (which you added 02f61e2 to fix)
- other cleanups in open-mpi/ompi#477 that are not currently present in this PR (whitespace, copyright updates, etc.)

If it helps, it might be easier to `git cherry-pick` the fix from master to v1.8...?  My eyeballs are usually a pretty lousy form of `interdiff`, so I like it when the tool can manage this for us.

**Comment by rhc54** [comment]
I actually tried to cherry-pick it, but it didn't come thru cleanly because it is in two commits. So I tried to make it match. I'll take a look and see what is different.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/166/
Test PASSed.

**Comment by goodell** [comment]
The osc_base_obj_convert.c change (open-mpi/ompi@0cfb4f2) doesn't apply cleanly, so you'd have to either fix the pick or ignore that particular tweak:

```
$ git log --graph --oneline --boundary ee23b7f^..ee23b7f
*   ee23b7f Merge pull request #477 from rhc54/topic/keepalive
|\  
| * 64d11f1 Adjust the default keepalive interval. Refactor the code when setting keepalive options
| * 4ded049 Modify MCA param description
| * 019bba5 Cleanup a bit - don't need to lookup the protocol number if we just use the right define
| * 69ac25b Add support for TCP keepalive on inter-node sockets
| * 0cfb4f2 Silence compiler warning
|/  
o 7640507 Merge pull request #472 from miked-mellanox/topic/fix_compile_warn

$ git cherry-pick 0cfb4f2..64d11f1
[tmp 48a850d] Add support for TCP keepalive on inter-node sockets
 Author: Ralph Castain <rhc@open-mpi.org>
 Date: Mon Mar 16 09:59:44 2015 -0700
 3 files changed, 122 insertions(+), 17 deletions(-)
[tmp 722ec75] Cleanup a bit - don't need to lookup the protocol number if we just use the right define
 Author: Ralph Castain <rhc@open-mpi.org>
 Date: Mon Mar 16 11:54:51 2015 -0700
 3 files changed, 5 insertions(+), 18 deletions(-)
[tmp 0c2e743] Modify MCA param description
 Author: Ralph Castain <rhc@open-mpi.org>
 Date: Mon Mar 16 11:57:32 2015 -0700
 1 file changed, 1 insertion(+), 1 deletion(-)
[tmp 5044e39] Adjust the default keepalive interval. Refactor the code when setting keepalive options
 Author: Ralph Castain <rhc@open-mpi.org>
 Date: Mon Mar 16 12:32:58 2015 -0700
 2 files changed, 71 insertions(+), 67 deletions(-)
```

IMO it would be best to then squash that using `git rebase` or similar, but that would just be for bonus points.

**Comment by rhc54** [comment]
Will try rebuilding the PR again

**Pull request closed without merging**
