### PR TITLE
v1.10: allow Open MPI to be built with pre C99 compilers

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2134/ for details.

**Comment by jsquyres** [comment]
@ggouaillardet Unless you have modified these commits, you should pull them directly from the source so that the attribution can be preserved.

**Comment by ggouaillardet** [comment]
good point.
only one was taken as is.
I will update the PR and cherry-pick the last one

**Comment by jsquyres** [comment]
The `ompi-release` repo is now closed; all release branches have been moved to the `ompi` repo (https://github.com/open-mpi/ompi).  Please re-open this PR on the corresponding branch on the `ompi` repo.

**Comment by jsquyres** [comment]
This repo is now closed.

**Pull request closed without merging**
