### PR TITLE
v2.x mpool rewrite rollup

### PR DESCRIPTION
**Pull request by hjelmn**
:bot:milestone:v2.1.0
:bot:label:enhancement
:bot:assign: @bosilca 

This PR may take a could of iterations before it is ready for 2.1.0.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1473/ for details.

**Comment by hjelmn** [comment]
:bot:milestone:v2.1.0

**Comment by hppritcha** [comment]
see open-mpi/ompi#1546 before merging this in.

**Comment by hjelmn** [comment]
Yup. Will add that commit today.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1533/ for details.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2051/ for details.

**Comment by hjelmn** [comment]
This needs to be rebased. Will do so once the ompi-release and ompi repos have been merged.

**Pull request closed without merging**
