### PR TITLE
Resolve thread safety in TCP BTL jenkins: threads, known_issues

### PR DESCRIPTION
**Pull request by rhc54**
Based on patch provided by George

### CODE REVIEW

**Comment by mike-dubman** [comment]
@rhc54 - could you please add to the PR title:

``` shell
jenkins: threads, known_issues
```

thanks

**Comment by mike-dubman** [comment]
retest this please

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/80/
Test PASSed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/81/

**Build Log**
_last 50 lines_

```
[...truncated 28642 lines...]
***    and potentially your MPI job)
[jenkins01:20235] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[57831,1],2]) is on host: jenkins01
  Process 2 ([[57831,1],0]) is on host: jenkins01
  BTLs attempted: self

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_INIT has failed because at least one MPI process is unreachable
from another.  This *usually* means that an underlying communication
plugin -- such as a BTL or an MTL -- has either not loaded or not
allowed itself to be used.  Your MPI job will now abort.

You may wish to try to narrow down the problem;

 * Check the output of ompi_info to see which BTL/MTL plugins are
   available.
 * Run your application with MPI_THREAD_SINGLE.
 * Set the MCA parameter btl_base_verbose to 100 (or mtl_base_verbose,
   if using MTL-based communications) to see exactly which
   communication plugins were considered and/or discarded.
--------------------------------------------------------------------------
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[57831,1],0]
  Exit code:    1
--------------------------------------------------------------------------
[jenkins01:20229] 3 more processes have sent help message help-mca-bml-r2.txt / unreachable proc
[jenkins01:20229] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[jenkins01:20229] 3 more processes have sent help message help-mpi-runtime / mpi_init:startup:pml-add-procs-fail
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by mike-dubman** [comment]
failed on openib tests, disabled openib as it does not support threads

**Comment by mike-dubman** [comment]
retest this please

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/82/

**Build Log**
_last 50 lines_

```
[...truncated 28900 lines...]
176      72.844982
192      40.736437
208      0.909567
224      56.456447
240      25.907516
256      200.769544
320      29.646516
384      30.555964
448      232.374430
512      77.667475
576      33.251524
640      1.622438
704      49.470425
768      79.387069
832      35.656095
896      50.986528
960      4.034042
1024     66.316485
+ '[' yes == yes ']'
+ timeout -s SIGKILL 3m mpirun -np 2 -bind-to core -mca pml ob1 -mca btl self,vader /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/latency_th 8
Size (bytes)     Time (us)
0    89.697957
16   44.736981
32   0.935555
48   0.939965
64   29.942989
80   190.623045
96   45.985937
112      1.000524
128      8.358479
144      24.026513
160      62.504053
176      1.014590
192      98.012447
208      1.007915
224      34.990430
240      1.014471
256      267.973542
320      28.094530
384      80.812931
448      74.415445
512      1.279473
576      29.374599
640      54.122090
./hpc_tests/jenkins/ompi/ompi_jenkins.sh: line 83:  6889 Killed                  $timeout_exe mpirun -np $np $mca -mca pml ob1 -mca btl self,vader ${exe_path} ${exe_args}
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by mike-dubman** [comment]
tcp passed, but not vader @hjelmn

**Comment by hppritcha** [comment]
Works for me on my mac and on a linux x86_64 box using self and tcp btls.

**Comment by rhc54** [comment]
This patch has nothing to do with vader so it's irrelevant

**Comment by mike-dubman** [comment]
retest this please

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/83/
Test PASSed.

**Pull request merged**
