### PR TITLE
configury: remove OPAL_SETUP_FT_* invokation

### PR DESCRIPTION
**Pull request by ggouaillardet**
This is a one off commit that finalizes open-mpi/ompi-release#714

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:label:code-cleanup
:bot:milestone:v2.0.0
:bot:assign: @hppritcha

**Comment by ggouaillardet** [comment]
:bot:label:Code-cleanup-low-priority

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1395/ for details.

**Comment by hppritcha** [comment]
:+1:

**Comment by hppritcha** [comment]
@jsquyres ready to go

**Pull request merged**
