### PR TITLE
mca/base: fix bugs in framework deregistration/re-registration

### PR DESCRIPTION
**Pull request by hjelmn**
cherry-picked from master commit open-mpi/ompi@ccba8ce856eab89ddc548f8c7cadf133f77965d2

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

### CODE REVIEW

**Comment by hjelmn** [comment]
@jsquyres Please review.

Fixes two issues:
- Correctly close all open frameworks with using MPI_T.
- Maintain ordering within groups as required by MPI-3.

**Comment by mellanox-github** [comment]
- Coverity found 1482 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_170/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_170/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_170/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/170/
Test PASSed.

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
bot:milestone:v1.8.5

**Pull request merged**
