### PR TITLE
BUILD: update mellanox platform file

### PR DESCRIPTION
**Pull request by mike-dubman**
- add UCX support

### CODE REVIEW

**Comment by mike-dubman** [comment]
:bot:assign: @rhc54 
:bot:milestone:v1.10.1
:bot:label:enhancement

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/892/ for details.

**Comment by jsquyres** [comment]
I don't see UCX on the v1.10 branch -- is it planned to be part of the v1.10.1 release?

**Comment by mike-dubman** [comment]
yep, we plan to submit tomorrow

**Comment by rhc54** [comment]
@miked-mellanox now don't take this the wrong way, but we cannot accept UCX in the 1.10.1 release. It's just too late for such a big change. We can consider it for 1.10.2, but I'm not sure when that will come out (definitely not before next year) and if we will even have such a release.

**Comment by mike-dubman** [comment]
@rhc54 - thanks for headsup, 1.10.2 is fine too.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/970/ for details.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/978/ for details.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/979/ for details.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/980/ for details.

**Comment by jsquyres** [comment]
UCX is still not in v1.10.x.

@rhc54 @miked-mellanox Per http://www.open-mpi.org/community/lists/devel/2015/11/18354.php, it sounds like this should be pushed to v1.10.3...?

**Comment by mike-dubman** [comment]
:bot:milestone:v1.10.3

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1041/ for details.

**Comment by rhc54** [comment]
Looks like there is no harm in bringing this across - it just won't do anything until UCX comes over.

**Pull request merged**
