### PR TITLE
PML UCX: fix typo (following 7becc54d).

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1128/ for details.

**Comment by alinask** [comment]
@miked-mellanox please review.

**Comment by mike-dubman** [comment]
:bot:assign: @hppritcha 
:bot:milestone:v2.0.0
:bot:label:bug

**Comment by mike-dubman** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Pull request merged**
