### PR TITLE
mtl/ofi: Cherry-pick changes from master.

### PR DESCRIPTION
**Pull request by yburette**
bot:milestone:v2.0.0
bot:label:bug

### CODE REVIEW

**Comment by yburette** [comment]
bot:milestone:v2.0.0

**Comment by jsquyres** [comment]
@miked-mellanox Looks like a local failure in the Mellanox Jenkins...?

**Comment by mike-dubman** [comment]
seems real:

``` shell
% ./configure --with-platform=contrib/platform/mellanox/optimized --with-ompi-param-check --enable-picky --enable-mpi-thread-multiple --enable-opal-multi-threads --prefix=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
...
% make -j32 install
...
20:09:21 make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal/asm'
20:09:21 rm -f atomic-asm.S
20:09:21   CC       asm.lo
20:09:21 /bin/sh: ../../config/depcomp: No such file or directory
20:09:21 ln -s "../../opal/asm/generated/atomic-local.s" atomic-asm.S
20:09:21 make[2]: *** [asm.lo] Error 127
20:09:21 make[2]: *** Waiting for unfinished jobs....
20:09:21 make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal/asm'
20:09:21 make[1]: *** [install-recursive] Error 1
20:09:21 make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal'
20:09:21 make: *** [install-recursive] Error 1
```

**Comment by jsquyres** [comment]
@miked-mellanox This PR has nothing to do with atomics.  2 of the 3 LANL Jenkins have finished successfully...

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mike-dubman** [comment]
maybe "make -j32 ..." has issues

**Comment by hppritcha** [comment]
I'll run usual sanity checks on one of the PSM systems at LANL tomorrow.

**Comment by hppritcha** [comment]
sanity checks work for me on LANL's  psm cluster both for psm and ofi mtls.
:+1:

**Pull request merged**
