### PR TITLE
oshmem: restore value of ompi_proc_local_proc before mpi

### PR DESCRIPTION
**Pull request by mike-dubman**
- fixes valgrind invalid read error from shmem_finalize flow

### CODE REVIEW

**Comment by mike-dubman** [comment]
:bot:assign: @rhc54 
:bot:milestone:v1.10.2
:bot:label:bug

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1009/ for details.

**Comment by mike-dubman** [comment]
fixed by @yosefe , reviewed by @alex-mikheev and myself

**Comment by mike-dubman** [comment]
:+1:

**Comment by rhc54** [comment]
@miked-mellanox Thanks, Mike. I know this isn't as elegant a fix as anyone would like, but it looks lower risk in that it impacts a lot less of the code base. I appreciate your taking time to create it.

**Comment by jladd-mlnx** [comment]
:+1: thanks, @miked-mellanox

**Pull request merged**
