### PR TITLE
v2.x - BUILD: allow platform patches

### PR DESCRIPTION
**Pull request by mike-dubman**
Master commit: open-mpi/ompi@7502d2a7

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/769/ for details.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mike-dubman** [comment]
:bot:milestone:v2.0.0
:bot:assign: @hppritcha 
:bot:label:enhancement

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/771/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/780/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
It looks like this PR was modified similar to open-mpi/ompi#961 and #620: i.e., AC_MSG_NOTICEs were changed to OPAL_LOG_MESSAGEs.  :-1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/790/ for details.

**Comment by jsquyres** [comment]
:+1: 

Thanks @miked-mellanox

**Pull request merged**
