### PR TITLE
Topic/v2.x/nag configury

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1857/ for details.

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1898/ for details.

**Comment by jsquyres** [comment]
Pushed back per https://github.com/open-mpi/ompi/issues/1884

**Comment by ggouaillardet** [comment]
PR was updated with the fix for open-mpi/ompi#1884

:bot:nolabel:pushed-back
:bot:assign: @jsquyres

**Comment by jsquyres** [comment]
👎 

This unfortunately broke the nightly build:

```
*** Wrapper compiler final setup
checking for perl... /usr/bin/perl
checking if linker supports RPATH... yes (-Wl,-rpath -Wl,LIBDIR + -Wl,-rpath -Wl,LIBDIR)
checking if linker supports RUNPATH... yes (-Wl,--enable-new-dtags)
libtool:   error: ignoring unknown tag FC--config
libtool:   error: you must specify a MODE
./conftest.2944.out: line 1: Usage:: command not found
./conftest.2944.out: line 2: Try: command not found
checking for OPAL CPPFLAGS...    
checking for OPAL CFLAGS... -pthread 
checking for OPAL CFLAGS_PREFIX... 
checking for OPAL CXXFLAGS... -pthread 
checking for OPAL CXXFLAGS_PREFIX... 
checking for OPAL LDFLAGS...     -Wl,-rpath -Wl,@{libdir} -Wl,--enable-new-dtags
checking for OPAL pkg-config LDFLAGS...     -Wl,-rpath -Wl,${libdir} -Wl,--enable-new-dtags
checking for OPAL LIBS... -lm -lutil -lrt 
checking for ORTE CPPFLAGS...    
checking for ORTE CFLAGS... -pthread 
checking for ORTE CFLAGS_PREFIX... 
checking for ORTE LDFLAGS...     -Wl,-rpath -Wl,@{libdir} -Wl,--enable-new-dtags
checking for ORTE pkg-config LDFLAGS...     -Wl,-rpath -Wl,${libdir} -Wl,--enable-new-dtags
checking for ORTE LIBS... -lm -lutil -lrt 
checking for OMPI CPPFLAGS...    
checking for OMPI CFLAGS... -pthread 
checking for OMPI CFLAGS_PREFIX... 
checking for OMPI CXXFLAGS... -pthread 
checking for OMPI CXXFLAGS_PREFIX... 
checking for OMPI FCFLAGS... -pthread  -I${libdir}
checking for OMPI FCFLAGS_PREFIX... 
checking for OMPI LDFLAGS...     -Wl,-rpath -Wl,@{libdir} -Wl,--enable-new-dtags
./configure: line 342881: syntax error near unexpected token `OMPI_WRAPPER_EXTRA_FC_LDFLAGS'
./configure: line 342881: `       RPATHIFY_FC_LDFLAGS(OMPI_WRAPPER_EXTRA_FC_LDFLAGS)'
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1953/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1954/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1961/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2073/ for details.

**Comment by ggouaillardet** [comment]
:bot:nolabel:pushed-back
:bot:noassign: @ggouaillardet
:bot:assign: @jsquyres 

@jsquyres i updated the PR (fix `autogen.sh --no-ompi` and a typo in the sed for NAG)
i guess that could be postponed for v2.0.2/v2.1

**Comment by hppritcha** [comment]
postponed it is.

**Comment by jsquyres** [comment]
@ggouaillardet I'm sorry; this has been a very low priority for me to review, and I just haven't gotten to it yet.  😦 

Would we be ok re-targeting this to v2.1.0?

**Comment by jsquyres** [comment]
The `ompi-release` repo is now closed; all release branches have been moved to the `ompi` repo (https://github.com/open-mpi/ompi).  Please re-open this PR on the corresponding branch on the `ompi` repo.

**Comment by ggouaillardet** [comment]
moved to open-mpi/ompi#2092 and open-mpi/ompi#2093

**Pull request closed without merging**
