### PR TITLE
coll/hcoll mpi datatypes support

### PR DESCRIPTION
**Pull request by vspetrov**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2001/ for details.

**Comment by jladd-mlnx** [comment]
bot:label:reviewed
@rhc54 - Please merge this PR.

**Comment by hppritcha** [comment]
what's the target milestone for this PR?

**Comment by jladd-mlnx** [comment]
bot:milestone:v1.10.4
@hppritcha 1.10.4, but it really doesn't matter if it's ever released. We pull from the head of 1.10.x regardless of release status, so having it merged is sufficient for us.

**Comment by rhc54** [comment]
Could you please point to the corresponding commit to master, and the bug that this addresses?

**Comment by jladd-mlnx** [comment]
open-mpi/ompi@3582bba6b77a2656d5

This commit fixes multiple issues with HCOLL datatype handling.

**Comment by rhc54** [comment]
thanks!

**Pull request merged**
