### PR TITLE
v1.10 - BUILD: allow platform patches

### PR DESCRIPTION
**Pull request by mike-dubman**
master commits: 
open-mpi/ompi@7502d2a7
open-mpi/ompi#961

### CODE REVIEW

**Comment by mike-dubman** [comment]
:bot:milestone:v1.10.1
:bot:assign: @jsquyres 
:bot:label:enhancement

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/770/ for details.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/772/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/778/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/779/ for details.

**Comment by jsquyres** [comment]
@miked-mellanox I don't actually like the functionality from open-mpi/ompi#961: per https://github.com/open-mpi/ompi/pull/961#issuecomment-144762788, I like the messages on stdout where users can actually see that patches were applied.

**Comment by jsquyres** [comment]
:-1:

**Comment by mike-dubman** [comment]
will use both macros for same string: NOTICE and LOG, will apply shorty.

**Comment by jsquyres** [comment]
Many thanks, @miked-mellanox

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/789/ for details.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/793/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/796/ for details.

**Comment by jsquyres** [comment]
Looks good now; thanks @miked-mellanox 

:+1:

**Pull request merged**
