### PR TITLE
Adding support for dynamic endpoint creation

### PR DESCRIPTION
**Pull request by jladd-mlnx**
open-mpi/ompi@3858bc8e625eb1531c4a2b
open-mpi/ompi@afa62d8ca107ffb05cadb6fb
open-mpi/ompi@18c5a215628a1ef9a8b28
Signed-off-by: Tomislav Janjusic tomislavj@mngx-apl-01.mtl.labs.mlnx
Signed-off-by: Tomislavj Janjusic tomislavj@mellanox.com
Signed-off-by: Joshua Ladd jladd.mlnx@gmail.com

### CODE REVIEW

**Comment by jladd-mlnx** [comment]
@yosefe @alex-mikheev @miked-mellanox 

Please review

**Comment by rhc54** [comment]
hey guys - just curious. you have been among the most adamant about everything coming into OMPI via a PR, yet this code went directly into master. may one ask why?

**Comment by jladd-mlnx** [comment]
@rhc54 My bad :see_no_evil: , was too focused on my :cherries:-picking and :hash: referencing.

**Comment by rhc54** [comment]
lol - couldn't resist :smiley_cat:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1216/ for details.

**Comment by jladd-mlnx** [comment]
:relaxed:

**Comment by yosefe** [comment]
we need to have mca parameter to enable/disable

**Comment by rhc54** [comment]
@yosefe We already have a param for this purpose, I believe: mpi_add_procs_cutoff is what is used elsewhere, if I understand this PR correctly. Would it work for you here?

**Comment by jladd-mlnx** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1220/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1221/ for details.

**Comment by jladd-mlnx** [comment]
@miked-mellanox @yosefe @janjust please review.

**Comment by mike-dubman** [comment]
:+1:

**Comment by yosefe** [comment]
:+1:

**Comment by yosefe** [comment]
@janjust @jladd-mlnx please add the fixes to master as well

**Comment by hppritcha** [comment]
Are the new commits in this PR based on feedback going to go back in to master?

**Comment by jladd-mlnx** [comment]
@hppritcha Yes, and I added the relevant hash to cross reference against in the first comment. See above.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1223/ for details.

**Pull request merged**
