### PR TITLE
coll/base: return MPI_ERR_UNSUPPORTED_OPERATION when coll_base_*_two_…

### PR DESCRIPTION
**Pull request by ggouaillardet**
…procs algo is used on a communicator that has no two tasks

Thanks Dave Love for the report

(cherry picked from commit open-mpi/ompi@0a193373715492ea89d9c39fde0453974d8ff214)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @bosilca 
:bot:label:bug
:bot:milestone:v2.0.1

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1641/ for details.

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1644/ for details.

**Comment by bosilca** [comment]
👍

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
bot:retest

**Comment by bosilca** [comment]
👍

**Comment by hppritcha** [comment]
travis 'sed' error not related to this PR and mlnx not running.

**Pull request merged**
