### PR TITLE
Pr/v2.x/alpsv3

### PR DESCRIPTION
**Pull request by marksantcroos**
This is a PR to v2.x cherry-picked from open-mpi/ompi/pull/1105/.

@hppritcha Sorry for the delay.

ps. This is my first PR towards ompi-release, so hopefully I did it correct :-)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1085/ for details.

**Comment by hppritcha** [comment]
:bot:assign: @hppritcha
:bot:milestone:v2.0.0

**Comment by hppritcha** [comment]
I'd like to see if this patch has a hope of working on rhine/redwood before merging in.

**Comment by hppritcha** [comment]
got verification from cray engineering that ALPS_APPINFO_VERSION is set to 3 on rhine/redwood at least for now.

**Comment by hppritcha** [comment]
modulo a borked batch scheduler, I was able to verify that this works for me on a Cray XC that still uses aprun.
:+1:
@jsquyres this is ready to go

**Comment by marksantcroos** [comment]
Thanks @hppritcha !

**Pull request merged**
