### PR TITLE
Update the Linux timer per the master and George's patch on the devel mailing list.

### PR DESCRIPTION
**Pull request by rhc54**
@bosilca Can you please review? Your patch on the devel mailing list did not apply cleanly to 1.10, so I tried my best to capture things from master.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1693/ for details.

**Comment by bosilca** [comment]
This is indeed an old patch open-mpi/ompi@00300f46. 👍

**Comment by rhc54** [comment]
Not sure of the source of the issue with pthread_atfork on Mellanox - not seeing an issue anywhere else. I will take a look, but don't have much time to spend on it. Suggest that perhaps Mellanox diagnose why their environments are missing it.

**Comment by rhc54** [comment]
Built it again just fine on CentOS7, so I suspect indeed that this is an issue of Mellanox not having a pthread library installed. Note also that this was in last night's tarball, and that no MTT failures were reported this morning.

**Comment by jladd-mlnx** [comment]
@rhc54 Negative, Ghostrider. We have pthread installed. 
$ls -l /usr/include/pthread.h
-rw-r--r-- 1 root root 40491 Nov  5  2013 /usr/include/pthread.h
$ls -l /usr/lib64/libpthread.so
-rw-r--r-- 1 root root 222 Nov  5  2013 /usr/lib64/libpthread.so

Git bisect squarely points to this PR.

**Comment by jsquyres** [comment]
@jladd-mlnx See open-mpi/ompi#1699.  Do you have someone who can look into this?

**Comment by jladd-mlnx** [comment]
@jsquyres I do not. We are trying to get an HPC-X release done this week.

**Comment by jladd-mlnx** [comment]
@rhc54 Can you revert this? It's causing all kinds of problems with our QA and we're in a critical release phase with both HPC-X and MOFED.

**Comment by bosilca** [comment]
I don't know why -lpthread would be required for this patch. It does however need -lrt.

**Comment by jsquyres** [comment]
@bosilca See the detailed analysis on https://github.com/open-mpi/ompi/issues/1699

**Pull request merged**
