### PR TITLE
configury: test portability

### PR DESCRIPTION
**Pull request by ggouaillardet**
replace test ... -o ... with test ... || test ...
and test ... -a ... with test ... && test ...

(back-ported from commit open-mpi/ompi@fec973efda4682645be812cf549dc927b87286aa)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1209/ for details.

**Comment by ggouaillardet** [comment]
:bot:assign: @jsquyres 
:bot:label:enhancement
:bot:milestone:v2.0.0

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
Accepting this because these changes do increase portability, and therefore can be considered a bug fix.

**Pull request merged**
