### PR TITLE
Correctly move the pointer back by the true_lb.

### PR DESCRIPTION
**Pull request by ggouaillardet**
(cherry picked from commit open-mpi/ompi@e3f74aca1c0482816e85da9f018872b7fe98e227)

@bosilca could you please review this ?

### CODE REVIEW

**Comment by rhc54** [comment]
The master commit link provided leads to a "404" error - please provide the correct link.

**Comment by ggouaillardet** [comment]
sorry about that.

i corrected this by both :
- editing the PR
- rewriting history of the topic/coll_tuned_allgather_intra_bruck branch of the ggouaillardet/ompi-release repository

**Comment by jsquyres** [comment]
@ggouaillardet Could you also fix the commit message -- "mote" --> "move".

**Comment by ggouaillardet** [comment]
@jsquyres done

**Pull request merged**
