### PR TITLE
openib btl: add Soft iWARP device to the ini file

### PR DESCRIPTION
**Pull request by larrystevenwise**
This enables IBM's software iWARP provider.  With this driver you can
run iWARP/RDMA over any ethernet NIC.  Useful for testing OMPI RDMA
logic without requiring an expensive RDMA adapter/infrastructure.

The Soft iWARP code is at: https://www.gitorious.org/softiwarp

Cherry-picked from open-mpi/mpi@7316a887546acad2010c27087a403bf7dfe04dc6

### CODE REVIEW

**Comment by jsquyres** [comment]
I guess this is technically an enhancement, not a bug.  But I think it falls in the category of "vendors supporting new devices/drivers", and should therefore be allowed.

@rhc54 ok?

**Comment by mike-dubman** [comment]
Merged build triggered.

**Comment by mike-dubman** [comment]
Merged build started.

**Comment by mike-dubman** [comment]
Merged build finished. Test PASSed.

**Pull request merged**
