### PR TITLE
Custom patch for 1.10 to deal with oversubscription.

### PR DESCRIPTION
**Pull request by rhc54**
Thanks to @ammore1 for raising the issue

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/837/ for details.

**Comment by rhc54** [comment]
@jsquyres I'm not sure we aren't chasing our tail here - however, there was a bug in that the "slots_given" flag was being ignored. This corrects that situation, and restores what I believe is the expected oversubscription behavior. See what you think.

And yes - I know there's a bunch of whitespace changes in here. It isn't that hard to find the large sections of green where the changes occurred, so please take a moment to do so.

**Comment by jsquyres** [comment]
@ammore1 Did this fix the issue for you?

**Comment by jsquyres** [comment]
I found an email from @ammore1 from several days ago:

> when I run mpirun , I am able to run maximum 2 processes now.

``` sh
ammore@usnic3:/opt/cisco/usnic/bin> mpirun -host 10.10.10.2,10.10.10.7 -np  2 hostname
usnic2
usnic3
ammore@usnic3:/opt/cisco/usnic/bin> mpirun -host 10.10.10.2,10.10.10.7 -np  3 hostname
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 3 slots
that were requested by the application:
 hostname

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------

ammore@usnic3:/opt/cisco/usnic/bin> nproc
32

ammore@usnic3:/opt/cisco/usnic/bin> lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Model name:            Intel(R) Xeon(R) CPU E5-2470 0 @ 2.30GHz
Stepping:              7
CPU MHz:               1520.335
CPU max MHz:           3100.0000
CPU min MHz:           1200.0000
BogoMIPS:              4601.53
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31
```

**Comment by jsquyres** [comment]
@rhc54 If it's too much work to put in at the last second here, we're ok with deferring this issue to a future release -- it doesn't have to go into v1.10.1.

**Comment by rhc54** [comment]
Ah yes, I had forgotten that email. Let's defer as I think we are indeed chasing our tails here. The "new" behavior he noted is in fact correct by our current definitions for -host behavior.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/972/ for details.

**Comment by jsquyres** [comment]
Per http://www.open-mpi.org/community/lists/devel/2015/11/18354.php, this is not a critical bug fix.  Pushing to v1.10.3.

**Comment by rhc54** [comment]
This fixes a bug, and so we might as well bring it across. The behavior with this patch is as we have defined.

**Pull request merged**
