### PR TITLE
v1.10: use distinct namespaces in osc_pt2pt

### PR DESCRIPTION
**Pull request by ggouaillardet**
Thanks Bruce J Palmer for the report

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:label:bug
:bot:assign: @hjelmn 
:bot:milestone:v1.10.3

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1580/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1581/ for details.

**Comment by rhc54** [comment]
👍  per @hjelmn

**Pull request merged**
