### PR TITLE
Pr/commits of week 34

### PR DESCRIPTION
**Pull request by edgargabriel**

### CODE REVIEW

**Comment by hppritcha** [comment]
bot:retest

**Comment by hppritcha** [comment]
more UH testing
bot:retest

**Comment by hppritcha** [comment]
I'll give this a shake out at NERSC

**Comment by hppritcha** [comment]
@edgargabriel 

I'm getting a segfault with ompi-tests/mpi2basic-test/file/filetest when the romio314 component is selected:

#0  0x00002aab03057c74 in ADIOI_Flatten (datatype=0x1844840, flat=0x1844af0, st_offset=0, curr_index=0x7fffffff8438) at adio/common/flatten.c:232
232                 flat->indices[j] = st_offset;
(gdb) bt
#0  0x00002aab03057c74 in ADIOI_Flatten (datatype=0x1844840, flat=0x1844af0, st_offset=0, curr_index=0x7fffffff8438) at adio/common/flatten.c:232
#1  0x00002aab03057821 in ADIOI_Flatten_datatype (datatype=0x1844840) at adio/common/flatten.c:81
#2  0x00002aab0304dbe1 in ADIO_Set_view (fd=0x8270b0, disp=2144, etype=0x60b280 <ompi_mpi_comm_world>, filetype=0x818560, info=0x60ca80 <ompi_mpi_op_max+256>, error_code=0x7fffffff8534)
    at adio/common/ad_set_view.c:52
#3  0x00002aab03028374 in mca_io_romio314_dist_MPI_File_set_view (fh=0x8270b0, disp=2144, etype=0x60b280 <ompi_mpi_comm_world>, filetype=0x818560, datarep=0x4095d4 "native", info=0x60ca80 <ompi_mpi_op_max+256>)
    at mpi-io/set_view.c:157
#4  0x00002aab03020b2b in mca_io_romio314_file_set_view (fh=0x827b10, disp=2144, etype=0x60b280 <ompi_mpi_comm_world>, filetype=0x818560, datarep=0x4095d4 "native", info=0x60ca80 <ompi_mpi_op_max+256>)
    at src/io_romio314_file_open.c:193
#5  0x00002aaaaad84534 in PMPI_File_set_view (fh=0x827b10, disp=2144, etype=0x60b280 <ompi_mpi_comm_world>, filetype=0x818560, datarep=0x4095d4 "native", info=0x60ca80 <ompi_mpi_op_max+256>) at pfile_set_view.c:75
#6  0x0000000000403338 in fileview_test (comm=0x60b480 <ompi_mpi_comm_world+512>, root=0) at fileview.c:444

but I also see this with master.  It happens on both lustre and nfs file systems at NERSC.

My configure options are

./configure --with-memory-manager=none --prefix=/global/homes/h/hpp/ompi_install --with-io-romio-flags=--with-file-system=ufs+nfs+lustre --with-verbs=no

Probably unrelated to this PR,

**Comment by edgargabriel** [comment]
It is unrelated to this set of commits, and I have to admit that I haven't run romio on my test suite for a while.  Last time I ran it did finish (although reporting one or two errors, but I was always a bit unsure whether the assumptions in my testsuite are a bit too strict). However, the testsuite was extended significantly over the last year,  so maybe one of the cases that I added leads to this result.

**Comment by hppritcha** [comment]
@jsquyres Edgar and I don't think the segfaults with romio are related to this PR.  I think its ready to merge.

**Comment by edgargabriel** [comment]
To formulate it a bit stronger, there is no way that this error is related to the pr. You have to explicitly disable ompio and force the utilization of romio to get this error.

**Comment by hppritcha** [comment]
@jsquyres this is ready to merge

**Pull request merged**
