### PR TITLE
ompio: correctly handle zero f_cc_size in mca_io_ompio_simple_grouping

### PR DESCRIPTION
**Pull request by ggouaillardet**
(cherry picked from commit open-mpi/ompi@59a361b7811d61941789d22be299fa6c78edbdc8)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @edgargabriel 
:bot:milestone:v2.0.0
:bot:label:bug

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1109/ for details.

**Comment by edgargabriel** [comment]
:+1:

**Comment by jsquyres** [comment]
FWIW, put colons around the +1 to make it the github "thumbs up" emoticon (and also trigger the ompi-bot to put the "reviewed" label on this PR).

I.e.: :+1:

**Pull request merged**
