### PR TITLE
fcoll/dynamic_gen2: add new  component

### PR DESCRIPTION
**Pull request by edgargabriel**
this component is supposed to fix the performance problems of ompio on Lustre file systems.

bot:milestone:v2.0.1
bot:label:bug

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1373/ for details.

**Comment by jsquyres** [comment]
bot:retest

**Comment by edgargabriel** [comment]
@hppritcha this component is specifically designed for lustre file systems, to the best of my knowledge you are the only person having access to a lustre file system. Would you mind reviewing the new component?

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1917/ for details.

**Comment by hppritcha** [comment]
RMs decided since this is really a new feature, even if fixing a performance problem, we'll move to 2.1 milestone.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2063/ for details.

**Comment by jsquyres** [comment]
@edgargabriel This was originally committed 7 months ago.  Is it still good / up-to-date?

**Comment by edgargabriel** [comment]
yes, I just tested it 3 weeks back. I will do a rebase once we get close to merging it.

**Comment by jsquyres** [comment]
@edgargabriel We're pretty close to merging.  If you don't mind rebasing, that would be great.  Thank you!

**Comment by edgargabriel** [comment]
ok, just did that.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2171/ for details.

**Comment by hppritcha** [comment]
As long as I export OMPI_MCA_io=ompio the usual filetest passes with this PR on my lustre file system.  Otherwise, if it uses romio (which seems to be what it does by default) there is a segfault in romio:

```
nid00111:04345] [nid00111:04346] [ 0] /lib64/libpthread.so.0(+0xf850)[0x7ffff7853850]
[nid00111:04346] [ 1] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(ADIOI_Flatten+0x448)[0x7fffa6e7ae97]
[nid00111:04346] [ 2] [nid00111:04347] [ 0] /lib64/libpthread.so.0(+0xf850)[0x7ffff7853850]
[nid00111:04347] [ 1] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(ADIOI_Flatten+0x448)[0x7fffa6e7ae97]
[nid00111:04347] [ 2] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(ADIOI_Flatten_datatype+0x17f)[0x7fffa6e7aa3b]
[nid00111:04347] [ 3] [nid00111:04348] [ 0] /lib64/libpthread.so.0(+0xf850)[0x7ffff7853850]
[nid00111:04348] [ 1] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(ADIOI_Flatten+0x448)[0x7fffa6e7ae97]
[nid00111:04348] [ 2] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(ADIOI_Flatten_datatype+0x17f)[0x7fffa6e7aa3b]
[nid00111:04348] [ 3] [nid00111:04349] [ 0] /lib64/libpthread.so.0(+0xf850)[0x7ffff7853850]
[nid00111:04349] [ 1] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(ADIOI_Flatten+0x448)[0x7fffa6e7ae97]
[nid00111:04349] [ 2] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(ADIOI_Flatten_datatype+0x17f)[0x7fffa6e7aa3b]
[nid00111:04349] [ 3] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(ADIO_Set_view+0x1b1)[0x7fffa6e70df5]
[nid00111:04349] [ 4] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(ADIOI_Flatten_datatype+0x17f)[0x7fffa6e7aa3b]
[nid00111:04346] [ 3] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(ADIO_Set_view+0x1b1)[0x7fffa6e70df5]
[nid00111:04346] [ 4] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(mca_io_romio314_dist_MPI_File_set_view+0x5e0)[0x7fffa6e52bd4]
[nid00111:04346] [ 5] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(mca_io_romio314_file_set_view+0x58)[0x7fffa6e4b35e]
[nid00111:04346] [ 6] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(ADIO_Set_view+0x1b1)[0x7fffa6e70df5]
[nid00111:04347] [ 4] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(mca_io_romio314_dist_MPI_File_set_view+0x5e0)[0x7fffa6e52bd4]
[nid00111:04347] [ 5] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(mca_io_romio314_file_set_view+0x58)[0x7fffa6e4b35e]
[nid00111:04347] [ 6] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(ADIO_Set_view+0x1b1)[0x7fffa6e70df5]
[nid00111:04348] [ 4] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(mca_io_romio314_dist_MPI_File_set_view+0x5e0)[0x7fffa6e52bd4]
[nid00111:04348] [ 5] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(mca_io_romio314_file_set_view+0x58)[0x7fffa6e4b35e]
[nid00111:04348] [ 6] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(mca_io_romio314_dist_MPI_File_set_view+0x5e0)[0x7fffa6e52bd4]
[nid00111:04349] [ 5] /cray/css/users/n17276/ompi_release_install/lib/openmpi/mca_io_romio314.so(mca_io_romio314_file_set_view+0x58)[0x7fffa6e4b35e]
[nid00111:04349] [ 6] /cray/css/users/n17276/ompi_release_install/lib/libmpi.so.20(PMPI_File_set_view+0x1c2)[0x7ffff7b22a40]
[nid00111:04346] [ 7] /lus/dal/n17276/./filetest[0x403839]
[nid00111:04346] [ 8] /lus/dal/n17276/./filetest[0x4025aa]
[nid00111:04346] [ 9] /cray/css/users/n17276/ompi_release_install/lib/libmpi.so.20(PMPI_File_set_view+0x1c2)[0x7ffff7b22a40]
[nid00111:04347] [ 7] /lus/dal/n17276/./filetest[0x403839]
[nid00111:04347] [ 8] /lus/dal/n17276/./filetest[0x4025aa]
[nid00111:04347] [ 9] /cray/css/users/n17276/ompi_release_install/lib/libmpi.so.20(PMPI_File_set_view+0x1c2)[0x7ffff7b22a40]
[nid00111:04348] [ 7] /lus/dal/n17276/./filetest[0x403839]
[nid00111:04348] [ 8] /lus/dal/n17276/./filetest[0x4025aa]
[nid00111:04348] [ 9] /cray/css/users/n17276/ompi_release_install/lib/libmpi.so.20(PMPI_File_set_view+0x1c2)[0x7ffff7b22a40]
[nid00111:04349] [ 7] /lus/dal/n17276/./filetest[0x403839]
[nid00111:04349] [ 8] /lus/dal/n17276/./filetest[0x4025aa]
[nid00111:04349] [ 9] /lib64/libc.so.6(__libc_start_main+0xe6)[0x7ffff74e6c36]
[nid00111:04346] [10] /lus/dal/n17276/./filetest[0x4023a9]
```

since the purpose of this PR is for ompi and has nothing to do with romio, I'm good with this.

:+1:

**Comment by hppritcha** [comment]
@jsquyres ready to merge

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2188/ for details.

**Comment by edgargabriel** [comment]
? Where does this failed Jenkins test suddenly come from?

**Comment by artpol84** [comment]
Indeed this is strange. I'll try to check.

But you can safely ignore it as this repo is empty now and failure is expected.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2189/ for details.

**Pull request merged**
