### PR TITLE
Topic/v1.8/hcoll fca configury

### PR DESCRIPTION
**Pull request by ggouaillardet**
:bot:assign: @jsquyres 
:bot:milestone:v1.8.9
:bot:label:bug

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:milestone:v1.8.9

**Comment by ggouaillardet** [comment]
@rhc54 @hppritcha could you please create the v1.8.9 milestone ?

**Comment by jsquyres** [comment]
See open-mpi/ompi#796 @bureddy

**Comment by bureddy** [comment]
:+1:

**Pull request closed without merging**
