### PR TITLE
Topic/v2.x/missing include files

### PR DESCRIPTION
**Pull request by ggouaillardet**
this is a merge of open-mpi/ompi#1258
back to v2.x branch.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1199/ for details.

**Comment by ggouaillardet** [comment]
:bot:label:bug
:bot:label:milestone:v2.0.0
:bot:assign: @hppritcha

**Comment by ggouaillardet** [comment]
@hppritcha these are a bunch of missing include files.
if you think i should issue several PRs and assign them to their respective owners, please let me know

**Comment by ggouaillardet** [comment]
:bot:milestone:v2.0.0

**Comment by hppritcha** [comment]
:+1:
@jsquyres I suggest waiting till open-mpi/ompi#1258 cooks with MTT testing for a couple of days before merging.

**Comment by hppritcha** [comment]
@jsquyres I think this is ready to merge.

**Pull request merged**
