### PR TITLE
HCOLL: fix hang in hcoll barrier called from finalize for MXM/yalla

### PR DESCRIPTION
**Pull request by bureddy**
HCOLL barrier may not complete if HCOLL progress is not called periodically.
which is the case in HCOLL teardown progress in the finalize.

### CODE REVIEW

**Comment by bureddy** [comment]
@miked-mellanox , @jladd-mlnx  can you please review?

**Comment by jladd-mlnx** [comment]
:+1:

**Comment by jladd-mlnx** [comment]
bot:milestone:v1.10.1

**Comment by jladd-mlnx** [comment]
Assigning to gatekeeper. 

bot:assign:@jsquyres

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/811/ for details.

**Pull request merged**
