### PR TITLE
Fix PMI and PMI2 builds

### PR DESCRIPTION
**Pull request by nysal**
(cherry picked from commit open-mpi/ompi@2d2ea63)

### CODE REVIEW

**Comment by nysal** [comment]
:bot:assign: @jsquyres 
:bot:milestone:v2.0.0
:bot:label:bug

**Comment by nysal** [comment]
Ralph reviewed the fix for master - https://github.com/open-mpi/ompi/pull/798

**Comment by jsquyres** [comment]
If @rhc54 reviewed this on master, it's ok for him to review it here, too.  :-)

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
