### PR TITLE
Fix a typo in the alignment threshold in openib BTL.

### PR DESCRIPTION
**Pull request by rhc54**
Cherry-picked from open-mpi/ompi@ce915b5757d428d3e914dcef50bd4b2636561bca

@hjelmn please take a look

### CODE REVIEW

**Comment by mellanox-github** [comment]
- Coverity found 1465 errors for all
- Coverity found 23 errors for oshmem
- Coverity found 7 errors for fca
- Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//289/Coverity_Report <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/289/

**Build Log**
_last 50 lines_

```
[...truncated 54903 lines...]

Success rank - 3: only one NUMA is scheduled.

Success rank - 6: only one NUMA is scheduled.

Success rank - 1: only one NUMA is scheduled.

Success rank - 0: only one NUMA is scheduled.
+ val=0
+ '[' 0 -ne 0 ']'
+ for hca_dev in '$(ibstat -l)'
++ cat /sys/class/infiniband/mlx5_0/device/numa_node
+ var=0
+ export TEST_CLOSEST_NUMA=0
+ TEST_CLOSEST_NUMA=0
+ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpirun -np 8 -mca mpi_warn_on_fork 0 -mca btl_openib_warn_default_gid_prefix 0 --map-by dist:mlx5_0 -x TEST_CLOSEST_NUMA -x TEST_PHYS_ID_COUNT -x TEST_CORE_ID_COUNT /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test

Success rank - 4: only one NUMA is scheduled.

Success rank - 7: only one NUMA is scheduled.

Success rank - 6: only one NUMA is scheduled.

Success rank - 3: only one NUMA is scheduled.

Success rank - 1: only one NUMA is scheduled.

Success rank - 5: only one NUMA is scheduled.

Success rank - 2: only one NUMA is scheduled.

Success rank - 0: only one NUMA is scheduled.
+ val=0
+ '[' 0 -ne 0 ']'
+ set -e
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
There are failed test cases and the job is configured to mark the build as failure. Marking build as FAILURE
TAP Reports Processing: FINISH
Build step 'Publish TAP Results' changed build result to FAILURE
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/289/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi-release/commit/6561b42f5b6d58cff27f4ccb2047309367fca3b0
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] TAP test failed
[BFA] Done. 0s
Setting status of 20b2a7d8b617236b9e3d7abd256f7696bcc09244 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/289/ and message: Build finished.
```

Test FAILed.

**Comment by rhc54** [comment]
@miked-mellanox Any idea what this is complaining about? I can't see any issue

**Comment by mike-dubman** [comment]
@elenash - seems mindist tests in jenkins are breaking, will disable for now - please check

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1465 errors for all
- Coverity found 23 errors for oshmem
- Coverity found 7 errors for fca
- Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//291/Coverity_Report <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/291/

**Build Log**
_last 50 lines_

```
[...truncated 54820 lines...]
Thread 2, message rate 6344.408975 messages/sec
Thread 0, message rate 6390.241465 messages/sec
Thread 5, message rate 6349.762696 messages/sec
Thread 1, message rate 6371.009844 messages/sec
+ '[' 0 -gt 0 ']'
+ '[' -n '' ']'
+ btl_openib=yes
+ btl_tcp=yes
+ btl_sm=yes
+ btl_vader=yes
+ for mpit in '$abs_path/*.c'
++ basename /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi.c .c
+ out_name=env_mpi
+ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi.c
+ for mpit in '$abs_path/*.c'
++ basename /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test.c .c
+ out_name=mindist_test
+ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test.c
++ echo /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
+ for OMPI_HOME in '$(echo $ompi_home_list)'
+ test_tune
+ echo 'check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_env_list
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
+ echo 'check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_envar_file_prefix
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
There are failed test cases and the job is configured to mark the build as failure. Marking build as FAILURE
TAP Reports Processing: FINISH
Build step 'Publish TAP Results' changed build result to FAILURE
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/291/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi-release/commit/6561b42f5b6d58cff27f4ccb2047309367fca3b0
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] TAP test failed
[BFA] Done. 0s
Setting status of 20b2a7d8b617236b9e3d7abd256f7696bcc09244 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/291/ and message: Build finished.
```

Test FAILed.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1465 errors for all
- Coverity found 23 errors for oshmem
- Coverity found 7 errors for fca
- Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//292/Coverity_Report <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/292/

**Build Log**
_last 50 lines_

```
[...truncated 54827 lines...]
+ btl_tcp=yes
+ btl_sm=yes
+ btl_vader=yes
+ for mpit in '$abs_path/*.c'
++ basename /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi.c .c
+ out_name=env_mpi
+ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/env_mpi.c
+ for mpit in '$abs_path/*.c'
++ basename /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test.c .c
+ out_name=mindist_test
+ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test /scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test.c
++ echo /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
+ for OMPI_HOME in '$(echo $ompi_home_list)'
+ test_tune
+ echo 'check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_env_list
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
+ echo 'check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_envar_file_prefix
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/292/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/292/tap-master-files/cov_stat.tap].
not ok - coverity detected 1465 failures in all # SKIP
not ok - coverity detected 23 failures in oshmem # SKIP
ok - coverity found no issues for mxm
not ok - coverity detected 7 failures in fca # SKIP
ok - coverity found no issues for hcoll

There are failed test cases. Marking build as UNSTABLE
TAP Reports Processing: FINISH
Build step 'Publish TAP Results' changed build result to UNSTABLE
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at BUILD level /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/cov_build to /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/292/htmlreports/Coverity_Report
Setting commit status on GitHub for https://github.com/open-mpi/ompi-release/commit/6561b42f5b6d58cff27f4ccb2047309367fca3b0
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 20b2a7d8b617236b9e3d7abd256f7696bcc09244 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/292/ and message: Build finished.
```

Test FAILed.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1465 errors for all
- Coverity found 23 errors for oshmem
- Coverity found 7 errors for fca
- Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//293/Coverity_Report <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/293/
Test PASSed.

**Comment by elenash** [comment]
@miked-mellanox It looks like the problem is not in mindist test. As far as I can see jenkins failed after you disabled it. Moreover, the first line of mindist test is 'echo' which we don't see in the output. I noticed that last successful report doesn't contain TAP Reports Processing. Probably it causes failure?

**Comment by mike-dubman** [comment]
@elenash - right, the mindist test are fine, sorry for confusion.
The jenkins was upgraded and TAP plugin has "issues", so disabled it.

**Pull request merged**
