### PR TITLE
Protect the oob/tcp component from port scanners

### PR DESCRIPTION
**Pull request by rhc54**
(cherry picked from commit open-mpi/ompi@4352123c26346de6a3dbe02dafaf1e4bc432bbdb)

@jsquyres please review

### CODE REVIEW

**Comment by jsquyres** [comment]
@rhc54 (and maybe @bosilca ?) Just so I understand this: is the intent that port scanners will hang up before sending the required number of bytes for the incoming blob?

**Comment by rhc54** [comment]
@jsquyres Port scanners touch the port and thus cause a connect/accept to begin, but they send no bytes - they just immediately disconnect. We didn't protect against that, and so when we see the connection error, we have peer=NULL and go into the error code - which segfaults.

Reported by two independent sets of folks, hence the fix.

**Comment by jsquyres** [comment]
Ah, ok.

I think this is a good fix -- it definitely fixes the `peer==NULL` case before trying to access `peer->state`, but I wonder a port scanner hanging up would end up in that code path to begin with.  Premature hangups should be detected in the block before this one (i.e., the block checking for `retval==0`).  This block should only be entered when retval is some uncommon _error_.

Shrug.  The fix is good, regardless, so it shouldn't be held up even if we don't understand how the code execution got to this specific code path from a port scanner...

:+1:

**Comment by hppritcha** [comment]
bot:retest

**Comment by hppritcha** [comment]
looks like we also need a PR for v2.x for this fix.
@rhc54

**Pull request merged**
