### PR TITLE
btl/vader: use FRAG_ALLOC_USER when single_copy_mechanism is VADER_NONE

### PR DESCRIPTION
**Pull request by ggouaillardet**
back-ported from commit open-mpi/ompi@d2d7f39a4bc8dde7e8c480f248819ec0d0e6be62

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@hjelmn could you please review this PR ?

**Comment by mellanox-github** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/18/

**Build Log**
_last 50 lines_

```
[...truncated 24519 lines...]
              MCA sshmem: parameter "sshmem_base_start_address" (current value: "4278190080", data source: default, level: 9 dev/all, type: unsigned long long, synonyms: memheap_base_start_address)
                          Specify base address for shared memory region
              MCA sshmem: parameter "sshmem_base_backing_file_dir" (current value: "/dev/shm", data source: default, level: 9 dev/all, type: string)
                          Specifies where backing files will be created when mmap is used and shmem_mmap_anonymous set to 0.
              MCA sshmem: parameter "sshmem_mmap_priority" (current value: "20", data source: default, level: 3 user/all, type: int)
                          Priority for sshmem mmap component (default: 20)
              MCA sshmem: parameter "sshmem_mmap_anonymous" (current value: "1", data source: default, level: 4 tuner/basic, type: int)
                          Select whether anonymous sshmem is used for mmap component (default: 1)
              MCA sshmem: parameter "sshmem_mmap_fixed" (current value: "1", data source: default, level: 4 tuner/basic, type: int)
                          Select whether fixed start address is used for shmem (default: 1)
              MCA sshmem: parameter "sshmem_sysv_priority" (current value: "30", data source: default, level: 3 user/all, type: int)
                          Priority for the sshmem sysv component (default: 30)
              MCA sshmem: parameter "sshmem_sysv_use_hp" (current value: "-1", data source: default, level: 4 tuner/basic, type: int)
                          Huge pages usage [0 - off, 1 - on, -1 - auto] (default: -1)
              MCA sshmem: parameter "sshmem_verbs_priority" (current value: "40", data source: default, level: 3 user/all, type: int)
                          Priority for sshmem verbs component (default: 40)
              MCA sshmem: parameter "sshmem_verbs_hca_name" (current value: "", data source: default, level: 3 user/all, type: string, synonyms: memheap_base_hca_name)
                          Preferred hca (default: the first)
              MCA sshmem: parameter "sshmem_verbs_mr_interleave_factor" (current value: "2", data source: default, level: 3 user/all, type: int, synonyms: memheap_base_mr_interleave_factor)
                          try to give at least N Gbytes spaces between mapped memheaps of other PEs that are local to me (default: 2)
              MCA sshmem: parameter "sshmem_verbs_shared_mr" (current value: "-1", data source: default, level: 4 tuner/basic, type: int)
                          Shared memory region usage [0 - off, 1 - on, -1 - auto] (default: -1)
+ local 'common_mca=--bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M'
+ local 'mca=--bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M'
+ timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,tcp /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_max_reduction
6/8 dst = 7 8 9
4/8 dst = 7 8 9
3/8 dst = 7 8 9
5/8 dst = 7 8 9
7/8 dst = 7 8 9
2/8 dst = 7 8 9
0/8 dst = 7 8 9
1/8 dst = 7 8 9
+ '[' no == no ']'
+ timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,sm /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_max_reduction
4/8 dst = 7 8 9
6/8 dst = 7 8 9
2/8 dst = 7 8 9
0/8 dst = 7 8 9
3/8 dst = 7 8 9
7/8 dst = 7 8 9
5/8 dst = 7 8 9
1/8 dst = 7 8 9
+ timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,vader /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_max_reduction
./hpc_tests/jenkins/ompi/ompi_jenkins.sh: line 108:  3759 Killed                  $timeout_exe oshrun -np $np $mca $spml_yoda -mca pml ob1 -mca btl self,vader ${exe_path} ${exe_args}
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by hjelmn** [comment]
What does this PR fix? if there is no single-copy mechanism reserve will never be 0.

**Comment by ggouaillardet** [comment]
@hjelmn i ran into the case where there is **no** single-copy mechanism and reserve **is** 0 :

```
$ OMPI_MCA_btl_vader_single_copy_mechanism=none oshrun -np 2 -mca btl self,vader ./hello_oshmem_c
--------------------------------------------------------------------------
It looks like SHMEM_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during SHMEM_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open SHMEM
developer):

  mca_memheap_base_select() failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
[helios87:16901] Error: pshmem_init.c:61 - shmem_init() SHMEM failed to initialize - aborting
[helios87:16902] Error: pshmem_init.c:61 - shmem_init() SHMEM failed to initialize - aborting
--------------------------------------------------------------------------
SHMEM_ABORT was invoked on rank 1 (pid 16902, host=helios87) with errorcode -1.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A SHMEM process is aborting at a time when it cannot guarantee that all
of its peer processes in the job will be killed properly.  You should
double check that everything has shut down cleanly.

Local host: helios87
PID:        16902
--------------------------------------------------------------------------
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
oshrun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[42641,1],0]
  Exit code:    255
--------------------------------------------------------------------------
[helios87:16899] 1 more process has sent help message help-shmem-runtime.txt / shmem_init:startup:internal-failure
[helios87:16899] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[helios87:16899] 1 more process has sent help message help-shmem-api.txt / shmem-abort
[helios87:16899] 1 more process has sent help message help-shmem-runtime.txt / oshmem shmem abort:cannot guarantee all killed
```

the commit fixes this

i am also seeing some weird things with oshmem and i am now investigating them.
bottom line, i might have fixed a case that should have never happened ...

**Comment by mike-dubman** [comment]
retest this please

**Comment by mellanox-github** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/21/

**Build Log**
_last 50 lines_

```
[...truncated 26440 lines...]
                MCA spml: parameter "spml_yoda_free_list_num" (current value: "1024", data source: default, level: 9 dev/all, type: int)
                MCA spml: parameter "spml_yoda_free_list_max" (current value: "1024", data source: default, level: 9 dev/all, type: int)
                MCA spml: parameter "spml_yoda_free_list_inc" (current value: "16", data source: default, level: 9 dev/all, type: int)
                MCA spml: parameter "spml_yoda_bml_alloc_threshold" (current value: "3", data source: default, level: 9 dev/all, type: int)
                          number of puts to wait                                       in case of put/get temporary buffer                                       allocation failture
                MCA spml: parameter "spml_yoda_priority" (current value: "10", data source: default, level: 9 dev/all, type: int)
                          [integer] yoda priority
              MCA sshmem: parameter "sshmem" (current value: "", data source: default, level: 2 user/detail, type: string)
                          Default selection set of components for the sshmem framework (<none> means use all components that can be found)
              MCA sshmem: parameter "sshmem_base_verbose" (current value: "0", data source: default, level: 8 dev/detail, type: int)
                          Verbosity level for the sshmem framework (0 = no verbosity)
              MCA sshmem: parameter "sshmem_base_start_address" (current value: "4278190080", data source: default, level: 9 dev/all, type: unsigned long long, synonyms: memheap_base_start_address)
                          Specify base address for shared memory region
              MCA sshmem: parameter "sshmem_base_backing_file_dir" (current value: "/dev/shm", data source: default, level: 9 dev/all, type: string)
                          Specifies where backing files will be created when mmap is used and shmem_mmap_anonymous set to 0.
              MCA sshmem: parameter "sshmem_mmap_priority" (current value: "20", data source: default, level: 3 user/all, type: int)
                          Priority for sshmem mmap component (default: 20)
              MCA sshmem: parameter "sshmem_mmap_anonymous" (current value: "1", data source: default, level: 4 tuner/basic, type: int)
                          Select whether anonymous sshmem is used for mmap component (default: 1)
              MCA sshmem: parameter "sshmem_mmap_fixed" (current value: "1", data source: default, level: 4 tuner/basic, type: int)
                          Select whether fixed start address is used for shmem (default: 1)
              MCA sshmem: parameter "sshmem_sysv_priority" (current value: "30", data source: default, level: 3 user/all, type: int)
                          Priority for the sshmem sysv component (default: 30)
              MCA sshmem: parameter "sshmem_sysv_use_hp" (current value: "-1", data source: default, level: 4 tuner/basic, type: int)
                          Huge pages usage [0 - off, 1 - on, -1 - auto] (default: -1)
              MCA sshmem: parameter "sshmem_verbs_priority" (current value: "40", data source: default, level: 3 user/all, type: int)
                          Priority for sshmem verbs component (default: 40)
              MCA sshmem: parameter "sshmem_verbs_hca_name" (current value: "", data source: default, level: 3 user/all, type: string, synonyms: memheap_base_hca_name)
                          Preferred hca (default: the first)
              MCA sshmem: parameter "sshmem_verbs_mr_interleave_factor" (current value: "2", data source: default, level: 3 user/all, type: int, synonyms: memheap_base_mr_interleave_factor)
                          try to give at least N Gbytes spaces between mapped memheaps of other PEs that are local to me (default: 2)
              MCA sshmem: parameter "sshmem_verbs_shared_mr" (current value: "-1", data source: default, level: 4 tuner/basic, type: int)
                          Shared memory region usage [0 - off, 1 - on, -1 - auto] (default: -1)
+ local 'common_mca=--bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M'
+ local 'mca=--bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M'
+ timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,tcp /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace-2/ompi_install1/examples/oshmem_strided_puts
target on PE 1 is 1 3 5 7 9
+ '[' no == no ']'
+ timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,sm /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace-2/ompi_install1/examples/oshmem_strided_puts
target on PE 1 is 1 3 5 7 9
+ '[' yes == yes ']'
+ timeout -s SIGKILL 3m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca spml yoda -mca pml ob1 -mca btl self,vader /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace-2/ompi_install1/examples/oshmem_strided_puts
--------------------------------------------------------------------------
SHMEM_ABORT was invoked on rank 0 (pid 20800, host=jenkins01) with errorcode -1.
--------------------------------------------------------------------------
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by mike-dubman** [comment]
retest this please

**Comment by mellanox-github** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/22/
Test PASSed.

**Comment by hjelmn** [comment]
It isn't explicitly stated in the BTL documentation but a reserve of 0 will only return a fragment valid for put/get. vader is not the only btl that makes this assumption as it inherited this assumption for btl/sm. I will need to discuss this to make sure that assumption is actually correct.

If indeed it is then this fix is wrong and should be backed out of master. The bug will need to be fixed in oshmem.

@miked-mellanox Can you look at spml_yoda.c and see why a function that states:

/\* Register proc memory in every rdma BTL. */

is calling prepare_src on a btl that does not support rdma (MCA_BTL_FLAGS_RDMA not set)?

**Comment by mike-dubman** [comment]
@alex-mikheev  - please comment.

**Comment by ggouaillardet** [comment]
@hjelmn i apologize in advance for my very naive question ...
is the vader btl RDMA capable **only** with knem ?

in the mean time, do you mind me waiting for oshmem/yoda to get fixed before reverting the changes in the master ?

**Comment by hjelmn** [comment]
@ggouaillardet Vader is capable of RDMA with any of the single-copy mechanisms (xpmem, cma, and knem).

No problem waiting. Looks like oshmem doesn't use the bogus fragment so this gets things running until mellanox has a chance to fix yoda.

**Comment by alex-mikheev** [comment]
@hjelmn we check for the presence of prepare_src() method in the btl. I am not sure why. In other places we explicitely check for PUT or GET flags

**Comment by hjelmn** [comment]
@alex-mikheev can you fix yoda to check for GET or PUT before registering? that will correctly fix this problem.

**Comment by hjelmn** [comment]
The underlying issue is corrected by:
https://github.com/open-mpi/ompi-release/pull/95

Please close this PR.

**Comment by hjelmn** [comment]
@ggouaillardet Now that yoda is fixed in master can you back this commit out of master.

**Comment by ggouaillardet** [comment]
@hjelmn i reverted the commit from the master and i close this PR

**Pull request closed without merging**
