### PR TITLE
README: update MPI_THREAD_MULTIPLE support

### PR DESCRIPTION
**Pull request by hppritcha**
@jsquyres 

Fixes open-mpi/ompi#1407

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1590/ for details.

**Comment by hppritcha** [comment]
hmm... turns out PSM/PSM2 don't support MPI_THREAD_MULTIPLE according to Intel.  Need to fix.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1604/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1807/ for details.

**Comment by hppritcha** [comment]
@jsquyres this is the last 2.0.0 pr left.

**Comment by jsquyres** [comment]
Per http://www.open-mpi.org/community/lists/users/2016/06/29549.php, we should probably not mention ummunotify in README.  Or at least say that it may have bit rotted, etc.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1815/ for details.

**Pull request merged**
