### PR TITLE
2.0.0: hwloc: upgrade from v1.11.0 to v1.11.1

### PR DESCRIPTION
**Pull request by jsquyres**
Taken from upstream v1.11.1 release.

(cherry picked from commit open-mpi/ompi@f69364e7685e34a43d972cde411e59dbdc435a59)

@hppritcha Please review.

### CODE REVIEW

**Comment by hppritcha** [comment]
:+1: 

has someone from Fujitsu had a chance to double check that this works for them?  I noticed a bunch of new Fujitsu/sparc stuff.

**Comment by jsquyres** [comment]
@kawashima-fj Can you verify that the new hwloc 1.11.1 works on your hardware?  We committed it to master already (or you can try the standalone hwloc 1.11.1 download).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/855/ for details.

**Comment by jsquyres** [comment]
This is all but ready to go -- we'll give @kawashima-fj a few days to verify hwloc 1.11.1 on their hardware.

**Comment by jsquyres** [comment]
@kawashima-fj Are you guys able to test this on your hardware?  If we don't hear anything by COB tomorrow, we'll merge it in and clean up afterwards if necessary.  Thanks!

**Comment by hppritcha** [comment]
@jsquyres I think my merge of #663 ended up requiring this PR to need a rebase.

**Comment by jsquyres** [comment]
@hppritcha No problem. Rebased.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/894/ for details.

**Comment by kawashima-fj** [comment]
@jsquyres
Sorry, very late.
The new hwloc code was written by Brice with my assist
and I had confirmed the new hwloc (standalone) on my machine.
So it should be OK.
I'll test the integrated code later.

Sorry, I didn't notice your invitation. GitHub didn't mail to me. Why...?
I found your invitation when I searched my name today.

**Comment by jsquyres** [comment]
That's very odd -- did the email end up in your spam folder, perchance?

**Pull request merged**
