### PR TITLE
v2.x mpi ext updates

### PR DESCRIPTION
**Pull request by jsquyres**
These are pulled straight from master.  I did not include @rolfv's new cuda MPI extension; that can be a separate PR.

@ggouaillardet please review

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/job/gh-ompi-release-v1.8-pr/369/

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@hppritcha This looks like a false failure on the distcheck jenkins:

```
  CCLD     libmca_common_verbs.la
gcc: /usr/lib64/libosmcomp.so: No such file or directory
make[3]: *** [libmca_common_verbs.la] Error 1
make[3]: Leaving directory `/global/u2/h/hpp/jenkins_hopper/workspace/ompi_v2.x_pr_distcheck2/openmpi-gitclone/_build/opal/mca/common/verbs'
```

Can you confirm?

**Comment by jsquyres** [comment]
@hppritcha BTW, why do all the LANL CI checks say "No test results found"?

**Comment by hppritcha** [comment]
This is a false failure on the jenkins distcheck.  

The no test results found is a default from the ghprb - trying to figure out how to turn this off.  There's a lot of churn in the options for the ghprb lately.

**Comment by hppritcha** [comment]
bot:retest

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hppritcha** [comment]
okay try again - consequence of temporarily moving distcheck to hopper.

bot:retest

**Comment by ggouaillardet** [comment]
@jsquyres you need to cherry-pick open-mpi/ompi@a4cc83f4f769f006aa374931befd77a083e13352 as well (incomplete prototype)
(there might be a conflict in the copyright due to the massive whitespace removal ...)

:bot:label:pushed-back

**Comment by jsquyres** [comment]
@ggouaillardet Got it; thanks.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/375/

**Comment by ggouaillardet** [comment]
@rhc54 suggested off list that the affinity extension should not be built at all without helicopter support
(e.g. update configury)

any thought ?

**Comment by rhc54** [comment]
my whirlybird actually suggests that it is better to build as you have done - that way, a user's code can just call the extension without worrying that it might not be there. It just can't tell them anything useful as we cannot bind without helicopter <love auto-spell>

**Comment by ggouaillardet** [comment]
+1
btw, iPad thinks hwloc is an helicopter :-)

**Comment by hppritcha** [comment]
sanity check since IU jenkins ghprb plugin was upgraded to 1.24.4 and there were errors processing the ompi-release webhooks on the server.

bot:retest

**Comment by jsquyres** [comment]
I'm assuming @ggouaillardet's "+1" was meant to be a :+1:

**Pull request merged**
