### PR TITLE
v2.x: misc coll/libnbc fixes

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2006/ for details.

**Comment by hppritcha** [comment]
bot:mellanox:retest

**Comment by hppritcha** [comment]
please assign a target milestone.  If the goal is to get this in to 2.0.1 has to be reviewed by 8/9/16.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2010/ for details.

**Comment by ggouaillardet** [comment]
:bot:label:bug
:bot:assign: @bosilca 
:bot:milestone:v2.0.1

only alignment sensitive arch (sparc, ppc?) are impacted

**Comment by bosilca** [comment]
👍

**Comment by hppritcha** [comment]
@jsquyres ready to go

**Pull request merged**
