### PR TITLE
v2.0.0: usnic fixes

### PR DESCRIPTION
**Pull request by jsquyres**
This is the v2.x PR of #933 (i.e., it's the same, but for the v2.x branch).

@bturrubiates Please review

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1288/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1289/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1293/ for details.

**Comment by jsquyres** [comment]
Pushed one additional commit as a result of @bturrubiates's review.  Ben now gives a :+1: for this PR.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1295/ for details.

**Pull request merged**
