### PR TITLE
Topic/v2.x/f08 bindings and makefiles

### PR DESCRIPTION
**Pull request by ggouaillardet**
:bot:assign: @jsquyres
:bot:milestone:v2.0.0
:bot:label:bug

### CODE REVIEW

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
@ggouaillardet I'm worried about the ABI implications of this, and I'm a bit nervous about the whole new Fortran scheme being dropped in literally right before we release v1.8.8.  I'm proposing #437 as a smaller / safer fix to this mpi_f08 sentinels problem.  Can you please review #437?

**Comment by jsquyres** [comment]
@ggouaillardet approved #437, so let's close this one.

**Comment by jsquyres** [comment]
Meh -- those last two comments were meant to be on #434, not this one.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request merged**
