### PR TITLE
V2.x fifo lifo fixes

### PR DESCRIPTION
**Pull request by hjelmn**

### CODE REVIEW

**Comment by hjelmn** [comment]
:bot:label:bugfix

**Comment by hjelmn** [comment]
:bot:label:bug

**Comment by hjelmn** [comment]
See open-mpi/ompi#770 and open-mpi/ompi#771

**Comment by hppritcha** [comment]
@hjelmn 
please assign a reviewer for this PR.

**Comment by hjelmn** [comment]
:bot:reviewer @nysal

**Comment by nysal** [comment]
This looks good to me. The opal_lifo/fifo tests now pass on a Power 8 system.

**Comment by nysal** [comment]
bot:label:reviewed

**Comment by hppritcha** [comment]
@jsquyres I'm good with this if you want to merge.

**Pull request merged**
