### PR TITLE
ompi/datatype: make datatype pack thread safe

### LINKED ISSUE #1317: ompi_datatype_get_pack_description not thread safe
Opened a PR to fix. See #1316.

### PR DESCRIPTION
**Pull request by hjelmn**
This commit makes ompi_datatype_get_pack_description thread safe. The
call is used by osc/pt2pt to send the packed description to remote
peers. Before this commit if MPI_THREAD_MULTIPLE is enabled and the
user uses MPI_Put, MPI_Get, etc we could hit a race where multiple
threads attempt to store the packed description on the datatype. Since
the code in question is not performance-critical the threading fix
uses opal_atomic_\* calls instead of bothering with OPAL_THREAD_*.

(cherry picked from open-mpi/ompi@b921831f2b9daabf3f52dfde3a866d37e2600960)

Fixes open-mpi/ompi#1317

:bot:label:bug
:bot:milestone:v2.0.0
:bot:assign: @bosilca

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

### CODE REVIEW

**Comment by bosilca** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1244/ for details.

**Comment by hppritcha** [comment]
looks like this commit has not made it through MTT testing on master yet.

**Comment by hppritcha** [comment]
@jsquyres 
looks like this didn't cause mtt issues - was tested with the 70787d1 tarball.

**Pull request merged**
