### PR TITLE
Topic/v2.x/oob usock fixes

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1491/ for details.

**Comment by hppritcha** [comment]
@rhc54 how critical is this?  can it be deferred to 2.0.1?

**Comment by ggouaillardet** [comment]
:bot:assign: @rhx54
:bot:milestone:v2.0.0
:bot:label:critical
:bot:retest

@hppritcha currently, the `dynamic/loop_spawn` test from the `ibm` test suite can spawn only 3 tasks before it crashes.
so as far as i am concerned, i'd rather not wait for v2.0.1

**Comment by ggouaillardet** [comment]
:bot:label:blocker
:bot:assign: @rhc54

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1494/ for details.

**Comment by rhc54** [comment]
@hppritcha It's a pretty simple bug fix, really, and probably should go into 2.0

:+1:

**Comment by hppritcha** [comment]
okay I'm going to go ahead and merge.

**Pull request merged**
