### PR TITLE
v2.x libnbc updates

### PR DESCRIPTION
**Pull request by hjelmn**

### CODE REVIEW

**Comment by hjelmn** [comment]
:bot:assign: @ggouaillardet 
:bot:milestone:v2.0.0
:bot:label:enhancement

@ggouaillardet I pulled one of your commits in with this make the cherry-pick clean. Can you make sure there isn't another commit that needs to come along?

**Comment by hppritcha** [comment]
@miked-mellanox @jladd-mlnx could one of you check the jenkins failure here?

**Comment by mike-dubman** [comment]
bot:retest

**Comment by hppritcha** [comment]
@ggouaillardet can you take a look at this PR?

**Comment by hjelmn** [comment]
libnbc is coverity clean after this PR.

Not sure if @ggouaillardet will have time to review. See open-mpi/ompi#699

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/742/ for details.

**Comment by ggouaillardet** [comment]
:+1: 
sorry for the delay ...
iirc, Nathan pushed some more changes a few days ago, should they also be part of this pr ?

**Comment by hjelmn** [comment]
@ggouaillardet Added the coverity fixes to this PR yesterday.

**Comment by hppritcha** [comment]
@ggouaillardet please rebase your PR #600 once this is merged.

**Pull request merged**
