### PR TITLE
Don't build the New Fortran Goodness (NFG) when the compiler doesn't support C_FUNLOC properly

### PR DESCRIPTION
**Pull request by jsquyres**
Original patch from @ggouaillardet; slight wording tweak by @jsquyres.

This patch is reviewed and ready to go.  It fixes an issue that Siegmar has raised on the mailing list about recent versions of the Oracle Fortran compiler.

Cherry picked from master:
- open-mpi/ompi@27aec2e - original @ggouaillardet commit
- open-mpi/ompi@e5b0b81 - working tweak from @jsquyres

### CODE REVIEW

**Comment by jsquyres** [comment]
Oops -- added the relevant master commits to the description.

**Comment by mike-dubman** [comment]
btw, my other jenkins says this, is it rellated ?

``` shell
11:32:20 ERROR: files left in build directory after distclean:
11:32:20 ./ompi/mpi/fortran/mpif-h/mpi_f08_sizeof.mod
```

**Comment by jsquyres** [comment]
Mmm.  Not to this one, but probably to #135.  I'll check into it.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/86/
Test PASSed.

**Pull request merged**
