### PR TITLE
BUILD: add support for UCX detection

### PR DESCRIPTION
**Pull request by mike-dubman**

### CODE REVIEW

**Comment by mike-dubman** [comment]
:bot:assign: @jsquyres  
:bot:milestone:v2.x
:bot:label:enhancement

**Comment by mike-dubman** [comment]
:bot:milestone:v2.0.0

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/891/ for details.

**Comment by jsquyres** [comment]
@miked-mellanox I don't see UCX on the v2.x branch yet.  Shouldn't this wait until UCX is merged over?

**Comment by hppritcha** [comment]
what's the corresponding commit into master?

**Comment by jsquyres** [comment]
@miked-mellanox Can you confirm that this is in master?

**Comment by jladd-mlnx** [comment]
Pushed in open-ompi/ompi@cdffe4f92d4d8

**Comment by jsquyres** [comment]
Sweet; thanks.

This is a local mellanox platform file change; it can go directly in.

**Pull request merged**
