### PR TITLE
mpi_f08: correctly implements MPI_{COMM,TYPE,WIN}_{DUP,NULL_{COPY,DEL…

### PR DESCRIPTION
**Pull request by ggouaillardet**
…ETE}}_FN

Fixes open-mpi/ompi#1323

(back-ported from commit open-mpi/ompi@cda094afc7ea56f037a9363b7ab8c053b91e232f)

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1336/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1337/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1338/ for details.

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1340/ for details.

**Pull request merged**
