### PR TITLE
v2.0.2: compiler warnings stomp

### PR DESCRIPTION
**Pull request by jsquyres**
Fix some compiler warnings that were already done on master, but didn't come over to v2.x.

Master commits are noted in individual commit messages.

@rhc54 Are the pmix fixes necessary?  These were lumped into warnings fixes commits. 😦

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2132/ for details.

**Comment by rhc54** [comment]
No, you don't need the pmix changes in here - @jjhursey has those in another PR. They won't harm anything, but won't contribute anything either.

👍  on the rest

**Comment by jsquyres** [comment]
@hppritcha Let's wait for the @jjhursey PR to come in first.  Then I'll de-tangle what's left.

**Comment by jjhursey** [comment]
I believe the few compiler fixes you are waiting on are in PR #1354 - which is ready to go.

**Comment by jsquyres** [comment]
@jjhursey Au contraire, mon frair -- #1354 still needs a review.  😮

**Comment by jsquyres** [comment]
#1354 is now merged; this one is good to go.

**Pull request merged**
