### PR TITLE
usock: remove left-over CR code

### PR DESCRIPTION
**Pull request by jsquyres**
Signed-off-by: Jeff Squyres jsquyres@cisco.com

@hppritcha This code was accidentally left over in The Great CR Purge of 2016.  Do you have strong feelings about whether this fix goes into v2.0.0 or v2.0.1?  It causes a compile warning because `OPAL_ENABLE_FT_CR` is no longer defined.

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1786/ for details.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1787/ for details.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1788/ for details.

**Comment by hppritcha** [comment]
@jsquyres this was intentionally left in because I thought Cisco wanted to keep us nic code as similar as possible across all branches.  But it's Cisco code and if you'd like it removed that's fine with me.

**Comment by jsquyres** [comment]
@hppritcha The code in question is in oob/usock, not btl/usnic.

**Comment by rhc54** [comment]
Yeah, that needs to come out - it snuck in when we restored the usock component

👍

**Pull request merged**
