### PR TITLE
osc/pt2pt threading fixes

### PR DESCRIPTION
**Pull request by hjelmn**
Uncovered more threading issues while testing osc/pt2pt. Not sure if they have all been resolved but it is now running cleanly (with #1325).

:bot:label:bug
:bot:milestone:v2.0.2
:bot:assign: @regrant

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2154/ for details.

**Comment by jsquyres** [comment]
@regrant Awaiting your review.

**Comment by regrant** [comment]
:+1:

**Comment by hppritcha** [comment]
@jsquyres ready to go

**Pull request merged**
