### PR TITLE
osc/sm: fix pscw synchronization

### PR DESCRIPTION
**Pull request by hjelmn**
The osc/sm component was using a simple counter to determine if all
expected posts had arrived to start a PSCW access epoch. This is
incorrect as a post may arrive from a peer that isn't part of the
current start group. There are many ways this could have been fixed.
This commit adds an n^2 bitmap. When a process posts it sets a bit in
the bitmap associated with the access rank to indicate the post is
complete. The access rank checks for and clears the bits associated
with all the processes in the start group.

The bitmap requires comm_size ^ 2 bits of space. This should be
managable as most nodes have relatively small numbers of processes. If
this changes another algorigthm can be implemented.

(cherry picked from commit open-mpi/ompi@903762e19456d797bec6d05ff4a56e5f936d14bc)

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

### CODE REVIEW

**Comment by hjelmn** [comment]
:bot:label:bug
:bot:milestone:v2.0.0
:bot:assign: @kawashima-fj

**Comment by kawashima-fj** [comment]
I compared this PR with master but open-mpi/ompi@248212276d1aec284ff5fd0fccb74052ba97f628 is missing in this PR. Do we need it too?
PR #822 is the same.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1119/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1121/ for details.

**Comment by hjelmn** [comment]
@kawashima-fj Updated both PRs with open-mpi/ompi@2482122.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1123/ for details.

**Comment by kawashima-fj** [comment]
:+1:

**Comment by kawashima-fj** [comment]
:+1:
(Try to add a label again; OMPIBot didn't work for my previous comment probablly because I spelled incorrectly and edited it later)

**Pull request merged**
