### PR TITLE
v1.10.1: Fortran: add missing MPI_AINT in mpi_f08 module

### PR DESCRIPTION
**Pull request by jsquyres**
(cherry picked from commit open-mpi/ompi@2b9c9f3093c7f90121e7453bccce1d7e47a4db21)

@ggouaillardet please review

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/850/ for details.

**Comment by jsquyres** [comment]
@miked-mellanox Is there a problem with Mellanox's Jenkins?

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/852/ for details.

**Comment by ggouaillardet** [comment]
:+1:

**Pull request merged**
