### PR TITLE
Adding entry points for Allgatherv, iAllgatherv, Reduce, and iReduce.

### PR DESCRIPTION
**Pull request by jladd-mlnx**
Signed-off-by: Joshua Ladd jladd.mlnx@gmail.com

Conflicts:
    ompi/mca/coll/hcoll/coll_hcoll.h
    ompi/mca/coll/hcoll/coll_hcoll_ops.c

:cherries: -picked from open-mpi/ompi@e398bf6

### CODE REVIEW

**Comment by jladd-mlnx** [comment]
bot:label:enhancement

**Comment by jladd-mlnx** [comment]
bot:milestone:v1.10.3

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1263/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1266/ for details.

**Comment by mike-dubman** [comment]
:+1:

**Pull request merged**
