### PR TITLE
First part of compiler warning fixes

### PR DESCRIPTION
**Pull request by jsquyres**
Here's a few fixes.  Based on Ralph's comments, I think I need to compile differently to enable more of the warnings.  Waiting on @rhc54 to provide some guidance on how to generate those additional warnings.

So there will likely be more added to this PR.

### CODE REVIEW

**Comment by rhc54** [comment]
:+1: 

Will merge when test build completes

**Comment by mellanox-github** [comment]
- Coverity found 1467 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_257/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_257/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_257/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by jsquyres** [comment]
Well, I was assuming that I'd have more to add here when I figure out how to replicate all those warnings that you are getting... :-\

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/257/
Test PASSed.

**Pull request merged**
