### PR TITLE
mtl/ofi: merge commits from master to v2.x

### PR DESCRIPTION
**Pull request by yburette**
bot:assign: @hppritcha 
bot:milestone:v2.0.0
bot:label:bug

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1365/ for details.

**Comment by hppritcha** [comment]
@yburette for the record,  could you update the description with the PR's to master that are associated with these commits?

**Comment by yburette** [comment]
@hppritcha I added a "cherry-picked from open-mpi/ompi@..." message to each one of these commits. Do you want me to gather them into this merge PR's description, instead?

**Comment by hppritcha** [comment]
:+1:

**Pull request merged**
