### PR TITLE
Patchs on mtl portals4

### PR DESCRIPTION
**Pull request by PDeveze**
This set of patchs first frees the portals4 resources in order, then it sets the PTL_PT_FLOWCTRL flag only if OMPI_MTL_PORTALS4_FLOW_CONTROL is set. It also displays (in debug mode) the limits returned by the portals4 PtlNIInit function. At least, it brings some corrections in the short message management.

It is related with open-mpi/ompi#1478 (with only one difference).

### CODE REVIEW

**Comment by PDeveze** [comment]
:bot:assign: @tkordenbrock
:bot:milestone:v2.0.1
:bot:label:bug

**Comment by tkordenbrock** [comment]
:bot:assign: @tkordenbrock
:bot:milestone:v2.0.1
:bot:label:bug

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1980/ for details.

**Comment by tkordenbrock** [comment]
This PR is based on open-mpi/ompi#1850.  The related commits are:

open-mpi/ompi@bed572c
open-mpi/ompi@f666b0d
open-mpi/ompi@b87ed1a
open-mpi/ompi@49e9936
open-mpi/ompi@9cac32b

**Comment by tkordenbrock** [comment]
This PR looks good.  :+1:

**Pull request merged**
