### PR TITLE
v1.10 - add mpi barrier in mxm finalize flow

### PR DESCRIPTION
**Pull request by mike-dubman**

### CODE REVIEW

**Comment by mike-dubman** [comment]
:bot:assign: @jsquyres 
:bot:label:bug
:bot:milestone:v1.10.1

**Comment by mike-dubman** [comment]
@alex-mikheev - please review

**Comment by alex-mikheev** [comment]
:+1:

**Comment by jsquyres** [comment]
We talked about this extensively on the 2015-09-06 weekly teleconf.  @jsquyres @bosilca @jladd-mlnx @miked-mellanox all agree that this is the best solution for v1.10.

Thank you!

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/808/ for details.

**Comment by mike-dubman** [comment]
we have issue in coll/hcoll which uses mxm as well. need to rework this patch.

**Pull request merged**
