### PR TITLE
v2.x: fortran: Correct named constants and a datatype name

### PR DESCRIPTION
**Pull request by kawashima-fj**
PR for v2.0.1

@bosilca please review

:bot:label:bug
:bot:milestone:v2.0.1
:bot:assign: @bosilca

The diffrence from master is that the change regarding `MPI_C_COMPLEX` is excluded for the binary compatibility between v2.0.0 and v2.0.1.

(cherry picked from commits
open-mpi/ompi@ad3b5901725a7a0180def6f91bb47d17fd19211f,
open-mpi/ompi@0cb5dfe18dc22a70c3faee2b46759b51af969062,
open-mpi/ompi@722e898e8e75aacf5a06d8a7a425ac008f017234,
and back-ported from a commit
open-mpi/ompi@5383003eab165af4716ee0b62367264178df2e6a)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2020/ for details.

**Comment by kawashima-fj** [comment]
This PR does not relate to HCOLL.
:bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2021/ for details.

**Comment by jsquyres** [comment]
@Di0gen @artpol84 @jladd-mlnx Can someone please fix the Mellanox jenkins?  It's been complaining about this for a few days now:

```
06:49:59 configure: error: HCOLL support requested but not found.  Aborting
```

Thanks!

**Comment by artpol84** [comment]
@jsquyres yes, I'll fix it tomorrow.
Sorry for the delay - we were busy investigating external problem because we need this fixed ASAP.

**Comment by jsquyres** [comment]
@artpol84 Thanks!

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2023/ for details.

**Comment by artpol84** [comment]
@jsquyres I've done quick investigation and I'll need @Di0gen 's help with this. May take some time but hopefully we will have it fixed till the end of the week.

I suggest to wait until that. 
Let's **not merge** PR's with failed Mellanox jenkins. Recently I had to deal with several problems that was left unnoticed because of that strategy. I'd like to save my time :).

**Comment by jsquyres** [comment]
@artpol84 Thanks for looking in to it.  Please know that people are getting quite frustrated with all the false failures from Mellanox Jenkins over the past few weeks.  😢   The sooner we can get this fixed and reliable, the better.  Thank you!

**Comment by hppritcha** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2042/ for details.

**Comment by kawashima-fj** [comment]
@bosilca Could you review? I want to see this in v2.0.1.

**Comment by bosilca** [comment]
👍

**Pull request merged**
