### PR TITLE
Patchs on osc portals4

### PR DESCRIPTION
**Pull request by PDeveze**
This set of patchs mainly splits Get and Put because portals4 may impose size restriction. It takes into account the lower bound of buffer before calling portals4. It also verifies that an ME is operational by waiting the EVENT_LINK. The other changes are minor changes (display, format, better check in PTAlloc, use of uid from GetUid, set the value of req_status.MPI_ERROR to MPI_SUCCESS, Store the no_locks parameter in osc_portals4_component.no_locks and correction in an if statement).

### CODE REVIEW

**Comment by PDeveze** [comment]
:bot:assign: @tkordenbrock
:bot:milestone:v2.0.1
:bot:label:bug

**Comment by tkordenbrock** [comment]
:bot:assign: @tkordenbrock
:bot:milestone:v2.0.1
:bot:label:bug

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1981/ for details.

**Comment by tkordenbrock** [comment]
This PR is based on open-mpi/ompi#1853.  The related commits are:

open-mpi/ompi@a76566c
open-mpi/ompi@56b36ee
open-mpi/ompi@e99e7d0
open-mpi/ompi@c418190
open-mpi/ompi@aa0d687
open-mpi/ompi@025201b
open-mpi/ompi@7aaf16e
open-mpi/ompi@76b3865
open-mpi/ompi@81823d7
open-mpi/ompi@f19a2b9

**Comment by tkordenbrock** [comment]
This PR looks good. :+1:

**Pull request merged**
