### PR TITLE
v2.x request rework

### PR DESCRIPTION
**Pull request by hjelmn**
:bot:assign:@bosilca 
:bot:label:blocker
:bot:label:enhancement
:bot:milestone:v2.0.0

### CODE REVIEW

**Comment by hjelmn** [comment]
@bosilca Let me know if I missed anything.

**Comment by bosilca** [comment]
I'm sorry I was traveling and didn't follow carefully the unfolding of the request PR over the last 2 days. Did we solve all pending issues (including the Open IB one) ?

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by bosilca** [comment]
What about the UCX patch ?

**Comment by hjelmn** [comment]
Ah, yes. UCX patch missing. The openib problem is unrelated and I think is triggered by the fact we are hitting the btl much harder now. Fix incoming.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by hjelmn** [comment]
Ok, fixed the missing header issue and added the additional commit from @thananon. If this fails due to the xrc bug I will pull that into this PR.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1715/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1716/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1717/ for details.

**Comment by hjelmn** [comment]
A couple more commits coming.

**Comment by hjelmn** [comment]
Still have an issue with osc/pt2pt. Tracking down now.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1725/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1729/ for details.

**Comment by hjelmn** [comment]
@bosilca Added your new commits per your request. Once the last of my fixes are in master I will add them.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hjelmn** [comment]
Looks like I messed up the conflicts. Will redo now.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1730/ for details.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hjelmn** [comment]
@bosilca Some new warning introduced by the new commits. I have a master PR to fix them. Will include that commit in this PR.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1731/ for details.

**Comment by bosilca** [comment]
Sorry I just noticed I haven't enabled the picky mode.

**Comment by jsquyres** [comment]
Per 2016-060-7 webex @hjelmn will cherry pick fixes and the "start" ob1/start fixes.

**Comment by hjelmn** [comment]
Start and ob1 bug fixes now included. One more fix for a known issue coming.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1755/ for details.

**Comment by hjelmn** [comment]
MTT waitany fix now included.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1756/ for details.

**Comment by hjelmn** [comment]
I think we got everything. master MTT is looking good.

**Comment by bosilca** [comment]
No I have one more fix (error code is not correctly reported for persistent requests).

**Comment by hjelmn** [comment]
@bosilca Is there a master commit?

**Comment by hppritcha** [comment]
Where are we on this PR?

**Comment by hjelmn** [comment]
I think just waiting on one more commit from @bosilca.

**Comment by hppritcha** [comment]
People are getting anxious.

**Comment by hppritcha** [comment]
How important is the commit we are waiting for?  Can this be deferred to 2.0.1?

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
@bosilca Do you think you can get this fix in by tomorrow?  We'd like to roll an RC tomorrow (Tue, 14 June), and call your fix a v2.0.1 fix if it's not in by tomorrow.  Cool?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1764/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@bosilca is unavailable at the moment; I'll make an issue for v2.0.1 per his comment above (https://github.com/open-mpi/ompi-release/pull/1199#issuecomment-224670918), and will merge this one in.

Per @hppritcha's comments from yesterday, the LANL Cray Jenkins failure is a (false) local failure at the site and can safely be ignored.

**Pull request merged**
