### PR TITLE
configury: fix XRC detection on OFED < 3.12

### PR DESCRIPTION
**Pull request by ggouaillardet**
Thanks Paul Hargrove for the report

(cherry picked from commit open-mpi/ompi@9a49d42f81e3ec2b63aa4e7805d4c5e44a90abab)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @miked-mellanox
:bot:label:bug
:bot:milestone:v2.0.0

**Comment by mike-dubman** [comment]
:+1:

**Comment by ggouaillardet** [comment]
:bot:nolabel:reviewed

i am now investigating a better fix, and will ask you to review this PR again

**Comment by ggouaillardet** [comment]
:bot:nolabel:pushed-back
@miked-mellanox could you please review this ?

**Comment by jsquyres** [comment]
:-1: 

See https://github.com/open-mpi/ompi-release/pull/384#issuecomment-120412836

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ggouaillardet** [comment]
:bot:nolabel:pushed-back

**Comment by hppritcha** [comment]
not sure why hopper is having.problems talking with github.
bot:retest

**Comment by jsquyres** [comment]
Tests ok (i.e., it builds) on RHEL 6.5 without OFED or MOFED.  :+1:

**Pull request merged**
