### PR TITLE
btl/openib: fix error path in init_one_device()

### PR DESCRIPTION
**Pull request by ggouaillardet**
do not explicitly release ib verbs components since they will
be released in the object destructor

plug misc memory leaks too.

Thanks Durga for the report

(back-ported from commit open-mpi/ompi@456b73da696ab69e88d36f6a72391b41b81c2792)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @miked-mellanox 
:bot:label:bug
:bot:milestone:v1.10.3

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1655/ for details.

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1657/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1658/ for details.

**Comment by mike-dubman** [comment]
mpirun hangs, segv comes from "timeout cmd" to print stack

``` shell
06:22:47 + taskset -c 4,5 timeout -s SIGSEGV 10m /var/lib/jenkins/jobs/gh-ompi-release-pr/workspace/ompi_install1/bin/mpirun -np 8 -bind-to core -mca btl_openib_if_include mlx4_0:1 -x MXM_RDMA_PORTS=mlx4_0:1 -x UCX_NET_DEVICES=mlx4_0:1 -x UCX_TLS=rc,cm -mca pml ob1 -mca btl self,openib /var/lib/jenkins/jobs/gh-ompi-release-pr/workspace/ompi_install1/examples/hello_c
06:32:47 [jenkins01:24954] *** Process received signal ***
06:32:47 mpirun: Forwarding signal 18 to job
06:32:47 [jenkins01:24954] Signal: Segmentation fault (11)
06:32:47 [jenkins01:24954] Signal code:  (0)
06:32:47 [jenkins01:24954] Failing at address: 0xb2000006179
06:32:47 [jenkins01:24954] [ 0] /lib64/libpthread.so.0[0x3d6980f710]
06:32:47 [jenkins01:24954] [ 1] /lib64/libc.so.6(__select+0x33)[0x3d690e15e3]
06:32:47 [jenkins01:24954] [ 2] /var/lib/jenkins/jobs/gh-ompi-release-pr/workspace/ompi_install1/lib/openmpi/mca_oob_tcp.so(+0xbf72)[0x7ffff61b2f72]
06:32:47 [jenkins01:24954] [ 3] /lib64/libpthread.so.0[0x3d698079d1]
06:32:47 [jenkins01:24954] [ 4] /lib64/libc.so.6(clone+0x6d)[0x3d690e8b6d]
06:32:47 [jenkins01:24954] *** End of error message ***
07:43:45 Build timed out (after 120 minutes). Marking the build as failed.
07:43:45 Build was aborted
```

**Comment by ggouaillardet** [comment]
i just found `allowed_ports` could be free'd twice, so i updated the PR
that might not be the root cause of the hang though ...

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1660/ for details.

**Comment by rhc54** [comment]
something seems to be stalled on LANL's tests

bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1661/ for details.

**Comment by rhc54** [comment]
@ggouaillardet So this differs from the code in the master - is that intentional? Does allowed_ports in the master get free'd because it doesn't happen in the same place here?

Just trying to understand why the two codes differ.

**Comment by ggouaillardet** [comment]
I checked again v1.10 vs master, and v1.10 did things a bit different, but there was some leaks in some error path.
I will update this PR on Monday to 
- fix the leak (e.g. do it like master)
- cherry pick the bug fix

**Comment by ggouaillardet** [comment]
@rhc54 i cherry-picked two commits that fixes Coverity reported misc memory leaks, so now v1.10 is up to date with master (at least regarding this fix)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1666/ for details.

**Pull request merged**
