### PR TITLE
coll/libnbc: ireduce_scatter_block

### PR DESCRIPTION
**Pull request by ggouaillardet**
silence malloc(0) warning reported by Lisandro

(back-ported from open-mpi/ompi@318a1a40a4ab345f417b8932326d4dd2e68d82bc)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @rhc54 
:bot:milestone: v1.8.8
:bot:label: bug

**Comment by ggouaillardet** [comment]
:bot:milestone:v1.8.8

**Comment by ggouaillardet** [comment]
:bot:label:bug

**Comment by rhc54** [comment]
Given that 1.8.8 is a bug-fix, and that this is in a section of code that is really forward-looking (i.e., we can and should redirect users of libnbc to the 1.10 and above series), I'm going to leave this out of 1.8.8 to reduce risk.

**Pull request closed without merging**
