### PR TITLE
Close only used file descriptors at fork/exec in 2.0

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/722/ for details.

**Comment by jsquyres** [comment]
Similar comment to the one I made in #590 

@plesn

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/729/ for details.

**Comment by rhc54** [comment]
@miked-mellanox Looks like a Jenkins problem - can you confirm?

**Comment by mike-dubman** [comment]
checking

**Comment by mike-dubman** [comment]
jenkins seems fine. we have an issue with make -jX. will disable jobserver mode for make in "make dist"

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/730/ for details.

**Comment by jsquyres** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/731/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/752/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/758/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/760/ for details.

**Pull request merged**
