### PR TITLE
v2.0.0 update usnic

### PR DESCRIPTION
**Pull request by jsquyres**
**_WARNING:**_ This PR depends on two other PRs to be merged first:
1. #626: dynamic add procs
2. #670: opal_progress_thread

Update the usnic BTL to the state it is on master (i.e., copy *.c and *.h from master to v2.x branch).

This PR is rebased off #626 and #670; the only meaningful commit on this PR is the last one (i.e., the usnic update).

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/849/ for details.

**Comment by lanl-ompi** [comment]
Build finished. No test results found.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/906/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/910/ for details.

**Comment by jsquyres** [comment]
@hppritcha This is now good to go.

**Pull request merged**
