### PR TITLE
Sync to PMIx master

### PR DESCRIPTION
**Pull request by rhc54**
Cherry-picked from:

open-mpi/ompi@749bd4e
open-mpi/ompi@209600f
open-mpi/ompi@fad563859630dc36f12bec559093c7fd1cedfd69
open-mpi/ompi@f713e71d51b9935ecc29046a87b2620a06b7c5e4
open-mpi/ompi@a4a3dfd

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/747/ for details.

**Comment by hppritcha** [comment]
neither open-mpi/ompi@be41ea8 nor open-mpi/mpi@415c891
seem to exist.

Which commits are these cherry-picked from?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/759/ for details.

**Comment by rhc54** [comment]
@hppritcha I corrected them - not sure why they were wrong

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
From what @rhc54 tells me, this makes the PMIx integration complete for master/v2.x.

**Comment by jsquyres** [comment]
@hppritcha I think we're ready to go with this one.

**Pull request merged**
