### PR TITLE
MTL portals4 : improve the rendez-vous protocol using PtlTriggeredGet…

### PR DESCRIPTION
**Pull request by francois-wellenreiter**
… operation

### CODE REVIEW

**Comment by francois-wellenreiter** [comment]
equivalent to PR open-mpi/ompi#1137 in ompi repository

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1065/ for details.

**Comment by hppritcha** [comment]
@regrant please double check

**Comment by regrant** [comment]
:+1: Looks good

**Pull request merged**
