### PR TITLE
OSC datatype fix

### PR DESCRIPTION
**Pull request by hjelmn**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/144/

**Build Log**
_last 50 lines_

```
[...truncated 70429 lines...]
config.status: creating ompi/include/mpi.h
config.status: ompi/include/mpi.h is unchanged
config.status: creating oshmem/include/shmem.h
config.status: oshmem/include/shmem.h is unchanged
config.status: creating opal/mca/hwloc/hwloc191/hwloc/include/private/autogen/config.h
config.status: creating opal/mca/hwloc/hwloc191/hwloc/include/hwloc/autogen/config.h
config.status: opal/mca/hwloc/hwloc191/hwloc/include/hwloc/autogen/config.h is unchanged
config.status: executing depfiles commands
config.status: executing opal/mca/event/libevent2021/libevent/include/event2/event-config.h commands
opal/mca/event/libevent2021/libevent/include/event2/event-config.h is unchanged
config.status: executing libtool commands
*** Removing old generated flex files...
./opal/util/show_help_lex.c
./opal/util/keyval/keyval_lex.c
./ompi/mca/btl/openib/btl_openib_lex.c
./ompi/mca/coll/ml/coll_ml_lex.c
./orte/util/hostfile/hostfile_lex.c
./orte/mca/rmaps/rank_file/rmaps_rank_file_lex.c
*** Running make distcheck...
make -j4 dist-bzip2 dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
if test -d "openmpi-1.8.5"; then find "openmpi-1.8.5" -type d ! -perm -200 -exec chmod u+w {} ';' && rm -rf "openmpi-1.8.5" || { sleep 5 && rm -rf "openmpi-1.8.5"; }; else :; fi
test -d "openmpi-1.8.5" || mkdir "openmpi-1.8.5"
 (cd config && make -j4 top_distdir=../openmpi-1.8.5 distdir=../openmpi-1.8.5/config \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/config'
make[2]: warning: -jN forced in submake: disabling jobserver mode.
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/config'
 (cd contrib && make -j4 top_distdir=../openmpi-1.8.5 distdir=../openmpi-1.8.5/contrib \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/contrib'
make[2]: warning: -jN forced in submake: disabling jobserver mode.
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/contrib'
 (cd opal && make -j4 top_distdir=../openmpi-1.8.5 distdir=../openmpi-1.8.5/opal \
     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal'
make[2]: warning: -jN forced in submake: disabling jobserver mode.
make[2]: *** No rule to make target `../config/depcomp', needed by `distdir'.  Stop.
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal'
make[1]: *** [distdir] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
make: *** [dist] Error 2
Make distcheck failed.  Aborting
+ exit 11
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 6795812ee59f98c92e33fa76a909233f868be2f1 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/144/ and message: Merged build finished.
```

Test FAILed.

**Comment by hjelmn** [comment]
retest this please

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/145/
Test PASSed.

**Pull request merged**
