### PR TITLE
mtl/ofi: Remove unused help messages.

### PR DESCRIPTION
**Pull request by yburette**
(cherry-picked from open-mpi/ompi@8bf1c95cdca8a46f588c95a51fedd4b1c1fafdcb)

### CODE REVIEW

**Comment by yburette** [comment]
bot:milestone:v1.10.2
bot:assignee:rhc54
bot:label:bug

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1091/ for details.

**Comment by jsquyres** [comment]
@yburette Can you get a review?

**Comment by rhc54** [comment]
I looked at it   :+1:

**Pull request merged**
