### PR TITLE
configury: test the __sun macro to detect solaris OS.

### PR DESCRIPTION
**Pull request by ggouaillardet**
recent oraclestudio compilers do not set the **sun** macro

(cherry picked from commit open-mpi/ompi@6418d0d118aff87ac3f36b87fb951bd55de21e06)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@rhc54 can you please review this ?

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/73/
Test PASSed.

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
@ggouaillardet Is this necessary for 1.8.4?

**Comment by ggouaillardet** [comment]
Yes,

It (partially) solve an issue reported by Paul when testing rc4 on Solaris with oracle compilers

**Pull request merged**
