### PR TITLE
dl framework: new dynamic loader framework

### PR DESCRIPTION
**Pull request by rhc54**
Embedding libltdl without the use of Libtool bootstrapping has
proven... difficult.  Instead, create a new simple "dl" framework.  It
only provides 4 functions:
- open a DSO (very similar to lt_dlopenadvise())
- lookup a symbol in a previously-opened DSO (very similar to lt_dlsym())
- close a previously-opened DSO (very similar to lt_dlclose())
- iterate over all files in a directory (very similar to ld_dlforeachfile())

There will be follow-on commits with a simple dlopen-based component
(nowhere near as complete/functional as libltdl, but good enough for
Linux and OS X), and a libltdl-based component for all other
platforms.

The intent is that the dlopen-based component can be built by default
in almost all cases.  But if libltdl is available, that component will
be built.  End result: we still get DSO-based functionality by default
in (almost?) all cases.  Without embedding libltdl.  Which is what we
want.

(cherry picked from commit open-mpi/ompi@e81c070ef0f68f9c1e8979cde20a26f622922198)
(cherry picked from commit open-mpi/ompi@7d340c0c26bec976a35297f725a199d7543b9c55)
(cherry picked from commit open-mpi/ompi@39364d315c6070e3e4349c599b9b12ffb840d249)
(cherry picked from commit open-mpi/ompi@a9d86129c6a4f0843f4e405b6d2d3a9e0c8e7c20)
(cherry picked from commit open-mpi/ompi@c683500a2921f05b7172312801545384aadc844f)
(cherry picked from commit open-mpi/ompi@1995f6bebac4d6d9530c0a045a8fbf64c14bf614)
(cherry picked from commit open-mpi/ompi@0a2767a5d33cf652245fce03a21ec76b197ae15a)
(cherry picked from commit open-mpi/ompi@a026456bef166b8896dad7b8b074d5467ef14e9d)
(cherry picked from commit open-mpi/ompi@914880a368566c9d56cd65cd153041cd3bc5759b)
(cherry picked from commit open-mpi/ompi@546ad3f06085fe61bdaef2c36b7908be4fe33233)
(cherry picked from commit open-mpi/ompi@86968dcdda81dabcda3fa3716f680ae87fe9b758)
(cherry picked from commit open-mpi/ompi@3efb5f56aeaa6ca6c845e3d705ad3f84e077f188)
(cherry picked from commit open-mpi/ompi@8fef4e865f0871bfa5f0c2ae768fb1918b4cf3db)
(cherry picked from commit open-mpi/ompi@65a0e041ac8777537ab30059b4f0e78245cf48e5)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/196/

**Build Log**
_last 50 lines_

```
[...truncated 5395 lines...]
 /usr/bin/install -c -m 644 opal_crs.7 '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/share/man/man7'
 /bin/mkdir -p '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/include/openmpi/opal/mca/crs/base'
 /usr/bin/install -c -m 644  base/base.h '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/include/openmpi/opal/mca/crs/base'
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal/mca/crs'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal/mca/crs'
Making install in mca/db
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal/mca/db'
  CC       base/db_base_frame.lo
  CC       base/db_base_select.lo
  CC       base/db_base_fns.lo
  CCLD     libmca_db.la
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal/mca/db'
make[3]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/share/openmpi'
 /bin/mkdir -p '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/include/openmpi/opal/mca/db'
 /usr/bin/install -c -m 644 base/help-db-base.txt '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/share/openmpi'
 /usr/bin/install -c -m 644  db.h db_types.h '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/include/openmpi/opal/mca/db/.'
 /bin/mkdir -p '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/include/openmpi/opal/mca/db/base'
 /usr/bin/install -c -m 644  base/base.h '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/include/openmpi/opal/mca/db/base'
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal/mca/db'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal/mca/db'
Making install in mca/dl
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal/mca/dl'
  CC       base/dl_base_open.lo
  CC       base/dl_base_close.lo
  CC       base/dl_base_select.lo
  CC       base/dl_base_fns.lo
  CCLD     libmca_dl.la
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal/mca/dl'
make[3]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/opal/mca/dl'
/bin/mkdir: cannot create directory `/opal': Permission denied
make[3]: *** [install-nobase_opalHEADERS] Error 1
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal/mca/dl'
make[2]: *** [install-am] Error 2
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal/mca/dl'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/opal'
make: *** [install-recursive] Error 1
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
Setting commit status on GitHub for https://api.github.com/repos/open-mpi/ompi-release/commit/e6f5eca743edface9b4c2ebd5326f9922b86ba7b
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of ef636fa991daab4d4feabfdb6383c2dac969f7a0 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/196/ and message: Merged build finished.
```

Test FAILed.

**Comment by rhc54** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1473 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_197/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_197/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_197/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/197/

**Build Log**
_last 50 lines_

```
[...truncated 24972 lines...]
components.c:106: error: implicit declaration of function ‘lt_dlsym’
components.c:106: error: ‘test_component_handle_t’ has no member named ‘tch_handle’
components.c: In function ‘test_component_close’:
components.c:118: error: ‘test_component_handle_t’ has no member named ‘tch_handle’
components.c:119: error: implicit declaration of function ‘lt_dlclose’
components.c:119: error: ‘test_component_handle_t’ has no member named ‘tch_handle’
components.c:120: error: implicit declaration of function ‘lt_dlexit’
components.c:121: error: ‘test_component_handle_t’ has no member named ‘tch_handle’
components.c: In function ‘try_dlopen’:
components.c:148: error: ‘test_component_handle_t’ has no member named ‘tch_handle’
components.c:148: error: implicit declaration of function ‘lt_dlopen’
components.c:149: error: ‘test_component_handle_t’ has no member named ‘tch_handle’
components.c:151: error: ‘test_component_handle_t’ has no member named ‘tch_handle’
components.c:155: error: ‘test_component_handle_t’ has no member named ‘tch_handle’
components.c:166: error: ‘test_component_handle_t’ has no member named ‘tch_handle’
components.c:166: error: implicit declaration of function ‘lt_dlopenext’
components.c:167: error: ‘test_component_handle_t’ has no member named ‘tch_handle’
components.c:169: error: ‘test_component_handle_t’ has no member named ‘tch_handle’
components.c:173: error: ‘test_component_handle_t’ has no member named ‘tch_handle’
make[3]: *** [components.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test/support'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test/support'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make: *** [check-recursive] Error 1
+ exit 12
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/197/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/197/tap-master-files/cov_stat.tap].
not ok - coverity detected 1473 failures in all_197 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_197/output/errors/index.html
not ok - coverity detected 23 failures in oshmem_197 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_197/output/errors/index.html
ok - coverity found no issues for mxm_197
not ok - coverity detected 7 failures in fca_197 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_197/output/errors/index.html
ok - coverity found no issues for hcoll_197

TAP Reports Processing: FINISH
coverity_for_all    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_197/output/errors/index.html
coverity_for_oshmem http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_197/output/errors/index.html
coverity_for_fca    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_197/output/errors/index.html
Setting commit status on GitHub for https://api.github.com/repos/open-mpi/ompi-release/commit/e81cb868e3e786957bb2c9821ca3be066cd3cfe1
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of c4ed9d3206fecf73020cbe5bf550b47ba99afb06 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/197/ and message: Merged build finished.
```

Test FAILed.

**Comment by mellanox-github** [comment]
- Coverity found 1473 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_198/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_198/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_198/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/198/
Test PASSed.

**Comment by rhc54** [comment]
Looks okay on Mac as well...conditional approval.

**Comment by rhc54** [comment]
Confirmed by Hargrove, Rolf, and MTT

**Pull request merged**
