### PR TITLE
correctly handle mpirun --host <user>@<ip>

### PR DESCRIPTION
**Pull request by ggouaillardet**
This is a one-off patch for the v1.10 series

Thanks Federico Reghenzani for reporting this issue

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:milestone:v1.10.2
:bot:label:bug
:bot:assign: @rhc54

**Comment by ggouaillardet** [comment]
see http://www.open-mpi.org/community/lists/users/2015/11/28042.php

as a side note, i have no idea why it works with two hosts (!)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1034/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1035/ for details.

**Comment by rhc54** [comment]
@ggouaillardet Thank you for looking into this. I'm trying to understand it a bit better, but my limited time may be causing me to miss how this fixes the ssh. I assume that the first ssh from mpirun to the first node is working okay as the rsh/plm component properly parsed the username/addr. I'm guessing that the nidmap the new daemon was given had an incorrect address for the next one to be launched due to this bug, and that is what broke the tree-based launch.

Does that match what you found?

**Comment by ggouaillardet** [comment]
@rhc54 as I wrote earlier, I do not understand everything ...
let's say that opal_net_is_addr("xxx@1.2.3.4") invokes getaddrinfo("xxx@1.2.3.4") and that is an undetermined behavior, or that this code path is only executed when more than two hosts are requested.
if it returns false, then xxx@1.2.3.4 is trimmed to xxx@1 and that will cause ssh to fail.
my pr ensures we invoke opal_net_is_addr("1.2.3.4") which returns true, and everything is fine.
makes (a bit more) sense ?

**Comment by rhc54** [comment]
Okay, I walked thru the code and figured out what was happening - thanks for the fix!

**Pull request merged**
