### PR TITLE
Openib dynamic add proc race conditions

### PR DESCRIPTION
**Pull request by artpol84**
Moving PR https://github.com/open-mpi/ompi/pull/1248 to the v2.x.

### CODE REVIEW

**Comment by artpol84** [comment]
:bot:assign: @hjelmn
:bot:milestone:v2.0.0
:bot:label:bug
:bot:label:blocker

**Comment by artpol84** [comment]
@hppritcha @rhc54 @jsquyres I'm seeing more errors with direct modex in v2.x release than in master. I think the reason is the version of PMIx library. v1.1.2 makes really a huge difference compared to v1.1.0 (that is in the release version).
I think it's time to cherry-pick this from master.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1193/ for details.

**Comment by hjelmn** [comment]
:+1:

**Pull request merged**
