### PR TITLE
Fix a warning and other small cleanups.

### PR DESCRIPTION
**Pull request by thananon**
This patch fixed the warning in MPI_WAIT_ANY

https://github.com/open-mpi/ompi/issues/1924

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2012/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2013/ for details.

**Comment by jsquyres** [comment]
@Di0gen @artpol84 @jladd-mlnx Jenkins MXM appears to be busted again:

```
11:55:16 valgrind: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /hpc/local/benchmarks/hpcx_install_Sunday/hpcx-gcc-redhat7.2/mxm/debug/lib/libmxm.so)
```

**Comment by jladd-mlnx** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2015/ for details.

**Comment by thananon** [comment]
bot:milestone:v2.0.1
bot:label:bug

@bosilca wrote it and I reviewed it. 👍

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Pull request merged**
