### PR TITLE
v2.x - OSHMEM/ikrit: fix valgrind error

### PR DESCRIPTION
**Pull request by mike-dubman**
master commit: https://github.com/open-mpi/ompi/pull/1133

### CODE REVIEW

**Comment by mike-dubman** [comment]
:bot:label:bug
:bot:milestone:v2.0.0

**Comment by mike-dubman** [comment]
@yosefe , @alex-mikheev - please review

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1025/ for details.

**Comment by hppritcha** [comment]
@yosefe please give thumbs up or down
@jladd-mlnx

**Comment by mike-dubman** [comment]
fixed by @yosefe , reviewed by miked.

:+1:

**Pull request merged**
