### PR TITLE
configury: fix pthread_join() call in OPAL_INTL_PTHREAD_TRY_LINK_FORTRAN

### PR DESCRIPTION
**Pull request by ggouaillardet**
(cherry picked from commit 713e3ea2e534b190f0edf37510c423d93f30a2aa)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @jsquyres 
:bot:milestone:v2.0.0
:bot:label:Code-cleanup-low-priority

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1713/ for details.

**Comment by jsquyres** [comment]
👍 

@hppritcha I'd be ok deferring this to v2.0.1.

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1900/ for details.

**Pull request merged**
