### PR TITLE
Add ucx support to ompi and oshmem.

### PR DESCRIPTION
**Pull request by yosefe**
https://github.com/open-mpi/ompi/pull/1008
https://github.com/open-mpi/ompi/pull/1050
https://github.com/open-mpi/ompi/pull/1076
https://github.com/open-mpi/ompi/pull/1086
https://github.com/open-mpi/ompi/pull/1099
https://github.com/open-mpi/ompi/pull/1127

### CODE REVIEW

**Comment by yosefe** [comment]
bot:label:enhancement
bot:milestone:v1.10.3
bot:assign: @rhc54

**Comment by yosefe** [comment]
@miked-mellanox @shamisp @bosilca @alex-mikheev

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1044/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1045/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1046/ for details.

**Comment by rhc54** [comment]
@yosefe Thanks for setting the milestone! I'll hold until after we release 1.10.2 just to keep separation between the bug fixes and the new feature, so we have time for folks to review (the US holiday season is starting and may likely delay things)

**Pull request merged**
