### PR TITLE
Update to latest nightly tarball of hwloc 1.9.1

### PR DESCRIPTION
**Pull request by rhc54**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1695/ for details.

**Comment by rhc54** [comment]
@Di0gen I'm seeing some strange error out of the Jenkins tests that doesn't seem related to anything being done:

```
23:11:34 ../../../opal/.libs/libopen-pal.so: undefined reference to `pthread_atfork'
```

Is there a pthread library missing on the Jenkins server?

**Comment by jladd-mlnx** [comment]
@rhc54 The following PR #1181 broke something and yet it was merged anyway.

**Comment by jladd-mlnx** [comment]
@rhc It's not just isolated to the Jenkins server, it's breaking our MTT builds everywhere. Please fix.

**Comment by jsquyres** [comment]
Yeah, the pthread_atfork problem is legit; not due to any site-specific CI issue.  I think we got "numbed" to CI failures, unfortunately, and missed that this was a legit problem.

**Comment by rhc54** [comment]
Why are we discussing it here instead of there? Has nothing to do with this PR.

**Comment by jsquyres** [comment]
@jladd-mlnx Can you file an issue about the pthread_atfork failure?  Please cite the originating PR (that you mentioned above).  Thanks.

**Comment by sjeaugey** [comment]
Tried that PR and it fixes the hwloc crash problem on my machine causing MTT to report 100% failure on v1.10. So :+1:

Note : I had to use "CFLAGS=-lpthread ./configure ..." to WAR the pthread problem.

**Pull request merged**
