### PR TITLE
oshmem: Fix tarball issue

### PR DESCRIPTION
**Pull request by igor-ivanov**
Fixes open-mpi/ompi#1036

:bot:assign: @jsquyres 
:bot:label:bug
:bot:milestone:v2.0.0

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/957/ for details.

**Comment by mike-dubman** [comment]
:+1:

**Comment by jsquyres** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/958/ for details.

**Pull request merged**
