### PR TITLE
v1.10.2: add missing MPI_xxx_DUP_FN bindings in use-mpi-tkr

### PR DESCRIPTION
**Pull request by jsquyres**
- MPI_COMM_DUP_FN
- MPI_TYPE_DUP_FN
- MPI_WIN_DUP_FN

(cherry picked from commit open-mpi/ompi@26b2ed1069bc9dcf0b7b5912acb90e82678e4e23)

This is from PR open-mpi/ompi#1180

@ggouaillardet please review that I brought this over properly

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1146/ for details.

**Comment by ggouaillardet** [comment]
same comment, open-mpi/ompi@98bf02485dd0040f5db26128d047ee4a3f712975 should be backported to v1.10 too

**Comment by rhc54** [comment]
@ggouaillardet @jsquyres Can we wrap this one up by EOD Friday? I'd like to spin an rc1 prior to the holidays, if possible

**Comment by ggouaillardet** [comment]
@rhc54 i do not have write access to @jsquyres repo, but i can make a new PR right now if needed.

**Comment by rhc54** [comment]
@ggouaillardet That might be the best solution - would you mind?

**Comment by ggouaillardet** [comment]
replaced by #851 
this PR can now be closed (and i do not have the permissions to do it)

**Comment by rhc54** [comment]
Replaced by #851

**Pull request closed without merging**
