### PR TITLE
Fix a build failure when configure'd with --without-hwloc

### PR DESCRIPTION
**Pull request by ggouaillardet**
see http://mtt.open-mpi.org/index.php?do_redir=2236

bot:assign:@rhc54 bot:label:bug bot:milestone:v1.8.5

### CODE REVIEW

**Comment by rhc54** [comment]
This isn't in the 1.8 series and never will be

**Comment by ggouaillardet** [comment]
i think it is ...
i should have mentionned this is a one-off patch (no such problem in the master)
and this is not a backport of open-mpi/ompi@8fe807908031666f00fed514c4e1797c948155c6 i pushed earlier

**Comment by rhc54** [comment]
Sorry - I saw the commit targeted orte-submit, which is not in the 1.8 series. I agree that the singleton component is - I'll have to look at it more closely as that component is very different in 1.8

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/143/
Test PASSed.

**Pull request merged**
