### PR TITLE
osc/pt2pt: do not set rdma_frag after start

### PR DESCRIPTION
**Pull request by hjelmn**
It is possible for the start call to complete the requests. For this
reason the module rdma_frag field should be filled in before start is
called. If the request completes the completion callback will reset
the rdma_frag field to NULL. Fixes a bug discovered by @tkordenbrock.

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

(cherry picked from commit open-mpi/ompi@11c853d05ed2bf364bc659f5a3a21c94d394feae)

### CODE REVIEW

**Comment by hjelmn** [comment]
:bot:label:bug
:bot:milestone:v2.0.1
:bot:assign: @tkordenbrock

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2070/ for details.

**Comment by tkordenbrock** [comment]
This PR fixes the assert() I saw in osc-pt2pt.  :+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Pull request merged**
