### PR TITLE
 Merge pull request #835 to branch v2.x

### PR DESCRIPTION
**Pull request by Zhiming-Wang**
I merged the change set of "Pull Request" #835 into  branch v2.x and added myself into "AUTHORS"

### CODE REVIEW

**Comment by jsquyres** [comment]
This PR includes a change to AUTHORS that is not on master.  Can you commit the change to master first?

**Comment by Zhiming-Wang** [comment]
Done. 
https://github.com/open-mpi/ompi-release/pull/552

**Comment by jsquyres** [comment]
Er... I still don't see your name in AUTHORS on master...?

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
