### PR TITLE
ompi/win: use type int* for MPI_WIN_DISP_UNIT, MPI_WIN_CREATE_FLAVOR …

### PR DESCRIPTION
**Pull request by ggouaillardet**
…and MPI_WIN_MODEL

Thanks Alastair McKinstry for the report.

(back-ported from commit open-mpi/ompi@d08fb46ec732ea36fe5ecb2e33d7fb7c60206b21)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @hjelmn 
:bot:milestone:v1.10.3
:bot:label:bug

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1426/ for details.

**Comment by hjelmn** [comment]
:+1:

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
