### PR TITLE
README: fix a bunch of typos

### PR DESCRIPTION
**Pull request by jsquyres**
Thanks to @PHHargrove for pointing them out.  Really.

Signed-off-by: Jeff Squyres jsquyres@cisco.com

(cherry picked from commit open-mpi/ompi@0d19cc4a13dbf8977f8b1281c67cb60fbca9b140)

### CODE REVIEW

**Comment by jsquyres** [comment]
This is a README update; not waiting for CI.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request merged**
