### PR TITLE
HCOLL: refactoring hcoll_init

### PR DESCRIPTION
**Pull request by bureddy**
https://github.com/open-mpi/ompi/commit/88eb1fa9368400fbdde1790d8a9f3df09473618e

### CODE REVIEW

**Comment by mellanox-github** [comment]
- Coverity found 1467 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_273/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_273/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_273/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/273/
Test PASSed.

**Comment by jladd-mlnx** [comment]
@rhc54 can we please include this PR in the 1.8.5 release? It only affects the HCOLL Coll component. 

bot:assign: @rhc54 
bot:label:enhancement

**Comment by jladd-mlnx** [comment]
bot:assign: @rhc54 
bot:label:enhancement

**Comment by rhc54** [comment]
@jladd-mlnx Looks innocuous enough...sure!

**Pull request merged**
