### PR TITLE
Pr/getview preallocate fixes

### PR DESCRIPTION
**Pull request by edgargabriel**
fixes two of the items reported by @dalcini

@bosilca you already were involved in the creation of one of the patches, would you mind quiickly reviewing this?

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1625/ for details.

**Comment by hppritcha** [comment]
Milestone for this PR?

**Comment by edgargabriel** [comment]
bot:milestone:v2.0.0
bot:label:bug

**Comment by edgargabriel** [comment]
bot:milestone:v2.0.0

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1626/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@jladd-mlnx @Di0gen This is another PR with a failed UCX configure test -- looks like some kind of local error.

**Comment by jladd-mlnx** [comment]
@jsquyres I've disabled the UCX check.

**Comment by jladd-mlnx** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1635/ for details.

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1637/ for details.

**Comment by jsquyres** [comment]
Now the mindist test is failing.

@Di0gen Is there a way to get Jenkins to report each failure -- i.e., export the results into the Jenkins-native format so that it can just show which tests passed / failed (vs. an all-or-nothing result for the entire thing)?

**Comment by bosilca** [comment]
👍

**Comment by opoplawski** [comment]
I'm not sure this completely fixes the behavior of preallocate.  mpi4py test still fails a little later:

```
    def testPreallocate(self):
        ## MPICH2 1.0.x emits a nesting level warning
        ## when preallocating zero size.
        name, ver = MPI.get_vendor()
        if not (name == 'MPICH2' and ver  < (1,1,0)):
            self.FILE.Preallocate(0)
        size = self.FILE.Get_size()
        self.assertEqual(size, 0)
        self.FILE.Preallocate(1)
        size = self.FILE.Get_size()
        self.assertEqual(size, 1)
        self.FILE.Preallocate(100)
        size = self.FILE.Get_size()
        self.assertEqual(size, 100)
        self.FILE.Preallocate(10)
        size = self.FILE.Get_size()
        self.assertEqual(size, 100)
```

fails at the final assert:

```
FAIL: testPreallocate (test_file.TestFileSelf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_file.py", line 49, in testPreallocate
    self.assertEqual(size, 100)
AssertionError: 10 != 100
```

So it looks like the size is going down instead of being unchanged.  Apparently the standard reads:

```
If size is larger than the current file size, the file size increases to size. If size is less than or equal to the current file size, the file size is unchanged.
```

See also https://bitbucket.org/mpi4py/mpi4py/issues/40/test-failures-with-openmpi-200rc2

**Comment by edgargabriel** [comment]
I did already reopen the other ticket, will look into this.

**Pull request merged**
