### PR TITLE
Fix thread multiple performance hit

### PR DESCRIPTION
**Pull request by rhc54**
Pull over Jeff's original patch. Update it per George's comments: since opal_using_threads is always false if thread-multiple hasn't been enabled, there is no reason to include checks for it in that condition. So restore the #if statements in opal/threads/mutex.h to regain the remaining missing performance. Also, restore the thread debugging code as there is no reason to exclude it as it only builds in debug environments

No corresponding master commit as this is solely a 1.8 series issue

@jsquyres @bosilca @hjelmn  please review

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/35/

**Build Log**
_last 50 lines_

```
[...truncated 28112 lines...]
+ make CC=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o bw.o bw.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o bw bw.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o bw_th.o bw_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o bw_th bw_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o latency.o latency.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o latency latency.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o latency_th.o latency_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o latency_th latency_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o shortlong.o shortlong.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o shortlong shortlong.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o shortlong_th.o shortlong_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o shortlong_th shortlong_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o overlap.o overlap.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o overlap overlap.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o no_overlap.o no_overlap.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o no_overlap no_overlap.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o conc_allred.o conc_allred.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o conc_allred conc_allred.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o conc_allred_th.o conc_allred_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o conc_allred_th conc_allred_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o collcomp.o collcomp.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o collcomp collcomp.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o message_rate.o message_rate.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o message_rate message_rate.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o message_rate_th.o message_rate_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o message_rate_th message_rate_th.o
+ popd
/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace
+ for exe in overlap latency latency_th bw_th message_rate_th
+ exe_path=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ PATH=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin:/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ LD_LIBRARY_PATH=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/lib:
+ mpi_runner 2 /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
+ local np=2
+ local exe_path=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ local exe_args=8
+ local 'common_mca=-bind-to core'
+ local 'mca=-bind-to core'
+ timeout -s SIGKILL 3m mpirun -np 2 -bind-to core -mca pml ob1 -mca btl self,tcp /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
[warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
[warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
Time per iteration on each process (ms)
Time     Compute time    Comm time
./hpc_tests/jenkins/ompi/ompi_jenkins.sh: line 77: 19177 Killed                  $timeout_exe mpirun -np $np $mca -mca pml ob1 -mca btl self,tcp ${exe_path} ${exe_args}
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by rhc54** [comment]
I have no idea what that means as there is nothing to tell me about this test - what does it do? Given that this passes my tests locally, I can only discount the report with a shrug

**Comment by mike-dubman** [comment]
@rhc54 - the test downloads package: wget --no-check-certificate http://www.mcs.anl.gov/~thakur/thread-tests/thread-tests-1.1.tar.gz and runs it as 

``` shell
22:47:53 + timeout -s SIGKILL 3m mpirun -np 2 -bind-to core -mca pml ob1 -mca btl self,tcp /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
22:47:53 [warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
22:47:53 [warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
22:47:53 Time per iteration on each process (ms)
22:47:53 Time    Compute time    Comm time
22:47:53 ./hpc_tests/jenkins/ompi/ompi_jenkins.sh: line 77: 19177 Killed                  $timeout_exe mpirun -np $np $mca -mca pml ob1 -
```

tests fails to complete after 3m

**Comment by rhc54** [comment]
Afraid I have no idea why those tests are hanging. Non-threaded apps are working fine, so perhaps someone who cares more about thread-multiple can take a look and find the issue. It doesn't appear related to the changes I made in response to George's requests as I find the same behavior with Jeff's branch, so this must be something to do with enabling thread multiple in general.

**Comment by rhc54** [comment]
@hjelmn @jsquyres I've given you both write permissions into my ompi-release repo so you can commit changes to this branch. Please feel free to clone and update.

**Comment by jsquyres** [comment]
@hjelmn I don't believe that this commit is correct.  Can you look into it?  I _think_ you mentioned that you have a half-complete patch somewhere to fix the real issue.  Is that correct?  If so, can you complete that patch?

I'm struggling with Fortran nastiness at the moment.  :-(

**Comment by jsquyres** [comment]
@hjelmn What's the status -- got an updated patch yet?

**Comment by hjelmn** [comment]
Retest this please

**Comment by mellanox-github** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/41/

**Build Log**
_last 50 lines_

```
[...truncated 28114 lines...]
+ make CC=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o bw.o bw.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o bw bw.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o bw_th.o bw_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o bw_th bw_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o latency.o latency.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o latency latency.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o latency_th.o latency_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o latency_th latency_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o shortlong.o shortlong.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o shortlong shortlong.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o shortlong_th.o shortlong_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o shortlong_th shortlong_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o overlap.o overlap.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o overlap overlap.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o no_overlap.o no_overlap.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o no_overlap no_overlap.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o conc_allred.o conc_allred.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o conc_allred conc_allred.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o conc_allred_th.o conc_allred_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o conc_allred_th conc_allred_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o collcomp.o collcomp.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o collcomp collcomp.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o message_rate.o message_rate.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o message_rate message_rate.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o message_rate_th.o message_rate_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o message_rate_th message_rate_th.o
+ popd
/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace
+ for exe in overlap latency latency_th bw_th message_rate_th
+ exe_path=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ PATH=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin:/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ LD_LIBRARY_PATH=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/lib:
+ mpi_runner 2 /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
+ local np=2
+ local exe_path=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ local exe_args=8
+ local 'common_mca=-bind-to core'
+ local 'mca=-bind-to core'
+ timeout -s SIGKILL 3m mpirun -np 2 -bind-to core -mca pml ob1 -mca btl self,tcp /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
[warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
Time per iteration on each process (ms)
Time     Compute time    Comm time
[warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
./hpc_tests/jenkins/ompi/ompi_jenkins.sh: line 77: 17461 Killed                  $timeout_exe mpirun -np $np $mca -mca pml ob1 -mca btl self,tcp ${exe_path} ${exe_args}
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by hjelmn** [comment]
Drat. Still something wrong. I can't get that test to pass with sm or tcp. Will dig deeper tomorrow.

**Comment by hjelmn** [comment]
There is an issue with the overlap test that jenkins is running. I dug into it and it looks like if the number of ranks is less than 4 then bogus ranks are passed to MPI_Irecv. @miked-mellanox Can you modify jenkins to use at least 4 ranks and retest?

**Comment by mike-dubman** [comment]
@hjelmn - sure, fixed

**Comment by mike-dubman** [comment]
retest this please

**Comment by mellanox-github** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/42/

**Build Log**
_last 50 lines_

```
[...truncated 28116 lines...]
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o bw bw.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o bw_th.o bw_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o bw_th bw_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o latency.o latency.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o latency latency.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o latency_th.o latency_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o latency_th latency_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o shortlong.o shortlong.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o shortlong shortlong.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o shortlong_th.o shortlong_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o shortlong_th shortlong_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o overlap.o overlap.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o overlap overlap.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o no_overlap.o no_overlap.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o no_overlap no_overlap.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o conc_allred.o conc_allred.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o conc_allred conc_allred.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o conc_allred_th.o conc_allred_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o conc_allred_th conc_allred_th.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o collcomp.o collcomp.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o collcomp collcomp.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o message_rate.o message_rate.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o message_rate message_rate.o
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -O   -c -o message_rate_th.o message_rate_th.c
/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/mpicc -o message_rate_th message_rate_th.o
+ popd
/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace
+ for exe in overlap latency latency_th bw_th message_rate_th
+ exe_path=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ PATH=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin:/hpc/local/bin::/usr/local/bin:/bin:/usr/bin:/usr/sbin:/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ LD_LIBRARY_PATH=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/lib:
+ mpi_runner 4 /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
+ local np=4
+ local exe_path=/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap
+ local exe_args=8
+ local 'common_mca=-bind-to core'
+ local 'mca=-bind-to core'
+ timeout -s SIGKILL 3m mpirun -np 4 -bind-to core -mca pml ob1 -mca btl self,tcp /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/thread_tests/thread-tests-1.1/overlap 8
[warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
[warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
[warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
Time per iteration on each process (ms)
Time     Compute time    Comm time
[warn] opal_libevent2021_event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
./hpc_tests/jenkins/ompi/ompi_jenkins.sh: line 77: 17965 Killed                  $timeout_exe mpirun -np $np $mca -mca pml ob1 -mca btl self,tcp ${exe_path} ${exe_args}
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by hjelmn** [comment]
@miked-mellanox Thanks! Looks like something else is still wrong in the tcp btl. Let me see why I can't reproduce the hang in my virtual machine.

**Comment by bosilca** [comment]
The BTL TCP is not supposed to call back into the opal_progress, except if
we run out of descriptors (and then the ompi_freelist is doing the call). I
can't replicate this on my OSX laptop. What are the configuration options
used?

**Comment by hjelmn** [comment]
@bosilca I couldn’t replicate it either until I tried on linux. I configured with: —enable-debug —enable-picky —enable-mpi-thread-multiple

Ran the test with:

mpirun -n 4 -mca btl self,tcp ./overlap 8

And it hangs.

I attached a debugger and found one thread blocked trying to acquire the endpoint send lock and another thread blocked in opal_event_del. Not sure exactly what was going wrong but dropping the send lock fixed that hold-and-wait error but I ran into another similar error. I can get you backtraces of the blocked threads tomorrow.

**Comment by bosilca** [comment]
Thanks, I could now replicate the issue.

The warning is harmless.  The threads are not silently waiting for their
message to arrive, but instead actively call opal_progress, which then
calls opal_event_loop on opal_event_base. Thus, when multiple threads are
calling blocking functions (MPI_Recv and MPI_Waitall in the overlap test),
the warning is triggered. However, while annoying this should be harmless
(because there is nothing waiting on the opal_event_base).

However, the deadlock is real. The fragments seems to be enqueued in the
BTL, but the second send never completes.

  George.

**Comment by hjelmn** [comment]
@bosilca It looks to me like in some cases the thread holding the endpoint lock calls event_del on the event the thread blocked trying to acquire the endpoint lock is processing. This blocks the event_del thread in a condition variable leading to hold-and-wait. One fix is if you can drop both the send and recv endpoint lock whenever you are calling event_del. I don't know the code well enough to know if that is safe to do.

Anyway, should we consider that a separate bug from the one this pull request addresses? If so we can bump fixing thread multiple for tcp to 1.8.5 if needed.

**Comment by rhc54** [comment]
I'm inclined to accept George's suggestion so we can at least let the Intel guys verify that performance has been restored to 1.6 levels. Any comments?

**Comment by bosilca** [comment]
I'm working on a fix. I did some progress this week, but due to travel I
had no time to complete everything. Give me a week, and I'll do my best to
provide a patch to solve the deadlock issue.

**Comment by rhc54** [comment]
@bosilca Sorry to be a nag, but I was wondering if you have had time to work on this? If not, would you be okay with me at least generating a release candidate with the patch as-is? Should we have the tcp/btl disqualify itself (with warning?) if thread-multiple is requested?

**Comment by bosilca** [comment]
Disqualifying the TCP BTL seems like a major step backward. I have a patch that make it work on all Linux boxes I have access to (3-4). However, it fails to complete on my Mac for a strange reason, not yet very clear in my mind.

The issue is always the same: I end-up having a connection problem, the callback associated with an send event is never triggered (so all the pending message will not be delivered), while the callback associated with the recv handler is triggered every iteration of opal_progress (despite the fact that the corresponding read reads 0 bytes). This leads me to the conclusion that somehow we are using the libevent in a non standard, maybe non thread-safe way. and libevent end-up confusing the send and recv events.

Bear with me for the longer explanation. When we remove an event from the libevent, this removal is not done right away. Instead the libevent schedule an internal trigger, that will be called at the end of the opal_progress (and this will indeed remove the event from the libevent queue). However, the most usual instance in the TCP BTL for deleting an event is during the connection stage, when both peers initiate the connection in same time (which is exactly what the overlap test is doing). During this initial handshake, one of the peers will drop the original socket (the one created with a connect) in order to replace it with the socket created by the accept. In this execution path, we are reinstating the send and recv event, right after deleting them. As, I explained above, the deletion is delayed we are totally confusing the libevent, and the result is that the wrong events are triggered.

**Comment by rhc54** [comment]
Yeah, I really, really would rather not disable TCP under thread-multiple.

Libevent is supposed to be built with its internal thread-safety enabled in the 1.8 series, so the threading issue shouldn't be causing the problem. I know we had simultaneous connection issues in the OOB, but this sounds somewhat different so I don't think our solution would resolve this one. I'll ponder too.

**Comment by bosilca** [comment]
Just to be clear, I was not blaming libevent per se, but the way we are
using it. The more I look at the output I get on my Mac, the more I think
the problem is a subtle race condition between the delayed event_delete and
the addition of a new event on the same data structure.

The puzzling part is that this code worked perfectly before, so I wonder if
there was a change lately in the way libevent add and removes events from
the base.

  George.

**Comment by rhc54** [comment]
Could be. One thing occurred to me as I was playing around a bit. I managed to get a warning about re-entrant behavior on libevent, and traced it back to use of the tcp/btl. Is it possible you are calling opal_progress from within an event? If so, libevent doesn't support that operation.

What we do in ORTE is have a single thread that is calling event_loop, and then multiple threads that are adding/deleting events. libevent seems to handle that just fine - at least, we haven't surfaced any problems even when we stress test it in the Intel QA team.

When you are in an event, you can modify events - the only thing you cannot do is call event_loop, or have multiple threads calling event_loop. Is it possible you have multiple threads calling opal_progress, and that the event_loop call down there isn't protected?

**Comment by bosilca** [comment]
On Fri, Dec 12, 2014 at 5:02 AM, rhc54 notifications@github.com wrote:

> Could be. One thing occurred to me as I was playing around a bit. I
> managed to get a warning about re-entrant behavior on libevent, and traced
> it back to use of the tcp/btl. Is it possible you are calling opal_progress
> from within an event? If so, libevent doesn't support that operation.
> 
> The libevent behavior is more subtle than suggested above. One can safely
> call progress recursively, it is just that the internal call does not
> progress anything. In other terms, one cannot wait for the completion of
> anything that is event-based in an libevent callback. If I remember
> correctly this was the type of behavior that plague ORTE for some time.

But the TCP BTL usage pattern is different. When multi-threaded is enabled,
two threads can call progress on the same base, raising the libevent error
you noticed. Fortunately, despite what the warning states this particular
usage is harmless (but indeed annoying).

> What we do in ORTE is have a single thread that is calling event_loop, and
> then multiple threads that are adding/deleting events. libevent seems to
> handle that just fine - at least, we haven't surfaced any problems even
> when we stress test it in the Intel QA team.
> 
> When you are in an event, you can modify events - the only thing you
> cannot do is call event_loop, or have multiple threads calling event_loop.
> Is it possible you have multiple threads calling opal_progress, and that
> the event_loop call down there isn't protected?
> 
> event_loop is protected against simultaneous calls from multiple threads.
> The usage pattern I described in my previous email is slightly different.
> Each endpoints (which represent a specific connection with a particular
> peer), has two placeholders for libevent events. These placeholders are
> statically allocated as part of the main endpoint structure. When a
> connection must be dropped because of the handshake protocol, we remove and
> then add in the same iteration of the event_loop the events associated with
> with the two placeholders in the endpoint structure, creating some kind of
> race condition between the old and the new triggers. I will continue to
> investigate...

**Comment by bosilca** [comment]
open-mpi/ompi@2edbe16c477bf20803367d430b0eefa5849eead8 and open-mpi/ompi@5b8616d8906ad379d7e949f2aa1487db1afbdfe8 fix the TCP deadlock issue in the trunk. If interested in the description of the problem and the proposed solution, read the log of open-mpi/ompi@5b8616d8906ad379d7e949f2aa1487db1afbdfe8. These two commits should be back-ported here to hopefully re-enable TCP thread-safety in the 1.8 series.

**Comment by rhc54** [comment]
Indeed subtle - thanks George!!

**Comment by rhc54** [comment]
Replaced by separate pull request that has all merge conflicts fixed.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/65/
Test PASSed.

**Pull request closed without merging**
