### PR TITLE
v2.x: various mca/coll fixes

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1836/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1837/ for details.

**Comment by ggouaillardet** [comment]
:bot:label:bug
:bot:milestone:v2.0.1
:bot:assign: @bosilca

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1838/ for details.

**Comment by bosilca** [comment]
👍

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1840/ for details.

**Comment by ggouaillardet** [comment]
@bosilca i pushed two more commits and rewrote one commit message

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1841/ for details.

**Comment by bosilca** [comment]
looks good. 👍

**Comment by hppritcha** [comment]
RMs plan to give this very big PR its own merge day.

**Comment by bosilca** [comment]
👍

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1968/ for details.

**Pull request merged**
