### PR TITLE
help-orterun: remove blank line at end of help message

### PR DESCRIPTION
**Pull request by jsquyres**
Signed-off-by: Jeff Squyres jsquyres@cisco.com

(cherry picked from commit open-mpi/ompi@cc651408dc4a12e6ff32700fb92a5f0deae87eed)

### CODE REVIEW

**Comment by jsquyres** [comment]
@hppritcha This is a trivial removal of a blank line in a help message.  I'll let you merge.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1994/ for details.

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1997/ for details.

**Pull request merged**
