### PR TITLE
bug fix: race condition when multiple threads create the same endpoint simultaneously

### PR DESCRIPTION
**Pull request by abouteiller**
This is a straight cherry-pick of 
open-mpi/ompi@7f65c2b
open-mpi/ompi@4899c89
open-mpi/ompi@627a89b

:bot:milestone:v2.0.0
:bot:label:bug

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1662/ for details.

**Comment by jsquyres** [comment]
@abouteiller Who can review this?

**Comment by hppritcha** [comment]
assigning to @hjelmn

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1669/ for details.

**Comment by hjelmn** [comment]
:+1: looks ok to me

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Pull request merged**
