### PR TITLE
Pr/1.10.x/fortran dup fn fix

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:label:bug
:bot:assign: @jsquyres 
:bot:milestone:v1.10.2

@rhc54 this replaces #839 
i am now testing it one more time

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1165/ for details.

**Comment by ggouaillardet** [comment]
@rhc54 as far as i am concerned, this is ready for primetime

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1166/ for details.

**Comment by jsquyres** [comment]
@ggouaillardet Did you write some tests for this, perchance?

**Comment by ggouaillardet** [comment]
yes, I will commit them on monday.
note the ibm test suite cannot build unless the pr are merged, so I might wait until I commit.

**Comment by jsquyres** [comment]
Fair enough. If you want to send them to me out-of-band, I'll check them.

**Pull request merged**
