### PR TITLE
v2.x: fix sec/native module under Solaris and other misc issues

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:label:bug
:bot:label:blocker
:bot:label:WIP-DNM
:bot:milestone:v2.0.1
:bot:assign: @rhc54 

this PR should not be merged before both pmix/master#135 and open-mpi/ompi#2001 are merged upstream

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2117/ for details.

**Comment by rhc54** [comment]
👍 

Been committed upstream in PMIx - ready to go here

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2118/ for details.

**Comment by jsquyres** [comment]
@hppritcha Looks like all conditions have been satisfied.  Good to go.

**Pull request merged**
