### PR TITLE
Update the PMI configure logic

### PR DESCRIPTION
**Pull request by rhc54**
Update the PMI configure logic to the minimum level required to address user-reported problems

@jsquyres please review

### CODE REVIEW

**Comment by rhc54** [comment]
FWIW: I have verified this patch on the release branch. Just waiting for official "okey-dokey" from @jsquyres

**Comment by jsquyres** [comment]
@rhc54 I have a dim recollection that this PR does not directly correspond to master commits because v1.8 has diverged too far -- is that right?

If so, is that why this commit does not reflect the simpler breakdown of helper macros in opal_check_pmi.m4 from master?

**Comment by rhc54** [comment]
Yeah, that's the problem all right. In master, we have separate pmi1 and pmi2 components, and so we need to reflect that in the logic. In 1.8, we only have one pmi component and use #if's to select pmi2 vs pmi1.

**Comment by jsquyres** [comment]
Good enough for v1.8.

**Pull request merged**
