### PR TITLE
Topic/v2.x/no cast away const

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/736/ for details.

**Comment by hjelmn** [comment]
Opps, this tries to pull in the libnbc rewrite which conflicts with another PR.

**Comment by hppritcha** [comment]
I want to test this with artifacts in the compiler museum on hopper before merging.

**Comment by hppritcha** [comment]
@ggouaillardet  what's the reason for including b4aa612

**Comment by hjelmn** [comment]
I think it was included because he modified libnbc to include const. If we merge the libnbc changes before this we should be ok. Otherwise it will take some work by @ggouaillardet to separate out those changes.

**Comment by hppritcha** [comment]
@ggouaillardet  please review #549 so that can be merged, then we can pull in this pr.  Marking as pushed back till PR #549 is merged.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/753/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/754/ for details.

**Comment by hppritcha** [comment]
@miked-mellanox  what's this new jenkins project?

**Comment by jsquyres** [comment]
#549 was merged -- please rebase this PR and fix conflicts, then we should be good to go.

Thanks!

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/763/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/765/ for details.

**Comment by ggouaillardet** [comment]
:bot:nolabel:pushed-back
@jsquyres @hppritcha i did rebase and fixed what had to be fixed, this PR should (finally !) be good for primetime

**Comment by jsquyres** [comment]
@hppritcha I think this is good to go.

**Pull request merged**
