### PR TITLE
ikrit: set DC defaults.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@miked-mellanox

**Comment by mike-dubman** [comment]
:+1:

**Comment by mike-dubman** [comment]
bot:milestone:v1.8.0

**Comment by mike-dubman** [comment]
bot:milestone:v1.8

**Comment by mike-dubman** [comment]
bot:milestome:v1.8.7

**Comment by jsquyres** [comment]
v1.8.7 was released July 15.  I assume you mean v1.8.8?

**Comment by mike-dubman** [comment]
bot:milestome:v1.8.8

**Comment by mike-dubman** [comment]
bot:milestone:v1.8.

**Comment by mike-dubman** [comment]
bot:milestome:v1.8.8

**Comment by mike-dubman** [comment]
bot:milestone:v1.8.8

**Pull request merged**
