### PR TITLE
Fix abnormal shutdown when a node dies

### PR DESCRIPTION
**Pull request by rhc54**
(cherry picked from commit open-mpi/ompi@bc7a7f3de557ee568d782288efce6b9cf2b7e46e)
(cherry picked from commit open-mpi/ompi@3510bb4cedb8b70a340a33e0fa192691c260cdec)
(cherry picked from commit open-mpi/ompi@55cd2a07f6c6b242f797cb8282a956bc4ad46405)

@jsquyres please review

### CODE REVIEW

**Comment by mellanox-github** [comment]
- Coverity found 1465 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_286/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_286/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_286/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/286/
Test PASSed.

**Comment by jsquyres** [comment]
I confirm that this PR works, however, it has the same problem noted in https://github.com/open-mpi/ompi/pull/598#issuecomment-104881184: the ssh to the failed server is still running, and eventually times out / dies, and emits a nebulous error message to the shell asynchronously.

:bot:assign:rhc54

**Comment by rhc54** [comment]
@jsquyres I think I have this fixed - at least, on my multi-node tests on odin using the rsh launcher, the ssh sessions are gone when we abnormally terminate. However, I'm not sure I was seeing that behavior reliably, and so I don't know for certain that I've fixed it.

Can you please confirm?

**Comment by mellanox-github** [comment]
- Coverity found 1465 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_287/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_287/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_287/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/287/
Test PASSed.

**Comment by jsquyres** [comment]
FWIW: I confirm that this appears to be fixed on the v1.8 branch and master.

**Pull request merged**
