### PR TITLE
io/ompio: Add barrier to file_close and file_set_size

### PR DESCRIPTION
**Pull request by edgargabriel**
This fixes a bug reported on the mailing for ompio.
https://www.open-mpi.org/community/lists/users/2016/05/29333.php

:bot:milestone:v2.0.1
:bot:label:bug
:bot:assign:@ggouaillardet

@ggouaillardet would you mind reviewing this fix, since you did the counterpart in romio314 ? The issue here was that the barrier in file_close was not sufficient, there has to be a barrier in file_set_size as well, since the user test case otherwise had the potential to reset the size to 0 _after_ some processes already wrote some data. It works now for me for both file_write_at and file_write_shared without any issues.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2026/ for details.

**Comment by edgargabriel** [comment]
the same hcoll issues on mellanox

19:54:07 --- MCA component coll:hcoll (m4 configuration macro)
19:54:07 checking for MCA component coll:hcoll compile mode... dso
19:54:07 checking hcoll/api/hcoll_api.h usability... yes
19:54:07 checking hcoll/api/hcoll_api.h presence... yes
19:54:07 checking for hcoll/api/hcoll_api.h... yes
19:54:07 looking for library in lib
19:54:07 checking for library containing hcoll_get_version... no
19:54:08 looking for library in lib64
19:54:08 checking for library containing hcoll_get_version... no
19:54:08 configure: error: HCOLL support requested but not found.  Aborting
19:54:08 Build step 'Execute shell' marked build as failure

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2027/ for details.

**Comment by hppritcha** [comment]
@edgargabriel please assign a reviewer.

**Comment by edgargabriel** [comment]
I actually did, butit does not show up for whatever reason, lets try again
:bot:assign:@ggouaillardet

**Comment by edgargabriel** [comment]
bot:assign:@ggouaillardet

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2034/ for details.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2043/ for details.

**Comment by ggouaillardet** [comment]
:+1:

**Comment by hppritcha** [comment]
@jsquyres ready to go

**Pull request merged**
