### PR TITLE
timer/aix: remove stale code

### PR DESCRIPTION
**Pull request by jsquyres**
Per discussion on the mailing list and with IBM, remove the AIX timer
code (since AIX is no longer supported).

Signed-off-by: Jeff Squyres jsquyres@cisco.com

(cherry picked from commit open-mpi/ompi@b4982d7725b44d0dbd00710e438adc5502c122aa)

### CODE REVIEW

**Comment by jsquyres** [comment]
@hppritcha Got feelings about removing `timer/aix` from 2.0.0 or pushing this to v2.0.1?  I'm ok either way.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1640/ for details.

**Comment by jsquyres** [comment]
@jladd-mlnx @Di0gen Is it possible to get a backtrace from the corefile generated by the failed Jenkins test?  The output from jenkins is unreadable -- we can't tell where the actual error is (it doesn't have anything to do with this PR, though).

**Comment by mike-dubman** [comment]
- judging by console output - it seems like munmap issues driven by patcher framework, which is appearing and loaded in the stacktraces.
- maybe it should be OFF by default and tested aside

``` shell
23:27:38 + /var/lib/jenkins/jobs/gh-ompi-release-pr/workspace/ompi_install1/bin/mpirun -np 8 --map-by dist -mca rmaps_dist_device mlx4_0 -x TEST_CLOSEST_NUMA -x TEST_PHYS_ID_COUNT -x TEST_CORE_ID_COUNT /scrap/jenkins/jenkins/jobs/gh-ompi-release-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test
23:27:40 *** glibc detected *** /scrap/jenkins/jenkins/jobs/gh-ompi-release-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test: munmap_chunk(): invalid pointer: 0x00007fffffffda0d ***
23:27:40 *** glibc detected *** /scrap/jenkins/jenkins/jobs/gh-ompi-release-pr/workspace/jenkins_scripts/jenkins/ompi/mindist_test: munmap_chunk(): invalid pointer: 0x00007fffffffda0d ***
```

**Comment by mike-dubman** [comment]
@jsquyres - the output of jenkins is a simple text console log. 
We did not find a better way to render results. 
If you have suggestions how to format it better - please send.
Jenkins runs many tests and presenting results and UI for it is not well-defined in jenkins itself.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1643/ for details.

**Comment by jsquyres** [comment]
@miked-mellanox I was asking just for a specific core file for this specific failed test, but it looks like the real error was http://www.open-mpi.org/community/lists/devel/2016/05/18962.php, and has apparently been fixed.  Thanks!

**Comment by hppritcha** [comment]
I vote for removal.

**Comment by jsquyres** [comment]
👍

**Pull request merged**
