### PR TITLE
Pr/commits of week 47

### PR DESCRIPTION
**Pull request by edgargabriel**
@hppritcha could you give these commits a try on one of your machines? It fixes the lustre configuration problem that Ralph reported on odin, and one item that we found during our performance tests in the last two weeks.

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1028/ for details.

**Comment by hppritcha** [comment]
mlnx jenkins is never in a good mood nowadays, but it looks like the lanl disable dlopen check is transient.  Let's try again.
bot:retest

**Comment by hppritcha** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1031/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1032/ for details.

**Comment by hppritcha** [comment]
I will get to this next week.

**Comment by hppritcha** [comment]
:+1:
works for me on gpfs and lustre at nersc.
@jsquyres this is ready to go.

**Comment by hppritcha** [comment]
bot:retest

**Pull request merged**
