### PR TITLE
Roll the update for PMIx to the 1.1.2 release, and add support for external PMIx libraries

### PR DESCRIPTION
**Pull request by rhc54**
The following is not an exhaustive list of changesets, but represents the major ones:

open-mpi/ompi@9803d69d024381657ca2daa2cc44b5e989099a3a
open-mpi/ompi@03eb1a80bf088bfbb058282afedce4beed79a3d4
open-mpi/ompi@3a56f0d34b86a337faa5c36f04535b0e45876961
open-mpi/ompi@75d16cfb2741345cc54a596198dd479ad37fe4df

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1158/ for details.

**Comment by hppritcha** [comment]
I'll do some sanity checks on various clusters.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1163/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1164/ for details.

**Comment by hppritcha** [comment]
:+1:

I'm hitting some issues on the system at nersc but I don't think they are related this pmix refresh.

**Comment by jsquyres** [comment]
@hppritcha Do you want me to roll this in before the rc?  Seems like a big change with no testing for the rc...?

**Comment by hppritcha** [comment]
okay lets hold off for rc1.

**Comment by jsquyres** [comment]
Now that we're past the winter holidays and rc1 is out, let's put this in an let it soak on the branch.

**Pull request merged**
