### PR TITLE
ikrit: set DC defaults.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@miked-mellanox

**Comment by mike-dubman** [comment]
:+1:

**Comment by jsquyres** [comment]
@yosefe can you please set a milestone on this PR (and your other PRs)?  Thanks.

**Comment by mike-dubman** [comment]
bot:milestone:v1.10
bot:label:enhancement

**Comment by mike-dubman** [comment]
bot:milestone:v1.10.0

**Pull request merged**
