### PR TITLE
fix infinite recursion during mkey exchange at scale

### PR DESCRIPTION
**Pull request by mike-dubman**
in master: https://github.com/open-mpi/ompi/pull/331

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/102/
Test PASSed.

**Comment by jladd-mlnx** [comment]
@rhc54 I spoke with @miked-mellanox about this and he said it would not be catastrophic if 1.8.5 (and, hence, this PR) went out in a month or so. No need to rapidly put out 1.8.5 on account of the PR. Thanks for asking, though.

**Comment by rhc54** [comment]
Okay, thanks - can someone please review it?

**Comment by mike-dubman** [comment]
it was reviewed by @alex-mikheev

**Pull request merged**
