### PR TITLE
osc/sm: create datafile into the per proc directory in order to make …

### PR DESCRIPTION
**Pull request by ggouaillardet**
…it unique per communicator

Thanks Peter Wind for the report

(cherry picked from commit open-mpi/ompi@6eac6a8b002d3992182c141334a7009ba5fa6176)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @hjelmn 
:bot:milestone:v2.0.0
:bot:label:bug
:bot:label:blocker

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1311/ for details.

**Comment by hjelmn** [comment]
:+1:

**Comment by hppritcha** [comment]
@jsquyres do any of the cisco mtt runs use SM btl?  Doesn't look like cisco mtt ran last nite.  I'd like for commit open-mpi/ompi@6eac6a8b to get tested at cisco before merging in to 2.x

**Comment by jsquyres** [comment]
Yes, we test both vader and sm.  I'll go kick MTT to see why it didn't run...

**Comment by hjelmn** [comment]
This doesn't involve the sm btl. This is the sm osc component which is tested by everyone running the ibm test suite in ompi-tests.

**Comment by hppritcha** [comment]
there appear to be one-sided failures on ivy cluster MTT runs last nite.
@sjeaugey could you check about these?  It looks like there are new ones since the open-mpi/ompi@6eac6a8b commit.

**Comment by hppritcha** [comment]
no go on this stuff till problems in master are resolved.  see yet another issue related to osc on master-
https://github.com/open-mpi/ompi/issues/1342#issuecomment-180163538
this is really getting annoying.

**Comment by ggouaillardet** [comment]
@hppritcha these are two independant issues

this PR fixes a bug in the `sm` `osc` component
open-mpi/ompi#1341 is the PR that fixes the regression recently introduced in th `pt2pt` `osc` component
the mtt failures are all related to `pt2pt`

**Comment by hppritcha** [comment]
Yep I agree.  Removing the pushed-back label for this PR.

**Comment by hppritcha** [comment]
@jsquyres I think this is good to go.

**Pull request merged**
