### PR TITLE
Fix iallgather problem with intercommunicators

### PR DESCRIPTION
**Pull request by hppritcha**
A problem was found with the libnbc MPI_Iallgather
routine when using intercommunicators.  Special
thanks to Takahiro Kawashima(Fujitsu) for the patch
and a test case.  Verified master fails without the
patch and the test passes with the patch applied.

open-mpi/ompi@bb65835816056b1f51d6b91ee3998f836634e9bc

### CODE REVIEW

**Comment by mike-dubman** [comment]
Can one of the admins verify this patch?

**Comment by jsquyres** [comment]
@miked-mellanox To whom are you referring?  I.e., who is it that you want to review this patch?

**Comment by mike-dubman** [comment]
oohh... sorry. testing jenkins plugin which does commenting as well with my username "access key" :)
intent was to use my other repo for tests, missed it.
sorry about that.

**Comment by rhc54** [comment]
Needs a review in order to progress

**Comment by hjelmn** [comment]
Reviewed. PR fixes an obvious typo in the collective.

Howard, if you haven't already can you push the test to ompi-tests?

**Comment by hppritcha** [comment]
Yep,

Will do that next week.

Howard

2014-10-23 8:58 GMT-06:00 Nathan Hjelm notifications@github.com:

**Pull request merged**
