### PR TITLE
Add opal destructor/fini function

### PR DESCRIPTION
**Pull request by hjelmn**
In order for this to be useful several commits had to be brought over from master. All of these commits fix bugs relevant to 1.8.5.

### CODE REVIEW

**Comment by hjelmn** [comment]
@rhc54, @jsquyres Please take a look.

**Comment by hjelmn** [comment]
Runs new MPI_T MTT tests cleanly:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
PASS: simple_init
PASS: init_after_finalize
PASS: loop_init
PASS: init_before_mpi
make[3]: Nothing to be done for `all'.
============================================================================
Testsuite summary for ompi-ibm 10.0
============================================================================
# TOTAL: 4
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

**Comment by hjelmn** [comment]
One nice feature of the the destructor/fini commit is if the compiler/linker combination doesn't support either a destructor or -fini on re-init it will print out a message and exit. This is an improvement on the current behavior: SEGV.

**Comment by hjelmn** [comment]
:bot:assign: @rhc54

**Comment by hjelmn** [comment]
Just for reference there is a combination without either -fini or destructor. OS X ld + pgi. I don't think any of us use pgi on the Mac though.

**Comment by mellanox-github** [comment]
- Coverity found 1472 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_221/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_221/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_221/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/221/
Test PASSed.

**Comment by hjelmn** [comment]
Latest version is a spelling fix.

**Comment by mellanox-github** [comment]
- Coverity found 1472 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_223/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_223/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_223/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/223/
Test PASSed.

**Comment by hjelmn** [comment]
@jsquyres I modified the configury. Let me know what you think.

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/230/

**Build Log**
_last 50 lines_

```
[...truncated 126 lines...]
+++ shopt -s checkwinsize
+++ '[' '\u@\h \w \n\$' = '\s-\v\$ ' ']'
+++ shopt -q login_shell
++ source /hpc/local/etc/hpc_profile
+++ '[' -f /usr/share/Modules/init/bash ']'
+++ . /usr/share/Modules/init/bash
++++ export -f module
++++ MODULESHOME=/usr/share/Modules
++++ export MODULESHOME
++++ '[' tools/hpc = '' ']'
++++ '[' /usr/share/Modules/modulefiles:/etc/modulefiles:/hpc/local/etc/modulefiles:/opt/mellanox/bupc/2.18.0/modules = '' ']'
++++ '[' 4 -ge 3 ']'
++++ '[' -r /usr/share/Modules/init/bash_completion ']'
++++ . /usr/share/Modules/init/bash_completion
+++++ complete -o default -F _module module
+++ module load tools/hpc
++++ /usr/bin/modulecmd bash load tools/hpc
+++ eval SSH_ASKPASS= ';export' 'SSH_ASKPASS;'
++++ SSH_ASKPASS=
++++ export SSH_ASKPASS
+++ export PATH=/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+++ PATH=/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+++ export 'PS1=\u@\h \w \n\$'
+++ PS1='\u@\h \w \n\$'
++ BLACK='\[\033[0;0m\]'
++ RED='\[\033[0;31m\]'
++ RED_BOLD='\[\033[01;31m\]'
++ BLUE='\[\033[01;94m\]'
++ GREEN='\[\033[0;32m\]'
++ CYAN_BOLD='\[\033[1;36m\]'
++ YELLOW_BOLD='\[\033[1;33m\]'
++ WHITE_BOLD='\[\033[1;37m\]'
+ export PATH=/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ PATH=/hpc/local/bin:/hpc/local/bin/:/hpc/local/bin/:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/sbin:/opt/ibutils/bin
+ rm -rf jenkins_scripts
+ git clone https://github.com/mellanox-hpc/jenkins_scripts
Cloning into 'jenkins_scripts'...
error: Failed connect to github.com:443; Operation now in progress while accessing https://github.com/mellanox-hpc/jenkins_scripts/info/refs?service=git-upload-pack
fatal: HTTP request failed
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
Setting commit status on GitHub for https://github.com/open-mpi/ompi-release/commit/178337a637bcb908ec18fad175b583cad456158d
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Setting status of 329fac3e8bff9bba9f6570e1bec6684a80671bb8 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/230/ and message: Merged build finished.
```

Test FAILed.

**Comment by hjelmn** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1472 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_231/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_231/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_231/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/231/
Test PASSed.

**Comment by hjelmn** [comment]
Merged into master as commit open-mpi/ompi@8287e1d28faa83e99de378badd71ad7a57b0f4c0.

**Comment by rhc54** [comment]
@hjelmn I see where you set opal_register_done to false, but I never see a place where it gets set to true. Did I miss it somewhere?

**Comment by hjelmn** [comment]
It was already set in `opal_register_params()`. As George already did on master I moved the variable definition out of that function and made it static in the file. If the value is not set to false on opal_finalize_util subsequent attempts to register opal parameters will fail.

**Comment by rhc54** [comment]
Okay, thanks!
:+1:

**Pull request merged**
