### PR TITLE
Openib proc account fix v2.x

### PR DESCRIPTION
**Pull request by artpol84**
**Comes from PR https://github.com/open-mpi/ompi/pull/1260**

### CODE REVIEW

**Comment by artpol84** [comment]
:bot:assign: @hjelmn
:bot:milestone:v2.0.0
:bot:label:bug
:bot:label:blocker

**Comment by artpol84** [comment]
@hjelmn with 3 recent PR's I still see a hang that appears for P2P test in ompi-test-suite. None of my PRs affect this hang (it appears regardless whether they present or not).
master is free from that problem so I guess that something wasn't ported to v2.0.

**Comment by artpol84** [comment]
P.S. and this problem seems familiar however I can't remember exactly what it was.
I'll be able to return to this after Thursday.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1214/ for details.

**Comment by hjelmn** [comment]
:+1:

**Pull request merged**
