### PR TITLE
v2.x MPI_Aint functions

### PR DESCRIPTION
**Pull request by hjelmn**
Opps, forgot to bring these over earlier.

:bot:assign: @jsquyres 
:bot:label:bug
:bot:milestone:v2.0.0

### CODE REVIEW

**Comment by hppritcha** [comment]
note I'm upgrading some plugins on the IU jenkins server so the LANL checks are not going to complete for a while, as the server is draining the current builds in order to safely restart.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/841/ for details.

**Comment by jsquyres** [comment]
@hjelmn Same comment as https://github.com/open-mpi/ompi-release/pull/666#issuecomment-148127582 -- do we have any regression tests for these (particularly the Fortran bindings)?  I ask because the Fortran bindings are tricky to get right.  :-(

**Comment by hjelmn** [comment]
@jsquyres If I remember you did some testing which lead to the second commit in this PR.

**Comment by hppritcha** [comment]
I thought Nathan used some of the mpich tests and found bugs in them.

**Comment by hjelmn** [comment]
@hppritcha Yes, we found bugs in the fortran that @jsquyres fixed. All the relevant commits are in this PR.

**Comment by hjelmn** [comment]
See open-mpi/ompi#629

**Comment by hjelmn** [comment]
missed a minor commit. added.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/844/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
MTT IBM MPI_Aint_\* tests coming shortly.

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/853/ for details.

**Comment by hppritcha** [comment]
is this ready to merge?

**Comment by jsquyres** [comment]
Yes.  Tests have been committed to the IBM test suite, so we'll find out if there's any problems.

**Pull request merged**
