### PR TITLE
BUILD: allow specifying platform patch_dir from cmd line

### PR DESCRIPTION
**Pull request by mike-dubman**
before:

patch_dir=$PLATFORM.patches

after

./configure --with-platform=FILE --with-platform-patches-dir=DIR ...
if not specified - use default

master commit: https://github.com/open-mpi/ompi/pull/992

### CODE REVIEW

**Comment by mike-dubman** [comment]
:bot:assign: @hppritcha

:bot:label:enhancement
:bot:milestone:v2.0.0

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/821/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/825/ for details.

**Comment by hppritcha** [comment]
:+1:

**Comment by hppritcha** [comment]
@jsquyres I think this is good to merge.

**Comment by jsquyres** [comment]
@miked-mellanox please fix the commit message :-1:

**Pull request closed without merging**
