### PR TITLE
Ensure that configure aborts if knem support explicitly requested, but not found

### PR DESCRIPTION
**Pull request by rhc54**
Ensure that configure aborts if knem support was explicitly requested, but the required headers cannot be found

Tracks master commit open-mpi/ompi@6287d43c475fe6de6e3e44cbc3fdbe4f7e08e9a2

@hjelmn please review

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/38/
Test PASSed.

**Comment by jsquyres** [comment]
If I revert open-mpi/ompi@6287d43c475fe6de6e3e44cbc3fdbe4f7e08e9a2 (i.e., this patch) on the master, and I a) install KNEM to /opt/knem, and b) specify `--with-knem`, then configure fails as expected (because knem_io.h is not found in any default paths):

``` shell
$ ./configure --with-knem |& tee config.out 
...
--- MCA component btl:sm (m4 configuration macro)
checking for MCA component btl:sm compile mode... dso
checking if user requested CMA build... no
checking --with-knem value... simple ok (unspecified)
checking knem_io.h usability... no
checking knem_io.h presence... no
checking for knem_io.h... no
configure: error: KNEM support requested but not found.  Aborting
```

This is on master.  Same thing happens on v1.8.

**Comment by jsquyres** [comment]
@loveshack I am unable to replicate the error you described w.r.t. `--with-knem` not causing configure to abort if knem support is not found (see prior comment on this PR).

Can you describe exactly what is happening?

**Comment by loveshack** [comment]
Jeff Squyres notifications@github.com writes:

> @loveshack I am unable to replicate the error you described w.r.t. `--with-knem` not causing configure to abort if knem support is not found (see prior comment on this PR).
> 
> Can you describe exactly what is happening?

Not immediately.  I'll try to reproduce it tomorrow.

**Comment by jsquyres** [comment]
Great, many thanks.

**Comment by loveshack** [comment]
It turns out what I saw was probably a basic autoconf issue, along with
local configuration that's incorrect, apologies.

I was using an rpm spec file with a configure fragment

  %if %{with knem}
    --with-knem=%{?kneminst} \
  %endif

and kneminst undefined, so effectively "--with-knem=".  That's not
equivalent to "--with-knem"; --help does say "--with-knem(=DIR)", even
if it's possibly surprising.  You'd think someone could get that sort of
thing right after ~20 years :-/.

**Comment by rhc54** [comment]
Thanks Dave! I'll revert the change from master as it had some undesirable side-effects, and close out this PR.

**Pull request closed without merging**
