### PR TITLE
OSHMEM/UCX: implements atomic support

### PR DESCRIPTION
**Pull request by alex-mikheev**
@miked-mellanox 
ucx atomic component has a real code now.
fixes bug in spml ucx arr_procs
removes redundant parameter checks from atomic components.
(cherry picked from commit open-mpi/ompi@f627608e4215f2fdef8a3561fbe0242e2ca14f55)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1251/ for details.

**Comment by jsquyres** [comment]
Sorry, we are already feature complete for v2.0.0.  Deferring to v2.1.

**Comment by mike-dubman** [comment]
:+1:

**Comment by igor-ivanov** [comment]
@hppritcha is it ready to be merged?

**Comment by hppritcha** [comment]
This PR will be merged in to v2.x branch once we have branched off 2.0.x for 2.0 release.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2057/ for details.

**Comment by jladd-mlnx** [comment]
@hppritcha Since this is a bug fix, we would very much like to have this included into 2.0.1. 
bot:milestone:v2.0.1
bot:label:bug

**Comment by hppritcha** [comment]
This doesn't look like a bug fix.  I think this should go in to 2.1.

**Comment by jsquyres** [comment]
@jladd-mlnx Is there a bug fix in this PR that can be separated out into a v2.0.1 PR?

**Comment by jsquyres** [comment]
@alex-mikheev @jladd-mlnx This has merge conflicts.  Can someone rebase?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2176/ for details.

**Comment by hppritcha** [comment]
@jsquyres I think this is ready to go and it looks like some other oshmem prs depend on this one first.

**Pull request merged**
