### PR TITLE
coll/tuned: remove unused prototypes from coll_tuned.h

### PR DESCRIPTION
**Pull request by ggouaillardet**
(cherry picked from commit open-mpi/ompi@de8de65b073541ac2017c3aca3443bf48be2b6d2)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/801/ for details.

**Comment by ggouaillardet** [comment]
:bot:assign: @bosilca 
:bot:milestone:v2.0.0
:bot:label:code-cleanup-low-priority

**Comment by bosilca** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Pull request merged**
