### PR TITLE
Topic/v1.10/coll fixes

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1842/ for details.

**Comment by ggouaillardet** [comment]
:bot:assign: @bosilca 
:bot:label:bug
:bot:milestone:v1.10.4

**Comment by bosilca** [comment]
👍

**Comment by jsquyres** [comment]
@jladd-mlnx @artpol84 Looks like Mellanox Jenkins timed out on the thread tests.  But I see that the `--bind-to none` fix was applied there.  Are the thread tests relevant to run on the v1.10 branch?

**Comment by artpol84** [comment]
Yes for the yalla I think.
I noticed that some tests are really slow progressing and the runtime was
close to timeout value. I can increase it for now. With to check the reason
of the slowness when I'll have the time.

понедельник, 11 июля 2016 г. пользователь Jeff Squyres написал:

> @jladd-mlnx https://github.com/jladd-mlnx @artpol84
> https://github.com/artpol84 Looks like Mellanox Jenkins timed out on
> the thread tests. But I see that the --bind-to none fix was applied
> there. Are the thread tests relevant to run on the v1.10 branch?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/open-mpi/ompi-release/pull/1262#issuecomment-231713474,
> or mute the thread
> https://github.com/notifications/unsubscribe/AHL5PmZiP72a7drQ9MDWmrW0LhR65zGNks5qUi7kgaJpZM4JJIeS
> .

## 

---

Best regards, Artem Polyakov
(Mobile mail)

**Comment by artpol84** [comment]
Indeed those are high latencies. Maybe related to non-bounded run:

12:16:11 Size (bytes)    Time (us)
12:16:31 0   9906.442500
12:16:50 16      9628.991000
12:17:10 32      9732.075000
12:17:30 48      10289.908500
12:17:51 64      10521.495500
12:18:13 80      10696.196000
12:18:33 96      10311.793000
12:18:54 112     10442.492000
12:19:15 128     10665.487000
12:19:35 144     9607.496000
12:19:54 160     9481.857500
12:20:14 176     10232.132000
12:20:36 192     10754.497500
12:20:56 208     10296.493500
12:21:15 224     9524.908000
12:21:35 240     10106.571500
12:21:57 256     10715.749500
12:22:18 320     10668.747000
12:22:40 384     10953.499000
12:23:02 448     10758.986500
12:23:23 512     10828.990000
12:23:44 576     10571.493500
12:24:06 640     10701.493000
12:24:26 704     10335.995500
12:24:45 768     9506.994000
12:25:07 832     10707.497000
12:25:28 896     10694.498000
12:25:50 960     10679.993000

I'll check ASAP

**Comment by artpol84** [comment]
Bot:retest

**Comment by jsquyres** [comment]
@artpol84 The thread tests might not be relevant for the v1.10 branch.  Only in master / v2.x did we do all the correctness and performance improvements for THREAD_MULTIPLE.

**Comment by jsquyres** [comment]
bot:assign: @bosilca 
bot:label:bug
bot:milestone:v1.10.4

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1843/ for details.

**Comment by artpol84** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1884/ for details.

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1887/ for details.

**Comment by artpol84** [comment]
bot:retest

**Comment by artpol84** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1889/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1890/ for details.

**Comment by bosilca** [comment]
👍

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1974/ for details.

**Pull request merged**
