### PR TITLE
btl/vader: clean up progress of waiting endpoints

### PR DESCRIPTION
**Pull request by hjelmn**
master commits
open-mpi/ompi@69e70776aa909845d4a55ba2ad336227c4253ad2
open-mpi/ompi@108f55a9630f2ee079000f65790c67af7cded3b8

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

### CODE REVIEW

**Comment by hjelmn** [comment]
Need to wait on confirmation from @gonnetp. See issue open-mpi/ompi#594

**Comment by mellanox-github** [comment]
- Coverity found 1465 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_283/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_283/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_283/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/283/
Test PASSed.

**Comment by jsquyres** [comment]
@gonnetp Can you confirm that this fixes the issue for you?  Thanks!  (and also open-mpi/ompi#594)

**Comment by rhc54** [comment]
Conditionally approved pending confirmation

**Comment by gonnetp** [comment]
Trying to get this to run from master, but `mpirun` says

```
[pedro@laika examples]$ mpirun -np 2 xterm -e gdb -ex run --args ./test_mindt_mpi -r 10000 -t 1 -f SedovBlast/sedov.hdf5 -m 0.02 -w 5000 -d 5e-5 -g "2 1 1"
mpirun: symbol lookup error: /usr/lib/openmpi/mca_oob_ud.so: undefined symbol: opal_common_verbs_fork_test
```

Looks like an unrelated issue, not sure if I've configured anything wrong. Running on a repository reset to this commit produces the same output.

**Comment by rhc54** [comment]
For now, just add "-mca oob ^ud" to your cmd line - we'll have to look at the issue.

**Comment by gonnetp** [comment]
Just downloaded openmpi-1.8.6rc1, and it seems to be working fine. Guessing that the change made it into there?

**Comment by gonnetp** [comment]
I can now also confirm that it works as well with 1.9.0a1 (current master) with the suggested `-mca oob ^ud` on the `mpirun` command line.

**Comment by rhc54** [comment]
@gonnetp Yes, the change is in there. Thanks for confirming it!

**Comment by gonnetp** [comment]
@rhc54 @hjelmn Thanks to you guys for fixing and pushing this so quickly!

**Pull request merged**
