### PR TITLE
v1.10: Do not return MPI_ERR_PENDING from collectives.

### PR DESCRIPTION
**Pull request by abouteiller**
open-mpi/ompi@c98e97a

### CODE REVIEW

**Comment by abouteiller** [comment]
bot:milestone:v1.10.0
bot:label:bug

**Comment by abouteiller** [comment]
bot:milestone:v1.10.3

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1425/ for details.

**Comment by ggouaillardet** [comment]
@abouteiller you also need open-mpi/ompi@fbed6df4a34b06ae4c8b2f1d3d42c950d904494e
(minor typo)
i guess this should also land into v2.x

**Comment by abouteiller** [comment]
@ggouaillardet thanks for spotting this one. It will indeed be needed in v2.x. 

However, it is actually not needed for v1.10

**Comment by rhc54** [comment]
@abouteiller @ggouaillardet Do we agree then that this can be closed as unneeded in 1.10?

**Comment by rhc54** [comment]
Or should I interpret the above that this particular change is required, but the one suggested by @ggouaillardet is not required in addition to this one?

**Comment by rhc54** [comment]
@abouteiller @ggouaillardet Hey guys - could you please answer my above questions? I'd like to get this either committed or closed so we can begin rolling out 1.10.3.

Thanks

**Comment by ggouaillardet** [comment]
waiting feedback frI'm @abouteiller about my review of #1014 ,
:bot:label:pushed-back

for the record

@abouteiller i do not fully understand the logic here.

with this code, i can see two cases that might not produce the desired output.

```
statuses[0].MPI_ERROR == MPI_ERR_PENDING
statuses[1].MPI_ERROR == MPI_SUCCESS
```

returns `MPI_SUCCESS`

```
statuses[0].MPI_ERROR == MPI_SUCCESS
statuses[1].MPI_ERROR == MPI_ERR_PENDING
```

returns `MPI_ERR_PENDING`

in these two cases, should the function returns an error code different than `MPI_SUCCESS` and `MPI_ERR_PENDING`

as a side note, is `MPI_Irecv` / `MPI_Isend` optimal here ?

for example, `MPI_Irecv` / `MPI_Send` could be a bit faster.

**Comment by abouteiller** [comment]
@rhc54 " this particular change is required, but the one suggested by @ggouaillardet is not required in addition to this one?"

This is correct. In v1.10, the supplementary patch proposed by @ggouaillardet for v2.x is not needed.

**Comment by rhc54** [comment]
@abouteiller Thanks!

**Pull request merged**
