### PR TITLE
v1.10 - Add in-finalize indicator, fca fall back to prev barrier if in-finalize

### PR DESCRIPTION
**Pull request by mike-dubman**
https://github.com/open-mpi/ompi/pull/972

### CODE REVIEW

**Comment by mike-dubman** [comment]
:bot:milestone:v1.10.1
:bot:assign: @jsquyres 
:bot:label:enhancement

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/791/ for details.

**Comment by mike-dubman** [comment]
:bot:label:bug

**Comment by jsquyres** [comment]
Same (minor) comment as #636.

**Comment by jsquyres** [comment]
My question (from #636) was answered enough for the context of v1.10 -- we don't need to care about MPI-3.1 issues with INITIALIZED/FINALIZED over here on v1.10.  So: :+1:

**Pull request merged**
