### PR TITLE
mtl/ofi: Merge some changes from master.

### PR DESCRIPTION
**Pull request by yburette**

### CODE REVIEW

**Comment by jsquyres** [comment]
Something didn't go right (I don't have time to investigate at the moment):

```
make[2]: Entering directory `/home/jsquyres/git/ompi-crossover/ompi/mca/mtl/ofi'
make[2]: *** No rule to make target `/opal/mca/common/libfabric/lib@OPAL_LIB_PREFIX@mca_common_libfabric.la', needed by `mca_mtl_ofi.la'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```

**Comment by yburette** [comment]
I removed the common libfabric commit until I figure out what was missing...

**Comment by hppritcha** [comment]
I'm installing libfabric on the IU jenkins master node so we can catch problems like this with the disable-dlopen check.

**Comment by jsquyres** [comment]
@yburette Perhaps it isn't worth it for the libfabric common commit on the v1.10 branch (I know I said the opposite, yesterday).  But a) since it's going to involve at least some level of porting, and b) the v1.10 series isn't expected to have a hugely long life, perhaps the Way Forward is 2.x -- and that's where we can have the libfabric common stuff.

Howzat sound?

**Comment by yburette** [comment]
@jsquyres Fine by me. I've already removed the common libfabric commit from this PR.
I was able to build and test it with the PSM provider.

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
