### PR TITLE
Restore the usock oob component

### PR DESCRIPTION
**Pull request by rhc54**
Revert part of open-mpi/ompi@c1bbbb5e2f54476f80a42a6390c9532de3e5a66e to restore the usock component, thus fixing show_help aggregation.

Fixes #1467

Restore debugger attach operations

Fixes #1225

(cherry picked from commit open-mpi/ompi@c146c4969b8a3cb19fcca52d2638e26d83d682ae)

### CODE REVIEW

**Comment by rhc54** [comment]
@jsquyres @hppritcha 

This PR looks a lot worse than it really is - almost all the changes are just the restored usock component files. Up to you how important it is to fix debugger and show_help issues.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1455/ for details.

**Comment by hppritcha** [comment]
Will merging this back in have any implications for PMIx 1.2 in the  OMPI 2.1 release?  If not, I"m okay with this approach to fixing the show help aggregation and debugger launch issues.

**Comment by rhc54** [comment]
None - I made sure to retain the notification hooks

**Comment by hppritcha** [comment]
Works on systems I have time to test on. :+1:

**Comment by hppritcha** [comment]
what was the new commit about?

**Comment by rhc54** [comment]
There was a missing fix for debugger attach that was pointed out this morning, and Coverity had complained about a minor typo that I fixed as well. Both are minor changes.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1467/ for details.

**Comment by hppritcha** [comment]
@jsquyres I think this is good to go.

**Comment by jsquyres** [comment]
Fixes the show_help aggregation problem for me, too.  Yay!  :+1:

**Pull request merged**
