### PR TITLE
v2.x osc/pt2pt fixes

### PR DESCRIPTION
**Pull request by hjelmn**
:bot:label:bug
:bot:milestone:v2.0.0
:bot:assign: @regrant 

@ggouaillardet Please take a look as well. I added one of the patches you committed to master but made some modifications. Let me know if there are any regressions.

### CODE REVIEW

**Comment by hjelmn** [comment]
@regrant Should mention that these bugs and some ugni btl bugs were found by the threaded rma benchmarks.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1313/ for details.

**Comment by regrant** [comment]
@hjelmn Glad to hear that the RMA-MT benchmarks are doing their job. I can take a look at this, but it won't be until early next week that I'll have time to really go over this thoroughly. I'm assuming that since this is not a blocker it can wait for a couple of days?

**Comment by hjelmn** [comment]
@regrant Would be nice to get this into the 2.0.0 final release. If you can't get to it by then that is fine. We will at least have osc/pt2pt working multithreaded in 2.0.1.

**Comment by ggouaillardet** [comment]
@hjelmn i found a quite big issue with this commit on master
issues can be evidenced with the `ibm/onesided` test suite (`c_get` is crashing for example)
(do not forget to disable the `rdma` osc component if your interconnect is rdma capable)

here is a snapshot of my patch

``` patch
diff --git a/ompi/mca/osc/pt2pt/osc_pt2pt_comm.c b/ompi/mca/osc/pt2pt/osc_pt2pt_comm.c
index a1dcfd7..5a6572f 100644
--- a/ompi/mca/osc/pt2pt/osc_pt2pt_comm.c
+++ b/ompi/mca/osc/pt2pt/osc_pt2pt_comm.c
@@ -34,14 +34,8 @@
 #include <stdio.h>

 /* progress an OSC request */
-static int ompi_osc_pt2pt_comm_complete (ompi_request_t *request)
+static inline int ompi_osc_pt2pt_comm_complete_internal (ompi_osc_pt2pt_module_t *module, ompi_request_t *request)
 {
-    ompi_osc_pt2pt_module_t *module =
-        (ompi_osc_pt2pt_module_t*) request->req_complete_cb_data;
-
-    OPAL_OUTPUT_VERBOSE((10, ompi_osc_base_framework.framework_output,
-                         "isend_completion_cb called"));
-
     mark_outgoing_completion(module);

     /* put this request on the garbage colletion list */
@@ -50,6 +44,17 @@ static int ompi_osc_pt2pt_comm_complete (ompi_request_t *request)
     return OMPI_SUCCESS;
 }

+static int ompi_osc_pt2pt_comm_complete (ompi_request_t *request)
+{
+    ompi_osc_pt2pt_module_t *module =
+        (ompi_osc_pt2pt_module_t*) request->req_complete_cb_data;
+
+    OPAL_OUTPUT_VERBOSE((10, ompi_osc_base_framework.framework_output,
+                         "ompi_osc_pt2pt_comm_complete called"));
+
+    return ompi_osc_pt2pt_comm_complete_internal(module, request);
+}
+
 static int ompi_osc_pt2pt_req_comm_complete (ompi_request_t *request)
 {
     ompi_osc_pt2pt_request_t *pt2pt_request = (ompi_osc_pt2pt_request_t *) request->req_complete_cb_data;
@@ -62,7 +67,8 @@ static int ompi_osc_pt2pt_req_comm_complete (ompi_request_t *request)
         ompi_osc_pt2pt_request_complete (pt2pt_request, request->req_status.MPI_ERROR);
     }

-    return ompi_osc_pt2pt_comm_complete (request);
+    
+    return ompi_osc_pt2pt_comm_complete_internal (pt2pt_request->module, request);
 }

 static inline int ompi_osc_pt2pt_data_isend (ompi_osc_pt2pt_module_t *module, const void *buf,
```

**Comment by ggouaillardet** [comment]
@hjelmn, i also had to restore the previous `OSC_PT2PT_FRAG_TAG` and `OSC_PT2PT_FRAG_MASK` values, otherwise `c_post_start` hangs

i noticed `osc_pt2pt` headers uses an `uint16_t` tag (and everything is well aligned with that), and that could explain why tags must fit into 16 bits

``` patch
diff --git a/ompi/mca/osc/pt2pt/osc_pt2pt.h b/ompi/mca/osc/pt2pt/osc_pt2pt.h
index 409011d..68ca022 100644
--- a/ompi/mca/osc/pt2pt/osc_pt2pt.h
+++ b/ompi/mca/osc/pt2pt/osc_pt2pt.h
@@ -631,8 +631,8 @@ static inline void osc_pt2pt_add_pending (ompi_osc_pt2pt_pending_t *pending)
                             opal_list_append (&mca_osc_pt2pt_component.pending_operations, &pending->super));
 }

-#define OSC_PT2PT_FRAG_TAG   0x80000
-#define OSC_PT2PT_FRAG_MASK  0x7ffff
+#define OSC_PT2PT_FRAG_TAG   0x10000
+#define OSC_PT2PT_FRAG_MASK  0x0ffff

 /**
  * get_tag:
```

now investigating `c_reqops` hang ...

**Comment by hjelmn** [comment]
Both these bugs look like I missed something in the commit. Weird that it didn't show up in MTT... Will fix on master and update this PR.

**Comment by ggouaillardet** [comment]
it did show up, see http://mtt.open-mpi.org/index.php?do_redir=2267

about the last hang, it occurs after task 1 MPI_Rget_accumulate to task 0.
it seems the request is never sent from task 1 to task 0

**Comment by hjelmn** [comment]
Huh, weird. I checked yesterday and didn't see any failures. In fact it was really clean for once.. Not sure why. Will fix today and see what tonight's MTTs show.

**Comment by hppritcha** [comment]
no go on this stuff till we figure out what's going on with master
https://github.com/open-mpi/ompi/issues/1342#issuecomment-180163538
yep again, this is getting annoying.
osc is really not that important to 99% of mpi apps.

**Comment by ggouaillardet** [comment]
master has been fixed by open-mpi/ompi#1341, and this PR should be updated to cherry pick the latest fixes

**Comment by hppritcha** [comment]
i'd like to see at least one night of MTT for open-mpi/ompi#1341.  If MTT runs are clean, then this PR can be merged, per @ggouaillardet recommendation,  after including open-mpi/ompi#1341 with this PR.

**Comment by hjelmn** [comment]
Agreed. Was hoping the PR would make it into the tarball but just missed it.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1314/ for details.

**Comment by hppritcha** [comment]
Looks like the overnite MTT results for ivy cluster (which seemed to be showing most of the problems with all these osc bug fixes) ran clean overnite.
@jsquyres I think this is good to go.

**Pull request merged**
