### PR TITLE
hwloc 1.9.x updates for v1.8

### PR DESCRIPTION
**Pull request by jsquyres**
From open-mpi/ompi#498:

Bring over all hwloc commits after the hwloc v1.9.1 tag (including the fix for the "Lhwloc1" duplicate symbol issue).  

@rhc54 Can you review / test?

Here's all the commits from master:
- open-mpi/ompi@0c502d9 hwloc README-ompi.txt: update for what we
- open-mpi/ompi@29ccbfd hwloc pci: fix bridge depth
- open-mpi/ompi@1905f35 hwloc: bitmap: fix a corner case in hwloc_bitmap_isincluded() with i
- open-mpi/ompi@5c9157c hwloc: core: only update root->complete sets if insert succeeds
- open-mpi/ompi@dec0109 hwloc: groups: add complete sets when inserting distance/pci groups
- open-mpi/ompi@d6e415c hwloc: AIX: Fix PU os_index
- open-mpi/ompi@80140bb hwloc: distances: when we fail to insert an intermediate group, don'
- open-mpi/ompi@29c9915 hwloc: pci: fix SR-IOV VF vendor/device names
- open-mpi/ompi@da164be hwloc: error: point to the FAQ when displaying the big OS error mess
- open-mpi/ompi@3f96e7a hwloc: synthetic: Misc levels are not allowed in the synthetic descr
- open-mpi/ompi@050bb35 hwloc: x86: use Group instead of Misc for unknown x2apic levels
- open-mpi/ompi@379c7b0 hwloc: x86: use ulong for cache sizes, uint won't be enough in the n
- open-mpi/ompi@6caf9ed hwloc: hpux: improve hwloc_hpux_find_ldom() looking for NUMA node
- open-mpi/ompi@fff1bb5 hwloc: core: reorder children in merge_useless_child() as well
- open-mpi/ompi@77978a8 hwloc: core: fix the merging of identical objects in presence of Mis
- open-mpi/ompi@5427b33 hwloc: debug: fix an overzealous assertion about the parent cpuset v
- open-mpi/ompi@9b59d53 hwloc: cpuid-x86: Fix duplicate asm labels in case of heavy inlining
- open-mpi/ompi@86a536c hwloc: x86 and OSF: Don't forget to set NUMA node nodeset
- open-mpi/ompi@db5bc72 hwloc: API: clearly state that os_index isn't unique while logical_i
- open-mpi/ompi@a636790 hwloc: opal/mca/hwloc/hwloc191/hwloc/NEWS update
- open-mpi/ompi@7c96aec hwloc: errors: improve the advice to send hwloc-gather-topology file
- open-mpi/ompi@d5f8c89 hwloc: configure: fix the check for X11/Xutil.h
- open-mpi/ompi@50b035d hwloc: misc.h: Fix hwloc_strncasecmp() with some icc
- open-mpi/ompi@6764413 hwloc: misc.h: Fix hwloc_strncasecmp() build under strict flags on B
- open-mpi/ompi@6b0011f hwloc: v1.9.1 released, doing 1.9.2rc1 now

### CODE REVIEW

**Comment by jsquyres** [comment]
Add @petergottesman, since he reported the issue.

**Comment by jsquyres** [comment]
And @bgoglin, because he's such a great guy (and keeps me honest!) :-)

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/177/

**Build Log**
_last 50 lines_

```
GitHub pull request #218 of commit 8a95301ecce89c8d47ab35436f3fa1290779ff46 automatically merged.
Setting status of 8a95301ecce89c8d47ab35436f3fa1290779ff46 to PENDING with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/177/ and message: Merged build started.
[EnvInject] - Loading node environment variables.
Building on master in workspace /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository https://github.com/open-mpi/ompi-release
 > /usr/bin/git init /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace # timeout=60
Fetching upstream changes from https://github.com/open-mpi/ompi-release
 > /usr/bin/git --version # timeout=60
using .gitcredentials to set credentials
 > /usr/bin/git config --local credential.helper store --file=/tmp/git2774857291012553203.credentials # timeout=60
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/open-mpi/ompi-release +refs/heads/*:refs/remotes/origin/* # timeout=60
 > /usr/bin/git config --local --remove-section credential # timeout=60
ERROR: Error cloning remote repo 'origin'
ERROR: Error cloning remote repo 'origin'
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: Cannot determine sha1 of the commit. The status cannot be reported
    at org.jenkinsci.plugins.github.util.BuildDataHelper.getCommitSHA1(BuildDataHelper.java:31)
    at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:102)
    at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1776)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 8a95301ecce89c8d47ab35436f3fa1290779ff46 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/177/ and message: Merged build finished.
```

Test FAILed.

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1473 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_178/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_178/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_178/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/178/

**Build Log**
_last 50 lines_

```
[...truncated 142479 lines...]
++ echo /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
+ for OMPI_HOME in '$(echo $ompi_home_list)'
+ echo 'check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_env_list
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
+ echo 'check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_envar_file_prefix
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/178/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/178/tap-master-files/cov_stat.tap].
not ok - coverity detected 1473 failures in all_178 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_178/output/errors/index.html
not ok - coverity detected 23 failures in oshmem_178 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_178/output/errors/index.html
ok - coverity found no issues for mxm_178
not ok - coverity detected 7 failures in fca_178 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_178/output/errors/index.html
ok - coverity found no issues for hcoll_178

TAP Reports Processing: FINISH
coverity_for_all    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_178/output/errors/index.html
coverity_for_oshmem http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_178/output/errors/index.html
coverity_for_fca    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_178/output/errors/index.html
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: Cannot determine sha1 of the commit. The status cannot be reported
    at org.jenkinsci.plugins.github.util.BuildDataHelper.getCommitSHA1(BuildDataHelper.java:31)
    at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:102)
    at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1776)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 8a95301ecce89c8d47ab35436f3fa1290779ff46 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/178/ and message: Merged build finished.
```

Test FAILed.

**Comment by jsquyres** [comment]
@mikedubman These look like false Jenkins failures...?

**Comment by jsquyres** [comment]
@miked-mellanox These look like false Jenkins failures.  Is something wrong with Jenkins?

**Comment by mike-dubman** [comment]
yep, github API changed but jenkins plugin uses outdated version. will reload shorty.

**Comment by jsquyres** [comment]
Sweet -- thank you!

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1473 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_180/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_180/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_180/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/180/

**Build Log**
_last 50 lines_

```
[...truncated 146746 lines...]
++ echo /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
+ for OMPI_HOME in '$(echo $ompi_home_list)'
+ echo 'check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_env_list
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
+ echo 'check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_envar_file_prefix
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/180/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/180/tap-master-files/cov_stat.tap].
not ok - coverity detected 1473 failures in all_180 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_180/output/errors/index.html
not ok - coverity detected 23 failures in oshmem_180 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_180/output/errors/index.html
ok - coverity found no issues for mxm_180
not ok - coverity detected 7 failures in fca_180 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_180/output/errors/index.html
ok - coverity found no issues for hcoll_180

TAP Reports Processing: FINISH
coverity_for_all    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_180/output/errors/index.html
coverity_for_oshmem http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_180/output/errors/index.html
coverity_for_fca    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_180/output/errors/index.html
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: Cannot determine sha1 of the commit. The status cannot be reported
    at org.jenkinsci.plugins.github.util.BuildDataHelper.getCommitSHA1(BuildDataHelper.java:31)
    at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:102)
    at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1776)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 8a95301ecce89c8d47ab35436f3fa1290779ff46 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/180/ and message: Merged build finished.
```

Test FAILed.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/181/

**Build Log**
_last 50 lines_

```
[...truncated 19661 lines...]
  CCLD     orte-ps
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/tools/orte-ps'
Making all in tools/orte-restart
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/tools/orte-restart'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/tools/orte-restart'
Making all in tools/orted
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/tools/orted'
  CC       orted.o
  CCLD     orted
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/tools/orted'
Making all in tools/orterun
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/tools/orterun'
  CC       main.o
  CC       orterun.o
  CCLD     orterun
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/tools/orterun'
Making all in tools/wrappers
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/tools/wrappers'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/tools/wrappers'
Making all in tools/orte-top
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/orte/tools/orte-top'
  CC       orte-top.o
  CCLD     orte-top
Build was aborted
Aborted by miked
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Did not find any matching files.
Anchor chain: could not read file with links: /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/jenkins_sidelinks.txt (No such file or directory)
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: Cannot determine sha1 of the commit. The status cannot be reported
    at org.jenkinsci.plugins.github.util.BuildDataHelper.getCommitSHA1(BuildDataHelper.java:31)
    at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:102)
    at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1776)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 8a95301ecce89c8d47ab35436f3fa1290779ff46 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/181/ and message: Merged build finished.
```

Test FAILed.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1473 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_182/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_182/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_182/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/182/

**Build Log**
_last 50 lines_

```
[...truncated 142489 lines...]
++ echo /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
+ for OMPI_HOME in '$(echo $ompi_home_list)'
+ echo 'check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_env_list
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
+ echo 'check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_envar_file_prefix
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/182/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/182/tap-master-files/cov_stat.tap].
not ok - coverity detected 1473 failures in all_182 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_182/output/errors/index.html
not ok - coverity detected 23 failures in oshmem_182 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_182/output/errors/index.html
ok - coverity found no issues for mxm_182
not ok - coverity detected 7 failures in fca_182 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_182/output/errors/index.html
ok - coverity found no issues for hcoll_182

TAP Reports Processing: FINISH
coverity_for_all    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_182/output/errors/index.html
coverity_for_oshmem http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_182/output/errors/index.html
coverity_for_fca    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_182/output/errors/index.html
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: Cannot determine sha1 of the commit. The status cannot be reported
    at org.jenkinsci.plugins.github.util.BuildDataHelper.getCommitSHA1(BuildDataHelper.java:31)
    at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:102)
    at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1776)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 8a95301ecce89c8d47ab35436f3fa1290779ff46 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/182/ and message: Merged build finished.
```

Test FAILed.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1473 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_183/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_183/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_183/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/183/

**Build Log**
_last 50 lines_

```
[...truncated 142479 lines...]
++ echo /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
+ for OMPI_HOME in '$(echo $ompi_home_list)'
+ echo 'check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
check if mca_base_env_list parameter is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_env_list
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
+ echo 'check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1'
check if mca_base_envar_file_prefix parameter (a.k.a -tune cmd line option) is supported in /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1
++ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/bin/ompi_info --param mca base --level 9
++ grep mca_base_envar_file_prefix
++ wc -l
+ val=0
+ '[' 0 -gt 0 ']'
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/183/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/183/tap-master-files/cov_stat.tap].
not ok - coverity detected 1473 failures in all_183 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_183/output/errors/index.html
not ok - coverity detected 23 failures in oshmem_183 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_183/output/errors/index.html
ok - coverity found no issues for mxm_183
not ok - coverity detected 7 failures in fca_183 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_183/output/errors/index.html
ok - coverity found no issues for hcoll_183

TAP Reports Processing: FINISH
coverity_for_all    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_183/output/errors/index.html
coverity_for_oshmem http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_183/output/errors/index.html
coverity_for_fca    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_183/output/errors/index.html
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: Cannot determine sha1 of the commit. The status cannot be reported
    at org.jenkinsci.plugins.github.util.BuildDataHelper.getCommitSHA1(BuildDataHelper.java:31)
    at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:102)
    at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1776)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of 8a95301ecce89c8d47ab35436f3fa1290779ff46 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/183/ and message: Merged build finished.
```

Test FAILed.

**Comment by jsquyres** [comment]
@rhc54 Ralph: @miked-mellanox and I chatted offlist -- we think that the failed build status here is a Jenkins bug.

**Comment by rhc54** [comment]
@jsquyres hmmm....where are we on this, then? I'm behind a firewall today and can't easily get at the PR to test it, though I can visually review it.

**Comment by rhc54** [comment]
Is there a way I can look at the total change, or do I really have to leaf thru these one click at a time?

**Comment by jsquyres** [comment]
Click on the "Files changed" tag on this page.

**Comment by jsquyres** [comment]
Er... "Files changed 'tab'" (not "tag").

**Comment by rhc54** [comment]
:+1:

**Pull request merged**
