### PR TITLE
PML UCX: fix typo.

### PR DESCRIPTION
**Pull request by yosefe**
https://github.com/open-mpi/ompi/pull/1203

### CODE REVIEW

**Comment by yosefe** [comment]
bot:label:enhancement
bot:milestone:v1.10.3
bot:assign: @hppritcha

**Comment by yosefe** [comment]
@miked-mellanox

**Comment by mike-dubman** [comment]
bot:label:bug
bot:assign: @rhc54 
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1138/ for details.

**Pull request merged**
