### PR TITLE
v2.x: ompi/datatype: Fix args of HINDEXED_BLOCK

### PR DESCRIPTION
**Pull request by kawashima-fj**
PR for v2.0.1

@bosilca please review

This is a coding bug but probably no defect for users.

bot:label:bug
bot:milestone:v2.0.1

(cherry picked from commit open-mpi/ompi@84b110a1f2e1952459aed5dd788261fe2e68a87b)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1765/ for details.

**Comment by bosilca** [comment]
👍

**Comment by jsquyres** [comment]
bot:retest

**Comment by hppritcha** [comment]
travis 'sed' error and mellanox not progressing.  not related to this PR.

**Pull request merged**
