### PR TITLE
If we can't output an entire block, then we need to adjust the number of bytes

### PR DESCRIPTION
**Pull request by rhc54**
...remaining to be output or else we will output duplicate bytes when next we are able to write.

Cherry-pick of ompi-master:
open-mpi/ompi@8c837d3cb34e0d871dde0e13b734f96ce1e52dc3

@jsquyres please review this trivial fix

### CODE REVIEW

**Comment by mellanox-github** [comment]
Merged build triggered.

**Comment by mellanox-github** [comment]
Merged build started.

**Comment by mellanox-github** [comment]
Merged build finished. Test PASSed.

**Comment by mellanox-github** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/15/
Test PASSed.

**Comment by jsquyres** [comment]
Wow; can't believe that buglet has been in there for so long!

**Pull request merged**
