### PR TITLE
mellanox/optimized: set enable_openib_rdmacm_ibaddr=yes in the mellanox/optimized file.

### PR DESCRIPTION
**Pull request by alinask**

### CODE REVIEW

**Comment by alinask** [comment]
bot:milestone:v2.1.0
depends on #1043 

@jladd-mlnx please review.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1531/ for details.

**Comment by jladd-mlnx** [comment]
:+1: 
bot:label:reviewed

**Comment by jladd-mlnx** [comment]
bot:milestone:v2.0.1

**Pull request closed without merging**
