### PR TITLE
v2.0.0: f08: do not BIND(C) to subroutines with LOGICAL parameters

### PR DESCRIPTION
**Pull request by jsquyres**
Thanks Paul Romano (@paulromano) for reporting this issue (see open-mpi/ompi#1323).

(cherry picked from commit open-mpi/ompi@704f14f)

@jsquyres already reviewed; @ggouaillardet please sanity check

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1302/ for details.

**Comment by ggouaillardet** [comment]
shall we add open-mpi/ompi#1337 (once you reviewed it) and merge all at once ?
if I understand correctly, it will not break abi (no symbol is removed) and f08 apps will be fixed when recompiled
(well, newly compiled f08 apps will not run with an older f08 openmpI lib, not sure this kind of compatibility matters though)

**Comment by jsquyres** [comment]
@ggouaillardet I'm ok doing open-mpi/ompi#1337 separately (which I'm [finally] reviewing right now...).  Either way, this LOGICAL fix and the default attribute handling functions fix will be separate commits, so I don't see a big deal in making them separate PRs.

**Comment by ggouaillardet** [comment]
:+1:

**Pull request merged**
