### PR TITLE
Fix some inconsistencies in pmix_status_t vs int declarations. These …

### PR DESCRIPTION
**Pull request by rhc54**
…have been fixed upstream, but we don't want to bring all that down.

Thanks to Paul Hargrove for pointing it out

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1593/ for details.

**Comment by hppritcha** [comment]
@jsquyres  ready to go for me

**Comment by PHHargrove** [comment]
I see this is already RM-Approved.
However, I have found this _does not_ fix all of the errors (just the ones I saw). :-1: 
There are still 19 more mismatched decl/defn pairs in the pmix code that I had not reached in my previous testing:

```
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/internal_functions.c", line 117.5: 1506-343 (S) Redeclaration of opal_pmix_pmix112_pmix_bfrop_get_data_type differs from previous declaration on line 469 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/internal.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/pack.c", line 63.5: 1506-343 (S) Redeclaration of opal_pmix_pmix112_pmix_bfrop_pack_buffer differs from previous declaration on line 237 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/internal.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/util/pmix_environ.c", line 178.5: 1506-343 (S) Redeclaration of opal_pmix_pmix112_pmix_unsetenv differs from previous declaration on line 132 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/util/pmix_environ.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/util/hash.c", line 65.5: 1506-343 (S) Redeclaration of opal_pmix_pmix112_pmix_hash_store differs from previous declaration on line 27 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/util/hash.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/util/hash.c", line 150.5: 1506-343 (S) Redeclaration of opal_pmix_pmix112_pmix_hash_remove_data differs from previous declaration on line 42 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/util/hash.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client.c", line 224.5: 1506-343 (S) Redeclaration of OPAL_PMIX_PMIX112_PMIx_Init differs from previous declaration on line 86 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/include/pmix.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client.c", line 467.5: 1506-343 (S) Redeclaration of OPAL_PMIX_PMIX112_PMIx_Abort differs from previous declaration on line 117 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/include/pmix.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_fence.c", line 68.5: 1506-343 (S) Redeclaration of OPAL_PMIX_PMIX112_PMIx_Fence differs from previous declaration on line 170 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/include/pmix.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_fence.c", line 110.5: 1506-343 (S) Redeclaration of OPAL_PMIX_PMIX112_PMIx_Fence_nb differs from previous declaration on line 175 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/include/pmix.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_fence.c", line 168.22: 1506-343 (S) Redeclaration of unpack_return differs from previous declaration on line 59 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_fence.c".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_fence.c", line 188.22: 1506-343 (S) Redeclaration of pack_fence differs from previous declaration on line 60 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_fence.c".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_get.c", line 70.5: 1506-343 (S) Redeclaration of OPAL_PMIX_PMIX112_PMIx_Get differs from previous declaration on line 196 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/include/pmix.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_pub.c", line 169.5: 1506-343 (S) Redeclaration of OPAL_PMIX_PMIX112_PMIx_Lookup differs from previous declaration on line 269 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/include/pmix.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_pub.c", line 295.5: 1506-343 (S) Redeclaration of OPAL_PMIX_PMIX112_PMIx_Unpublish differs from previous declaration on line 290 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/include/pmix.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_spawn.c", line 60.5: 1506-343 (S) Redeclaration of OPAL_PMIX_PMIX112_PMIx_Spawn differs from previous declaration on line 331 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/include/pmix.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_spawn.c", line 215.13: 1506-343 (W) Redeclaration of spawn_cbfunc differs from previous declaration on line 58 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_spawn.c".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_connect.c", line 61.5: 1506-343 (S) Redeclaration of OPAL_PMIX_PMIX112_PMIx_Connect differs from previous declaration on line 363 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/include/pmix.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_connect.c", line 172.5: 1506-343 (S) Redeclaration of OPAL_PMIX_PMIX112_PMIx_Disconnect differs from previous declaration on line 376 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/include/pmix.h".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/server/pmix_server_listener.c", line 71.15: 1506-343 (S) Redeclaration of opal_pmix_pmix112_pmix_start_listening differs from previous declaration on line 182 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/server/pmix_server_ops.h".

```

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1596/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@rhc54 Looks like failures like this:

```
In file included from src/buffer_ops/internal_functions.c:30:0:
./src/buffer_ops/internal.h:106:2: error: #error Unsupported pmix_status_t size!
 #error Unsupported pmix_status_t size!
  ^
```

**Comment by rhc54** [comment]
yeah, i know - working on it

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by rhc54** [comment]
@PHHargrove Please see if this solves the xlc problem.

**Comment by PHHargrove** [comment]
@rhc54 
Test queued, but I will be offline for the next 3 hours.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1602/ for details.

**Comment by PHHargrove** [comment]
@rhc54
I still see two fatal errors due  to inconsistent return types, and one warning for an inconsistent  argument type. 

There are also many warnings related in int\* vs enum{}\* mismatchs in assignment and initialization. 

Bellow are the fatal errors. 
I will send the warnings when I am at a real screen / keyboard. 

-Paul [Sent from my phone] 

```
"/gpfs-biou/phh1/OMPI/openmpi-2.0.0rc2-linux-ppc64-xlc-13.1/openmpi-2
.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/open_close.c", line
 42.5: 1506-343 (S) Redeclaration of opal_pmix_pmix112_pmix_pmix_bfro
p_initial_size differs from previous declaration on line 197 of "/gpf
s-biou/phh1/OMPI/openmpi-2.0.0rc2-linux-ppc64-xlc-13.1/openmpi-2.0.0r
c2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/internal.h".
"/gpfs-biou/phh1/OMPI/openmpi-2.0.0rc2-linux-ppc64-xlc-13.1/openmpi-2
.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/open_close.c", line
 43.5: 1506-343 (S) Redeclaration of opal_pmix_pmix112_pmix_pmix_bfro
p_threshold_size differs from previous declaration on line 198 of "/g
pfs-biou/phh1/OMPI/openmpi-2.0.0rc2-linux-ppc64-xlc-13.1/openmpi-2.0.
0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/internal.h".
```

**Comment by PHHargrove** [comment]
@rhc54 

Below are the warnings.
They probably don't matter for 2.0.0.

-Paul

```
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 516.86: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 521.86: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 526.88: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 531.86: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 536.85: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 541.89: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 546.86: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 551.87: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 556.87: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 561.87: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 566.86: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 571.87: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 576.88: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 581.88: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 586.88: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 591.86: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 596.86: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 601.84: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 606.87: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 611.84: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 978.80: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 1020.86: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 1024.84: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/buffer_ops/unpack.c", line 1028.84: 1506-280 (W) Function argument assignment between types "int*" and "enum {...}*" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_fence.c", line 94.45: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},void*)" and "void(*)(int,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_get.c", line 96.67: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},struct {...}*,void*)" and "void(*)(int,struct {...}*,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_pub.c", line 86.60: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},void*)" and "void(*)(int,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_pub.c", line 201.46: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},struct {...}*,unsigned long,void*)" and "void(*)(int,struct {...}*,unsigned long,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_pub.c", line 310.68: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},void*)" and "void(*)(int,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_spawn.c", line 88.75: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},char*,void*)" and "void(*)(int,char*,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_spawn.c", line 215.13: 1506-343 (W) Redeclaration of spawn_cbfunc differs from previous declaration on line 58 of "[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_spawn.c".
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_connect.c", line 86.75: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},void*)" and "void(*)(int,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/client/pmix_client_connect.c", line 193.78: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},void*)" and "void(*)(int,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/server/pmix_server.c", line 2087.64: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},void*)" and "void(*)(int,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/server/pmix_server.c", line 2103.76: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},void*)" and "void(*)(int,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/server/pmix_server.c", line 2128.73: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},void*)" and "void(*)(int,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/server/pmix_server.c", line 2145.66: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},void*)" and "void(*)(int,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/server/pmix_server.c", line 2165.68: 1506-280 (W) Function argument assignment between types "void(*)(enum {...},void*)" and "void(*)(int,void*)" is not allowed.
"[...]/openmpi-2.0.0rc2/opal/mca/pmix/pmix112/pmix/src/sec/pmix_native.c", line 39.5: 1506-196 (W) Initialization between types "enum {...}(*)(struct pmix_peer_t*,char*)" and "int(*)(struct pmix_peer_t*,char*)" is not allowed.
```

**Comment by rhc54** [comment]
IBM is taking over from here as I don't have an xlc compiler, and I'm just shooting in the dark.

**Comment by PHHargrove** [comment]
@gpaulsen 
I am using

```
IBM XL C/C++ for Linux, V13.1
Version: 13.01.0000.0000

IBM XL Fortran for Linux, V15.1
Version: 15.01.0000.0001
```

on a big-endian Power7 system (Power 750 Express Server, IIRC).
I have configured with 

```
--enable-debug --disable-oshmem-fortran CC=xlc CXX=xlC FC=xlf --with-hwloc=FOO
```

where FOO is is the path to a pre-built (w/ gcc) install of hwloc (because this xlc SEGVs building hwloc).

-Paul

**Comment by PHHargrove** [comment]
Also seen now with:

```
IBM XL C/C++ for Blue Gene, V12.1
Version: 12.01.0000.0013
```

So this particular pickiness may be universal across xlc releases.

**Comment by jjhursey** [comment]
bot:assign: @jjhursey
I have a box with Power7 and XL v12.1 to test - setting up the build now.

**Comment by jjhursey** [comment]
I just issued a PR to @rhc54  branch to clean up the rest of these issues.
  https://github.com/rhc54/ompi-release/pull/4

This is building fine now on a power7 machine with:

``` shell
shell$ xlc -qversion
IBM XL C/C++ for Linux, V12.1 (5765-J03, 5725-C73)
Version: 12.01.0000.0000
```

**Comment by PHHargrove** [comment]
With Josh's commits applied over Ralph's, I can build with both of the XL compilers I mentioned in my previous two comments.  

However, for completeness I will plan to retest after Ralph has updated this PR.

**Comment by rhc54** [comment]
@PHHargrove Should all be complete now - please let me know how it looks to you

**Comment by PHHargrove** [comment]
@rhc54 
Will test as soon as I get back to my desk. 
Did you take care of the size variables you commented on in Josh's PR? 
-Paul [Sent from my phone]

**Comment by rhc54** [comment]
Yes - all complete

**Comment by jjhursey** [comment]
👍 Build on my machine built fine with this branch. I would like to see Paul confirm as well on his system.

I want to check to see if we need this on v1.10 and master branches as well (starting builds now).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1614/ for details.

**Comment by rhc54** [comment]
Not in v1.10 as PMIx isn't over there - it does need to come to master, but we should do that upstream in PMIx 1.1.4 and then bring it down. Can you provide a PR for 1.1.4?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1615/ for details.

**Comment by jjhursey** [comment]
Yep, I'll work on the PR for PMIx 1.1.4 and try to get that out this afternoon.

**Comment by PHHargrove** [comment]
:+1: Works for me w/ both XLC 12.1 and 13.1

**Comment by jjhursey** [comment]
I opened a PR for the PMIx 1.1.4 release branch:
- https://github.com/pmix/releases/pull/11

**Pull request merged**
