### PR TITLE
v2.x: topo/basic: remove stale (empty) .windows file

### PR DESCRIPTION
**Pull request by jsquyres**
(cherry picked from commit open-mpi/ompi@24ca887bd84b8995c0739ec26450b7c9628723d2)

@hppritcha please review

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
I'm not sure why the thread tests were run at Mellanox, but this PR doesn't change any code at all, so I'm not sure why it would fail Jenkins.

**Comment by hppritcha** [comment]
I don't understand the mlnx jenkins failure either.
bot:retest

**Comment by hppritcha** [comment]
I"m going ahead and merging.  It looks like one of the jenkins multithreaded bw tests is hanging or timing out.
@miked-mellanox @jladd-mlnx  could one of you check what's up with the multi-threaded test?

**Comment by mike-dubman** [comment]
tried manually and it works fine
is there any way to make OMPI dump stacktrace by some signal?

**Comment by hppritcha** [comment]
good to go in.  I think the mlnx jenkins problem needs investigating, but this PR can't be causing that issue.

**Pull request merged**
