### PR TITLE
v1.10: fortran typos

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:milestone:v1.10.0

**Comment by ggouaillardet** [comment]
:bot:assign: @jsquyres 
:bot:label: bug

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
@hppritcha Can you check your Jenkins config?  I don't see LANL checks for the v1.10 branch on ompi-release.  Thanks!

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
