### PR TITLE
Topic/v2.x/mpi osc prototypes fixes

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:milestone:v2.0.0
:bot:assign: @hjelmn 
:bot:label:bug

**Comment by hppritcha** [comment]
@tkordenbrock could you double check that portals4 osc comp still works for you with the PR?

**Comment by tkordenbrock** [comment]
@hppritcha  This PR works for me.  :+1:

**Comment by ggouaillardet** [comment]
@hppritcha @hjelmn @rhc54 @jsquyres 
shall i PR for the v1.10 series ?
from the user point of view, some mpi prototypes were fixed (e.g. add the missing const keyword)
so since v1.10.0 has already been released, i am not sure we want to fix this

**Comment by rhc54** [comment]
@ggouaillardet We talked about this at today's telecon, and agreed that we should indeed backport this to v1.10. Could you please do so?

**Comment by ggouaillardet** [comment]
ok, will do tomorrow

**Pull request merged**
