### PR TITLE
coll-portals4: add scatter and iscatter implementations that use Portals4 triggered operations

### PR DESCRIPTION
**Pull request by tkordenbrock**
This commit adds implementations of scatter and iscatter using
Portals4 triggered operations.  Currently, the only algorithm
is linear.

(cherry picked from open-mpi/ompi@4721b70)

### CODE REVIEW

**Comment by tkordenbrock** [comment]
:bot:label:enhancement
:bot:label:blocker
:bot:milestone:v2.0.0
:bot:assign: @regrant

**Comment by hppritcha** [comment]
what's the corresponding commit in master?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1141/ for details.

**Comment by tkordenbrock** [comment]
Added master commit to original PR message.

**Comment by regrant** [comment]
:+1:

**Pull request merged**
