### PR TITLE
oshmem: Fix issue #367

### PR DESCRIPTION
**Pull request by igor-ivanov**
Issue relates at least following configuration as spml=yoda btl=vader,self.
See for additional details open-mpi/ompi#367

bot:milestone:v1.8.5
bot:label:bug
bot:assign:@bertwesarg

### CODE REVIEW

**Comment by jsquyres** [comment]
@bertwesarg  Please make your membership to the Open MPI organization public, and then the bot will let you interact with it / be assigned tickets, etc.  I.e., visit https://github.com/orgs/open-mpi/people, find yourself, and set your membership to "public".

**Comment by jsquyres** [comment]
@igor-ivanov Please do the same (sorry, should have included that in the prior comment)

**Comment by bertwesarg** [comment]
Done. Sorry, I lost your mail about this.

**Comment by mellanox-github** [comment]
- Coverity found 1765 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_160/output/errors/index.html
- Coverity found 40 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_160/output/errors/index.html
- Coverity found 1 errors for mxm: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/mxm_160/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_160/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/160/
Test PASSed.

**Comment by jsquyres** [comment]
bot:milestone:v1.8.5
bot:label:bug
bot:assign:@bertwesarg

**Comment by bertwesarg** [comment]
Sorry for being not up-to-date, but what is my responsibility as the assignee for thus PR to 1.8? Back in the SVN days, there exists the reviewer for a CMR, which than assigned it to the RM or GK (I can't remember the order anymore) so that it can be merged into the release branch. Though I can't review this PR, as I'm totally unfamiliar with the code. I'm also neither the RM nor the GK. So what does it mean to be the assignee than?

Oh, and will this also be fixed in master? I reported that I have the same failure with dev-791-g03c2adf back than, but did not follow the master commits since than and neither tried master in recent weeks!

**Comment by jsquyres** [comment]
@ggouaillardet Any idea why the bot is insisting that v1.8.5 is not a valid milestone?

@bertwesarg When you have reviewed this and you're happy, then assign the "reviewed" tag.  That way, the RM knows that this PR is ok to apply to v1.8.

**Comment by rhc54** [comment]
I empathize with Bert - why would this be assigned to him??

**Comment by rhc54** [comment]
Also, where is the tag for the corresponding master commit?

**Comment by jsquyres** [comment]
(SIDENOTE: Sorry -- I shouldn't be commenting here, because my attention is divided because I'm trying to pay attention at the Forum meeting!  So I'll try to get this right and then go away until the Forum meeting is done :-) )

@igor-ivanov Are you assigning to @bertwesarg because he reported the bug?  If so, he can verify that it is fixed, but you still need to get a code review.  Also, you need to include the corresponding master commit hash here in the PR (i.e., this has to go to master first, and v1.8 second).

**Comment by igor-ivanov** [comment]
This issue can be reproduced on open-mpi/ompi@03c2adf as @bertwesarg noticed but current master   does not report this issue. There is no separate commit in master related this bug. I believe that it was fixed as part of 'BTL 3.0 interface' related commits from @hjelmn (probably open-mpi/ompi@16ae7d9). It is a reason I pushed PR directly to v1.8.

**Comment by ggouaillardet** [comment]
@jsquyres 
You can check the content of milestones.json on the bot web server.
Then you can check the webhook logs for this event (both request and reply)
Note that in order to set a milestone, the bot must use the milestone index, and not the milestone value

**Comment by bertwesarg** [comment]
@jsquyres @rhc54 It doesn't look like there was a consensus regarding my assignee state. Can we please reach one. Thanks.

**Comment by jsquyres** [comment]
@igor-ivanov @miked-mellanox Are you assigning to @bertwesarg because he reported the bug? If so, he can verify that it is fixed, but you still need to get a code review.

**Comment by mike-dubman** [comment]
i think it is a historic assign.
reviewed, looks good.

**Comment by jsquyres** [comment]
I.e., you mean: :+1: :-)

**Comment by mike-dubman** [comment]
@igor-ivanov - so, can we consider it closed by referenced commit?

**Comment by igor-ivanov** [comment]
yep

**Pull request merged**
