### PR TITLE
Port the changes from #782

### PR DESCRIPTION
**Pull request by rhc54**
Bring over commit  open-mpi/ompi@5e5adebf8e7151c8d603ae0b0ee62af0cca45eda, modifying it slightly as the code in the 1.10 series is a little different.

Pick up the rest of the changes from the original PR that only pertain to the v1.10 series

Thanks to @jsharpe for the PR

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1126/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1127/ for details.

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
