### PR TITLE
Topic/v2.x/pmpi vs mpi

### PR DESCRIPTION
**Pull request by ggouaillardet**
- remove the `--disable-mpi-profile` option
- invoke `PMPI_*` C functions from Fortran bindings and oshmem

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @jsquyres 
:bot:milestone:v2.0.0
:bot:label:rfc
:bot:label:enhancement

**Comment by ggouaillardet** [comment]
@jsquyres note this PR has been rebased from #667 which has not yet been merged

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/846/ for details.

**Comment by hppritcha** [comment]
@ggouaillardet  please rebase

**Comment by jsquyres** [comment]
@ggouaillardet Can you provide a good title and description so that we know what this PR is?  It's not clear what it's supposed to be, because it's got commits for MPI_Aint, mpi_f08 stuff, ...etc.

**Comment by jsquyres** [comment]
@ggouaillardet Oh, I see -- I missed your comment about this being rebased from #667.  But can you still fill in a title / description, anyway?  Thanks!

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/874/ for details.

**Comment by ggouaillardet** [comment]
@jsquyres i rebased (again) and added a description

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/938/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/971/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1007/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1049/ for details.

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1084/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1103/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1099/ for details.

**Comment by jsquyres** [comment]
@ggouaillardet A quick look through here indicates to me that I think you made all the changes I requested.  Thanks!

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha I think this is good to go.

**Pull request merged**
