### PR TITLE
MPI_Ibarrier.3in: add missing man page

### PR DESCRIPTION
**Pull request by jsquyres**
Add MPI_Ibarrier.3in to reference MPI_Barrier.3, and update MPI_Barrier.3in to include bindings for MPI_Ibarrier.  Slightly update the text to be inclusive of the non-blocking case.

Fixes open-mpi/ompi#242.

(cherry picked from commit 952be15d7f539ec1be3199eddee7baadb8c8cf91)

### CODE REVIEW

**Comment by jsquyres** [comment]
@rhc54 Trivial man page addition -- can you review?

**Comment by rhc54** [comment]
@jsquyres Hey Jeff, I'm a little confused here. I see the manpage addition, but I also see changes to the MPI_Barrier manpage that adds stuff about IBarrier. Are these duplicate entries?

**Comment by jsquyres** [comment]
Nope, not duplicates.

The new MPI_Ibarrier.3in page is a 1-liner that refers to the MPI_Barrier.3 man page. That's how all our non-blocking collective pages are (i.e., the Ifoo.3in page refers to the Foo.3 page, and the Foo.3 page contains the details of both MPI_Foo and MPI_Ifoo).

**Comment by rhc54** [comment]
Looks good - thanks!

**Pull request merged**
