### PR TITLE
NEWS: updates for v2.0.0

### PR DESCRIPTION
**Pull request by jsquyres**
Split v2.0.0 NEWS bullets into 4 sections:
1. Major new features
2. Changes in behavior compared to prior versions
3. Removed legacy support
4. Bug fixes / minor enhancements

Also add new bullets since the last major NEWS update on Apr 28.

Signed-off-by: Jeff Squyres jsquyres@cisco.com

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1766/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1767/ for details.

**Comment by jsquyres** [comment]
@Di0gen @jladd-mlnx Looks like a local failure in the Mellanox Jenkins:

```
libtoolize:   error: copying '/hpc/local/share/libtool/build-aux/ltmain.sh' to 'confdb/' failed
```

This PR is solely updating a NEWS (text) file, and has nothing to do with the build system.  You might want to check your Jenkins server.

**Comment by jladd-mlnx** [comment]
@jsquyres Worked for me when I tried.
bot:retest

**Comment by jsquyres** [comment]
@jladd-mlnx Go figure.  Must be anomalous solar flare activity today.  Bits will be flipping all over the world.  Not much we can do about it.  😉

**Comment by hppritcha** [comment]
:+1:

**Comment by jsquyres** [comment]
This NEWS pre-emptively mentions the PSM/PSM2 fix, even though it's not in yet.  So we just need to be sure to get that PSM/PSM2 fix over here before doing the actual release.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1768/ for details.

**Comment by jsquyres** [comment]
@hppritcha @rhc54 In anticipation of the PSM fix being included in v1.10.3, I removed the following bullet:
- Disable backtrace support by default in the PSM/PSM2 libraries to prevent unintentional conflicting behavior.

We didn't really get to talk about this this morning, however.  If v2.0.0 goes out before v1.10.3, then this bullet should be included in the v2.0.0 NEWS.  But if it's the other way around, then it should be included in the v1.10.3 NEWS.

I didn't check to see if there were other bullets in this same kind of predicament...  I think we had been assuming that v1.10.3 was going to come out first.  But if v2.0.0 comes out first, we might need to shuffle some NEWS bullets around...?

It can happen after this PR, though.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1771/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request merged**
