### PR TITLE
Fix typo that caused compile error

### PR DESCRIPTION
**Pull request by rolfv**
(cherry picked from commit open-mpi/ompi@fc83400123ed4317e8dd59435ad144a855302c47)

@jsquyres , can you review?

### CODE REVIEW

**Comment by rolfv** [comment]
bot:label:bug
bot:milestone:v2.0.0
bot:assign: @jsquyres

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
This is so trivial that I'll just go ahead and RM approve it.  When jenkins finishes, we'll merge.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/799/ for details.

**Pull request merged**
