### PR TITLE
oshmem: Fix issue #367

### PR DESCRIPTION
**Pull request by igor-ivanov**
This issue came with commit 3443c1d.
It relates at least following configuration as spml=yoda btl=vader,self.
See for additional details https://github.com/open-mpi/ompi/issues/367

bot:milestone:v1.8.5
bot:label:bug
bot:assign:@hjelmn

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/159/
Test PASSed.

**Comment by mike-dubman** [comment]
@bertwesarg - could you please check if it solves issue for you?
Thanks

**Comment by bertwesarg** [comment]
Sorry, I'm currently unable to run autogen.pl on this branch. I get:

=== Found oshmem / sshmem framework
--- Found oshmem / sshmem / mmap component
    Found configure.m4 file
--- Found oshmem / sshmem / sysv component
    Found configure.m4 file
--- Found oshmem / sshmem / verbs component
    Found configure.m4 file
Missing orte/mca/common/Makefile.am at ./autogen.pl line 92.

The head says:
1. Checking tool versions
   
   Searching for autoconf
    Found autoconf version 2.69; checking version...
      Found version component 2 -- need 2
      Found version component 69 -- need 65
    ==> ACCEPTED
   Searching for libtoolize
    Found libtoolize version 2.4.2; checking version...
      Found version component 2 -- need 2
      Found version component 4 -- need 2
    ==> ACCEPTED
   Searching for automake
    Found automake version 1.15; checking version...
      Found version component 1 -- need 1
      Found version component 15 -- need 12
    ==> ACCEPTED

I'm trying the 1.8 branch and master now.

**Comment by bertwesarg** [comment]
Btw, a 'git clean -Xf' did not helped.

**Comment by bertwesarg** [comment]
v1.8 does have the same problem. master works. Here is the autogen.pl output for the oshmem/sshmem framework:

=== Found oshmem / sshmem framework
--- Found oshmem / sshmem / mmap component
    Found configure.m4 file
--- Found oshmem / sshmem / sysv component
    Found configure.m4 file
--- Found oshmem / sshmem / verbs component
    Found configure.m4 file

**Comment by bertwesarg** [comment]
Hmm, 'git clean -Xf' did not removed the 'orte/mca/common' directory, which is present only in master. I can now run autogen.pl. Sorry for the noise.

**Comment by bertwesarg** [comment]
If this is the expected output, than I can confirm, that this fixes my reported issue:

[ii] ybtl->btl_type=0 ybtl->btl->btl_prepare_src=0x7f9314207edb ybtl->btl->btl_flags=10
[ii] ybtl->btl_type=0 ybtl->btl->btl_prepare_src=0x7f9314207edb ybtl->btl->btl_flags=10
[ii] ybtl->btl_type=0 ybtl->btl->btl_prepare_src=0x7f0661357edb ybtl->btl->btl_flags=10
[ii] ybtl->btl_type=0 ybtl->btl->btl_prepare_src=0x7f0661357edb ybtl->btl->btl_flags=10
[ii] ybtl->btl_type=3 ybtl->btl->btl_prepare_src=0x7f0660a6a2e6 ybtl->btl->btl_flags=8
[ii] ybtl->btl_type=3 ybtl->btl->btl_prepare_src=0x7f93141562e6 ybtl->btl->btl_flags=8
Hello from PE 1 of 2
Hello from PE 2 of 2

**Pull request closed without merging**
