### PR TITLE
pmix: do not include automatically generated include/private/autogen/…

### PR DESCRIPTION
**Pull request by ggouaillardet**
…config.h into dist tarball

Thanks Siegmar Gross for the initial report of this issue

(back-ported from commit open-mpi/ompi@73daf58ee5f230b58291beb0563a50dc21b0b69e)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1271/ for details.

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1270/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1272/ for details.

**Comment by jsquyres** [comment]
@ggouaillardet Can you please set the labels and milestones on PRs?  Thanks.

Also, this PR should probably be filed with pmix upstream, as well (if you haven't already done so).

**Comment by ggouaillardet** [comment]
:bot:assign: @rhc54 

upstream pmix has already been updated

**Comment by rhc54** [comment]
@ggouaillardet @jsquyres This PR is not correct. I had to make a change when we upstreamed it as it broke the upstream tarball creation. I would suggest that we pull the change from there.

:-1:

**Comment by ggouaillardet** [comment]
ok, I will update ompi master first, and then update this pr with both commits

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1273/ for details.

**Comment by ggouaillardet** [comment]
:bot:nolabel:pushed-back

@rhc54 done, i back-ported the changes from upstream pmix

**Comment by jsquyres** [comment]
@rhc54 Look ok?

**Comment by hppritcha** [comment]
travis red mark is attributed to github being down.

**Comment by rhc54** [comment]
:+1:

**Comment by hppritcha** [comment]
I think this travis error can be ignored.  Looks like something didn't install right on the container that prevents usnic provider from building during the libfabric build.
@jsquyres modulo the travis build failure, I think this is ready to go.

**Pull request merged**
