### PR TITLE
Sync fortran from master

### PR DESCRIPTION
**Pull request by ggouaillardet**
Fixes open-mpi/ompi#1240

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @jsquyres 
:bot:milestone:v2.0.0
:bot:label:blocker
:bot:label:bug

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1177/ for details.

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1179/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1183/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1188/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1202/ for details.

**Comment by jsquyres** [comment]
Super minor, but it looks like open-mpi/ompi@fec973efd isn't in here.  That's a larger commit for configure test compatibility fixes, but it includes 1 line of Fortran configury.  I'm thinking that that should be a separate 2.x PR.

**Comment by jsquyres** [comment]
BTW, everything else looks good on this PR :+1:

**Comment by hppritcha** [comment]
so open-mpi/ompi@fec973e will go in to a separate PR.  merging this one.

**Pull request merged**
