### PR TITLE
README: restrict OS X and Oracle Studio compiler versions

### PR DESCRIPTION
**Pull request by jsquyres**
Signed-off-by: Jeff Squyres jsquyres@cisco.com

(cherry picked from commit open-mpi/ompi@a0a18491014ad9b2faaa881db29d8e8611e09fad)

@hppritcha Please review / merge.

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@hppritcha LANL bots are off the rails again -- looks like a local jenkins failure?  😦

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2110/ for details.

**Comment by hppritcha** [comment]
something seems to be going south with UH again.
since this is just documentation, ignoring.
:+1:

**Pull request merged**
