### PR TITLE
v2.x: mpi/c, mpi/fortran: Fix `MPI_IN_PLACE`-related bugs

### PR DESCRIPTION
**Pull request by kawashima-fj**
PR for v2.0.0

@jsquyres please review

bot:label:bug
bot:milestone:v2.0.0

Not critical; can be delayed to v2.0.1

### CODE REVIEW

**Comment by jsquyres** [comment]
I wouldn't mind deferring these to v2.0.1.  @bosilca Are you ok with deferring these?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1520/ for details.

**Comment by bosilca** [comment]
Up to you I don't have a strong opinion (despite the fact that this is an almost trivial 10 lines patch).

**Comment by jsquyres** [comment]
@hppritcha Got an opinion?  It's not big, it's a bug fix, and the risk is relatively low.  But it's also fairly obscure functionality.

**Comment by hppritcha** [comment]
let's let this wait to 2.0.1

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1913/ for details.

**Comment by hppritcha** [comment]
@bosilca could you give thumbs up if this is okay?

**Comment by bosilca** [comment]
I only had the opportunity for a quick scan, but things look ok.  👍

**Comment by hppritcha** [comment]
@jsquyres I think this can go in today.

**Pull request merged**
