### PR TITLE
Merge pull request #383 into branch v1.10

### PR DESCRIPTION
**Pull request by Zhiming-Wang**
https://github.com/open-mpi/ompi/issues/383

### CODE REVIEW

**Comment by jsquyres** [comment]
@Zhiming-Wang Please don't forget to assign a milestone and tag someone for the review of a PR into a release branch: https://github.com/open-mpi/ompi/wiki/SubmittingPullRequests and https://github.com/open-mpi/ompi/wiki/OmpiReleaseBotCommands

**Comment by jsquyres** [comment]
Looks like the actual PR that this came from was open-mpi/ompi#387 (383 was the bug, 387 was the PR that fixed it).

@nysal Can you review?

**Comment by Zhiming-Wang** [comment]
@nysal  Before, I didn't know "git cherry-pick" command, I did it using manually copies. It must be reviewed.
@jsquyres Thanks your comments, I learn a lot about GitHub from the docs.

**Comment by nysal** [comment]
@Zhiming-Wang I prefer to actually cherry pick the original commits. The commit message also should have a reference to the SHA1 of the commits in master branch. See the following commit message for an example (note the "cherry picked from....") :  https://github.com/open-mpi/ompi-release/commit/fa0c892803c35475814f3fc6638bdbac2c716c2f
If you need any help with cherry picking the commit, let me know (Read this - http://stackoverflow.com/questions/5120038/is-it-possible-to-cherry-pick-a-commit-from-another-git-repository). After you cherry pick the 2 commits, perform an interactive rebase and edit the two commit messages to add the "cherry picked from..." messages. Once done you can "git push -f" to your github topic branch & it should reflect in this PR.

**Comment by Zhiming-Wang** [comment]
@nysal  Done.  The "git cherry-pick" is powerful.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/713/ for details.

**Comment by nysal** [comment]
@Zhiming-Wang Thanks, just one minor comment. In the "cherry picked from..." commit message, the hash should point to the one in ompi master branch. So please change to the following format "open-mpi/ompi@<hash>". Replace <hash> with the actual SHA1 in the master branch. Everything else looks good to me. See here for details - https://github.com/open-mpi/ompi/wiki/SubmittingPullRequests

**Comment by nysal** [comment]
oops, had some trouble with github markdown. the format is "open-mpi/ompi@<hash>". Replace <hash> with actual SHA1

**Comment by Zhiming-Wang** [comment]
Done.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/714/ for details.

**Comment by nysal** [comment]
:+1:

**Pull request merged**
