### PR TITLE
Update NEWS release date

### PR DESCRIPTION
**Pull request by hppritcha**
@jsquyres 

Conflicts:
    NEWS

### CODE REVIEW

**Comment by jsquyres** [comment]
👍

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1808/ for details.

**Pull request merged**
