### PR TITLE
oshmem: do not include pml/ob1 headers

### PR DESCRIPTION
**Pull request by ggouaillardet**
this is an abstraction violation and that can cause linker failure

(back ported from commit open-mpi/ompi@8f2d3aeb65e6de672ec210ff41f70832f5135ac2)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @miked-mellanox 
:bot:milestone:v1.10.2
:bot:label:bug

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/998/ for details.

**Comment by jsquyres** [comment]
Per http://www.open-mpi.org/community/lists/devel/2015/11/18354.php, this is not a critical bug fix.

It could be shifted to v1.10.3.

@rhc54 What do you want to do with this one?

**Comment by mike-dubman** [comment]
@rhc54 - #758 can replace #752  for v1.10.2

**Comment by ggouaillardet** [comment]
@jsquyres without this pr, oshmem build fails, at least with fujitsu cross compilers.
That is not really critical, but since this is quite trivial stuff, it would be nice to have it in v1.10.2
@miked-mellanox #758 is not a replacement for this pr, right ?

**Comment by mike-dubman** [comment]
ohh... - commented in the wrong PR :) thanks my comment is unrelated to this one.

**Comment by rhc54** [comment]
This looks like near-zero risk to me, so let's bring it along.

**Comment by rhc54** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1030/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1036/ for details.

**Pull request merged**
