### PR TITLE
Bring ompio in the v2.x branch up to date with the fixes applied to master

### PR DESCRIPTION
**Pull request by edgargabriel**
bot:milestone:v2.0.0
bot:assign:@hppritcha

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/861/ for details.

**Comment by hppritcha** [comment]
This seems to work okay, but when I run the test filetest (mpi2basic_tests) on a lustre file system (I used --with-lustre=blah blah) I get this error:

malloc debug: error opening file testfile1.out

is this okay?

Otherwise this PR looks good to me.

:+1:

**Comment by edgargabriel** [comment]
hm, it shouldn't happen. I can check whether my account on the cray in Stuttgart is working again and see whether I find something. Give me a day or two.

**Comment by edgargabriel** [comment]
I ran it in Stuttgart, and I can confirm that everything is ok. The error message comes from the lustre fs component, and in those tests opening the file is supposed to fail (the ufs component just doesn't output a message, which maybe it should). So feel free to merge.

**Comment by hppritcha** [comment]
@jsquyres ready to merge

**Pull request merged**
