### PR TITLE
Topic/v1.10/nag configury

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1744/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1745/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1746/ for details.

**Comment by ggouaillardet** [comment]
@PHHargrove could you please give this PR a try ?

**Comment by PHHargrove** [comment]
Works for me :+1:

**Comment by rhc54** [comment]
Pushing this off, but may absorb it if we are delayed much longer

**Pull request merged**
