### PR TITLE
orte/mca/rmaps: Improve orte_rmaps_dist_device help message

### PR DESCRIPTION
**Pull request by igor-ivanov**
See: https://github.com/open-mpi/ompi/issues/953

:bot:assign: @jsquyres 
:bot:label:bug
:bot:milestone:v1.10.1

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/832/ for details.

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
Unless something goes wrong, this is probably too late for 1.10.1.

**Comment by rhc54** [comment]
Since 1.10.1 is badly delayed, we might as well absorb this one.

**Pull request merged**
