### PR TITLE
Topic/v2.x/dpm sentinel

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1232/ for details.

**Comment by ggouaillardet** [comment]
:bot:assign: @jsquyres 
:bot:milestone:v2.0.0
:bot:label:bug

**Comment by jsquyres** [comment]
@rhc54 Can you have a look?

**Comment by rhc54** [comment]
:+1:

**Comment by jsquyres** [comment]
Approved on 19 Jan 2016 weekly call.

**Pull request merged**
