### PR TITLE
pml/cm: fix heterogeneous mode

### PR DESCRIPTION
**Pull request by ggouaillardet**
v1.10 and master do things differently, so this is a one-off patch

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @jithinjosepkl 
:bot:milestone:v1.10.0
:bot:label:bug

**Comment by ggouaillardet** [comment]
:bot:milestone:v1.10.0

**Comment by ggouaillardet** [comment]
:bot:assign:@bosilca

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/374/

**Comment by bosilca** [comment]
:+1:

**Comment by jithinjosepkl** [comment]
:+1:

**Pull request merged**
