### PR TITLE
Topic/monitoring

### PR DESCRIPTION
**Pull request by bosilca**
open-mpi/ompi#724

bot:milestone:v2.x
bot:label:enhancement
bot:assign: @jsquyres

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/955/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/960/ for details.

**Comment by jsquyres** [comment]
@bosilca The "v2.x" milestone was missing from the ompi-release repo.  I just created it and added it to this PR.

**Comment by jsquyres** [comment]
@bosilca Can you fix the Coverity errors that showed up after you added the PML monitoring to master?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/973/ for details.

**Comment by ggouaillardet** [comment]
@bosilca can you cherry-pick open-mpi/ompi@c415ecf39e91fe87705cbd4f18265ba91fe6a30c to this PR ?

**Comment by ggouaillardet** [comment]
@bosilca and that one too ... open-mpi/ompi@d6ff25b9a2ccfc0a0e5d59c1a8bc23e57745483f

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/997/ for details.

**Comment by jsquyres** [comment]
@bosilca In addition to the commit @ggouaillardet mentions, I notice that a test hung.  Is that related to this PR?

**Comment by bosilca** [comment]
Tests hang all the time. Which one in particular you are referring to?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1001/ for details.

**Comment by jsquyres** [comment]
@bosilca It was hello_c.  :-)  Someone re-ran the test, though, and it apparently didn't hang this time...?  Maybe it's a race condition...?  And perhaps not even in this monitoring part of the code...?

**Comment by bosilca** [comment]
The monitoring PML is not enabled if you don't have special flags, which I guess we don't in the tests. Thus, I am not sure the hang is related to this PR.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1092/ for details.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2064/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2065/ for details.

**Comment by jsquyres** [comment]
@bosilca Is this still good to go with all the BTL / BML / PML updates since Nov 2015?

**Comment by jsquyres** [comment]
The `ompi-release` repo is now closed; all release branches have been moved to the `ompi` repo (https://github.com/open-mpi/ompi).  Please re-open this PR on the corresponding branch on the `ompi` repo.

**Comment by jsquyres** [comment]
This repo is now closed.

**Pull request closed without merging**
