### PR TITLE
Some cleanup of warnings when building optimized

### PR DESCRIPTION
**Pull request by rhc54**
@jsquyres please review

### CODE REVIEW

**Comment by rhc54** [comment]
The following items have not been changed - they involve variables that are only used in assert and OPAL_OUTPUT, both of which are empty in optimized builds:

``` c
opal_convertor.c: In function 'opal_convertor_prepare_for_recv':
opal_convertor.c:490:18: warning: variable 'bdt_mask' set but not used [-Wunused-but-set-variable]
         uint32_t bdt_mask;                                              \
                  ^
opal_convertor.c:564:5: note: in expansion of macro 'OPAL_CONVERTOR_PREPARE'
     OPAL_CONVERTOR_PREPARE( convertor, datatype, count, pUserBuf );
     ^
opal_convertor.c: In function 'opal_convertor_prepare_for_send':
opal_convertor.c:490:18: warning: variable 'bdt_mask' set but not used [-Wunused-but-set-variable]
         uint32_t bdt_mask;                                              \
                  ^
opal_convertor.c:603:5: note: in expansion of macro 'OPAL_CONVERTOR_PREPARE'
     OPAL_CONVERTOR_PREPARE( convertor, datatype, count, pUserBuf );
```

``` c
topology.c: In function 'hwloc__check_children':
topology.c:3080:9: warning: variable 'prev_firstchild' set but not used [-Wunused-but-set-variable]
     int prev_firstchild = -1; /* -1 works fine with first comparisons below */
         ^
topology-xml.c: In function 'opal_hwloc191_hwloc_export_obj_userdata_base64':
topology-xml.c:1408:7: warning: variable 'ret' set but not used [-Wunused-but-set-variable]
   int ret;
```

``` c
runtime/opal_progress.c: In function 'opal_progress_event_users_increment':
runtime/opal_progress.c:218:13: warning: variable 'val' set but not used [-Wunused-but-set-variable]
     int32_t val;
             ^
runtime/opal_progress.c: In function 'opal_progress_event_users_decrement':
runtime/opal_progress.c:236:13: warning: variable 'val' set but not used [-Wunused-but-set-variable]
     int32_t val;
             ^
```

**Comment by mellanox-github** [comment]
- Coverity found 1468 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_255/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_255/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_255/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/255/
Test PASSed.

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
FWIW, I found a few warnings in the OMPI layer like this, and I did end up surrounding the vars that are unused except in debug builds in `#if OPAL_ENABLE_DEBUG` blocks.

**Pull request merged**
