### PR TITLE
Adding entry points for Allgatherv, iAllgatherv, Reduce, and iReduce.

### PR DESCRIPTION
**Pull request by jladd-mlnx**
This replaces https://github.com/open-mpi/ompi-release/pull/922.

:cherries: -picked from  ompi-mpi/ompi@e398bf6

bot:milestone:v2.0.0
bot:label:enhancement
bot:assign:@hppritcha

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1308/ for details.

**Comment by hppritcha** [comment]
@jsquyres this was discussed at the last devel meeting.  At this point, these are just placeholder hooks for an upcoming HCOLL release (late Q01).  So at this point, merging this in should not result in finding bugs for the 2.0.0.  Given this, I'm okay with taking this PR for 2.0.0 even though its not nominally a bug fix.

**Comment by hppritcha** [comment]
I'm good with the code changes.
:+1:

**Comment by jsquyres** [comment]
@hppritcha Ok.

**Pull request merged**
