### PR TITLE
Add UCX support

### PR DESCRIPTION
**Pull request by yosefe**
Fixes open-mpi/ompi#982

### CODE REVIEW

**Comment by hjelmn** [comment]
Don't forget to set the milestone and labels. Also assign a reviewer.

**Comment by yosefe** [comment]
@hjelmn looks like i'm not able to do that (no enough permissions)?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/927/ for details.

**Comment by hjelmn** [comment]
Use the bot commands: https://github.com/open-mpi/ompi/wiki/OmpiReleaseBotCommands

**Comment by yosefe** [comment]
bot:label:enhancement
bot:assign:@bosilca

**Comment by yosefe** [comment]
bot:label:enhancement

**Comment by bosilca** [comment]
From a technical perspective I have nothing more (than open-mpi/ompi#1008) to add. I would appreciate few nights of MTT before moving forward with this.

**Comment by yosefe** [comment]
adding @shamisp

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/940/ for details.

**Comment by hppritcha** [comment]
@yosefe is there a  corresponding sha on master for https://github.com/yosefe/ompi-release/commit/b61bc0e8966a44d13e2bd088a08bfe583821aaf9 ?

**Comment by yosefe** [comment]
@hppritcha i've opened PR for this: https://github.com/open-mpi/ompi/pull/1076

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/942/ for details.

**Comment by hppritcha** [comment]
@yosefe the lanl build bot failure in 1076 is "spurious".  For whatever reason, the mpirun launches on the Univ. Houston server that runs that test periodically hang.  It can be ignored.

Is this pr ready to go?

**Comment by hppritcha** [comment]
Issue open-mpi/ompi#982 should be closed when this PR is merged.

**Comment by yosefe** [comment]
@hppritcha Our MTT which ran IMB-datacheck and mpi_test_suite passed with this PR, so IMHO we can merge it. 
We may find more bugs in UCX library, but this will most likely not require fixes in OpenMPI code.

**Pull request merged**
