### PR TITLE
Move treematch support to v2.x

### PR DESCRIPTION
**Pull request by bosilca**
The PR related to open-mpi/ompi#804

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1093/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ggouaillardet** [comment]
@bosilca can you also include open-mpi/ompi@a5440ade5faee1f36859455c35d35fbced730d43 ?

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1100/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1101/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1102/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by ggouaillardet** [comment]
@bosilca you also need to cherry-pick a piece of open-mpi/ompi@cf6137b530e7478720fbf87da83d6a46c1774dbe

``` patch
diff --git a/ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c b/ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
index 0673e26..436f60f 100644
--- a/ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
+++ b/ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
@@ -4,6 +4,7 @@
  *                         reserved.
  * Copyright (c) 2011-2015 INRIA.  All rights reserved.
  * Copyright (c) 2012-2015 Bordeaux Poytechnic Institute
+ * Copyright (c) 2015      Intel, Inc. All rights reserved
  * $COPYRIGHT$
  *
  * Additional copyrights may follow
@@ -25,7 +26,7 @@

 #include "ompi/mca/pml/pml.h"

-#include "opal/mca/dstore/dstore.h"
+#include "opal/mca/pmix/pmix.h"

 #define ERR_EXIT(ERR)                           \
     do { free(local_pattern);                   \
@@ -176,7 +177,7 @@ int mca_topo_treematch_dist_graph_create(mca_topo_base_module_t* topo_module,
         for(i = 0; i < size ; i++) {
             proc = ompi_group_peer_lookup(comm_old->c_local_group, i);
             pval = &val;
-            OPAL_MODEX_RECV_VALUE(err, OPAL_DSTORE_NODEID, &(proc->super), &pval, OPAL_UINT32);
+            OPAL_MODEX_RECV_VALUE(err, OPAL_PMIX_NODEID, &(proc->super.proc_name), &pval, OPAL_UINT32);
             if( OPAL_SUCCESS != err ) {
                 opal_output(0, "Unable to extract peer %s nodeid from the modex.\n",
                             OMPI_NAME_PRINT(&(proc->super)));
@@ -858,20 +859,20 @@ int mca_topo_treematch_dist_graph_create(mca_topo_base_module_t* topo_module,
 #endif

             OBJ_CONSTRUCT(&kv, opal_value_t);
-            kv.key = strdup(OPAL_DSTORE_CPUSET);
+            kv.key = strdup(OPAL_PMIX_CPUSET);
             kv.type = OPAL_STRING;
             kv.data.string = strdup(set_as_string);

-            (void)opal_dstore.store(opal_dstore_internal, (opal_process_name_t*)ORTE_PROC_MY_NAME, &kv);
+            (void)opal_pmix.store_local((opal_process_name_t*)ORTE_PROC_MY_NAME, &kv);
             OBJ_DESTRUCT(&kv);

             locality = opal_hwloc_base_get_relative_locality(opal_hwloc_topology,
                                                              orte_process_info.cpuset,set_as_string);
             OBJ_CONSTRUCT(&kv, opal_value_t);
-            kv.key = strdup(OPAL_DSTORE_LOCALITY);
+            kv.key = strdup(OPAL_PMIX_LOCALITY);
             kv.type = OPAL_UINT16;
             kv.data.uint16 = locality;
-            (void)opal_dstore.store(opal_dstore_internal, (opal_process_name_t*)ORTE_PROC_MY_NAME, &kv);
+            (void)opal_pmix.store_local((opal_process_name_t*)ORTE_PROC_MY_NAME, &kv);
             OBJ_DESTRUCT(&kv);

             if( OMPI_SUCCESS != (err = ompi_comm_create(comm_old,
```

note the `distgraph_test_4` now fails instead of hanging, see open-mpi/ompi#1183

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1104/ for details.

**Comment by hppritcha** [comment]
@ggouaillardet I do not want separate chunks of commits from other PR's to master, in this case 1 out of two commits from open-mpi/ompi#775, coming in to an unrelated PR on v2.x.

@rhc54 it doesn't look like open-mpi/ompi#775 was ever brought over from master.  Does this need to be brought over?  Or perhaps a combo of 775 and an additional pmix refresh?

**Comment by ggouaillardet** [comment]
@hppritcha open-mpi/ompi@cf6137b530e7478720fbf87da83d6a46c1774dbe has already been back-ported as part of open-mpi/ompi-release@78876d8cad7fecb68dc4527968019c8b0af45d06

at that time, `treematch` had not yet landed into `v2.x`, so there was no way @rhc54 could backport the piece of commit i pointed.

**Comment by hppritcha** [comment]
okay, but treematch was rebased on top of pmix changes open-mpi/ompi@cf6137b5 when it went in so why wasn't this in the code in the PR branch (sans the 83ed476).  

Was the code in this PR cherry-picked from commits off of master or is it being manually added?

I'm seeing this for the ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c in master:

```
git log --oneline -- ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
a5440ade topo/treematch: do not invoke hwloc_topology_{init,load}  * this is not necessary  * this overwrites existing topology, that could be different if hwloc_base_topo_file is used
2622b9d3 Fix minor issues in the treematch topo based on a patch provided by Guillaume.
02624bd0 Fix all treematch issues idenfied by Coverity.
6ab5f68f indentation.
43ef261d topo: do not cast way the const modifier when this is not necessary update the topo framework and mpi c bindings
d97bc291 Remove OPAL_HAVE_HWLOC qualifier and error out if --without-hwloc is given
cf6137b5 Integrate PMIx 1.0 with OMPI.
e239de58 Create a new topology framework using the TreeMatch library developped at Inria Bordeaux. This allows us to take advantage of the remap capability o
```

whereas for what's in this PR:

```
83ed4766 Patch proposed by @ggouaillardet based on open-mpi/ompi@cf6137b.
ba2b076f Manual import of open-mpi/ompi@a5440ade.
bf440ac0 Partial import from open-mpi/ompi@d97bc29.
c0a0f67f Create a new topology framework using the TreeMatch library developped at Inria Bordeaux. This allows us to take advantage of the remap capability of MPI to rearrange the ranks beased on the weights povided by the application.
```

I'm seeing differences between the two files between master and this PR even with the various patch commits.

**Comment by bosilca** [comment]
@hppritcha most of the differences are related to 2 patches in master (open-mpi/ompi@2622b9d3 and (open-mpi/ompi@02624bd0) that were not yet imported in this branch. I just cherry-picked both of them (plus minimal modifications). The remaining difference are from @ggouaillardet open-mpi/ompi@43ef261d which it is not critical in this context.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1147/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1148/ for details.

**Comment by hppritcha** [comment]
Thanks for clarifying.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2058/ for details.

**Comment by jsquyres** [comment]
The `ompi-release` repo is now closed; all release branches have been moved to the `ompi` repo (https://github.com/open-mpi/ompi).  Please re-open this PR on the corresponding branch on the `ompi` repo.

**Comment by jsquyres** [comment]
This repo is now closed.

**Pull request closed without merging**
