### PR TITLE
mtl/ofi: remove threading and progress hints.

### PR DESCRIPTION
**Pull request by yburette**

### CODE REVIEW

**Comment by yburette** [comment]
bot:milestone:v1.10.1
bot:label:bug
bot:assign: @rhc54

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/896/ for details.

**Comment by jsquyres** [comment]
@yburette Just curious -- why did you change these to UNSPEC?

**Comment by rhc54** [comment]
@yburette Could you please explain the change per @jsquyres question?

**Comment by yburette** [comment]
@jsquyres Actually, I don't even know why I had them in the first place!

FI_PROGRESS_AUTO would work but may add some overhead at the provider level. Thinking more about it, since I'm calling fi_cq_read() in progress, I should use FI_PROGRESS_MANUAL instead.

As for threading, I am not sure what to choose here.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/931/ for details.

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
