### PR TITLE
orte/oob: Fix issue #1301

### PR DESCRIPTION
**Pull request by igor-ivanov**
Fix #https://github.com/open-mpi/ompi/issues/1301

:bot:assign: @hjelmn
:bot:label:bug
:bot:milestone:v2.0.0

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1259/ for details.

**Comment by hppritcha** [comment]
bot:retest
something's going on with IU jenkins

**Comment by hjelmn** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1260/ for details.

**Comment by abeltre1** [comment]
> See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1260/ for details.

This link does not work. @jsquyres 

```
ailed to create a completion queue (CQ):

Hostname: mpi2
Requested CQE: 16384
Error:    Cannot allocate memory

Check the CQE attribute.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Open MPI has detected that there are UD-capable Verbs devices on your
system, but none of them were able to be setup properly.  This may
indicate a problem on this system.

You job will continue, but Open MPI will ignore the "ud" oob component
in this run.

Hostname: mpi2
--------------------------------------------------------------------------
ibv_exp_query_device: invalid comp_mask !!! (comp_mask = 0x40 valid_mask = 0x1)
[mpi2][[64601,1],1][btl_openib_component.c:1670:init_one_device] error obtaining device attributes for mlx4_0 errno says Invalid argument
ibv_exp_query_device: invalid comp_mask !!! (comp_mask = 0x40 valid_mask = 0x1)
[mpi1][[64601,1],0][btl_openib_component.c:1670:init_one_device] error obtaining device attributes for mlx4_0 errno says Invalid argument
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   mpi2
  Local device: mlx4_0
--------------------------------------------------------------------------
[1538604609.580548] [mpi2:345  :0]       ud_ep.c:924  MXM  ERROR failed to create recv cq: Cannot allocate memory
[1538604609.581147] [mpi1:375  :0]       ud_ep.c:924  MXM  ERROR failed to create recv cq: Cannot allocate memory
--------------------------------------------------------------------------

```

**Comment by jsquyres** [comment]
That link was for CI results that are from 2016; I'm sure they're long-since gone (CI results are transitory -- they are not kept).  This fix was merged into what became the v2.0.0 release, which is now old/out of date.  You might want to try with a newer Open MPI version (e.g., v3.1.2).

Indeed, this whole repo is stale -- all activity is now on open-mpi/ompi.  Please see the top-level README in this repo: https://github.com/open-mpi/ompi-release

**Pull request merged**
