### PR TITLE
btl/tcp: fix add_procs race condition

### PR DESCRIPTION
**Pull request by hjelmn**
This commit fixes a race between a thread calling the tcp btl's
add_procs and a thread processing an incomming connection. The race
occured because the add_procs thread adds a newly created proc object
to the hash table _before_ the object is fully initialized. The
connection thread then attempts to use the object before the endpoints
array on the object has beeen allocation. The fix is to only add the
proc to the hash table after it has been completely initialized.

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

(cherry picked from open-mpi/ompi@03f4a854cb7a7eb3b9f3dfe7cea544a4cc386caa)

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

### CODE REVIEW

**Comment by hjelmn** [comment]
:bot:label:bug
:bot:milestone:v2.0.0
:bot:assign: @bosilca

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1563/ for details.

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Comment by jsquyres** [comment]
I'm going to merge these so that they can get into tonight's snapshot.

**Pull request merged**
