### PR TITLE
Update the session directory code to no longer rely on getpwuid as it is unnecessary.

### PR DESCRIPTION
**Pull request by rhc54**
Fixes https://github.com/open-mpi/ompi/issues/1964

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2088/ for details.

**Comment by hppritcha** [comment]
hmmm, looks like mpirun can't work on a stock cluster.  let's retry
bot:lanl:retest

**Comment by hppritcha** [comment]
bot:mellanox:retest

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2089/ for details.

**Comment by hppritcha** [comment]
This PR causes both mlnx and UH hello worlds to hang.

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@rhc54 Are there follow-on commits that should be added to this PR?  (e.g., based on further activity in master, e.g., per https://github.com/open-mpi/ompi/issues/1967 and https://github.com/open-mpi/ompi/pull/1968 and https://github.com/open-mpi/ompi/pull/1971)?

**Comment by rhc54** [comment]
No - this PR isn't actually required any more. The rsh update is all that is needed to solve the problem, and is the minimal change required.

**Pull request closed without merging**
