### PR TITLE
Update the PMIx support to the PMIx 1.1.2 release.

### PR DESCRIPTION
**Pull request by rhc54**
Fix intercomm_create with minor update to ompi/dpm and update of the test

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1332/ for details.

**Comment by jsquyres** [comment]
@hppritcha Let's chat about this on Monday (Ralph and I chatted about this before he made this PR).  It:
- updates PMIx to 1.1.2
- updates some infrastructure to handle the new things in PMIx 1.1.2
- fixes some memory leaks
- fixes MPI_INTERCOMM_MERGE

**Comment by hppritcha** [comment]
@jsquyres 
@rhc54 
all I can say is > 200 lines and 30 files changed just a few days before a RC2 speaks volumes about this project.  we've got to get a better handle on release management.  No wonder we talked about releasing 2.0 last June and here we are in 2016 in February and have yet to have a release.

**Comment by jsquyres** [comment]
@hppritcha Yes, we should talk about this one.  It synchronizes an external project that doesn't conform to the same release schedule as Open MPI... hence it's working at a different pace.  More importantly, it fixes some important bugs.

**Comment by hppritcha** [comment]
i'll give this PR a spin on one of the slurm/pmi1 clusters here.

**Comment by hppritcha** [comment]
:+1:
works for me with pmi1 on a slurm cluster.

**Comment by hppritcha** [comment]
@jsquyres this is ready to go.

**Comment by artpol84** [comment]
@jladd-mlnx @hppritcha @jsquyres @rhc54 to what changes in master this PR corresponds to?
Is this a cherry-picking or just a standalone set of commits that has nothing to do with master?

**Comment by artpol84** [comment]
Originally I thought that it is related to open-mpi/ompi@03eb1a80bf088bfbb058282afedce4beed79a3d4 but it doesn't seem like it is.
At least a) open-mpi/ompi@03eb1a80bf088bfbb058282afedce4beed79a3d4 has even more files changed; b) it doesn't introduce opal/errhandler directory that this commit introduces.

**Comment by artpol84** [comment]
The question is in the context of https://github.com/open-mpi/ompi/issues/2129

**Comment by artpol84** [comment]
The question is in the context of open-mpi/ompi#2072

**Comment by jsquyres** [comment]
I believe the way @rhc54 does this is:
- Make a branch off the OMPI release branch
- Make a new component for the target PMIx release
- Un-tar the PMIx release tarball in that new component, trim/adjust it as relevant
- Cherry pick and/or adjust the rest of the code base as appropriate

I believe that Ralph has discussed this methodology in face-to-face meetings; that's why there's no corresponding master commits.

**Pull request merged**
