### PR TITLE
Update extensions section to include cuda

### PR DESCRIPTION
**Pull request by rolfv**
Update MPI extensions section to include CUDA piece

(cherry picked from commit ompi-mpi/ompi@d184f260adddf9fab307adc94f2c8e08853485cf)

### CODE REVIEW

**Comment by rolfv** [comment]
bot:milestone:v2.0.0
bot:assign: @jsquyres

**Comment by jsquyres** [comment]
@rolfv Do you have a man page for your cuda extension?  If so, do you want to cite it in the README?  E.g., "For more information, see ....".

**Comment by rolfv** [comment]
There is one.  Maybe we could just go with what we have now and then I will update it later.  I think I still want to make some other changes in the CUDA extensions like fix the return value and have them build even when CUDA-aware is not there but just have them set to the right values.

**Comment by jsquyres** [comment]
@rolfv Sure, sounds fine -- just don't forget (but we're not going to immediately release v2.0.0, so you've got some time).

Can you do me a favor and file an issue against 2.0.0 with what you plan to do for 2.0.0 (i.e., the stuff you mentioned in your comment), so that we can track it?  Thanks.

**Pull request merged**
