### PR TITLE
Updated psm2 mtl with new externally exposed symbols of psm2.so

### PR DESCRIPTION
**Pull request by matcabral**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1055/ for details.

**Comment by matcabral** [comment]
he was merged in ompi:master mpi/ompi@8ebcac1b2c8f79c866c058e81afe58a19abd94ff

**Comment by matcabral** [comment]
bot:milestone:v2.0.0

**Comment by hppritcha** [comment]
@matcabral  please assign a reviewer

**Comment by matcabral** [comment]
bot:assign:@jsquyres

**Comment by jsquyres** [comment]
I cannot test this, but with some greps, I can see that all PSM names have been changed to PSM2.  Yay!

Two minor quibbles:
- mtl_psm2_types.h is marked as executable.  That should be fixed.
- There is no "owner.txt" file.

**Comment by hppritcha** [comment]
As an FYI, I can't test this either.  I only have access to Intel systems with infinipath/psm software stack.

**Comment by matcabral** [comment]
Jeff,  
Comments addressed. 

Testing: I understand the hassles around testing since the product is not yet publicly available. If it helps, I can say that our validation team has done extensive testing of this MTL.

**Comment by jsquyres** [comment]
@matcabral Perfect -- thanks! :+1:

**Pull request merged**
