### PR TITLE
Bring missing osc/rdma fixes to v2.x

### PR DESCRIPTION
**Pull request by hjelmn**
These commits fixed bugs found by MTT on master. They were intended for the v2.x branch but were never brought over. Fixes a failure on nvidia MTT.

See open-mpi/ompi#1427 for a typical backtrack. Ignore the title of the bug though as this has nothing to do with MPI_Aint.

:bot:assign: @sjeaugey 
:bot:label:bug
:bot:milestone:v2.0.0

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1411/ for details.

**Comment by jsquyres** [comment]
@hjelmn Is this critical for v2.0.0?  If so, please mark it with the "blocker" label.

**Comment by hjelmn** [comment]
:bot:label:blocker

**Comment by jsquyres** [comment]
@sjeaugey Please review for v2.0.0.

**Comment by sjeaugey** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Pull request merged**
