### PR TITLE
Added Intel HFI1 default parameters for openib

### PR DESCRIPTION
**Pull request by matcabral**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1053/ for details.

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
@matcabral Can you have a look at https://github.com/open-mpi/ompi/wiki/OmpiReleaseBotCommands and use the "bot" commands on future PR's to set milestones, etc.?  Thanks.

**Comment by matcabral** [comment]
sure. Do all ompi-release PRs  require a milestone to be assigned ?  thanks,

**Comment by jsquyres** [comment]
@matcabral Yes, a milestone is required so that we can classify them properly (e.g., it helps with looking at the various Github reports).  Also, we require someone to thumbs-up a PR (i.e., give a review) on the release branches before they are merged in.  Here's our general process: https://github.com/open-mpi/ompi/wiki/SubmittingPullRequests

**Comment by matcabral** [comment]
merged in ompi:master mpi/ompi@45c27843e1972b6a2a744773074f86d1694cb912

**Pull request merged**
