### PR TITLE
Correctly set the #procs in the job to "job_size", and the max_procs to "univ_size"

### PR DESCRIPTION
**Pull request by rhc54**
(cherry picked from commit open-mpi/ompi@75dc4c305a0ce3151ea4567a5223100822f80d09)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1566/ for details.

**Comment by jjhursey** [comment]
👍 
A few notes for those interested:
- `orte/util/proc_info.c` sets both `max_procs` and `num_procs` to 1 (default).
- `orte/mca/ess/pmi/ess_pmi_module.c` (around like 379-380) sets the `max_procs` equal to `num_procs` if it is less than `num_procs`. So that is why it seemed to just work before. This patch provides the PMIx server the ability to set these separately for the Open MPI processes.

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1911/ for details.

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1971/ for details.

**Comment by jsquyres** [comment]
For some reason, ompibot didn't capture Josh's 👍

**Comment by jsquyres** [comment]
@hppritcha This is good to go.

**Pull request merged**
