### PR TITLE
NEWS: updates for 2.0.0 rc4

### PR DESCRIPTION
**Pull request by hppritcha**
@jsquyres 

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

**Comment by jsquyres** [comment]
👍

**Comment by hppritcha** [comment]
@jsquyres this needs to be merged with 9acf4926

**Comment by hppritcha** [comment]
i'll just open a new PR.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1805/ for details.

**Pull request merged**
