### PR TITLE
ft removal: remove ft related configury options

### PR DESCRIPTION
**Pull request by hppritcha**
remove ft and checkpoint stuff from configury
opal ignore all of the crs components
remove references to removed ft/crs support from README

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

**Comment by hppritcha** [comment]
@jsquyres take a look and see if this is going in the right direction.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/721/ for details.

**Comment by jsquyres** [comment]
Did you plan to .opal_ignore the components, or outright remove them?

**Comment by hppritcha** [comment]
If you'd prefer I could just remove them.  I did this in a test branch and I believe I had to make some changes outside of the crs framework to get it to still compile.  I'll give that a try.

**Comment by hppritcha** [comment]
closing this as PR #714 supersedes it.

**Pull request closed without merging**
