### PR TITLE
Fix an annoying segfault caused by incorrect indentation

### PR DESCRIPTION
**Pull request by rhc54**
Fix an annoying segfault caused by incorrect indentation in a loop that causes the buffer to not be created prior to packing.

(cherry picked from commit open-mpi/ompi@9bc384282a310421c08df54bbc6a3d1307d014ce)

@jsquyres This should fix the no-disconnect problem. It is actually a fairly small change, but caused lots of re-indentation.

### CODE REVIEW

**Comment by hppritcha** [comment]
Was this caused by the white space tool?  I'm confused about the title of the PR.

**Comment by rhc54** [comment]
No, it was caused by an obj_new being in the wrong level of indentation.

**Comment by jsquyres** [comment]
The no-disconnect test still hangs, but now when you kill mpirun, the procs die, too.

Thanks!

:+1:

**Comment by rhc54** [comment]
Really? It no longer hangs on master for me, so it looks like something else must also be missing on 2.x. What I changed here should in no way have impacted the "suicide" operation - it was intended to solve the no-disconnect hang, which it fixed for me.

**Comment by jsquyres** [comment]
Let me try the test on master...

**Comment by jsquyres** [comment]
Ah, I think I see the problem.

I'm running under SLURM, and if I don't specify `--oversubscribe` on the `mpirun` command line, I get this error in the middle of the test:

```
--------------------------------------------------------------------------
All nodes which are allocated for this job are already filled.
--------------------------------------------------------------------------
```

and the test hangs there (assumedly because MPI_COMM_SPAWN is trying to spawn, but ORTE says "Nay nay! There art too many processes on thine nodes!"... but then doesn't actually return a failure up to MPI_COMM_SPAWN, which would trigger killing the jobs.  (this is a guess)

If I add `--oversubscribe` to the `mpirun` command line, then the test completes as normal.

So I think this PR is good for fixing the first problem.  Should we have a different issue/PR for the hanging issue?

**Comment by hppritcha** [comment]
@jsquyres are you good with merging this?

**Comment by rhc54** [comment]
@jsquyres Yeah, that's a separate issue that needs to be addressed. Nothing to do with this one.

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
