### PR TITLE
osc/rdma: bring over one-sided fixes from master

### PR DESCRIPTION
**Pull request by hjelmn**
This commit brings over two commits:

open-mpi/ompi@eed7b45db59b356f6257f3b019e77643f14f84ce

osc/rdma: fix issue identified by Berk Hess

osc/rdma uses counters to determine if all messages have been received
before exiting synchronization calls. The problem is that the active
target counter is always increasing (never zeroed). If over 2^31-1
messages are sent this causes the counter to overflow (in itself this
isn't an error). This causes test/wait to return before the communication
is complete. There is an additional error in the use of the fragment
flush function. If PSCW synchronization is in use this function CAN NOT
be called unless a post message has arrived.

Relevant mailing list thread: http://www.open-mpi.org/community/lists/devel/2014/10/16016.php

This commit fixes both issues. Tested against MTT and issue reproducer.

open-mpi/ompi@23dd3af946dbfec55f3261c2a1a8e3ea30ed695c

osc/rdma: use unsigned types for all counters

Some of the counters used by the "rdma" one-sided component are intended
to overflow. Since overflow behavior is undefined for signed integers in
C it is safer to use unsigned integers here.

### CODE REVIEW

**Comment by hjelmn** [comment]
This replaces pull request #13. In addition to the original commit this addresses the issue identified by @goodell

**Comment by jsquyres** [comment]
Does it need a new review from @goodell?

**Comment by goodell** [comment]
Looks OK to me, though I would prefer that if you are bringing over two commits, just bring over two commits.  There's no reason to squash them into a single commit now that we have Git.  That's the role of the merge commit that will be created when Ralph approves the PR.

**Comment by hjelmn** [comment]
@goodell Redid the branch with cherry-picks

**Comment by goodell** [comment]
Looks OK to me.

**Pull request merged**
