### PR TITLE
Merge pull request #835 into branch v1.10

### PR DESCRIPTION
**Pull request by Zhiming-Wang**
I merged the change set of "Pull Request" #835 into branch v1.10

### CODE REVIEW

**Comment by jsquyres** [comment]
This one doesn't include the AUTHORS change.  Can you add that commit to this PR?

Some pro / Github tips:
1. To refer to an issue / PR from master, prefix the token with "open-mpi/ompi".  For example, open-mpi/ompi#835 will correctly link to PR/issue 835 on the open-mpi/ompi git repo.
2. It's ok to not squash commits down into a single commit for PRs to release branches.  E.g., on #553, you cherry picked the one commit from master, but also added a change to AUTHORS.  It would probably be good to see  a second commit for the AUTHORS change (since that was a second commit on master).  See the "git cherry-pick" command, and the wiki pages listed below for good ways to do this.
3. PRs to release branches need to be reviewed before they will be merged.  In most cases, you can @ mention the person you want to review it, and/or use a "bot:" command to assign the PR to them for review (see below for "bot" commands).  For this PR, for example, you could say "@jsquyres please review", or somesuch.
4. PRs to release branches need to include the git hash of the master commit from which they were derived.
5. Be sure to assign labels and milestones to PRs on release branches.  See these two wiki pages for instructions:
   - https://github.com/open-mpi/ompi/wiki/SubmittingPullRequests
   - https://github.com/open-mpi/ompi/wiki/OmpiReleaseBotCommands

**Comment by Zhiming-Wang** [comment]
Done. My name was added into "AUTHORS".

**Comment by jsquyres** [comment]
I'm now a little confused by this PR -- it seems to have 2 duplicate commits (albeit one with a change to AUTHORS) and a merge commit...?

Can you make this PR be just a cherry pick of the individual relevant commits from master?

**Comment by Zhiming-Wang** [comment]
I combined the comments into one. I suppose this is all right. Please recheck it.
About Git commands, I have almost collapsed! I should use "git reset --soft", not "git rebase -i", if I just want to combine the comments.

**Comment by jsquyres** [comment]
@Zhiming-Wang Yes, this is better, thanks!  In the future, note that you don't have to squash down to one commit.

Can you still commit the change to AUTHORS to master (in a separate PR)?  We like to see stuff on master before we approve putting them to the release branches.

**Comment by Zhiming-Wang** [comment]
@jsquyres , Is it the master of open-mpi/ompi ?
Done. https://github.com/open-mpi/ompi/pull/880

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
