### PR TITLE
btl/ugni: actually make the endpoint lock recursive

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

(cherry picked from commit open-mpi/ompi@83062db7cbe3824b98406fb26a513eec3ee22309)

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

### CODE REVIEW

**Comment by hjelmn** [comment]
:bot:label:bug
:bot:milestone:v2.0.1
:bot:assign: @hppritcha 

Missed this when transcribing the patch.

**Comment by jsquyres** [comment]
@hjelmn What bug does this solve?

**Comment by hjelmn** [comment]
A bug I introduced. If MPI_THREAD_MULTIPLE is on it deadlocks on the first connection. Couldn't test after transcribing because none of our open Cray systems were up. Hit the bug immediately once I got to test.

**Comment by hjelmn** [comment]
Half of the fix made it. See https://github.com/open-mpi/ompi-release/blob/v2.x/opal/mca/btl/ugni/btl_ugni_endpoint.h#L37

**Comment by hjelmn** [comment]
Also, this does not require an rc2 IMO.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
@hppritcha Assuming you can review, I'm ok with this.

**Comment by hjelmn** [comment]
LANL jenkins blew up.

:bot:lanl:retest

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hjelmn** [comment]
@hppritcha LANL jenkins looks like it is busted.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2122/ for details.

**Comment by hjelmn** [comment]
And now the mellanox Jenkins is belly-up.

```
00:48:21.114 --2016-08-24 20:56:33--  (try: 2)  http://www.mcs.anl.gov/~thakur/thread-tests/thread-tests-1.1.tar.gz
00:48:21.114 Connecting to www.mcs.anl.gov (www.mcs.anl.gov)|140.221.6.95|:80... failed: Connection timed out.
00:50:28.370 Retrying.
```

**Comment by hjelmn** [comment]
bot:mellanox:retest
bot:lanl:retest

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2124/ for details.

**Comment by hppritcha** [comment]
bot:lanl:retest

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by hppritcha** [comment]
UH network problems hitting of some sort.
@edgargabriel if you have the chance could you see if the cluster at UH is having external connectivity issues?

**Comment by hppritcha** [comment]
lets wait for CI modulo the mess up at UH then merge.
👍

**Comment by edgargabriel** [comment]
I can login onto the node without issues, but I know that there were some network issues the last two days.

**Comment by jsquyres** [comment]
bot:ibm:retest

**Comment by hppritcha** [comment]
@edgargabriel says UH is messed up while school starts up so we'll ignore dlopen and distcheck tests for this PR.

**Comment by edgargabriel** [comment]
not objecting to the decision, but I am still a bit surprised that it 'hangs' since both of my pr's that I filed today got through that point without major issues.

**Comment by hppritcha** [comment]
bot:lanl:retest
@jsquyres i vote for merging in and seeing how mtt goes over the weekend

**Pull request merged**
