### PR TITLE
Remove "signed vs. unsigned" warnings.

### PR DESCRIPTION
**Pull request by jsquyres**
(cherry picked from commit open-mpi/ompi@702f80ad7ee2eb2e7b377d0b728bd91392b4aa74)

@bosilca Please review; straightforward cherry pick from master.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1586/ for details.

**Comment by bosilca** [comment]
👍

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
bot:retest

**Pull request merged**
