### PR TITLE
v2.x fortran dup fn fix

### PR DESCRIPTION
**Pull request by jsquyres**
- MPI_COMM_DUP_FN
- MPI_TYPE_DUP_FN
- MPI_WIN_DUP_FN

(cherry picked from commit open-mpi/ompi@26b2ed1069bc9dcf0b7b5912acb90e82678e4e23)

This is from PR open-mpi/ompi#1180

@ggouaillardet please review that I brought this over properly

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1145/ for details.

**Comment by ggouaillardet** [comment]
@jsquyres open-mpi/ompi@98bf02485dd0040f5db26128d047ee4a3f712975 has never been backported (!) so fortran 2008 does not work on v2.x
i will commit some mtt tests today

**Comment by jsquyres** [comment]
@ggouaillardet Ugh.  Looking closer, I realize that we actually have quite a bit of drift between master Fortran support and v2.x Fortran support.  :cry: Should we just do a PR to completely sync master/Fortran with v2.x/Fortran?

**Comment by ggouaillardet** [comment]
that would be best

**Comment by jsquyres** [comment]
Ok, let me kill this PR and let's open a new one.  I don't think I'll try to cherry-pick every single Fortran-related commit (I think that is what has led to this drift).  Rather, I'll just copy over everything from master to v2.x manually and try to summarize the commits that all the changes span.

I think there will be some configury changes, dragged along, too.

Sound good?

**Pull request closed without merging**
