### PR TITLE
pmix/pmix112: Fix comments

### PR DESCRIPTION
**Pull request by jjhursey**
- Resulting from bad search/replace from https://github.com/open-mpi/ompi-release/pull/1129

### CODE REVIEW

**Comment by jjhursey** [comment]
:bot:assign: @rhc54
:bot:label:code cleanup
:bot:milestone:v2.0.0

**Comment by jjhursey** [comment]
:bot:label:Code-cleanup-low-priority

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1618/ for details.

**Comment by jsquyres** [comment]
👍 

This changes no code; the risk is minimal.

**Pull request merged**
