### PR TITLE
v1.10 - port rmaps dist_device support from master

### PR DESCRIPTION
**Pull request by mike-dubman**
master: open-mpi/ompii@1e913c76c

### CODE REVIEW

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mike-dubman** [comment]
@vasilyMellanox - please review

**Comment by mike-dubman** [comment]
bot:milestone:v1.10.1
bot:label:enhancement
bot:assign: @rhc54

**Comment by jsquyres** [comment]
@miked-mellanox It's confusing that you're @ mentioning someone to review these PR's, and then assigning the PR to someone else...

**Pull request merged**
