### PR TITLE
Topic/hwloc update

### PR DESCRIPTION
**Pull request by ggouaillardet**
Per our discussion on the devel ML, here is a PR that brings the latest hwloc v1.7 branch to the OpenMPI v1.8 series

note i had to do a dirty patch (see the second one line commit) to get things work,
at this stage, i do not understand what is going wrong

@rhc54 @jsquyres could you please review this ?

### CODE REVIEW

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/72/
Test PASSed.

**Comment by rhc54** [comment]
I filed another PR that updates hwloc to 1.9.1 - it was a clean update, so I'm not sure why this one had problems. Could you test the other one? It seems to be okay for me, but my resource access is limited this week. If the 1.9 update passes muster, I think we'll go with it for easier long-term maintenance.

**Comment by ggouaillardet** [comment]
I am ok with that too.

I did not see any updates of hwloc in the ompi master (Brice pushed some fixes in the hwloc v1.9 branch).

Did you make the PR based on hwloc repo or ompi master repo ?

**Comment by rhc54** [comment]
I took the 1.9 branch inside of OMPI master - I didn't know about the
upstream fixes. We generally only take them if they apply to systems of
interest. Can you tell what they are? If they apply to Linux or Solaris,
then we should probably take them into the master and I can update the PR
after we've let it soak for a couple of days.

**Comment by ggouaillardet** [comment]
My goal was to fix the issue discussed at http://www.open-mpi.org/community/lists/users/2014/12/25995.php :
Heavy inlining with gcc 5 on ia32

**Comment by rhc54** [comment]
Okay, I'll take a look - thanks!

**Comment by rhc54** [comment]
Took alternative update to 1.9.1

**Pull request closed without merging**
