### PR TITLE
plm rsh: assign some levels to the rsh PLM MCA params

### PR DESCRIPTION
**Pull request by jsquyres**
Need to add final 2 params when open-mpi/ompi-release#243 is merged.

(cherry picked from commit open-mpi/ompi@11e8c2096b6bfdec2433fa43316d2a4c439a4102)

Do not merge yet.  Waiting for #243.

### CODE REVIEW

**Comment by mellanox-github** [comment]
- Coverity found 1472 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_233/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_233/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_233/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/233/
Test PASSed.

**Comment by jsquyres** [comment]
@rhc54 I rebased this commit, now that #243 was merged.  So this one should be good to go, once you review it.

Note, too, that I fixed a grammar error in one of the help strings, too.

**Comment by mellanox-github** [comment]
- Coverity found 1468 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_236/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_236/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_236/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/236/
Test PASSed.

**Pull request merged**
