### PR TITLE
v2.x trailing whitespace purge

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

### CODE REVIEW

**Comment by hjelmn** [comment]
:bot:milestone:v2.0.0
:bot:assign: @jsquyres

**Comment by hjelmn** [comment]
Purge white-space errors using:

```
git ls-files | grep -v pdf | grep -v 3in | tr '\n' '\0' | xargs -0 sed -i '' -E "s/[[:space:]]*$//"
```

**Comment by hppritcha** [comment]
Is this a cherry-pick of open-mpi/ompi@869041f7 ?

**Comment by hjelmn** [comment]
More or less. It was easier to just run the purge script again. I modified the script to avoid changing pdfs (pdfs were changed on master then reverted) and the man pages. I am not sure how trailing whitespace appears when run through roff.

**Comment by hjelmn** [comment]
I will update the commit message to reference the master commit.

**Comment by hppritcha** [comment]
@jsquyres lets discuss on Monday before merging.  Not opposed to this, just want to make sure we don't make things more difficult.

**Comment by rhc54** [comment]
FWIW: there is also a whitespace purging script in contrib that we used on master - might be safer method

**Comment by hjelmn** [comment]
@rhc54 Same thing but only modifies files known to the git repository.

**Comment by rhc54** [comment]
@hjelmn kewl - then let's modify the script in the code base so others don't have to figure it out :-)

**Comment by rhc54** [comment]
@hjelmn ok, I updated it

**Comment by rhc54** [comment]
@jsquyres @hppritcha  I'd recommend caution here - I tried Nathan's script on the 1.10 branch, and it converted symbolic links into the actual files.

**Comment by hppritcha** [comment]
thanks for the headsup.  whats the real neef for this pr anyway?

---

sent from my smart phonr so no good type.

Howard

**Comment by hjelmn** [comment]
@rhc54. Ok, let me modify the script to ensure it doesn't muck with symlinks.

@hppritcha The PR is intended to reduce the time to create a master -> 2.x PR. It takes time to work through all the whitespace differences. I am waiting on bringing over any more master PRs until this is in.

**Comment by rhc54** [comment]
@hjelmn kewl - when you get it right, could you please put it in contrib/whitespace_purge.sh so we preserve it?

**Comment by hjelmn** [comment]
Should be better now. Using a more complicated script that checks that the mime-type is text/

``` sh
for file in $(git ls-files) ; do
    # check for the mime-type and do not follow symbolic links. this
    # will cause file to print application/x-symlink for the mime-type
    # allowing us to only have to check if the type is application to
    # skip sym links, pdfs, etc. If any other file types should be
    # skipped add the check here.
    type=$(file -b --mime-type -h $file)
    if test -f $file && test ${type::4} == "text" ; then
        LC_ALL=C sed -i '' -E "s/[[:space:]]*$//" $file
    fi
done
```

**Comment by jsquyres** [comment]
@hjelmn This PR now has conflicts :-(  Can you update?

**Comment by hjelmn** [comment]
@jsquyres Should be fixed now.

**Comment by jsquyres** [comment]
@hjelmn Github still says there are conflicts :-(

**Comment by hjelmn** [comment]
@jsquyres Ok, I reran the whitespace script on Friday. Probably just need to run it again. Fixing now.

**Comment by jsquyres** [comment]
@hjelmn Keeps getting hosed by every 2.x PR that gets merged, so I'm not going to wait for the Jenkins instances to complete, and will just merge this now.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request merged**
