### PR TITLE
mtl/ofi: Merge changes from master.

### PR DESCRIPTION
**Pull request by yburette**
This is a combination of 7 commits:
   mtl/ofi: Deprioritize some OFI providers.
   mtl/ofi: add include/exclude list MCA vars.
   mtl/ofi: remove redundant code.
   mtl/ofi: Handle -FI_EAGAIN on send and recv operations.
   mtl/ofi: Renamed macro to prevent clash with FI_ namespace.
   mtl/ofi: Minor code cleanup.
   Fix warnings in direct (pml-cm,mtl-ofi) build

### CODE REVIEW

**Comment by hppritcha** [comment]
@jsquyres  I want to give this a spin on one of the truescale clusters here at LANL before merging.
 @yburette I know its kind of a pain but in the future could PRs back to 2.x be arranged so that there is a one-to-one cherry-pick between commits to master and commits to v2.x?  That makes it much simpler to check if commits by someone have been missed.

**Comment by jsquyres** [comment]
@yburette You may already know this, but just in case you didn't: you can use `git cherry-pick -x ...` to pick across the specific commits you want; the `-x` will add a comment in the commit message containing the hash that you cherry-picked.  I usually edit the commit message and add `open-mpi/ompi@` before the hash, so that Github will autolink it properly.

**Comment by hppritcha** [comment]
I'm having problems trying to run ring_c with this build.  I've installed libfabric on my system and do include --with-libfabric=blahblah on my config line.  When I try to run I get

users/hpp/ompi_release_install/lib/openmpi/mca_mtl_psm.so: undefined symbol: psm_setopt

The psm lib on my system is installed in /usr/lib64.

Maybe just dumb user error but I'd not hit that before.

I'm not using --disable-dlopen on the config line.

**Comment by hppritcha** [comment]
something doesn't seem right here.  If I use mpirun blah blah --mca mtl ofi, ring_c works.
Also I notice this:

``` sh
hpp@wf472[96.74]:/turquoise/users/hpp/ompi-release/examples> ((2b7d48d...) *)ldd ~/ompi_release_install/lib/openmpi/mca_mtl_ofi.so
    linux-vdso.so.1 =>  (0x00007fffed9de000)
    libmca_common_libfabric.so.0 => /users/hpp/ompi_release_install/lib/libmca_common_libfabric.so.0 (0x00002ad344c2a000)
    libfabric.so.1 => /users/hpp/libfabric_install/lib/libfabric.so.1 (0x00002ad344e2c000)
    librdmacm.so.1 => /usr/lib64/librdmacm.so.1 (0x00002ad34509d000)
    libibverbs.so.1 => /usr/lib64/libibverbs.so.1 (0x00002ad3452b2000)
    libpsm_infinipath.so.1 => /usr/lib64/libpsm_infinipath.so.1 (0x00002ad3454c5000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ad345717000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00002ad345934000)
    librt.so.1 => /lib64/librt.so.1 (0x00002ad345b39000)
    libm.so.6 => /lib64/libm.so.6 (0x00002ad345d41000)
    libutil.so.1 => /lib64/libutil.so.1 (0x00002ad345fc5000)
    libc.so.6 => /lib64/libc.so.6 (0x00002ad3461c9000)
    /lib64/ld-linux-x86-64.so.2 (0x00002ad3447fe000)
    libnl.so.1 => /lib64/libnl.so.1 (0x00002ad34655d000)
    libinfinipath.so.4 => /usr/lib64/libinfinipath.so.4 (0x00002ad3467b0000)
```

but for the psm mtl dso:

``` sh
hpp@wf472[96.74]:/turquoise/users/hpp/ompi-release/examples> ((2b7d48d...) *)ldd /users/hpp/ompi_release_install/lib/openmpi/mca_mtl_psm.so
    linux-vdso.so.1 =>  (0x00007fff2c96d000)
    librt.so.1 => /lib64/librt.so.1 (0x00002b1c072ef000)
    libm.so.6 => /lib64/libm.so.6 (0x00002b1c074f7000)
    libutil.so.1 => /lib64/libutil.so.1 (0x00002b1c0777c000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b1c0797f000)
    libc.so.6 => /lib64/libc.so.6 (0x00002b1c07b9c000)
    /lib64/ld-linux-x86-64.so.2 (0x00002b1c06ea7000)
```

and an older install of master:

``` sh
hpp@wf472[96.74]:/turquoise/users/hpp/ompi-release/examples> ((2b7d48d...) *)ldd /users/hpp/ompi_install/lib/openmpi/mca_mtl_psm.so
    linux-vdso.so.1 =>  (0x00007fff495ff000)
    libpsm_infinipath.so.1 => /usr/lib64/libpsm_infinipath.so.1 (0x00002b061f651000)
    librt.so.1 => /lib64/librt.so.1 (0x00002b061f8a3000)
    libm.so.6 => /lib64/libm.so.6 (0x00002b061faac000)
    libutil.so.1 => /lib64/libutil.so.1 (0x00002b061fd30000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b061ff33000)
    libc.so.6 => /lib64/libc.so.6 (0x00002b0620151000)
    libinfinipath.so.4 => /usr/lib64/libinfinipath.so.4 (0x00002b06204e5000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00002b06206f2000)
    /lib64/ld-linux-x86-64.so.2 (0x00002b061f209000)
```

**Comment by hppritcha** [comment]
I tried building with --disable-dlopen and the results are strange.  I have no problems running the ofi
mtl, but with the psm mtl, the ring_c hangs for most rungs.  The unresolved symbol problem does, of
course, go away.

**Comment by hppritcha** [comment]
Looks like somehow in switching between branches in my ompi-release sandbox I clobbered the
configure.m4 in the ompi/mca/mtl/psm subdir.  That explains the missing dso dependency in the
mca_mtl_psm.so.

**Comment by yburette** [comment]
@hppritcha @jsquyres 
Let me close this PR and I will recreate cherry-picked ones then.
Thanks for the tip about `git cherry-pick -x`!

**Pull request closed without merging**
