### PR TITLE
coll/libnbc: fix MPI_Ireduce_scatter_block for one task communicator

### PR DESCRIPTION
**Pull request by ggouaillardet**
Thanks Lisandro Dalcin for the report

Fixes open-mpi/ompi#248

(cherry picked from commit open-mpi/ompi@6c9d65c0ca43a1de2a3efc433ceab3913a584e32)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @hjelmn 
:bot:milestone:v2.0.0
:bot:label:bug
:bot:label:blocker

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1620/ for details.

**Comment by hjelmn** [comment]
@ggouaillardet What is the bug? The linked bug is unrelated.

**Comment by ggouaillardet** [comment]
my bad, it fixes open-mpi/ompi#1636
i just pushed the fixed commit
v1.10 is ok, and i guess the fix got lost in the middle of some rewrite of libnbc

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1623/ for details.

**Comment by hjelmn** [comment]
:+1:

**Pull request merged**
