### PR TITLE
yalla: fix valgrind error due to uninitialized status field.

### PR DESCRIPTION
**Pull request by igor-ivanov**
port from v1.10 
https://github.com/open-mpi/ompi-release/commit/76053c1786d4bde3df65da430f50ab468b998657
https://github.com/open-mpi/ompi-release/commit/b0bedf6f5c94a6157ae3380968e58690040aa22a

:bot:label:bug
:bot:milestone:v2.0.0

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1042/ for details.

**Comment by igor-ivanov** [comment]
:bot:milestone:v2.0.0

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1043/ for details.

**Comment by hppritcha** [comment]
@igor-ivanov what are the corresponding commits into ompi/master for this PR?

**Comment by mike-dubman** [comment]
master commits:
https://github.com/open-mpi/ompi/pull/1138
https://github.com/open-mpi/ompi/pull/1133
:+1:

**Pull request merged**
