### PR TITLE
Mlnx copyright fix v2.x

### PR DESCRIPTION
**Pull request by artpol84**
Fix Mellanox copyrights with respect to the following PRs:
- https://github.com/open-mpi/ompi-release/pull/815
- https://github.com/open-mpi/ompi-release/pull/819
- https://github.com/open-mpi/ompi-release/pull/832
- https://github.com/open-mpi/ompi-release/pull/833
- https://github.com/open-mpi/ompi-release/pull/852
- https://github.com/open-mpi/ompi-release/pull/868
- https://github.com/open-mpi/ompi-release/pull/879
- https://github.com/open-mpi/ompi-release/pull/887
- https://github.com/open-mpi/ompi-release/pull/888
- https://github.com/open-mpi/ompi-release/pull/889

(related to the commit open-mpi/ompi@2abb2972acf38f2060ee20582061f60a686efdea)

### CODE REVIEW

**Comment by artpol84** [comment]
:bot:assign: @jladd-mlnx 
:bot:milestone:v2.0.0

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1326/ for details.

**Comment by jladd-mlnx** [comment]
:+1: 
bot:label:reviewed

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Pull request merged**
