### PR TITLE
Topic/v1.10/hcoll fca configury

### PR DESCRIPTION
**Pull request by ggouaillardet**
:bot:assign: @jsquyres 
:bot:milestone:v1.10.0
:bot:label:bug

### CODE REVIEW

**Comment by jsquyres** [comment]
See open-mpi/ompi#796 @bureddy

**Comment by rhc54** [comment]
I am now confused - I see that the 1.8.9 got reviewed okay, but then some other comment was added which made it unclear if it was actually okay...and there has been no indicated review here.

Can someone please clarify - is this ready to go or not?

**Comment by bureddy** [comment]
@rhc54 : I'm testing v1.10 and v2.x now.  will do thumps-up once it is done

**Comment by bureddy** [comment]
:+1:

**Pull request merged**
