### PR TITLE
coll-portals4: add gather and igather implementations that use Portals4 triggered operations

### PR DESCRIPTION
**Pull request by tkordenbrock**
This commit adds implementations of gather and igather using
Portals4 triggered operations.  The default algorithm is linear,
but binomial can be selected using an MCA parameter -
coll_portals4_use_binomial_gather_algorithm.

(rolled up two commits: open-mpi/ompi@7c738fb and open-mpi/ompi@f6f525e)

@regrant - please review

### CODE REVIEW

**Comment by tkordenbrock** [comment]
:bot:label:enhancement
:bot:milestone:v2.0.0
:bot:assign: @regrant

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1077/ for details.

**Comment by hppritcha** [comment]
@regrant when you have a chance can you review?

**Comment by regrant** [comment]
:+1: re-reviewed from the trunk version and this looks good.

**Pull request merged**
