### PR TITLE
btl/openib: fix rdmacm hang

### LINKED ISSUE #1829: rdmacm sometimes hangs in finalize in Mellanox Jenkins
http://bgate.mellanox.com/jenkins/job/gh-ompi-master-pr/2638/console -- which is a Jenkins run off https://github.com/open-mpi/ompi/pull/1821 -- shows a problem that we've been seeing in a few Jenkins runs: the rdmacm CPC in the openib BTL hangs during finalize.

Here's the command that is run:

```
/var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/bin/mpirun -np 8 -bind-to core --report-state-on-timeout --get-stack-traces --timeout 600 -mca btl_openib_receive_queues P,65536,256,192,128:S,128,256,192,128:S,2048,1024,1008,64:S,12288,1024,1008,64:S,65536,1024,1008,64 -mca btl_openib_cpc_include rdmacm -mca pml ob1 -mca btl self,openib -mca btl_if_include mlx4_0:2 /var/lib/jenkins/jobs/gh-ompi-master-pr/workspace/ompi_install1/examples/hello_c
```

This warning comes up; I don't know if it's significant:

```
11:17:09 --------------------------------------------------------------------------
11:17:09 No OpenFabrics connection schemes reported that they were able to be
11:17:09 used on a specific port.  As such, the openib BTL (OpenFabrics
11:17:09 support) will be disabled for this port.
11:17:09 
11:17:09   Local host:           jenkins01
11:17:09   Local device:         mlx5_0
11:17:09   Local port:           1
11:17:09   CPCs attempted:       rdmacm
11:17:09 --------------------------------------------------------------------------
```

But then all procs have a backtrace like this during finalize:

```
11:27:13 	Thread 1 (Thread 0x7ffff73e3700 (LWP 10492)):
11:27:13 	#0  0x0000003d6980b5bc in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
11:27:13 	#1  0x00007fffeeb81c6d in rdmacm_endpoint_finalize (endpoint=0x7fbdb0) at connect/btl_openib_connect_rdmacm.c:1229
11:27:13 	#2  0x00007fffeeb6cdeb in mca_btl_openib_endpoint_destruct (endpoint=0x7fbdb0) at btl_openib_endpoint.c:368
11:27:13 	#3  0x00007fffeeb559b7 in opal_obj_run_destructors (object=0x7fbdb0) at ../../../../opal/class/opal_object.h:460
11:27:13 	#4  0x00007fffeeb5ae97 in mca_btl_openib_del_procs (btl=0x748ed0, nprocs=1, procs=0x7fffffffc768, peers=0x802fa0) at btl_openib.c:1328
11:27:13 	#5  0x00007fffeefb2159 in mca_bml_r2_del_procs (nprocs=8, procs=0x78bf60) at bml_r2.c:623
11:27:13 	#6  0x00007fffee2ba612 in mca_pml_ob1_del_procs (procs=0x78bf60, nprocs=8) at pml_ob1.c:455
11:27:13 	#7  0x00007ffff7ca4b94 in ompi_mpi_finalize () at runtime/ompi_mpi_finalize.c:333
11:27:13 	#8  0x00007ffff7cd6fe1 in PMPI_Finalize () at pfinalize.c:47
11:27:13 	#9  0x0000000000400890 in main (argc=1, argv=0x7fffffffcb38) at hello_c.c:24
```

@jladd-mlnx @artpol84 Can you look into this?

@larrystevenwise @bharatpotnuri Is this happening on the v2.x branch for iWARP?

@hppritcha Is this a v2.0.0 or v2.0.1 item?  IIRC, rdmacm is a non-default CPC for IB, and you have to add a per-peer QP -- I thought we had this conversation before about a previous rdmacm CPC error: that we would push it to v2.0.1 (but then we didn't because it also affected iWARP).  Is my memory correct?

### PR DESCRIPTION
**Pull request by hjelmn**
This commit is an attempt to fix a hang in finalize of rdmacm. This fixes
a path where no rdmacm client is found for an endpoint.

Fixes open-mpi/ompi#1829

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

(cherry picked from commit open-mpi/ompi@960fcd292c2fc9a05acb9dd003ba9dfc27e8c1eb)

Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

### CODE REVIEW

**Comment by hjelmn** [comment]
:bot:label:bug
:bot:milestone:v2.0.0
:bot:assign: @bharatpotnuri

**Comment by hjelmn** [comment]
@bharatpotnuri  Please verify the fix and reply with `:+1:` to mark this as reviewed.

**Comment by hjelmn** [comment]
bah, the bot pulled the +1 out of that

:bot:nolabel:reviewed

**Comment by hjelmn** [comment]
:bot:nolabel:pushed-back

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1822/ for details.

**Comment by hjelmn** [comment]
Jenkins found a bug that looks like it has been in rdmacm for some time. It was hidden by us disabling the openib btl when thread multiple was in use. Should pass Jenkins now.

**Comment by bharatpotnuri** [comment]
commit ed2bba2 tests fine for iwarp and fixes the stall at MPI_Finalize.
Thanks @hjelmn !

**Comment by hjelmn** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1823/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1824/ for details.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

**Comment by jjhursey** [comment]
I don't know why the IBM CI tests are not showing up in the list, but here are the failure logs:
  https://gist.github.com/89fdbe8184b26859afcbe1d0528dfcac
  https://gist.github.com/ibm-ompi/1fefe2a65545eea068ddc825ebd5561f

**Comment by hjelmn** [comment]
@jjhursey There was a typo that I corrected before the IBM results came back. Probably why they are not showing up.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1825/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1826/ for details.

**Comment by hjelmn** [comment]
Mellanox failure is fixed by #1249. Both together should make Jenkins happy.

**Comment by jsquyres** [comment]
Per discussion on the webex today, @hjelmn will separate this into two PRs:
1. the regression fix for single-threaded fix will stay here and be in v2.0.0
2. move the multi-threaded rdmacm fix into a separate PR and put it in v2.0.1

**Comment by hjelmn** [comment]
@jsquyres Removed the threading bug fix. Now only has the regression fix.

**Comment by jsquyres** [comment]
@hjelmn Thanks
@hppritcha Once CI finishes, good to go (although until Mellanox removes the multi-threaded RDMACM test, it's going to fail)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1831/ for details.

**Pull request merged**
