### PR TITLE
Remove extraneous , from oshmem/mca/sshmem/verbs/configure.m4

### PR DESCRIPTION
**Pull request by opoplawski**
This resulted in:

 ./configure: line 271954: ,: command not found

with 1.8.4rc2

### CODE REVIEW

**Comment by jsquyres** [comment]
Looks right to me.  @jladd-mlnx @miked-mellanox can you confirm / complete the pull request?  (and probably PR over to v1.8?)

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/57/
Test PASSed.

**Comment by rhc54** [comment]
@jsquyres This is a PR against 1.8, yes? I think you meant that the mellanox folks should also PR it into the master.

**Comment by opoplawski** [comment]
I couldn't find the mistake in devel

**Comment by jsquyres** [comment]
Oops! Yes, I didn't pay attention to notice that this is against the release branch.

Regardless, @jladd-mlnx @miked-mellanox can you still verify this patch?

**Pull request merged**
