### PR TITLE
lsf configury: add dependent libraries for static linking

### PR DESCRIPTION
**Pull request by jsquyres**
Ensure to add the LSF dependent libraries and LD flags for the wrapper compiler static linking case.

Note that we add the same flags in all cases, but opal_mca.m4 will de-duplicate the flags so that they aren't actually added to the wrapper linker flags multiple times.

(cherry picked from commit open-mpi/ompi@56cfa90ddaaf9939926ff54b5f2f34e32254681e)

This issue was brought up as a side-effect of https://github.com/open-mpi/ompi/issues/271.

@rhc54 can you review?

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/40/
Test PASSed.

**Comment by rhc54** [comment]
Question: if we had to do this for LSF, then don't we need to do it for the others (e.g., doesn't tm need to add Torque, etc.)?

**Comment by jsquyres** [comment]
@rhc54 Yes.  Are you volunteering? :-)

**Comment by rhc54** [comment]
I guess so - fwiw, we have this in 1.6. Not sure why it was removed, do you have any idea?

**Comment by jsquyres** [comment]
Err... sunspots?

I'm guessing this is fallout from when we added the libs_static field to the wrapper compiler data files.  I.e., this is a consequence that wasn't envisioned.

**Comment by rhc54** [comment]
I'm going to close this PR and replace it with the complete one

**Pull request closed without merging**
