### PR TITLE
v1.8 - port mxm configure fix from master

### PR DESCRIPTION
**Pull request by mike-dubman**

### CODE REVIEW

**Comment by jsquyres** [comment]
The trailing [] is unnecessary but harmless. 

:+1:

**Comment by jsquyres** [comment]
BTW, please also file a corresponding PR for v1.10.

**Comment by mellanox-github** [comment]
- Coverity found 1465 errors for all
- Coverity found 23 errors for oshmem
- Coverity found 7 errors for fca
- Coverity report at http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//302/Coverity_Report <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/302/
Test PASSed.

**Pull request merged**
