### PR TITLE
Topic/v2.x/opal convert jobid to string revamp

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1233/ for details.

**Comment by ggouaillardet** [comment]
:bot:assign: @rhc54 
:bot:milestone:v2.0.0
:bot:label: enhancement

**Comment by ggouaillardet** [comment]
:bot:label:enhancement

**Comment by jsquyres** [comment]
@ggouaillardet Could you give us a little more explanation of what this PR is?  Your "description" entries have been a bit sparse recently.  :smile:

**Comment by rhc54** [comment]
What we used to have was only one convert_jobid_to_string and it allocates memory to do the conversion. In most places, we don't really need memory allocated, and so @ggouaillardet created an alternative function that takes a statically allocated array and snprintf's the jobid into it. This fixed a couple of memory leaks and is obviously more efficient.

:+1:

**Comment by jsquyres** [comment]
Approved on 19 Jan 2016 weekly call.

**Pull request merged**
