### PR TITLE
Update hwloc to 1.11.2 + Fix /proc/mounts bug

### PR DESCRIPTION
**Pull request by hjelmn**
:bot:assign: @hppritcha 
:bot:label:bug
:bot:label:blocker
:bot:milestone:v2.0.0

### CODE REVIEW

**Comment by hjelmn** [comment]
@jsquyres Will also need an update to the NEWS i'm sure

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1211/ for details.

**Comment by hppritcha** [comment]
works for me :+1:

**Comment by hppritcha** [comment]
@jsquyres this is ready to merge.

**Pull request merged**
