### PR TITLE
travis: add Travis CI support to the v2.x branch

### PR DESCRIPTION
**Pull request by jsquyres**
Travis support seems to have stabilized on master.  Bring over the Travis config file so that we get Travis builds on the v2.x branch.

@ggouaillardet @hppritcha Please review.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1226/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1228/ for details.

**Comment by hppritcha** [comment]
:+1:

**Comment by ggouaillardet** [comment]
@jsquyres what about open-mpi/ompi#1234 ?
(use gcc 5 in order to build f08 bindings)

**Comment by jsquyres** [comment]
@ggouaillardet Thanks for the reminder.  Merged into master; once that Travis build succeeds on master, I'll pull it over here to this PR.

**Comment by jsquyres** [comment]
@ggouaillardet Oops -- I didn't notice the bad commit message on open-mpi/ompi#1234 before I merged.  Oh well.  I fixed it on the commit here in this PR.  Jenkins+Travis is running on this PR; will merge when it's all done.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1234/ for details.

**Pull request merged**
