### PR TITLE
General cleanup

### PR DESCRIPTION
**Pull request by rhc54**
Add missing cmd line options to mpirun man page, update NEWS to contain that change

(cherry picked from commit open-mpi/ompi@186c18be0ecbf113a3fab2cfaf1d9951bdf868dd)

Remove debug from orte-submit help output

(cherry picked from commit open-mpi/ompi@0523f604793b932d51bf4721a91dfa7fb308aaea)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/951/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/952/ for details.

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Pull request merged**
