### PR TITLE
autogen.pl: ensure to patch *all* Autotools output

### PR DESCRIPTION
**Pull request by jsquyres**
This PR applies fixes for open-mpi/ompi#751 to the v2.x branch.

@ggouaillardet @eschnett

### CODE REVIEW

**Comment by jsquyres** [comment]
PR updated to include open-mpi/ompi@67fdfdd.

**Comment by jsquyres** [comment]
@ggouaillardet Can you review this please?  Thanks!

**Comment by jsquyres** [comment]
@eschnett Also, can you try this?

**Comment by eschnett** [comment]
@jsquyres I now switched to using snapshots of the 2.x version; I tried v2.x-dev-153-gf6a57cc last. Is there a snapshot version I can try?

**Comment by ggouaillardet** [comment]
:bot:assign: @ggouaillardet

**Comment by ggouaillardet** [comment]
:+1:

**Comment by jsquyres** [comment]
@eschnett Snapshots are made nightly.  I just merged this into the v2.x branch, so it should be in tonight's snapshot.

That being said, I've had good success with [hub](https://hub.github.com/), a CLI thingy for pulling down individual pull requests (e.g., exactly for testing a pull request before it is merged).

**Pull request merged**
