### PR TITLE
check-help-strings cleanup in oshmem

### PR DESCRIPTION
**Pull request by alex-mikheev**
This commit was SVN r32490.
(cherry picked from commit 03fbd9a12db5b88e9b13e3453194b1a847e9f4e6)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Merged build triggered.

**Comment by mellanox-github** [comment]
Merged build started.

**Comment by mellanox-github** [comment]
Merged build finished. Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/6/

**Build Log**
_last 50 lines_

```
[...truncated 18149 lines...]
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test/datatype'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test/datatype'
Making install in util
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test/util'
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test/util'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test/util'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test/util'
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[1]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
+ '[' -x /usr/bin/dpkg-buildpackage ']'
+ '[' -n yes ']'
+ '[' yes = yes ']'
+ '[' -f /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/contrib/check-help-strings.pl ']'
+ echo 'Checking help strings'
Checking help strings
++ echo oshmem ompi/mca/mtl/mxm ompi/mca/coll/fca ompi/mca/coll/hcoll
+ for dir in '$(echo $help_txt_list)'
+ '[' -d oshmem ']'
+ cd oshmem
+ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/contrib/check-help-strings.pl .
Searching for source and help files...
Indexing help files (from entire source tree)...
Searching source files (under oshmem)...
Checking for stale help messages / files...
*** WARNING: Possibly unused help topic
  Help file: ./mca/sshmem/mmap/help-oshmem-sshmem-mmap.txt
  Help topic: mmap:file open failure
*** WARNING: Possibly unused help topic
  Help file: ./mca/sshmem/mmap/help-oshmem-sshmem-mmap.txt
  Help topic: mmap:file truncate failure
Total number of warnings: 2
Total number of errors: 0
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by mellanox-github** [comment]
Merged build triggered.

**Comment by mellanox-github** [comment]
Merged build started.

**Comment by mellanox-github** [comment]
Merged build finished. Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/7/

**Build Log**
_last 50 lines_

```
[...truncated 18155 lines...]
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test/util'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test/util'
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[1]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
+ '[' -x /usr/bin/dpkg-buildpackage ']'
+ '[' -n yes ']'
+ '[' yes = yes ']'
+ '[' -f /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/contrib/check-help-strings.pl ']'
+ echo 'Checking help strings'
Checking help strings
++ echo oshmem ompi/mca/mtl/mxm ompi/mca/coll/fca ompi/mca/coll/hcoll
+ for dir in '$(echo $help_txt_list)'
+ '[' -d oshmem ']'
+ cd oshmem
+ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/contrib/check-help-strings.pl .
Searching for source and help files...
Indexing help files (from entire source tree)...
Searching source files (under oshmem)...
Checking for stale help messages / files...
+++ All seems good!
+ for dir in '$(echo $help_txt_list)'
+ '[' -d ompi/mca/mtl/mxm ']'
+ cd ompi/mca/mtl/mxm
+ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/contrib/check-help-strings.pl .
Searching for source and help files...
Indexing help files (from entire source tree)...
Searching source files (under ompi/mca/mtl/mxm)...
Checking for stale help messages / files...
*** WARNING: Possibly unused help topic
  Help file: ./help-mtl-mxm.txt
  Help topic: unable to extract endpoint ptl address
Total number of warnings: 1
Total number of errors: 0
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by mellanox-github** [comment]
Merged build triggered.

**Comment by mellanox-github** [comment]
Merged build started.

**Comment by mellanox-github** [comment]
Merged build finished. Test PASSed.

**Comment by mellanox-github** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/8/
Test PASSed.

**Comment by mike-dubman** [comment]
:+1: 
looks good

**Pull request merged**
