### PR TITLE
yalla: fix valgrind error due to uninitialized status field.

### PR DESCRIPTION
**Pull request by yosefe**

### CODE REVIEW

**Comment by yosefe** [comment]
@miked-mellanox @igor-ivanov

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1039/ for details.

**Comment by rhc54** [comment]
@yosefe Does this fix also need to come to 1.10 to fix the Mellanox Jenkins runs there?

**Comment by rhc54** [comment]
@yosefe My bad - you didn't set the milestone, and so I thought you were referencing 2.0. In the future, please remember to mark the milestone so the correct RM knows to look at it

**Comment by mike-dubman** [comment]
:+1: 
Thanks @rhc54 !
@yosefe - could you please integrate it into master and v2.x as well?

**Pull request merged**
