### PR TITLE
OSHMEM: fix the makefile.

### PR DESCRIPTION
**Pull request by alinask**
(oshmem/mca/sshmem/base/Makefile.am)

(cherry picked from commit 1eb6286547780e965b8b933bd67b0c42d6969714)

Conflicts:
    oshmem/mca/sshmem/base/Makefile.am

open-mpi/ompi@1eb6286547780e965b8b933bd67b0c42d6969714

@miked-mellanox @jladd-mlnx

### CODE REVIEW

**Comment by mike-dubman** [comment]
seems some confusion here discovered by @alex-mikheev 
- The master branch contains two commits: 5602156a1 by @rhc54  and another one from c57687d8ecca5c149a8ffc6d79c83af60812d485 by @ggouaillardet 

The origin/v1.8 uses ompidata namespace
@rhc54 ,shall we integrate these two commits into v1.8 as well?

**Comment by ggouaillardet** [comment]
Regarding my commit, @rhc54 correctly backported it to v1.8:
See r32245 vs r32269 in trac

Thanks Ralph!

I am confused you can see a commit for the master via the ompi-release repository but that is an other story
/\* should the garbage collector take/have taken care of it ? */

**Comment by rhc54** [comment]
I'm not sure what you folks are talking about, but we have never transferred the renaming of the distdir targets to the v1.8 branch, nor do we intend to do so.

I have no idea why the ompi-release history is showing something different, but those commits were made strictly to the devel trunk prior to the move to github.

**Comment by rhc54** [comment]
This PR is invalid - the distdir renaming was never brought to 1.8, nor will it be.

**Pull request closed without merging**
