### PR TITLE
Fix Mlnx copyright 

### PR DESCRIPTION
**Pull request by artpol84**
with respect to commit open-mpi/ompi-release@2b5b35afb4714ea0a84537a706ed3325c3378714

### CODE REVIEW

**Comment by artpol84** [comment]
:bot:assign: @jladd-mlnx 
:bot:milestone:v2.0.0

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1327/ for details.

**Comment by hppritcha** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1335/ for details.

**Pull request merged**
