### PR TITLE
bump mpi version to 3.1

### PR DESCRIPTION
**Pull request by hjelmn**
Signed-off-by: Nathan Hjelm hjelmn@lanl.gov

:bot:assign: @hppritcha 
:bot:label:blocker
:bot:label:MPI-3.1
:bot:milestone:v2.0.0

(cherry picked from open-mpi/ompi@06dd9ec317eff1ae4411d98a9e76ec284d75d9a0)

### CODE REVIEW

**Comment by hppritcha** [comment]
:+1:

**Comment by hppritcha** [comment]
hmm, wait.  what about fortran?

**Comment by hppritcha** [comment]
looks like there's y-a-p script for fortran, no?

**Comment by hppritcha** [comment]
:-1: 
till the fortran part is added.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/867/ for details.

**Comment by jsquyres** [comment]
@hjelmn I think you need this:

``` patch
diff --git a/ompi/include/mpif-values.pl b/ompi/include/mpif-values.pl
index 4ae1814..cfd9467 100755
--- a/ompi/include/mpif-values.pl
+++ b/ompi/include/mpif-values.pl
@@ -203,7 +203,7 @@ $io_handles->{MPI_FILE_NULL} = 0;
 my $constants;

 $constants->{MPI_VERSION} = 3;
-$constants->{MPI_SUBVERSION} = 0;
+$constants->{MPI_SUBVERSION} = 1;

 $constants->{MPI_ANY_SOURCE} = -1;
 $constants->{MPI_ANY_TAG} = -1;
```

**Comment by hjelmn** [comment]
@jsquyres Did you commit that to master?

**Comment by jsquyres** [comment]
No, you did the 3.1 bump on master.  :smile: 

I can commit it now...

**Comment by hjelmn** [comment]
Should be good to go.

**Comment by hjelmn** [comment]
bot:nolabel:pushed-back

**Comment by hppritcha** [comment]
I'm happy now.
:+1:

**Comment by hppritcha** [comment]
@jsquyres this is ready.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/868/ for details.

**Pull request merged**
