### PR TITLE
Fixing MXM Yalla and MTL add procs behavior. MXM cannot support dynam…

### PR DESCRIPTION
**Pull request by jladd-mlnx**
…ic add procs, so propagate this info to the MTL and PML layers.

:cherries: -picked from ompi-mpi/ompi@4dffae2f88a15ebc3c

Patch was developed by Tommy Janjusic and signed off on by me.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1405/ for details.

**Comment by hppritcha** [comment]
@miked-mellanox could you check the jenkins run?

**Comment by mike-dubman** [comment]
bot:retest

**Comment by jsquyres** [comment]
@miked-mellanox @jladd-mlnx Please don't forget to set labels and milestones, otherwise we can easily miss these PRs when viewing the filtered lists.

**Comment by jsquyres** [comment]
@hppritcha verbally gave a :+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1407/ for details.

**Pull request merged**
