### PR TITLE
Fix the subarray and darray type creation.

### PR DESCRIPTION
**Pull request by bosilca**
open-mpi/ompi#1072

bot:milestone:v2.0
bot:label:bug
bot:assign: @ggouaillardet

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/956/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/959/ for details.

**Comment by jsquyres** [comment]
bot:milestone:v2.0.0

**Comment by jsquyres** [comment]
@ggouaillardet Can you have a look?

**Comment by ggouaillardet** [comment]
@bosilca can you update the commit message to indicate this is a cherry-pick of open-mpi/ompi@679dc9b43712cf0a0f9057c2dfb38be56054c5ca
also, what about cherry-picking open-mpi/ompi@b14212f142a3dbdf3ad6fc13e5b71cbe6593a4a8 in the same PR ?

**Comment by ggouaillardet** [comment]
fwiw, this is now tested in the ibm test suite since open-mpi/ompi-tests@e79576e3df145831db4f2718162f9383c46d28c7

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/995/ for details.

**Comment by ggouaillardet** [comment]
:+1:

**Pull request merged**
