### PR TITLE
Protect the tools from PMI environments by ensuring they use the "tool" ess component

### PR DESCRIPTION
**Pull request by rhc54**
Corresponds to open-mpi/ompi@e8387fcf88cd47f8a22b67e60baad35c1a47f47f

@jsquyres please take a quick gander

### CODE REVIEW

**Comment by mellanox-github** [comment]
- Coverity found 1472 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_234/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_234/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_234/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/234/
Test PASSed.

**Comment by jsquyres** [comment]
Yo @hjelmn -- should this commit be using mca_base_var_set_value() instead of setting the `OPAL_MCA_ess` environment variable?

**Comment by hjelmn** [comment]
@jsquyres The environment way is probably more correct here. In order to use mca_base_var_set_value() the tools will need to: register the ess framework, set the variable value, then open the ess framework.

**Comment by jsquyres** [comment]
@hjelmn Cool; thanks.

:+1:

**Pull request merged**
