### PR TITLE
Allow PMIx external support for both 1.1.4 and 2.0 versions

### PR DESCRIPTION
**Pull request by rhc54**
Stealing some pieces of Josh Hursey's PR #1583 and modifying a bit, allow the opal/pmix external component to handle both PMIx 1.1.4 and PMIx 2.0 versions. Automatically detect the version of the target external library and adjust the only two APIs that changed (PMIx_Init and PMIx_Finalize)

Rename temp vars in .m4 to avoid conflict with Travis

(cherry picked from commit open-mpi/ompi@55923eacd3ca6e6a8fb5d9b67cc776105c55061e)

### CODE REVIEW

**Comment by rhc54** [comment]
@jsquyres @hppritcha I don't know if you want this in 2.0.0 or later. It allows forward-support for PMIx versions 1.1.4 and the current state of 2.0. However, PMIx 2.0 is evolving, and so more changes to support it may be required.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1724/ for details.

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1899/ for details.

**Comment by hppritcha** [comment]
RMs decided this should go in 2.0.1 since it may be important for distro maintainers.

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1998/ for details.

**Comment by rhc54** [comment]
This PR is stale and should no longer be committed.

**Pull request closed without merging**
