### PR TITLE
If we direct that oversubscription be allowed, then default to bind-to none

### PR DESCRIPTION
**Pull request by rhc54**
Will upstream to master later

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1568/ for details.

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha This fixes some errors with the `mpi2c++_dynamics` test seen in MTT.  Can be done now or wait until v2.0.1.

**Comment by jsquyres** [comment]
bot:retest

**Comment by jsquyres** [comment]
@rhc54 This PR is showing that it can't be merged due to conflicts; I'm afraid it has become stale.  Can you have a look?

**Comment by rhc54** [comment]
Perhaps because the branch doesn't even exist any more? It's impossible to keep track of what is still pending after such long periods, and so these things tend to get deleted. I have no idea what is even relevant any more, to be honest.

**Pull request closed without merging**
