### PR TITLE
oshmem: Enable force output for error messages

### PR DESCRIPTION
**Pull request by igor-ivanov**
This change fixes issue when oshmem related error messages are not
visible for an user.

:bot:label:bug
:bot:milestone:v1.10.2

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1010/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1011/ for details.

**Comment by igor-ivanov** [comment]
see related commit in master https://github.com/open-mpi/ompi/commit/c0518c0417b532bfdd3eb1f0fe51fa46ff136aad

**Comment by mike-dubman** [comment]
:+1:

**Comment by jsquyres** [comment]
Was the valgrind error fixed by a different PR?  I.e., should this PR be rebased on top of master, once the other valgrind fix is in place?

**Comment by mike-dubman** [comment]
the valgrind fix is here https://github.com/open-mpi/ompi-release/pull/758 and https://github.com/open-mpi/ompi-release/pull/748 (two variants)

**Comment by rhc54** [comment]
I'm a little confused by this - you are opening the output channel _prior_ to calling framework open, which is where the channel is normally opened. Doesn't your call have to come _after_ the framework open?

**Comment by igor-ivanov** [comment]
@rhc54 channel is opened during atomic/memheap/scoll/sshmem/spml framework openning.
See a part of opal/mca code https://github.com/open-mpi/ompi-release/blob/v1.10/opal/mca/base/mca_base_framework.c#L154-L162

**Comment by igor-ivanov** [comment]
@rhc54 @jsquyres is there a decision for this?

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1026/ for details.

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1038/ for details.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1040/ for details.

**Pull request merged**
