### PR TITLE
topo/base: correctly support MPI_UNWEIGHTED in mca_topo_base_dist_gra…

### PR DESCRIPTION
**Pull request by ggouaillardet**
…ph_neighbors()

Thanks Jun Kudo for the bug report.

(cherry picked from commit open-mpi/ompi@8aff67c3992c3b3f5f1235877d8131f9c59ab684)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1383/ for details.

**Comment by ggouaillardet** [comment]
:bot:label:bug
:bot:assign: @bosilca 
:bot:milestone:v2.0.0

**Comment by bosilca** [comment]
:+1:

**Comment by hppritcha** [comment]
@jsquyres this is ready to go

**Pull request merged**
