### PR TITLE
oshmem/fortran: fix warning mesages (Don't megre until #1329 is merge)

### PR DESCRIPTION
**Pull request by karasevb**
Cherry-picked from https://github.com/open-mpi/ompi/pull/1883.
Don't megre until https://github.com/open-mpi/ompi-release/pull/1329 is merge.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2105/ for details.

**Comment by hppritcha** [comment]
Why are there so many commits in this PR when there was only the one going in to master?
Also, please specify a milestone. You can do this using the bot as described at
https://github.com/open-mpi/ompi/wiki/OmpiReleaseBotCommands

**Comment by hppritcha** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2107/ for details.

**Comment by karasevb** [comment]
@hppritcha this PR depend on https://github.com/open-mpi/ompi-release/pull/1041 which don't merged yet

**Comment by karasevb** [comment]
bot:milestone:v2.1.0

**Comment by jladd-mlnx** [comment]
@artpol84 Please have a look.

**Comment by artpol84** [comment]
bot:milestone:v2.1.0

**Comment by artpol84** [comment]
@hppritcha as @karasevb already mentioned this PR will not go into the repo as is. It's pending for the mentioned PR (https://github.com/open-mpi/ompi-release/pull/1329) to be merged. Once it is merged we will rebase this PR against the trunk and there will be only one commit in this PR.

**Comment by artpol84** [comment]
bot:label:WIP-DNM

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2128/ for details.

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2168/ for details.

**Comment by jsquyres** [comment]
@karasevb @artpol84 Getting a compile failure in in SPML UCX.

**Comment by artpol84** [comment]
@jsquyres this is expected:

we depend on #1329 which depends on #1041 which in turn depends on #913. Won't get compiled untill those 3 are in.

**Comment by jsquyres** [comment]
@artpol84 Ok

**Comment by jsquyres** [comment]
The `ompi-release` repo is now closed; all release branches have been moved to the `ompi` repo (https://github.com/open-mpi/ompi).  Please re-open this PR on the corresponding branch on the `ompi` repo.

**Comment by artpol84** [comment]
Ported to ompi (open-mpi/ompi#2128)
please, close this one to avoid confusion.

**Pull request closed without merging**
