### PR TITLE
Fix: align OSHMEM API with spec v1.2

### PR DESCRIPTION
**Pull request by igor-ivanov**
This PR adapt OSHMEM API to v1.2 specification. 
It keeps backward compatibility with prevoius spec. hello_oshmem and ring_oshmem are changed according spec v1.2 as more popular while other oshmem examples are kept as is with warning pragma saying about deprecated api.

Port related PR
open-mpi/ompi#1149
open-mpi/ompi-release#787

:bot:label:bug
:bot:label:enhancement
:bot:milestone:v1.10.3
:bot:assign: @rhc54

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1073/ for details.

**Comment by jsquyres** [comment]
@igor-ivanov What effect does this PR have on the OSHMEM ABI for the v1.10 series?

**Comment by igor-ivanov** [comment]
@jsquyres I do not see any issue with ABI.

**Comment by jsquyres** [comment]
@igor-ivanov It looks like some functions have been deleted from pshmem.h and shmem.h.in...?  I didn't look closely, but the *x.h files changed a bunch, too -- are those net-zero changes, or are user-visible symbols disappearing?

**Comment by igor-ivanov** [comment]
@jsquyres all user previous visible sympols should stay (may be you see that some functions moved between shmem.h and shmemx.h). Let me know if you noticed absence of some symbols.

**Comment by jsquyres** [comment]
@igor-ivanov Ah!  Symbols like `_num_pes()` moved to the `*x.h` files.  Got it!

What about symbols like `pshmem_int6_p()`?  It looks like that moved from a symbol to a #define -- isn't that a problem for existing binaries?  (because that symbol will not exist in new versions of liboshmem)

**Comment by igor-ivanov** [comment]
@jsquyres yes, you are right.
We have symbols for shmem extension api as shmem_ (pshmem_) in v1.10.2 and will get shmemx_ (pshmemx_) in v1.10.3 but having related #define that translate shmem_ to shmemx_ in header file does not help to meet abi requirements.
So, it seems I need to extend this PR, right?

**Comment by jsquyres** [comment]
@igor-ivanov Yeah, I think so -- sorry! :-(  ABI needs to be preserved on the v1.10.x branch...  It's a major pain sometimes.  :frowning:

**Comment by igor-ivanov** [comment]
@jsquyres I have updated PR with special commit fixing ABI issue. I wish I had a possibility to use gcc weak aliasing (as void f () **attribute** ((weak, alias ("__f")));) :frowning:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1086/ for details.

**Comment by mike-dubman** [comment]
:+1:

**Pull request merged**
