### PR TITLE
ft-removal: remove remaining cr/ft components

### PR DESCRIPTION
**Pull request by hppritcha**
remove crcp, compress components, etc.
remove opal_cr.[c,h]
remove OPAL_ENABLE_FT_XXX
remove cr sections of README
remove cr/ft related configury components

Fixes open-mpi/ompi#668

@jsquyres here it is, the gigantic purge

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/920/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/923/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/924/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/926/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/941/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/967/ for details.

**Comment by hppritcha** [comment]
@jsquyres rebased

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1070/ for details.

**Comment by jsquyres** [comment]
@hppritcha Can you look at that Mellanox Jenkins failure?  I don't have the ability to test irkrit -- it may be a real error due to this PR.

**Comment by hppritcha** [comment]
yep its the usual mystery include file tree problem.
I'll push another commit to hopefully fix it.

**Comment by hppritcha** [comment]
@jsquyres I can actually build ikrit now on one of our mlnx systems now that mxm is installed right.  if the jenkins smoke tests pass, this should be ready to go.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1081/ for details.

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
