### PR TITLE
Check for the presence of setenv. If it is present, then use it in opal_...

### PR DESCRIPTION
**Pull request by rhc54**
...setenv when setting values in the environ

Port of open-mpi/ompi@907b4606c537e2b758921a90ed2037337ca6e6cd

@jsquyres please review

### CODE REVIEW

**Comment by jsquyres** [comment]
I thought we agreed not to use setenv() because of the portability concerns?  I.e., even if the symbol is present, it isn't guaranteed to have the same signature and/or behavior...?

From the call today, I thought the plan was just going to put a loop at https://github.com/open-mpi/ompi/blob/master/opal/util/opal_environ.c#L130 very similar to the loop at https://github.com/open-mpi/ompi/blob/master/opal/util/opal_environ.c#L150-L163.

**Comment by rhc54** [comment]
I don't see the issue - from what I can tell, the problem is only one of finding the function present or not. So if it is present, then you can use it.

I'm leery of free'ing and replacing memory in the actual environ - lots of posts out there warning against taking such actions outside of using the system functions. I think this is a much safer approach.

**Comment by jsquyres** [comment]
@rhc54 agree -- we don't want to change the memory in environ.  What I meant was that we should have a similar loop looking for a duplicate, and if overwrite=1 or (overwrite==0 and it's not found), then we putenv.

**Comment by jsquyres** [comment]
Ralph and I talked about this a bit in IM last night, but ran out of time. We'll figure out the Right thing to do sometime today...

**Comment by mike-dubman** [comment]
Merged build triggered.

**Comment by mike-dubman** [comment]
Merged build started.

**Comment by mike-dubman** [comment]
Merged build finished. Test PASSed.

**Comment by rhc54** [comment]
Updated:
 Pull over two cleanups from the master:

open-mpi/ompi@2c9987b
open-mpi/ompi@4e4920a

**Comment by mellanox-github** [comment]
Merged build triggered.

**Comment by mellanox-github** [comment]
Merged build started.

**Comment by mellanox-github** [comment]
Merged build finished. Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/9/

**Build Log**
_last 50 lines_

```
[...truncated 18156 lines...]
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test/util'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test/util'
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[3]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/test'
make[1]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
make[2]: Entering directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
make[1]: Leaving directory `/scrap/jenkins/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace'
+ '[' -x /usr/bin/dpkg-buildpackage ']'
+ '[' -n yes ']'
+ '[' yes = yes ']'
+ '[' -f /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/contrib/check-help-strings.pl ']'
+ echo 'Checking help strings'
Checking help strings
++ echo oshmem ompi/mca/mtl/mxm ompi/mca/coll/fca ompi/mca/coll/hcoll
+ for dir in '$(echo $help_txt_list)'
+ '[' -d oshmem ']'
+ cd oshmem
+ /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/contrib/check-help-strings.pl .
Searching for source and help files...
Indexing help files (from entire source tree)...
Searching source files (under oshmem)...
*** ERROR: Source-referenced help file does not exist
  Source file: ./mca/spml/ikrit/spml_ikrit.c
  Help file referenced: help-spml-ikrit.txt
*** ERROR: Source-referenced help file does not exist
  Source file: ./mca/spml/base/spml_base_select.c
  Help file referenced: help-shmem-mca.txt
Checking for stale help messages / files...
*** WARNING: Possibly unused help topic
  Help file: ./mca/sshmem/mmap/help-oshmem-sshmem-mmap.txt
  Help topic: mmap:file open failure
*** WARNING: Possibly unused help topic
  Help file: ./mca/sshmem/mmap/help-oshmem-sshmem-mmap.txt
  Help topic: mmap:file truncate failure
Total number of warnings: 2
Total number of errors: 2
Build step 'Execute shell' marked build as failure
[BFA] Scanning build for known causes...

[BFA] Done. 0s
```

Test FAILed.

**Comment by jsquyres** [comment]
I assume those help strings in the test failure will actually be fixed by #77.

**Pull request merged**
