### PR TITLE
libompitrace: Use VERSION file to set .so version

### PR DESCRIPTION
**Pull request by jjhursey**
(cherry picked from commit open-mpi/ompi@b8dfd9a92bc725ed35accb22adf9cb15f1187652)

bot:assign: @jsquyres 
bot:label:Code-cleanup-low-priority
bot:milestone:v2.0.2

### CODE REVIEW

**Comment by jjhursey** [comment]
Ref https://github.com/open-mpi/ompi/issues/1906

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/7f110ab6c94da788f0fed01d83c12215

**Comment by jsquyres** [comment]
👍

**Comment by jsquyres** [comment]
@hppritcha Good to go

**Comment by jjhursey** [comment]
The **IBM-CI (XL Compiler)** test failed due to an internal Jenkins failure (connection issue). I would not worry about it.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2177/ for details.

**Pull request merged**
