### PR TITLE
v2.0.0 examples: fix check for Fortran "use mpi" bindings

### PR DESCRIPTION
**Pull request by jsquyres**
The output from "ompi_info --parsable" for the Fortran "use mpi"
bindings apparently has changed over time.  It is now:

```
   "yes (full: ignore TKR)"
or "yes (limited: overloading)"
```

(including the quotes)

So update the test in examples/Makefile to also look for the quote.

(cherry picked from commit open-mpi/ompi@20fade1345620ba62ee875e277d82446938a3b38)

@ggouaillardet please review

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@jsquyres that is correct for master and v2.x
v1.10 does not double quote the values.
fwiw, i did a similar thing in mtt, and i used a regex to support all ompi versions

with grep

```
ompi_info --all --parseable | grep 'bindings:use_mpi:"\?yes'
```

or with egrep

```
ompi_info --all --parseable | egrep 'bindings:use_mpi:"?yes'
```

(i have no clue why i need to backquote the interrogation mark with grep and not egrep)

so one option is to merge this PR and close #994,
and an other option is to update both with (e)regexp

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1379/ for details.

**Comment by jsquyres** [comment]
@ggouaillardet This PR now includes open-mpi/ompi@677a31b

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1388/ for details.

**Comment by jsquyres** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1385/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1389/ for details.

**Comment by ggouaillardet** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha Good to go.

**Pull request merged**
