### PR TITLE
Only issue the event loop reentrant warning in debug builds

### PR DESCRIPTION
**Pull request by rhc54**
users have no idea what it means

@jsquyres please comment/review

### CODE REVIEW

**Comment by mellanox-github** [comment]
- Coverity found 1472 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_224/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_224/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_224/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/224/
Test PASSed.

**Comment by rhc54** [comment]
@jsquyres any chance you can glance at this? it's a really tiny change

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
