### PR TITLE
Add a workaroud for issue in libcuda.so library

### PR DESCRIPTION
**Pull request by rolfv**
(cherry picked from commit open-mpi/ompi@7703c964960226b4010bb55b7d998ec1160bd63a)

Marking @bureddy as reviewer as he reviewed for the master as well.

This is workaround for determining if pointer is host or GPU.

### CODE REVIEW

**Comment by rolfv** [comment]
bot:milestone:v2.0.0
bot:assign: @bureddy 
but:label:bug

**Comment by rolfv** [comment]
bot:assign: @bureddy

**Comment by jsquyres** [comment]
@bureddy I believe you need to follow the instructions here: https://github.com/open-mpi/ompi/wiki/OmpiReleaseBotCommands#one-time-setup

**Comment by bureddy** [comment]
@rolfv :+1:

**Pull request merged**
