### PR TITLE
Fix the application abort routine so we actually abort

### PR DESCRIPTION
**Pull request by jladd-mlnx**
Adding @bureddy 's solution for OSHMEM's global exit when applications are launched directly with srun.

I don't think this is the final solution, but I don't want this to get lost in the shuffle. @jsquyres @miked-mellanox @rhc54 

CMR Trac ticket:
https://svn.open-mpi.org/trac/ompi/ticket/4919

### CODE REVIEW

**Comment by bureddy** [comment]
commit in ompi:master:   open-mpi/ompi@cbb3e95ce9d4089e2436e27775c05e957af8fcf9
commit in ompi master:   open-mpi/ompi@8dfed1c657e6a7471f18cee7eb3cc6676e429a6c

**Comment by jsquyres** [comment]
@alex-mikheev  What does 8c567fc have to do with ensuring that abort actually aborts?

**Comment by alex-mikheev** [comment]
@jsquyres nothing actually. i have no idea why https://github.com/open-mpi/ompi-release/commit/8c567fc6fe1e3b8a66d21e4c42416fa3850fa97f is here

**Comment by jsquyres** [comment]
It probably got added to your topic branch by accident.

You might be able to remove it by "git reset --hard ..." to revert the HEAD to the commit before that one...?

If all else fails, you can kill the topic branch and re-create it with just the single / desired commit.

**Comment by alex-mikheev** [comment]
ughh it looks like my commit got into @jladd-mlnx  and @bureddy pull request

**Comment by jsquyres** [comment]
Yeah, looks like we all have a bit of a learning curve here with github/pull requests, etc...

**Comment by rhc54** [comment]
I need the extraneous patch removed so I can apply this PR. Thanks

**Comment by jladd-mlnx** [comment]
@alex-mikheev Please remove your errant commit into our topic branch/PR.

**Comment by alex-mikheev** [comment]
@jladd-mlnx the commit comes from your own fork of  https://github.com/open-mpi/ompi-release. I can not remove it from there.

Originally ca2e3ab0a4b1bf8f571281133d257fb2cd667d9f was added to the open-mpi/ompi-release:v1.8 by @miked-mellanox  PR https://github.com/open-mpi/ompi-release/pull/8

**Comment by jsquyres** [comment]
@jladd-mlnx @alex-mikheev Suggestion for future PR's: make topic branches that are specific to a given PR; don't use the main "v1.8" branch in your clone for a PR.  I.e., leave the main "v1.8" branch as pristine/identical to the upstream v1.8 branch.

**Comment by jladd-mlnx** [comment]
I think I am going to try this again. Closing this pull request.

**Pull request closed without merging**
