### PR TITLE
Topic/opal pretty output

### PR DESCRIPTION
**Pull request by hppritcha**
Merge of open-mpi/ompi#1515 open-mpi/ompi#1516 and open-mpi/ompi#1518 in to v2.x

@kmroz  please double check

### CODE REVIEW

**Comment by hppritcha** [comment]
The consensus was to merge this in to 2.0.0.  If it can't make it in to 2.0.0 then it needs to wait till the 3.x release stream.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1505/ for details.

**Comment by jsquyres** [comment]
@hppritcha Is this materially different than #1057?

**Comment by hppritcha** [comment]
no I had forgotten there was already a PR for this.

**Comment by ghost** [comment]
OK cool! I see you've closed this one out, but if you do decide to move forward with this PR, the only pieces missing would be:

opal_info_support: fix memory leak - https://github.com/open-mpi/ompi-release/pull/1057/commits/3b7864ae458dd9ec1b7731ef27974845e2b4a125
opal_info_support: refactor component output separation - https://github.com/open-mpi/ompi-release/pull/1057/commits/55edfa34ac92b2200fc5f1bb28d0c6d2eca175ef

They're included in https://github.com/open-mpi/ompi-release/pull/1057

**Pull request closed without merging**
