### PR TITLE
contrib: added the check-help-strings.pl file.

### PR DESCRIPTION
**Pull request by alinask**
(from master - commits: 98ef295c, 7a3adcf0, c59ca9c7, 82b49c2b)

@miked-mellanox @jladd-mlnx

### CODE REVIEW

**Comment by rhc54** [comment]
I fail to see a reason why this file needs to go into the production release tarball - we have it in the developer's trunk, which would seem adequate. Am I missing something? It certainly isn't a "bug"!

**Comment by mike-dubman** [comment]
@rhc54 ,
- we run this script as part of the jenkins routine for every commit/pr pushed to the any branch.
- w/o this fix, scripts fails and failing the jenkins.
- We can add extra logic to the jenkins script to bypass branches with old script interface but it does not seem right and complicates jenkins logic.

@jsquyres, @rhc54 - maybe all "support" scripts should be pushed to separate repo and it will be less hassle to support branches, no need to sync scripts from master to vX.Y on every script change?

Thanks

**Comment by jsquyres** [comment]
@rhc54 FWIW, I don't see a problem including this script on the v1.8 branch.

@miked-mellanox I'm still not convinced that a separate script repo is a good idea.  In some cases, there are definitely differences between the different release series for the various scripts.  I think there's pluses and minuses for both options (i.e., having the scripts in each branch and having one central set of scripts).  Meaning: I don't think there's necessarily more plusses to having them in a single/central repo.

**Comment by rhc54** [comment]
Here's another thought - I would have accepted it if someone had simply provided even a tiny bit of rationale behind the PR instead of just "add this because I said so". This is a _stable_ release branch, so there has to be _some_ justification for adding something - if you can't provide a reasonable explanation, then you should expect it to be rejected.

**Comment by mike-dubman** [comment]
@rhc54 - sorry about that, next PR will be better equipped.

**Pull request merged**
