### PR TITLE
Bring ltdl changes into CUDA support code

### PR DESCRIPTION
**Pull request by rolfv**

### CODE REVIEW

**Comment by mellanox-github** [comment]
- Coverity found 1473 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_200/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_200/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_200/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/200/

**Build Log**
_last 50 lines_

```
[...truncated 135179 lines...]
Process 3 exiting
Process 5 exiting
+ '[' -n '' ']'
+ for hca_dev in '$(ibstat -l)'
+ '[' -f /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_circular_shift ']'
+ local hca=mlx5_0:1
+ mca='--bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M'
+ mca='--bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca btl_openib_if_include mlx5_0:1 -x MXM_RDMA_PORTS=mlx5_0:1'
+ mca='--bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca btl_openib_if_include mlx5_0:1 -x MXM_RDMA_PORTS=mlx5_0:1 --mca rmaps_base_dist_hca mlx5_0:1 --mca sshmem_verbs_hca_name mlx5_0:1'
+ echo 'Running /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_circular_shift '
Running /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_circular_shift 
+ timeout -s SIGKILL 10m oshrun -np 8 --bind-to core -x SHMEM_SYMMETRIC_HEAP_SIZE=1024M --mca btl_openib_if_include mlx5_0:1 -x MXM_RDMA_PORTS=mlx5_0:1 --mca rmaps_base_dist_hca mlx5_0:1 --mca sshmem_verbs_hca_name mlx5_0:1 --mca spml yoda -mca pml ob1 -mca btl self,openib /var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/workspace/ompi_install1/examples/oshmem_circular_shift
--------------------------------------------------------------------------
Open MPI was unable to obtain the username in order to create a path
for its required temporary directories.  This type of error is usually
caused by a transient failure of network-based authentication services
(e.g., LDAP or NIS failure due to network congestion), but can also be
an indication of system misconfiguration.

Please consult your system administrator about these issues and try
again.
--------------------------------------------------------------------------
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
[jenkins01:31102] 5 more processes have sent help message help-orte-runtime.txt / orte:session:dir:nopwname
[jenkins01:31102] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
Build step 'Execute shell' marked build as failure
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: **/*.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/200/tap-master-files/cov_stat.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/gh-ompi-release-v1.8-pr/builds/200/tap-master-files/cov_stat.tap].
not ok - coverity detected 1473 failures in all_200 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_200/output/errors/index.html
not ok - coverity detected 23 failures in oshmem_200 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_200/output/errors/index.html
ok - coverity found no issues for mxm_200
not ok - coverity detected 7 failures in fca_200 # SKIP http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_200/output/errors/index.html
ok - coverity found no issues for hcoll_200

TAP Reports Processing: FINISH
coverity_for_all    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_200/output/errors/index.html
coverity_for_oshmem http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_200/output/errors/index.html
coverity_for_fca    http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_200/output/errors/index.html
Setting commit status on GitHub for https://api.github.com/repos/open-mpi/ompi-release/commit/eac4fbac3755a639cda82a886feaa71dc55c54c2
[BFA] Scanning build for known causes...

[BFA] Done. 0s
Setting status of f83e076e9072c295838efddf80519b2ea6a5c6e7 to FAILURE with url http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr/200/ and message: Merged build finished.
```

Test FAILed.

**Comment by rhc54** [comment]
bot;retest

**Comment by rhc54** [comment]
@miked-mellanox I can't see how this change would cause an overload of the LDAP server. Is something wrong with the Jenkins system?

**Comment by mike-dubman** [comment]
@rhc54 - checking.

**Comment by mike-dubman** [comment]
NIS seems fine, see no ypbind related errors in the /var/log/message
do you know what network/pw service call failed in OMPI to print it?

**Comment by rhc54** [comment]
It would have to be getpwuid

**Comment by mike-dubman** [comment]
seems it is a known issue in glibc 2.12.132 (jenkins) and fixed in 2.12.147

https://bugzilla.redhat.com/show_bug.cgi?id=706903
706903 - getpwuid unreliable when using NIS with many netgroups.

**Comment by mike-dubman** [comment]
could getpwuid be replaced with something reliable and "local operation"?
this is a stock rhel 6.5 and 6.6 has same old glibc version.
what do you think?

**Comment by rhc54** [comment]
We did it on the master, but have not brought it across. I can look at it,
but would not want to block this change just for that. I'm also concerned
because Rolf's change shouldn't have flagged the issue anyway - it has
nothing to do with it.

**Comment by mike-dubman** [comment]
started nscd on jenkins node, maybe it will help.

**Comment by mike-dubman** [comment]
bot:retest

**Comment by mellanox-github** [comment]
- Coverity found 1472 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_203/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_203/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_203/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/203/
Test PASSed.

**Comment by rhc54** [comment]
This fixes breakage from another CMR

**Pull request merged**
