### PR TITLE
Topic/v2.x/autogen force

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1083/ for details.

**Comment by ggouaillardet** [comment]
:bot:assign: @jsquyres 
:bot:milestone:v2.0.0
:bot:label:enhancement

**Comment by jsquyres** [comment]
:+1:

**Comment by jsquyres** [comment]
@hppritcha I think this is good to go.

**Pull request merged**
