### PR TITLE
v2.0.1 release stuff

### PR DESCRIPTION
**Pull request by jsquyres**
- Update VERSION
- Update AUTHORS / .mailmap to match master (i.e., the `make-authors.pl` script was brought over from master and run on the v2.x branch to generate `AUTHORS` specific to the v2.x branch so far).

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by jsquyres** [comment]
Looks like LANL <--> Github.com communication problems on those failures.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2108/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Pull request merged**
