### PR TITLE
v2.x: oshmem: Align OSHMEM API with spec v1.3 (nonblocking put/get) (this PR depends on #913)

### PR DESCRIPTION
**Pull request by igor-ivanov**
trunk: https://github.com/open-mpi/ompi/pull/1455

:bot:assign: @hppritcha
:bot:label:enhancement
:bot:milestone:v2.0.0

related commits:
open-mpi/ompi@8464b61
open-mpi/ompi@abe7ba57206e3257dddf848248054007d601b59f
open-mpi/ompi@70139147ab9a96c45998b39da5324333bffcaca1
open-mpi/ompi@e59bf31d6bb93f54170b2991b3603576be1aaff3
open-mpi/ompi@e0d87225eb7b0388105b723e560f173014ae17fe
open-mpi/ompi@450ea6684c9369153d8f71580eb0e929ceb89fc7
open-mpi/ompi@b2700320a3558daff2cc7c588c63e0717149d1da
open-mpi/ompi@36c29b393b3c9fee0266b17054cb74680297e9a5

### CODE REVIEW

**Comment by igor-ivanov** [comment]
:bot:label:enhancement

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1463/ for details.

**Comment by igor-ivanov** [comment]
@miked-mellanox @alex-mikheev  it seems that v2.x(spml/ucx) does not have https://github.com/open-mpi/ompi/commit/f627608e4 when trunk and v1.10 does.
Do you see any issue with this commit in v2.x?

**Comment by mike-dubman** [comment]
@igor-ivanov - could you please pr it into v2.x
thanks

**Comment by igor-ivanov** [comment]
@miked-mellanox I found related PR(v2.x) as https://github.com/open-mpi/ompi-release/pull/913
in waiting state.
@hppritcha @jsquyres can we apply https://github.com/open-mpi/ompi-release/pull/913

**Comment by igor-ivanov** [comment]
:bot:milestone:v2.1.0

**Comment by hppritcha** [comment]
@igor-ivanov since we don't currently have a separate 2.1.0 branch, we aren't merging in PR's with milestone 2.1.0 till after 2.0.0 is released.

**Comment by igor-ivanov** [comment]
@hppritcha it is ok, just this one should be on top of https://github.com/open-mpi/ompi-release/pull/913

**Comment by hppritcha** [comment]
I'm confused about what's going on with respect to shmem.h.in with this PR and PR 1042.

In particular,  whats going on with
https://github.com/open-mpi/ompi-release/pull/1042/commits/7a53bad2820cac5e554c1770fa7864e5c6879a99
and
https://github.com/open-mpi/ompi-release/pull/1041/commits/939eaada852d7ef7f8aceadef784c68069e2e0c3

?
:-1:

until this is clarified.

**Comment by hppritcha** [comment]
bot:retest

**Comment by hppritcha** [comment]
Can someone fix UCX so MLNX jenkins passes?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1468/ for details.

**Comment by igor-ivanov** [comment]
@hppritcha i see issue with shmem.h.in thanks. (Fixed)
ucx failure relates https://github.com/open-mpi/ompi-release/pull/913 (this PR depens on one )

**Comment by igor-ivanov** [comment]
@hppritcha just to double check. Fix for issue in shmem.h.in was provided (see comment above https://github.com/open-mpi/ompi-release/pull/1041#issuecomment-200418765). Do you see another issue?

**Comment by ggouaillardet** [comment]
:bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1648/ for details.

**Comment by artpol84** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2062/ for details.

**Comment by artpol84** [comment]
@igor-ivanov looks like a compiler issue. Can you please check?

**Comment by artpol84** [comment]
@igor-ivanov did you had a chance to investigate?

**Comment by igor-ivanov** [comment]
@artpol84 I have not looked at this

**Comment by igor-ivanov** [comment]
@artpol84 This PR depends on https://github.com/open-mpi/ompi-release/pull/913

See: https://github.com/open-mpi/ompi-release/pull/1041#issuecomment-199816762

**Comment by artpol84** [comment]
thank you.
I would suggest to rebase on top of that branch then as we've done with https://github.com/open-mpi/ompi-release/pull/1329

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2130/ for details.

**Comment by jsquyres** [comment]
bot:mellanox:retest

**Comment by hppritcha** [comment]
removing pushback but needs to go in after #913

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2170/ for details.

**Comment by jsquyres** [comment]
@artpol84 @igor-ivanov @jladd-mlnx We just merged #913, and this one -- which is apparently the next one in the OSHMEM v2.1.0 sequence -- now apparently has a conflict.  Can you have a look?  Thanks.

**Comment by artpol84** [comment]
Sure, will do.

**Comment by artpol84** [comment]
@igor-ivanov please, rebase.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2187/ for details.

**Comment by jsquyres** [comment]
The `ompi-release` repo is now closed; all release branches have been moved to the `ompi` repo (https://github.com/open-mpi/ompi).  Please re-open this PR on the corresponding branch on the `ompi` repo.

**Comment by artpol84** [comment]
Was backed up by open-mpi/ompi#2095, please close it to avoid confusion.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2190/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2191/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2192/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2193/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2194/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2195/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2196/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2197/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2198/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2199/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2200/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2201/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2202/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2203/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2204/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2205/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2206/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2207/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2208/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2209/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2210/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2211/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2212/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2213/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2214/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2215/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2216/ for details.

**Pull request closed without merging**
