### PR TITLE
Somehow, the logic for finalize got lost, so restore it here.

### PR DESCRIPTION
**Pull request by rhc54**
If pmix.fence_nb is available, then call it and cycle opal_progress until complete. If pmix.fence_nb is not available, then do an MPI_Barrier and call pmix.fence.

Needs to go over to 2.x

(cherry picked from commit open-mpi/ompi@737311166281589de642dbcaa19ac8d4afca3caa)

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1550/ for details.

**Comment by bosilca** [comment]
👍 Thanks Ralph for the quick fix.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1553/ for details.

**Comment by rhc54** [comment]
The Mellanox failure is unrelated to this PR - has something to do with a missing asm file?

**Comment by jsquyres** [comment]
@rhc54 @di0gen We've seen this type of failure from Mellanox Jenkins before: it complains that the `depcomp` script doesn't exist.  I don't know why this happens -- a bot:retest to make it go again usually works.

bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1557/ for details.

**Comment by hppritcha** [comment]
well this commit causes aprun launched jobs to hang in `MPI_Finalize` for a simple hello world program.

**Comment by rhc54** [comment]
Is it hanging in the MPI_Barrier? Or in the pmix.fence?

**Pull request merged**
