### PR TITLE
moved code to job setup first before enabling comm

### PR DESCRIPTION
**Pull request by rhc54**
(cherry picked from commit open-mpi/ompi@43f44f31c16a1153327e614abe7a070c076113ba)

### CODE REVIEW

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1194/ for details.

**Comment by lanl-ompi** [comment]
Test FAILed.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1196/ for details.

**Pull request merged**
