### PR TITLE
Revert "coll/hcoll mpi datatypes support"

### PR DESCRIPTION
**Pull request by hppritcha**
Reverts open-mpi/ompi-release#1313

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/2082/ for details.

**Comment by ibm-ompi** [comment]
Build Failed with GNU compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/514bb6fe123a40de30f56e64a600d85b

**Comment by ibm-ompi** [comment]
Build Failed with XL compiler! Please review the log, and get in touch if you have questions.

 Gist: https://gist.github.com/ibm-ompi/7f110ab6c94da788f0fed01d83c12215

**Comment by jjhursey** [comment]
IBM Jenkins failures due to picking up the PR after it was merged. So there was nothing to test. I don't know how to prevent Jenkins from identifying these as failures.

**Comment by rhc54** [comment]
@jjhursey I wouldn't worry about it - the log is dropped anyway when the PR is closed, so it really doesn't matter.

**Pull request merged**
