### PR TITLE
Topic/pml ob1 fixes

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
fix memory leak discussed at http://www.open-mpi.org/community/lists/devel/2015/07/17590.php

:bot:milestone:v1.8.6
:bot:assign: @hjelmn
:bot:label:blocker

**Comment by ggouaillardet** [comment]
:bot:milestone:v1.8.7

**Comment by hjelmn** [comment]
oh snap. guess it is not a potential leak.

:+1:

**Comment by rhc54** [comment]
@hjelmn what about the #if'd out code? Does that need to be included, should it be removed, ...?

**Comment by hjelmn** [comment]
@rhc54 yeah. i would take the entire pr as is to be safe.

**Comment by rhc54** [comment]
@hjelmn okay - thanks!

**Comment by hjelmn** [comment]
np. wish i had caught this before 1.8.6.

**Comment by rolfv** [comment]
Just retested the latest v1.8 with LAMMPS and I do not see the leak anymore.  Thanks.

**Pull request merged**
