### PR TITLE
fixes for the plfs file system

### PR DESCRIPTION
**Pull request by edgargabriel**
@hppritcha do you have somewhere access to a plfs installation? If not, let me know and I can set up something for you to test. Otherwise not sure how to review this pr, since without plfs it will not even compile the parts that were modifiied.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1208/ for details.

**Comment by hppritcha** [comment]
I am not currently set up for plus testing. Maybe we should at least install headers etc on uh Jenkins node.  I'm travel this week.  I will investigate next week.

**Comment by edgargabriel** [comment]
ok, lets discuss that next week. I could install the software necessary for plfs, pvfs2, lustre etc. and we could have at least a compile time test that runs regularly.

**Comment by edgargabriel** [comment]
@hppritcha I added a PLFS installation directory on ompi.cs.uh.edu, it is in /opt/PLFS. In theory, OpenMPI could now be configured with --with-plfs=/opt/PLFS and the component should at least compile correctly.

**Comment by hppritcha** [comment]
@edgargabriel I'm asking the a couple of the people in my group here at LANL - this is something from LANL originally - about where I can actually test plfs fs.  What caused you to want to fix plfs in ompiio?  Was there a user reported problem?

**Comment by edgargabriel** [comment]
yes, a user complained that ompio would not compile if plfs was 
detected. This fixes the compilation problem in that scenario.

**Comment by hppritcha** [comment]
works for me.  There don't appear to be any PLFS file systems available here at LANL - the home of PLFS, so I'm assuming that just a compile is good enough.

:+1:

**Comment by hppritcha** [comment]
@jsquyres ready to go

**Pull request merged**
