### PR TITLE
Topic/v1.10/pthread atfork

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign: @jsquyres 
:bot:label:blocker
:bot:milestone:v1.10.3

one commit was missing in open-mpi/ompi-release#1188

sorry @rhc54 it seems there will be a v1.10.3rc4 after all ...

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1708/ for details.

**Comment by PHHargrove** [comment]
@ggouaillardet 
I have tested this PR on the system showing the [reported failure](https://www.open-mpi.org/community/lists/devel/2016/05/19027.php)
Looks like this fixes it :+1:

The configure probe once again detects that Fortran needs `-pthread`.

**Comment by ggouaillardet** [comment]
Thanks @PHHargrove !

**Comment by jsquyres** [comment]
@ggouaillardet I think you need to rebase -- @rhc54 and I got this fix in to v1.10 last night: https://github.com/open-mpi/ompi-release/pull/1188

**Comment by ggouaillardet** [comment]
@jsquyres i do not understand ...
#1188 fixes C, this PR fixes Fortran
I will be afk until tomorrow ...

**Comment by jsquyres** [comment]
Ah!  I see -- I missed that this was updating a different section of the .m4.  Got it -- thanks!

(in my testing last night, I neglected to test Fortran -- that's why we missed this 😱 )

**Pull request merged**
