### PR TITLE
configury: fix git describe with VPATH

### PR DESCRIPTION
**Pull request by ggouaillardet**
(cherry picked from commit open-mpi/ompi@30cde041391b48dded41f48025d7f4c25174caa5)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
@jsquyres could you please review this ?

also, should repo_rev and tarball_version in the VERSION file match the values of the master ?

``` patch
diff --git a/VERSION b/VERSION
index f05d986..82fb8c0 100644
--- a/VERSION
+++ b/VERSION
@@ -31,7 +31,7 @@ greek=a1
 # command, or with the date (if "git describe" fails) in the form of
 # "date<date>".

-repo_rev=gitclone
+repo_rev=

 # If tarball_version is not empty, it is used as the version string in
 # the tarball filename, regardless of all other versions listed in
@@ -41,7 +41,7 @@ repo_rev=gitclone
 # tarball_version is not empty, the tarball filename will be of the
 # form openmpi-<tarball_version>.tar.*.

-tarball_version=
+tarball_version=gitclone

 # The date when this release was created

```

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/99/
Test PASSed.

**Comment by jsquyres** [comment]
Patch looks ok to me.

And yes, the VERSION on the v1.8 branch should say "gitclone".  I'll commit that separately.

**Comment by jsquyres** [comment]
Fixed VERSION in 64f373bbb29b97524cb0c453b5fee5d77fc08b5b.

**Pull request merged**
