### PR TITLE
mtl/ofi: Make sure the resources are managed by the provider.

### PR DESCRIPTION
**Pull request by yburette**
Merged from master

bot:milestone:v1.10.2
bot:label:bug

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1033/ for details.

**Comment by yburette** [comment]
@rhc54 @jsquyres @miked-mellanox 
I looked at the console output. The build seems to be successful but there is a memory check error in oshmem.
Sorry guys, I'm not sure what this has to do with my fix to OFI MTL. Any idea?

**Comment by igor-ivanov** [comment]
@yburette valgrind issue you obsreved in jenkins is common for all last PRs and probably relates pml/yalla. We are looking for a fix.

**Comment by yburette** [comment]
@igor-ivanov OK, I'm glad I wasn't doing anything wrong. Thank you :-)

**Pull request merged**
