### PR TITLE
btl/vader: fix typo in mca_btl_vader_put_knem

### PR DESCRIPTION
**Pull request by hjelmn**
Backported from open-mpi/ompi@b0881757058c94836fc5938a4398da013b6effcd

### CODE REVIEW

**Comment by hjelmn** [comment]
@ggouaillardet please review

**Comment by jsquyres** [comment]
This was initially submitted by @ggouaillardet and reviewed by @hjelmn.  I think it's safe to say it's reviewed already.

**Comment by ggouaillardet** [comment]
+1 :-)

**Comment by mellanox-github** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/24/
Test PASSed.

**Pull request merged**
