### PR TITLE
Fix building system: correct libltdl check for advise capability.

### PR DESCRIPTION
**Pull request by artpol84**
ompi commit: open-mpi/ompi@3ff16e7da7610a68c50ec89ef986e17191f03f3b
ompi pull request: https://github.com/open-mpi/ompi/pull/240

### CODE REVIEW

**Comment by jsquyres** [comment]
Artem --

I'm struggling to remember why the initial `-I.` was there.  In my comment on your master PR (https://github.com/open-mpi/ompi/pull/240#discussion_r19020450), I was only referring to your new second `-I`, not the first/original `-I.`.

Can you check to see exactly which `gcc -E ...` command is emitted, and see if changing `-I.` to `-I$srcdir` is necessary?

FWIW: the libltdl.h file should be in the source tree (vs. the build tree), so `-I$srcdir` might actually be correct.  But I'm not remembering exactly what that `-I.` was for -- i.e., was it actually for libltdl.h, or was it for something else?  And if it was actually for libltdl.h, is it just plain wrong, and your now `-I$srcdir/...` is the correct one?  I.e., should the original `-I.` (now `-I$srcdir`) just be deleted?

**Comment by artpol84** [comment]
That is a good point, Jeff.

Looking closely to the configuration system I can see that we deal with following conftest.c template:

``` bash
CPPFLAGS="-I$srcdir/ -I$srcdir/opal/libltdl/"
# Must specifically mention $srcdir here for VPATH builds
# (this file is in the src tree).
cat confdefs.h - <<_ACEOF >conftest.$ac_ext
/* end confdefs.h.  */
#include <$srcdir/opal/libltdl/ltdl.h>

_ACEOF
```

That will turn into

``` c
//... < lots of defines > ....
#define OMPI_MPI_CONTRIBS "libompitrace, vt"
#define OPAL_C_HAVE_VISIBILITY 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
/* end confdefs.h.  */

#include < ./opal/libltdl/ltdl.h > 
```

For local config and to 

``` c
...
#include < /some/vpath/path/opal/libltdl/ltdl.h >
```

for VPATH.

So we don't actually need "-I." or "-I$srcdir" at all because conftest.c always contains correct path relative to the current configuration directory. 
I updated my pull branch by changing the commit of interest.

**Comment by artpol84** [comment]
I guess I need to go back to ompi and apply this patch there? Additionall pull request?

**Comment by jsquyres** [comment]
Wait, let's figure this out before doing anything...

If we don't need the `-I`, then why did adding it fix your problem?

**Comment by artpol84** [comment]
Sure,
I didn't add -I. I proposed to add -I$srcdir/opal/libltdl/. And now I think that we can also remove "-I."

**Comment by jsquyres** [comment]
I know you didn't add `-I.` -- I just said `-I`, meaning the `-I$srcdir...` one.  :-)

I was responding to your prior comment:

> So we don't actually need "-I." or "-I$srcdir" at all ...

So if we need _neither_ `-I`, then why did your adding `-I$srcdir...` fix the problem for you?

**Comment by artpol84** [comment]
Because in conftest.c we include `ltdl.h` using its full path. And  `ltdl.h` includes few others:

``` c
#include <libltdl/lt_system.h>
#include <libltdl/lt_error.h>
```

They are located in `opal/libltdl/libltdl` and are reffered by relative paths and inaccessible for gcc without corresponding `-I$srcdir/opal/libltdl/`.

P.S. Check the latest patch to clarify my current version.

**Comment by jsquyres** [comment]
Ok, got it -- we _do_ need the `-I$srcdir...`.  Got it.

Yes, please push the final change back to master (i.e., delete the `-I.`), put the master hash here (per the requirement that we have to have all the relevant commits/functionality on master before bringing to v1.8, and then we'll be good to go.

**Comment by artpol84** [comment]
Done: open-mpi/ompi@ce7102cb54360a3ecc47d3d23a972b3c56621c23

**Pull request merged**
