### PR TITLE
Man page fixes

### PR DESCRIPTION
**Pull request by jsquyres**
Two commits:
1. Remove stale Java references
2. Add $COPYRIGHT$ and -_\- nroff -_\- tokens to all pages

@rhc54 please review

There's no rush on this; I marked milestone 1.8.4, but this could certainly slip to 1.8.5.

### CODE REVIEW

**Comment by jsquyres** [comment]
Master commit hashes:
- open-mpi/ompi@ec7808cd27fa30cca2b7a189dc2c8363772fbc90
- open-mpi/ompi@96c655ec67183ca7f2e372912d15ec5b1beef153

**Comment by jsquyres** [comment]
Check that -- @osvegis, please review.  :-)  Oscar cleverly threw open-mpi/ompi#244 to me, so he can review the PR.  :-D

**Comment by rhc54** [comment]
I looked it over - looks fine to me. Thanks for cleaning it up!

**Comment by osvegis** [comment]
Seems to be ok. Thanks.

**Pull request merged**
