### PR TITLE
v2.x: fix ompi_coll_base_allgatherv_intra_basic_default

### PR DESCRIPTION
**Pull request by ggouaillardet**

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:label:bug
:bot:milestone:v2.0.1
:bot:assign: @bosilca

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1988/ for details.

**Comment by bosilca** [comment]
👍

**Comment by hppritcha** [comment]
@jsquyres good to merge

**Pull request merged**
