### PR TITLE
NEWS - add a blurb about issue 1225

### PR DESCRIPTION
**Pull request by hppritcha**
@jsquyres feel free to edit and check-in as you like.

Signed-off-by: Howard Pritchard howardp@lanl.gov

### CODE REVIEW

**Comment by rhc54** [comment]
ouch! ow! umph! stop poking me!! :sweat:

**Comment by rhc54** [comment]
Just poking at you guys :smile: I'm hoping to finish this next week while traveling

**Comment by jsquyres** [comment]
:smile: :+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ompi-release-pr/1250/ for details.

**Pull request merged**
