### PR TITLE
man: fix a trivial typo in MPI_Neighbor_allgather.3in

### PR DESCRIPTION
**Pull request by ggouaillardet**
(cherry picked from commit open-mpi/ompi@c05b271c68672c9e456e7370a01d6549dba767bd)

### CODE REVIEW

**Comment by ggouaillardet** [comment]
:bot:assign @jsquyres
:bot:milestone:v1.8.6

**Comment by ggouaillardet** [comment]
:bot:assign: @jsquyres

**Comment by mellanox-github** [comment]
- Coverity found 1467 errors for all: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/all_280/output/errors/index.html
- Coverity found 23 errors for oshmem: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/oshmem_280/output/errors/index.html
- Coverity found 7 errors for fca: http://bgate.mellanox.com:8888/jenkins/job/gh-ompi-release-v1.8-pr//ws/cov_build/fca_280/output/errors/index.html <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mellanox-github** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bgate.mellanox.com/jenkins/job/gh-ompi-release-v1.8-pr/280/
Test PASSed.

**Comment by jsquyres** [comment]
:+1:

**Pull request merged**
